export enum Events {
  PAGE_VIEW = 'page_view',
  CLICKED_CONSULT_CGU = 'hasClickedConsultCGU',
  CLICKED_PERSONAL_DATA = 'hasClickedConsultPersonalData',
  CLICKED_CONSULT_SUPPORT = 'hasClickedConsultSupport',
  TUTO_PAGE_VIEW = 'tutoPageView',
  CLICKED_FORGOTTEN_PASSWORD = 'hasClickedForgottenPassword',
  CLICKED_HELP_CENTER = 'hasClickedHelpCenter',
  CLICKED_CREATE_OFFER = 'hasClickedCreateOffer',
  CLICKED_CREATE_VENUE = 'hasClickedCreateVenue',
  CLICKED_DOWNLOAD_BOOKINGS = 'hasClickedDownloadBooking',
  CLICKED_SHOW_BOOKINGS = 'hasClickedShowBooking',
  CLICKED_DOWNLOAD_BOOKINGS_XLS = 'hasClickedDownloadBookingXls',
  CLICKED_DOWNLOAD_BOOKINGS_CSV = 'hasClickedDownloadBookingCsv',
  CLICKED_HOME = 'hasClickedHome',
  CLICKED_TICKET = 'hasClickedTicket',
  CLICKED_OFFER = 'hasClickedOffer',
  CLICKED_BOOKING = 'hasClickedBooking',
  CLICKED_REIMBURSEMENT = 'hasClickedReimbursement',
  CLICKED_LOGOUT = 'hasClickedLogout',
  CLICKED_PRO = 'hasClickedPro',
}
