/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface BaseOffersStats
 */
export interface BaseOffersStats {
  /**
   *
   * @type {number}
   * @memberof BaseOffersStats
   */
  collective: number
  /**
   *
   * @type {number}
   * @memberof BaseOffersStats
   */
  individual: number
}

export function BaseOffersStatsFromJSON(json: any): BaseOffersStats {
  return BaseOffersStatsFromJSONTyped(json, false)
}

export function BaseOffersStatsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): BaseOffersStats {
  if (json === undefined || json === null) {
    return json
  }
  return {
    collective: json['collective'],
    individual: json['individual'],
  }
}

export function BaseOffersStatsToJSON(value?: BaseOffersStats | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    collective: value.collective,
    individual: value.individual,
  }
}
