/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  FraudReviewStatus,
  FraudReviewStatusFromJSON,
  FraudReviewStatusFromJSONTyped,
  FraudReviewStatusToJSON,
} from './'

/**
 *
 * @export
 * @interface BeneficiaryReviewResponseModel
 */
export interface BeneficiaryReviewResponseModel {
  /**
   *
   * @type {number}
   * @memberof BeneficiaryReviewResponseModel
   */
  authorId: number
  /**
   *
   * @type {string}
   * @memberof BeneficiaryReviewResponseModel
   */
  eligibility?: string | null
  /**
   *
   * @type {string}
   * @memberof BeneficiaryReviewResponseModel
   */
  reason: string
  /**
   *
   * @type {FraudReviewStatus}
   * @memberof BeneficiaryReviewResponseModel
   */
  review: FraudReviewStatus
  /**
   *
   * @type {number}
   * @memberof BeneficiaryReviewResponseModel
   */
  userId: number
}

export function BeneficiaryReviewResponseModelFromJSON(
  json: any
): BeneficiaryReviewResponseModel {
  return BeneficiaryReviewResponseModelFromJSONTyped(json, false)
}

export function BeneficiaryReviewResponseModelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): BeneficiaryReviewResponseModel {
  if (json === undefined || json === null) {
    return json
  }
  return {
    authorId: json['authorId'],
    eligibility: !exists(json, 'eligibility') ? undefined : json['eligibility'],
    reason: json['reason'],
    review: FraudReviewStatusFromJSON(json['review']),
    userId: json['userId'],
  }
}

export function BeneficiaryReviewResponseModelToJSON(
  value?: BeneficiaryReviewResponseModel | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    authorId: value.authorId,
    eligibility: value.eligibility,
    reason: value.reason,
    review: FraudReviewStatusToJSON(value.review),
    userId: value.userId,
  }
}
