/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface Comment
 */
export interface Comment {
  /**
   *
   * @type {string}
   * @memberof Comment
   */
  author?: string | null
  /**
   *
   * @type {string}
   * @memberof Comment
   */
  content: string
  /**
   *
   * @type {Date}
   * @memberof Comment
   */
  date: Date
}

export function CommentFromJSON(json: any): Comment {
  return CommentFromJSONTyped(json, false)
}

export function CommentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Comment {
  if (json === undefined || json === null) {
    return json
  }
  return {
    author: !exists(json, 'author') ? undefined : json['author'],
    content: json['content'],
    date: new Date(json['date']),
  }
}

export function CommentToJSON(value?: Comment | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    author: value.author,
    content: value.content,
    date: value.date.toISOString(),
  }
}
