/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CommentRequest
 */
export interface CommentRequest {
  /**
   *
   * @type {string}
   * @memberof CommentRequest
   */
  comment: string
}

export function CommentRequestFromJSON(json: any): CommentRequest {
  return CommentRequestFromJSONTyped(json, false)
}

export function CommentRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CommentRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    comment: json['comment'],
  }
}

export function CommentRequestToJSON(value?: CommentRequest | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    comment: value.comment,
  }
}
