/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * An enumeration.
 * @export
 * @enum {string}
 */
export enum FraudCheckStatus {
  Canceled = 'canceled',
  Error = 'error',
  Ko = 'ko',
  Ok = 'ok',
  Pending = 'pending',
  Started = 'started',
  Suspiscious = 'suspiscious',
}

export function FraudCheckStatusFromJSON(json: any): FraudCheckStatus {
  return FraudCheckStatusFromJSONTyped(json, false)
}

export function FraudCheckStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): FraudCheckStatus {
  return json as FraudCheckStatus
}

export function FraudCheckStatusToJSON(value?: FraudCheckStatus | null): any {
  return value as any
}
