/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * An enumeration.
 * @export
 * @enum {string}
 */
export enum FraudReviewStatus {
  KO = 'KO',
  OK = 'OK',
  REDIRECTEDTODMS = 'REDIRECTED_TO_DMS',
}

export function FraudReviewStatusFromJSON(json: any): FraudReviewStatus {
  return FraudReviewStatusFromJSONTyped(json, false)
}

export function FraudReviewStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): FraudReviewStatus {
  return json as FraudReviewStatus
}

export function FraudReviewStatusToJSON(value?: FraudReviewStatus | null): any {
  return value as any
}
