/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * An enumeration.
 * @export
 * @enum {string}
 */
export enum FraudCheckType {
  Dms = 'dms',
  Educonnect = 'educonnect',
  HonorStatement = 'honor_statement',
  InternalReview = 'internal_review',
  Jouve = 'jouve',
  PhoneValidation = 'phone_validation',
  ProfileCompletion = 'profile_completion',
  Ubble = 'ubble',
  UserProfiling = 'user_profiling',
}

export function FraudCheckTypeFromJSON(json: any): FraudCheckType {
  return FraudCheckTypeFromJSONTyped(json, false)
}

export function FraudCheckTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): FraudCheckType {
  return json as FraudCheckType
}

export function FraudCheckTypeToJSON(value?: FraudCheckType | null): any {
  return value as any
}
