/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface IsTopActorRequest
 */
export interface IsTopActorRequest {
  /**
   *
   * @type {boolean}
   * @memberof IsTopActorRequest
   */
  isTopActor: boolean
}

export function IsTopActorRequestFromJSON(json: any): IsTopActorRequest {
  return IsTopActorRequestFromJSONTyped(json, false)
}

export function IsTopActorRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IsTopActorRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    isTopActor: json['isTopActor'],
  }
}

export function IsTopActorRequestToJSON(value?: IsTopActorRequest | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    isTopActor: value.isTopActor,
  }
}
