/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  UserOffererToBeValidated,
  UserOffererToBeValidatedFromJSON,
  UserOffererToBeValidatedFromJSONTyped,
  UserOffererToBeValidatedToJSON,
} from './'

/**
 *
 * @export
 * @interface ListUserOffererToBeValidatedResponseModel
 */
export interface ListUserOffererToBeValidatedResponseModel {
  /**
   *
   * @type {Array<UserOffererToBeValidated>}
   * @memberof ListUserOffererToBeValidatedResponseModel
   */
  data: Array<UserOffererToBeValidated>
  /**
   *
   * @type {number}
   * @memberof ListUserOffererToBeValidatedResponseModel
   */
  page: number
  /**
   *
   * @type {number}
   * @memberof ListUserOffererToBeValidatedResponseModel
   */
  pages: number
  /**
   *
   * @type {number}
   * @memberof ListUserOffererToBeValidatedResponseModel
   */
  size: number
  /**
   *
   * @type {string}
   * @memberof ListUserOffererToBeValidatedResponseModel
   */
  sort?: string | null
  /**
   *
   * @type {number}
   * @memberof ListUserOffererToBeValidatedResponseModel
   */
  total: number
}

export function ListUserOffererToBeValidatedResponseModelFromJSON(
  json: any
): ListUserOffererToBeValidatedResponseModel {
  return ListUserOffererToBeValidatedResponseModelFromJSONTyped(json, false)
}

export function ListUserOffererToBeValidatedResponseModelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ListUserOffererToBeValidatedResponseModel {
  if (json === undefined || json === null) {
    return json
  }
  return {
    data: (json['data'] as Array<any>).map(UserOffererToBeValidatedFromJSON),
    page: json['page'],
    pages: json['pages'],
    size: json['size'],
    sort: !exists(json, 'sort') ? undefined : json['sort'],
    total: json['total'],
  }
}

export function ListUserOffererToBeValidatedResponseModelToJSON(
  value?: ListUserOffererToBeValidatedResponseModel | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    data: (value.data as Array<any>).map(UserOffererToBeValidatedToJSON),
    page: value.page,
    pages: value.pages,
    size: value.size,
    sort: value.sort,
    total: value.total,
  }
}
