/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import { Role, RoleFromJSON, RoleFromJSONTyped, RoleToJSON } from './index'

/**
 *
 * @export
 * @interface ListRoleResponseModel
 */
export interface ListRoleResponseModel {
  /**
   *
   * @type {Array<Role>}
   * @memberof ListRoleResponseModel
   */
  roles: Array<Role>
}

export function ListRoleResponseModelFromJSON(
  json: any
): ListRoleResponseModel {
  return ListRoleResponseModelFromJSONTyped(json, false)
}

export function ListRoleResponseModelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ListRoleResponseModel {
  if (json === undefined || json === null) {
    return json
  }
  return {
    roles: (json['roles'] as Array<any>).map(RoleFromJSON),
  }
}

export function ListRoleResponseModelToJSON(
  value?: ListRoleResponseModel | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    roles: (value.roles as Array<any>).map(RoleToJSON),
  }
}
