/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface OffererTagItem
 */
export interface OffererTagItem {
  /**
   *
   * @type {number}
   * @memberof OffererTagItem
   */
  id: number
  /**
   *
   * @type {string}
   * @memberof OffererTagItem
   */
  label?: string | null
  /**
   *
   * @type {string}
   * @memberof OffererTagItem
   */
  name: string
}

export function OffererTagItemFromJSON(json: any): OffererTagItem {
  return OffererTagItemFromJSONTyped(json, false)
}

export function OffererTagItemFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OffererTagItem {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json['id'],
    label: !exists(json, 'label') ? undefined : json['label'],
    name: json['name'],
  }
}

export function OffererTagItemToJSON(value?: OffererTagItem | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    label: value.label,
    name: value.name,
  }
}
