/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  OffererBasicInfo,
  OffererBasicInfoFromJSON,
  OffererBasicInfoFromJSONTyped,
  OffererBasicInfoToJSON,
} from './'

/**
 *
 * @export
 * @interface OffererBasicInfoResponseModel
 */
export interface OffererBasicInfoResponseModel {
  /**
   *
   * @type {OffererBasicInfo}
   * @memberof OffererBasicInfoResponseModel
   */
  data: OffererBasicInfo
}

export function OffererBasicInfoResponseModelFromJSON(
  json: any
): OffererBasicInfoResponseModel {
  return OffererBasicInfoResponseModelFromJSONTyped(json, false)
}

export function OffererBasicInfoResponseModelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OffererBasicInfoResponseModel {
  if (json === undefined || json === null) {
    return json
  }
  return {
    data: OffererBasicInfoFromJSON(json['data']),
  }
}

export function OffererBasicInfoResponseModelToJSON(
  value?: OffererBasicInfoResponseModel | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    data: OffererBasicInfoToJSON(value.data),
  }
}
