/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  Comment,
  CommentFromJSON,
  CommentFromJSONTyped,
  CommentToJSON,
} from './'

/**
 *
 * @export
 * @interface OffererToBeValidated
 */
export interface OffererToBeValidated {
  /**
   *
   * @type {string}
   * @memberof OffererToBeValidated
   */
  address: string
  /**
   *
   * @type {string}
   * @memberof OffererToBeValidated
   */
  city: string
  /**
   *
   * @type {string}
   * @memberof OffererToBeValidated
   */
  email?: string | null
  /**
   *
   * @type {number}
   * @memberof OffererToBeValidated
   */
  id: number
  /**
   *
   * @type {boolean}
   * @memberof OffererToBeValidated
   */
  isTopActor: boolean
  /**
   *
   * @type {Comment}
   * @memberof OffererToBeValidated
   */
  lastComment?: Comment | null
  /**
   *
   * @type {string}
   * @memberof OffererToBeValidated
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof OffererToBeValidated
   */
  owner?: string | null
  /**
   *
   * @type {string}
   * @memberof OffererToBeValidated
   */
  phoneNumber?: string | null
  /**
   *
   * @type {string}
   * @memberof OffererToBeValidated
   */
  postalCode: string
  /**
   *
   * @type {string}
   * @memberof OffererToBeValidated
   */
  siren: string
  /**
   *
   * @type {string}
   * @memberof OffererToBeValidated
   */
  status: string
  /**
   *
   * @type {string}
   * @memberof OffererToBeValidated
   */
  step?: string | null
}

export function OffererToBeValidatedFromJSON(json: any): OffererToBeValidated {
  return OffererToBeValidatedFromJSONTyped(json, false)
}

export function OffererToBeValidatedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OffererToBeValidated {
  if (json === undefined || json === null) {
    return json
  }
  return {
    address: json['address'],
    city: json['city'],
    email: !exists(json, 'email') ? undefined : json['email'],
    id: json['id'],
    isTopActor: json['isTopActor'],
    lastComment: !exists(json, 'lastComment')
      ? undefined
      : CommentFromJSON(json['lastComment']),
    name: json['name'],
    owner: !exists(json, 'owner') ? undefined : json['owner'],
    phoneNumber: !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
    postalCode: json['postalCode'],
    siren: json['siren'],
    status: json['status'],
    step: !exists(json, 'step') ? undefined : json['step'],
  }
}

export function OffererToBeValidatedToJSON(
  value?: OffererToBeValidated | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    address: value.address,
    city: value.city,
    email: value.email,
    id: value.id,
    isTopActor: value.isTopActor,
    lastComment: CommentToJSON(value.lastComment),
    name: value.name,
    owner: value.owner,
    phoneNumber: value.phoneNumber,
    postalCode: value.postalCode,
    siren: value.siren,
    status: value.status,
    step: value.step,
  }
}
