/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * le nombre de lieux dont les infos permettent (ok), ou pas (ko), les remboursements
 * @export
 * @interface OffererBankInformationStatus
 */
export interface OffererBankInformationStatus {
  /**
   *
   * @type {number}
   * @memberof OffererBankInformationStatus
   */
  ko: number
  /**
   *
   * @type {number}
   * @memberof OffererBankInformationStatus
   */
  ok: number
}

export function OffererBankInformationStatusFromJSON(
  json: any
): OffererBankInformationStatus {
  return OffererBankInformationStatusFromJSONTyped(json, false)
}

export function OffererBankInformationStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OffererBankInformationStatus {
  if (json === undefined || json === null) {
    return json
  }
  return {
    ko: json['ko'],
    ok: json['ok'],
  }
}

export function OffererBankInformationStatusToJSON(
  value?: OffererBankInformationStatus | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    ko: value.ko,
    ok: value.ok,
  }
}
