/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  BaseOffersStats,
  BaseOffersStatsFromJSON,
  BaseOffersStatsFromJSONTyped,
  BaseOffersStatsToJSON,
} from './'

/**
 *
 * @export
 * @interface OffersStats
 */
export interface OffersStats {
  /**
   *
   * @type {BaseOffersStats}
   * @memberof OffersStats
   */
  active: BaseOffersStats
  /**
   *
   * @type {BaseOffersStats}
   * @memberof OffersStats
   */
  inactive: BaseOffersStats
}

export function OffersStatsFromJSON(json: any): OffersStats {
  return OffersStatsFromJSONTyped(json, false)
}

export function OffersStatsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OffersStats {
  if (json === undefined || json === null) {
    return json
  }
  return {
    active: BaseOffersStatsFromJSON(json['active']),
    inactive: BaseOffersStatsFromJSON(json['inactive']),
  }
}

export function OffersStatsToJSON(value?: OffersStats | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    active: BaseOffersStatsToJSON(value.active),
    inactive: BaseOffersStatsToJSON(value.inactive),
  }
}
