/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface OptionalCommentRequest
 */
export interface OptionalCommentRequest {
  /**
   *
   * @type {string}
   * @memberof OptionalCommentRequest
   */
  comment?: string | null
}

export function OptionalCommentRequestFromJSON(
  json: any
): OptionalCommentRequest {
  return OptionalCommentRequestFromJSONTyped(json, false)
}

export function OptionalCommentRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OptionalCommentRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    comment: !exists(json, 'comment') ? undefined : json['comment'],
  }
}

export function OptionalCommentRequestToJSON(
  value?: OptionalCommentRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    comment: value.comment,
  }
}
