/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ProResult
 */
export interface ProResult {
  /**
   *
   * @type {number}
   * @memberof ProResult
   */
  id: number
  /**
   *
   * @type {object}
   * @memberof ProResult
   */
  payload: object
  /**
   *
   * @type {string}
   * @memberof ProResult
   */
  resourceType: string
}

export function ProResultFromJSON(json: any): ProResult {
  return ProResultFromJSONTyped(json, false)
}

export function ProResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ProResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json['id'],
    payload: json['payload'],
    resourceType: json['resourceType'],
  }
}

export function ProResultToJSON(value?: ProResult | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    payload: value.payload,
    resourceType: value.resourceType,
  }
}
