/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ProSearchQuery
 */
export interface ProSearchQuery {
  /**
   *
   * @type {number}
   * @memberof ProSearchQuery
   */
  page?: number | null
  /**
   *
   * @type {number}
   * @memberof ProSearchQuery
   */
  perPage?: number | null
  /**
   *
   * @type {string}
   * @memberof ProSearchQuery
   */
  q: string
  /**
   *
   * @type {string}
   * @memberof ProSearchQuery
   */
  sort?: string | null
  /**
   *
   * @type {string}
   * @memberof ProSearchQuery
   */
  type: string
}

export function ProSearchQueryFromJSON(json: any): ProSearchQuery {
  return ProSearchQueryFromJSONTyped(json, false)
}

export function ProSearchQueryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ProSearchQuery {
  if (json === undefined || json === null) {
    return json
  }
  return {
    page: !exists(json, 'page') ? undefined : json['page'],
    perPage: !exists(json, 'perPage') ? undefined : json['perPage'],
    q: json['q'],
    sort: !exists(json, 'sort') ? undefined : json['sort'],
    type: json['type'],
  }
}

export function ProSearchQueryToJSON(value?: ProSearchQuery | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    page: value.page,
    perPage: value.perPage,
    q: value.q,
    sort: value.sort,
    type: value.type,
  }
}
