/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface PublicHistoryItem
 */
export interface PublicHistoryItem {
  /**
   *
   * @type {string}
   * @memberof PublicHistoryItem
   */
  action: string
  /**
   *
   * @type {Date}
   * @memberof PublicHistoryItem
   */
  datetime: Date
  /**
   *
   * @type {string}
   * @memberof PublicHistoryItem
   */
  message: string
}

export function PublicHistoryItemFromJSON(json: any): PublicHistoryItem {
  return PublicHistoryItemFromJSONTyped(json, false)
}

export function PublicHistoryItemFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PublicHistoryItem {
  if (json === undefined || json === null) {
    return json
  }
  return {
    action: json['action'],
    datetime: new Date(json['datetime']),
    message: json['message'],
  }
}

export function PublicHistoryItemToJSON(value?: PublicHistoryItem | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    action: value.action,
    datetime: value.datetime.toISOString(),
    message: value.message,
  }
}
