/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  PublicHistoryItem,
  PublicHistoryItemFromJSON,
  PublicHistoryItemFromJSONTyped,
  PublicHistoryItemToJSON,
} from './'

/**
 *
 * @export
 * @interface PublicHistoryResponseModel
 */
export interface PublicHistoryResponseModel {
  /**
   *
   * @type {Array<PublicHistoryItem>}
   * @memberof PublicHistoryResponseModel
   */
  history: Array<PublicHistoryItem>
}

export function PublicHistoryResponseModelFromJSON(
  json: any
): PublicHistoryResponseModel {
  return PublicHistoryResponseModelFromJSONTyped(json, false)
}

export function PublicHistoryResponseModelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PublicHistoryResponseModel {
  if (json === undefined || json === null) {
    return json
  }
  return {
    history: (json['history'] as Array<any>).map(PublicHistoryItemFromJSON),
  }
}

export function PublicHistoryResponseModelToJSON(
  value?: PublicHistoryResponseModel | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    history: (value.history as Array<any>).map(PublicHistoryItemToJSON),
  }
}
