/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  SubscriptionItemStatus,
  SubscriptionItemStatusFromJSON,
  SubscriptionItemStatusFromJSONTyped,
  SubscriptionItemStatusToJSON,
  SubscriptionStep,
  SubscriptionStepFromJSON,
  SubscriptionStepFromJSONTyped,
  SubscriptionStepToJSON,
} from './index'

/**
 *
 * @export
 * @interface SubscriptionItemModel
 */
export interface SubscriptionItemModel {
  /**
   *
   * @type {SubscriptionItemStatus}
   * @memberof SubscriptionItemModel
   */
  status: SubscriptionItemStatus
  /**
   *
   * @type {SubscriptionStep}
   * @memberof SubscriptionItemModel
   */
  type: SubscriptionStep
}

export function SubscriptionItemModelFromJSON(
  json: any
): SubscriptionItemModel {
  return SubscriptionItemModelFromJSONTyped(json, false)
}

export function SubscriptionItemModelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SubscriptionItemModel {
  if (json === undefined || json === null) {
    return json
  }
  return {
    status: SubscriptionItemStatusFromJSON(json['status']),
    type: SubscriptionStepFromJSON(json['type']),
  }
}

export function SubscriptionItemModelToJSON(
  value?: SubscriptionItemModel | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    status: SubscriptionItemStatusToJSON(value.status),
    type: SubscriptionStepToJSON(value.type),
  }
}
