/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * An enumeration.
 * @export
 * @enum {string}
 */
export enum SubscriptionItemStatus {
  Ko = 'ko',
  NotApplicable = 'not-applicable',
  NotEnabled = 'not-enabled',
  Ok = 'ok',
  Pending = 'pending',
  Skipped = 'skipped',
  Suspicious = 'suspicious',
  Todo = 'todo',
  Void = 'void',
}

export function SubscriptionItemStatusFromJSON(
  json: any
): SubscriptionItemStatus {
  return SubscriptionItemStatusFromJSONTyped(json, false)
}

export function SubscriptionItemStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SubscriptionItemStatus {
  return json as SubscriptionItemStatus
}

export function SubscriptionItemStatusToJSON(
  value?: SubscriptionItemStatus | null
): any {
  return value as any
}
