/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * base class for backoffice filters, should probably be specialized for each endpoint
 * @export
 * @interface ToBeValidatedOffererFilter
 */
export interface ToBeValidatedOffererFilter {
  /**
   *
   * @type {string}
   * @memberof ToBeValidatedOffererFilter
   */
  field: ToBeValidatedOffererFilterFieldEnum
  /**
   *
   * @type {Array<string>}
   * @memberof ToBeValidatedOffererFilter
   */
  value: Array<ToBeValidatedOffererFilterValueEnum>
}

export function ToBeValidatedOffererFilterFromJSON(
  json: any
): ToBeValidatedOffererFilter {
  return ToBeValidatedOffererFilterFromJSONTyped(json, false)
}

export function ToBeValidatedOffererFilterFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ToBeValidatedOffererFilter {
  if (json === undefined || json === null) {
    return json
  }
  return {
    field: json['field'],
    value: json['value'],
  }
}

export function ToBeValidatedOffererFilterToJSON(
  value?: ToBeValidatedOffererFilter | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    field: value.field,
    value: value.value,
  }
}

/**
 * @export
 * @enum {string}
 */
export enum ToBeValidatedOffererFilterFieldEnum {
  Tags = 'tags',
}
/**
 * @export
 * @enum {string}
 */
export enum ToBeValidatedOffererFilterValueEnum {
  Collectivit = 'Collectivité',
  TopActeur = 'Top acteur',
  TablissementPublic = 'Établissement public',
}
