/* tslint:disable */
/* eslint-disable */
/**
 * pass Culture backoffice API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface UserOffererToBeValidatedQuery
 */
export interface UserOffererToBeValidatedQuery {
  /**
   *
   * @type {string}
   * @memberof UserOffererToBeValidatedQuery
   */
  filter?: string | null
  /**
   *
   * @type {number}
   * @memberof UserOffererToBeValidatedQuery
   */
  page?: number | null
  /**
   *
   * @type {number}
   * @memberof UserOffererToBeValidatedQuery
   */
  perPage?: number | null
  /**
   *
   * @type {string}
   * @memberof UserOffererToBeValidatedQuery
   */
  sort?: string | null
}

export function UserOffererToBeValidatedQueryFromJSON(
  json: any
): UserOffererToBeValidatedQuery {
  return UserOffererToBeValidatedQueryFromJSONTyped(json, false)
}

export function UserOffererToBeValidatedQueryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserOffererToBeValidatedQuery {
  if (json === undefined || json === null) {
    return json
  }
  return {
    filter: !exists(json, 'filter') ? undefined : json['filter'],
    page: !exists(json, 'page') ? undefined : json['page'],
    perPage: !exists(json, 'perPage') ? undefined : json['perPage'],
    sort: !exists(json, 'sort') ? undefined : json['sort'],
  }
}

export function UserOffererToBeValidatedQueryToJSON(
  value?: UserOffererToBeValidatedQuery | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    filter: value.filter,
    page: value.page,
    perPage: value.perPage,
    sort: value.sort,
  }
}
