import { OfferStatus, SubcategoryIdEnum } from 'api/v1/gen/api'

import { IOfferIndividual } from 'core/Offers/types'

export const fakeOffer: IOfferIndividual = {
  id: 'YA',
  author: '',
  bookingEmail: '',
  description: 'A passionate description of product 80',
  durationMinutes: null,
  isbn: '',
  isDuo: false,
  isEducational: false,
  noDisabilityCompliant: true,
  audioDisabilityCompliant: false,
  mentalDisabilityCompliant: false,
  motorDisabilityCompliant: false,
  visualDisabilityCompliant: false,
  isNational: false,
  name: 'Séance ciné duo',
  musicSubType: '',
  musicType: '',
  offererId: 'CU',
  performer: '',
  showSubType: '',
  showType: '',
  stageDirector: '',
  speaker: '',
  subcategoryId: SubcategoryIdEnum.SEANCECINE,
  url: '',
  externalTicketOfficeUrl: '',
  venueId: 'DY',
  visa: '',
  withdrawalDetails: '',
  withdrawalDelay: null,
  stocks: [
    {
      beginningDatetime: new Date('2022-05-23T08:25:31.009799Z'),
      bookingLimitDatetime: new Date('2022-05-23T07:25:31.009799Z'),
      bookingsQuantity: 2,
      dateCreated: new Date('2022-05-18T08:25:31.015652Z'),
      hasActivationCode: false,
      id: 'YE',
      isEventDeletable: false,
      isEventExpired: true,
      isSoftDeleted: false,
      offerId: 'YA',
      price: 10,
      quantity: 1000,
      remainingQuantity: 998,
    },
  ],
}
