/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum ActivityNotOpenToPublic {
  ARTISTIC_COMPANY = 'ARTISTIC_COMPANY',
  ARTISTIC_PRACTICE = 'ARTISTIC_PRACTICE',
  CULTURAL_MEDIATION = 'CULTURAL_MEDIATION',
  FESTIVAL = 'FESTIVAL',
  HERITAGE_SITE = 'HERITAGE_SITE',
  MUNICIPALITY_CULTURAL_DEPARTMENT = 'MUNICIPALITY_CULTURAL_DEPARTMENT',
  OTHER = 'OTHER',
  PRESS_OR_MEDIA = 'PRESS_OR_MEDIA',
  PRODUCTION_OR_PROMOTION_COMPANY = 'PRODUCTION_OR_PROMOTION_COMPANY',
  PUBLISHING_HOUSE = 'PUBLISHING_HOUSE',
  RADIO_OR_MUSIC_STREAMING = 'RADIO_OR_MUSIC_STREAMING',
  TELEVISION_OR_VIDEO_STREAMING = 'TELEVISION_OR_VIDEO_STREAMING',
  TRAVELLING_CINEMA = 'TRAVELLING_CINEMA',
}
