/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * An enumeration.
 */
export enum ActivityNotOpenToPublic {
  ARTISTIC_COMPANY = 'ARTISTIC_COMPANY',
  ARTS_EDUCATION = 'ARTS_EDUCATION',
  CULTURAL_MEDIATION = 'CULTURAL_MEDIATION',
  FESTIVAL = 'FESTIVAL',
  OTHER = 'OTHER',
  PRESS_OR_MEDIA = 'PRESS_OR_MEDIA',
  PRODUCTION_OR_PROMOTION_COMPANY = 'PRODUCTION_OR_PROMOTION_COMPANY',
  RADIO_OR_MUSIC_STREAMING = 'RADIO_OR_MUSIC_STREAMING',
  TELEVISION_OR_VIDEO_STREAMING = 'TELEVISION_OR_VIDEO_STREAMING',
  TRAVELLING_CINEMA = 'TRAVELLING_CINEMA',
}
