/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * An enumeration.
 */
export enum CollectiveBookingCancellationReasons {
  OFFERER = 'OFFERER',
  BENEFICIARY = 'BENEFICIARY',
  EXPIRED = 'EXPIRED',
  FRAUD = 'FRAUD',
  FRAUD_SUSPICION = 'FRAUD_SUSPICION',
  FRAUD_INAPPROPRIATE = 'FRAUD_INAPPROPRIATE',
  REFUSED_BY_INSTITUTE = 'REFUSED_BY_INSTITUTE',
  REFUSED_BY_HEADMASTER = 'REFUSED_BY_HEADMASTER',
  PUBLIC_API = 'PUBLIC_API',
  FINANCE_INCIDENT = 'FINANCE_INCIDENT',
  BACKOFFICE = 'BACKOFFICE',
  BACKOFFICE_EVENT_CANCELLED = 'BACKOFFICE_EVENT_CANCELLED',
  BACKOFFICE_OFFER_MODIFIED = 'BACKOFFICE_OFFER_MODIFIED',
  BACKOFFICE_OFFER_WITH_WRONG_INFORMATION = 'BACKOFFICE_OFFER_WITH_WRONG_INFORMATION',
  BACKOFFICE_OFFERER_BUSINESS_CLOSED = 'BACKOFFICE_OFFERER_BUSINESS_CLOSED',
  OFFERER_CONNECT_AS = 'OFFERER_CONNECT_AS',
  OFFERER_CLOSED = 'OFFERER_CLOSED',
}
