/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * An enumeration.
 */
export enum CollectiveBookingCancellationReasons {
  OFFERER = 'OFFERER',
  BENEFICIARY = 'BENEFICIARY',
  EXPIRED = 'EXPIRED',
  FRAUD = 'FRAUD',
  REFUSED_BY_INSTITUTE = 'REFUSED_BY_INSTITUTE',
  REFUSED_BY_HEADMASTER = 'REFUSED_BY_HEADMASTER',
  PUBLIC_API = 'PUBLIC_API',
  FINANCE_INCIDENT = 'FINANCE_INCIDENT',
  BACKOFFICE = 'BACKOFFICE',
  BACKOFFICE_EVENT_CANCELLED = 'BACKOFFICE_EVENT_CANCELLED',
  BACKOFFICE_SURBOOKING = 'BACKOFFICE_SURBOOKING',
  BACKOFFICE_BENEFICIARY_REQUEST = 'BACKOFFICE_BENEFICIARY_REQUEST',
  BACKOFFICE_OFFER_MODIFIED = 'BACKOFFICE_OFFER_MODIFIED',
  BACKOFFICE_OFFER_ERROR = 'BACKOFFICE_OFFER_ERROR',
  OFFERER_CONNECT_AS = 'OFFERER_CONNECT_AS',
}
