/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * An enumeration.
 */
export enum DisplayableActivity {
  ART_GALLERY = 'ART_GALLERY',
  ART_SCHOOL = 'ART_SCHOOL',
  ARTISTIC_COMPANY = 'ARTISTIC_COMPANY',
  ARTS_CENTRE = 'ARTS_CENTRE',
  ARTS_EDUCATION = 'ARTS_EDUCATION',
  BOOKSTORE = 'BOOKSTORE',
  CINEMA = 'CINEMA',
  COMMUNITY_CENTRE = 'COMMUNITY_CENTRE',
  CREATIVE_ARTS_STORE = 'CREATIVE_ARTS_STORE',
  CULTURAL_CENTRE = 'CULTURAL_CENTRE',
  CULTURAL_MEDIATION = 'CULTURAL_MEDIATION',
  DISTRIBUTION_STORE = 'DISTRIBUTION_STORE',
  FESTIVAL = 'FESTIVAL',
  GAMES_CENTRE = 'GAMES_CENTRE',
  HERITAGE_SITE = 'HERITAGE_SITE',
  LIBRARY = 'LIBRARY',
  MUSEUM = 'MUSEUM',
  MUSIC_INSTRUMENT_STORE = 'MUSIC_INSTRUMENT_STORE',
  OTHER = 'OTHER',
  PERFORMANCE_HALL = 'PERFORMANCE_HALL',
  PRESS = 'PRESS',
  PRODUCTION_OR_PROMOTION_COMPANY = 'PRODUCTION_OR_PROMOTION_COMPANY',
  RECORD_STORE = 'RECORD_STORE',
  SCIENCE_CENTRE = 'SCIENCE_CENTRE',
  STREAMING_PLATFORM = 'STREAMING_PLATFORM',
  TOURIST_INFORMATION_CENTRE = 'TOURIST_INFORMATION_CENTRE',
  TRAVELLING_CINEMA = 'TRAVELLING_CINEMA',
}
