/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * An enumeration.
 */
export enum DisplayableActivity {
  ART_GALLERY = 'ART_GALLERY',
  ART_SCHOOL = 'ART_SCHOOL',
  ARTS_CENTRE = 'ARTS_CENTRE',
  BOOKSTORE = 'BOOKSTORE',
  CINEMA = 'CINEMA',
  COMMUNITY_CENTRE = 'COMMUNITY_CENTRE',
  CREATIVE_ARTS_STORE = 'CREATIVE_ARTS_STORE',
  CULTURAL_CENTRE = 'CULTURAL_CENTRE',
  DISTRIBUTION_STORE = 'DISTRIBUTION_STORE',
  FESTIVAL = 'FESTIVAL',
  GAMES_CENTRE = 'GAMES_CENTRE',
  HERITAGE_SITE = 'HERITAGE_SITE',
  LIBRARY = 'LIBRARY',
  MUSEUM = 'MUSEUM',
  MUSIC_INSTRUMENT_STORE = 'MUSIC_INSTRUMENT_STORE',
  OTHER = 'OTHER',
  PERFORMANCE_HALL = 'PERFORMANCE_HALL',
  RECORD_STORE = 'RECORD_STORE',
  SCIENCE_CENTRE = 'SCIENCE_CENTRE',
  TOURIST_INFORMATION_CENTRE = 'TOURIST_INFORMATION_CENTRE',
}
