/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { _ExternalAccessibilityDataModel } from './_ExternalAccessibilityDataModel';
import type { BannerMetaModelV2 } from './BannerMetaModelV2';
import type { DisplayableActivity } from './DisplayableActivity';
import type { DMSApplicationForEACV2 } from './DMSApplicationForEACV2';
import type { GetVenueDomainResponseModelV2 } from './GetVenueDomainResponseModelV2';
import type { GetVenueManagingOffererResponseModel } from './GetVenueManagingOffererResponseModel';
import type { GetVenuePricingPointResponseModel } from './GetVenuePricingPointResponseModel';
import type { LegalStatusResponseModelV2 } from './LegalStatusResponseModelV2';
import type { LocationResponseModelV2 } from './LocationResponseModelV2';
import type { SimplifiedBankAccountStatus } from './SimplifiedBankAccountStatus';
import type { StudentLevels } from './StudentLevels';
import type { VenueContactModelV2 } from './VenueContactModelV2';
import type { VenueTypeResponseModelV2 } from './VenueTypeResponseModelV2';
import type { WeekdayOpeningHoursTimespansV2 } from './WeekdayOpeningHoursTimespansV2';
export type GetVenueResponseModel = {
  activity: (DisplayableActivity | null);
  adageInscriptionDate: (string | null);
  allowedOnAdage: boolean;
  audioDisabilityCompliant: (boolean | null);
  bankAccountStatus: (SimplifiedBankAccountStatus | null);
  bannerMeta: (BannerMetaModelV2 | null);
  bannerUrl: (string | null);
  bookingEmail: (string | null);
  canDisplayHighlights: boolean;
  collectiveAccessInformation: (string | null);
  collectiveDescription: (string | null);
  collectiveDmsApplications: Array<DMSApplicationForEACV2>;
  collectiveDomains: Array<GetVenueDomainResponseModelV2>;
  collectiveEmail: (string | null);
  collectiveInterventionArea: (Array<string> | null);
  collectiveLegalStatus: (LegalStatusResponseModelV2 | null);
  collectiveNetwork: (Array<string> | null);
  collectivePhone: (string | null);
  collectiveStudents: (Array<StudentLevels> | null);
  collectiveWebsite: (string | null);
  comment: (string | null);
  contact: (VenueContactModelV2 | null);
  dateCreated: string;
  description: string;
  externalAccessibilityData: (_ExternalAccessibilityDataModel | null);
  externalAccessibilityId: (string | null);
  externalAccessibilityUrl: (string | null);
  hasActiveIndividualOffer: boolean;
  hasAdageId: boolean;
  hasNonDraftOffers: boolean;
  hasNonFreeOffers: boolean;
  hasOffers: boolean;
  hasPartnerPage: boolean;
  id: number;
  isActive: boolean;
  isCaledonian: boolean;
  isOpenToPublic: boolean;
  isPermanent: (boolean | null);
  isValidated: boolean;
  isVirtual: boolean;
  location: (LocationResponseModelV2 | null);
  managingOfferer: GetVenueManagingOffererResponseModel;
  mentalDisabilityCompliant: (boolean | null);
  motorDisabilityCompliant: (boolean | null);
  name: string;
  openingHours: (WeekdayOpeningHoursTimespansV2 | null);
  pricingPoint: (GetVenuePricingPointResponseModel | null);
  publicName: string;
  siret: (string | null);
  venueType: VenueTypeResponseModelV2;
  visualDisabilityCompliant: (boolean | null);
  withdrawalDetails: (string | null);
};

