/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { BannerMetaModel } from './BannerMetaModel';
import type { DisplayableActivity } from './DisplayableActivity';
import type { DMSApplicationForEAC } from './DMSApplicationForEAC';
import type { ExternalAccessibilityDataModel } from './ExternalAccessibilityDataModel';
import type { GetVenueDomainResponseModel } from './GetVenueDomainResponseModel';
import type { GetVenueManagingOffererResponseModel } from './GetVenueManagingOffererResponseModel';
import type { GetVenuePricingPointResponseModel } from './GetVenuePricingPointResponseModel';
import type { LegalStatusResponseModel } from './LegalStatusResponseModel';
import type { LocationResponseModel } from './LocationResponseModel';
import type { SimplifiedBankAccountStatus } from './SimplifiedBankAccountStatus';
import type { StudentLevels } from './StudentLevels';
import type { VenueContactModel } from './VenueContactModel';
import type { VenueTypeResponseModel } from './VenueTypeResponseModel';
import type { WeekdayOpeningHoursTimespans } from './WeekdayOpeningHoursTimespans';
export type GetVenueResponseModel = {
  activity?: DisplayableActivity | null;
  adageInscriptionDate?: string | null;
  audioDisabilityCompliant?: boolean | null;
  bankAccountStatus?: SimplifiedBankAccountStatus | null;
  bannerMeta?: BannerMetaModel | null;
  bannerUrl?: string | null;
  bookingEmail?: string | null;
  collectiveAccessInformation?: string | null;
  collectiveDescription?: string | null;
  collectiveDmsApplications: Array<DMSApplicationForEAC>;
  collectiveDomains: Array<GetVenueDomainResponseModel>;
  collectiveEmail?: string | null;
  collectiveInterventionArea?: Array<string> | null;
  collectiveLegalStatus?: LegalStatusResponseModel | null;
  collectiveNetwork?: Array<string> | null;
  collectivePhone?: string | null;
  collectiveStudents?: Array<StudentLevels> | null;
  collectiveWebsite?: string | null;
  comment?: string | null;
  contact?: VenueContactModel | null;
  dateCreated: string;
  description?: string | null;
  dmsToken: string;
  externalAccessibilityData?: ExternalAccessibilityDataModel | null;
  externalAccessibilityId?: string | null;
  externalAccessibilityUrl?: string | null;
  hasActiveIndividualOffer: boolean;
  hasAdageId: boolean;
  hasNonFreeOffers: boolean;
  hasOffers: boolean;
  hasPartnerPage: boolean;
  id: number;
  isActive: boolean;
  isCaledonian: boolean;
  isOpenToPublic: boolean;
  isPermanent?: boolean | null;
  isValidated: boolean;
  isVirtual: boolean;
  location?: LocationResponseModel | null;
  managingOfferer: GetVenueManagingOffererResponseModel;
  mentalDisabilityCompliant?: boolean | null;
  motorDisabilityCompliant?: boolean | null;
  name: string;
  openingHours?: WeekdayOpeningHoursTimespans | null;
  pricingPoint?: GetVenuePricingPointResponseModel | null;
  publicName?: string | null;
  siret?: string | null;
  venueLabelId?: number | null;
  venueType: VenueTypeResponseModel;
  visualDisabilityCompliant?: boolean | null;
  withdrawalDetails?: string | null;
};

