#!/usr/bin/env bash
#
# Install Bats

set -e -o pipefail

: ${BATS_VERSION:='1.0.2'}
: ${BATS_SHA1SUM:='62090dd5070f0346cf1cedf06ec277f42b35e292'}
: ${PREFIX:=/usr/local}
: ${SRCDIR:="${PREFIX}/src"}

if [[ "${PREFIX:0:1}" != '/' ]]; then
  echo "$(basename $0): PREFIX must be an absolute path" >&2
  exit 1
fi

if [[ "${SRCDIR:0:1}" != '/' ]]; then
  echo "$(basename $0): SRCDIR must be an absolute path" >&2
  exit 1
fi

if [[ -n "$(which sha1sum)" ]]; then
  sha1_prog='sha1sum -c'
elif [[ -n "$(which shasum)" ]]; then
  sha1_prog='shasum -a 1 -c'
else
  echo "$(basename $0): No sha1 program found" >&2
  exit 1
fi

mkdir -p "${SRCDIR}"
cd "${SRCDIR}"
wget -nv "https://github.com/bats-core/bats-core/archive/v${BATS_VERSION}.tar.gz"
${sha1_prog} <<< "${BATS_SHA1SUM}  v${BATS_VERSION}.tar.gz"
tar -xf "v${BATS_VERSION}.tar.gz"
rm "v${BATS_VERSION}.tar.gz"
cd "bats-core-${BATS_VERSION}"

./install.sh "${PREFIX}"
