QUOTIENT_FAMILIAL_THRESHOLD = 700
MAX_QF_BONUS_RETRIES = 10
QUOTIENT_FAMILIAL_MONTH_RETENTION = 23

BACKOFFICE_ORIGIN_START = "backoffice"
DISABILITY_ENDPOINT_ORIGIN = "enrolled from /subscription/bonus/disability endpoint"
QUOTIENT_FAMILIAL_ENDPOINT_ORIGIN = "enrolled from /subscription/bonus/quotient_familial endpoint"
AUTOMATIC_ORIGIN = "automatic attempt"

MANUAL_FORM_ENDPOINT_ORIGINS = (DISABILITY_ENDPOINT_ORIGIN, QUOTIENT_FAMILIAL_ENDPOINT_ORIGIN)

QUOTIENT_FAMILIAL_CACHE_TTL = 36 * 60 * 60  # 36h
DISABILITY_COUNTDOWN = 60
