from enum import Enum


ANONYMIZED_EMAIL = "anonymized_email@anonymized.passculture"
BOOK_CLUB_FORM_ID = "K20ivtdr"
CINE_CLUB_FORM_ID = "kUeY2sN4"


class BookClub(Enum):
    FORM_ID = "K20ivtdr"
    AGE_ID = "JhzoZvt9BEtw"
    CITY_ID = "3JuCg33mKsKM"
    NAME_ID = "a8i1kybF46rP"
    BOOK_EAN_ID = "CmoeTUGh6ueZ"
    CHRONICLE_ID = "Cns4xsVc2QUB"
    DIFFUSIBLE_PERSONAL_DATA_QUESTION_ID = "HDGU6kbXD5uh"
    DIFFUSIBLE_PERSONAL_DATA_ANSWER_ID = "WOTBxKezQuY9"
    SOCIAL_MEDIA_QUESTION_ID = "j9l8TcDOCNN4"
    SOCIAL_MEDIA_ANSWER_ID = "1KVoMDhUVrEd"


class CineClub(Enum):
    FORM_ID = "kUeY2sN4"
    NAME_ID = "62f6nEVeTOdw"
    MOVIE_ID = "nv8CkjvnYsO1"
    CHRONICLE_ID = "mhuWo0Zb9Y1d"
    DIFFUSIBLE_PERSONAL_DATA_QUESTION_ID = "pmF7QlnbpbXE"
    DIFFUSIBLE_PERSONAL_DATA_ANSWER_ID = "34TU7FpVjo5b"
    SOCIAL_MEDIA_QUESTION_ID = "CiUbpTHx9qiI"
    SOCIAL_MEDIA_ANSWER_ID = "WvzWCPCSwSgZ"
