from enum import Enum


ANONYMIZED_EMAIL = "anonymized_email@anonymized.passculture"
BOOK_CLUB_FORM_ID = "K20ivtdr"
CINE_CLUB_FORM_ID = "kUeY2sN4"
ALBUM_CLUB_FORM_ID = "FT7dfbBL"
CONCERT_CLUB_FORM_ID = "myrTtah4"


class BookClub(Enum):
    FORM_ID = "K20ivtdr"
    AGE_ID = "JhzoZvt9BEtw"
    CITY_ID = "3JuCg33mKsKM"
    NAME_ID = "a8i1kybF46rP"
    PRODUCT_IDENTIFIER_FIELD_ID = "CmoeTUGh6ueZ"
    CHRONICLE_ID = "Cns4xsVc2QUB"
    DIFFUSIBLE_PERSONAL_DATA_QUESTION_ID = "HDGU6kbXD5uh"
    DIFFUSIBLE_PERSONAL_DATA_ANSWER_ID = "WOTBxKezQuY9"
    SOCIAL_MEDIA_QUESTION_ID = "j9l8TcDOCNN4"
    SOCIAL_MEDIA_ANSWER_ID = "1KVoMDhUVrEd"


class CineClub(Enum):
    FORM_ID = "kUeY2sN4"
    NAME_ID = "62f6nEVeTOdw"
    PRODUCT_IDENTIFIER_FIELD_ID = "nv8CkjvnYsO1"
    CHRONICLE_ID = "mhuWo0Zb9Y1d"
    DIFFUSIBLE_PERSONAL_DATA_QUESTION_ID = "pmF7QlnbpbXE"
    DIFFUSIBLE_PERSONAL_DATA_ANSWER_ID = "34TU7FpVjo5b"
    SOCIAL_MEDIA_QUESTION_ID = "CiUbpTHx9qiI"
    SOCIAL_MEDIA_ANSWER_ID = "WvzWCPCSwSgZ"


class AlbumClub(Enum):
    FORM_ID = "FT7dfbBL"
    NAME_ID = "qPBOKBtFD1D5"
    CITY_ID = "8H0SNn3rMUmi"
    AGE_ID = "XyMpGPxZcBD1"
    PRODUCT_IDENTIFIER_FIELD_ID = "smwMQpSSgmwo"
    CHRONICLE_ID = "GP3ZevIqRHaa"
    DIFFUSIBLE_PERSONAL_DATA_QUESTION_ID = "JrSIh3YQudWD"
    DIFFUSIBLE_PERSONAL_DATA_ANSWER_ID = "py2SkTE8PiRe"
    SOCIAL_MEDIA_QUESTION_ID = "GBwA63s82JSl"
    SOCIAL_MEDIA_ANSWER_ID = "KTCAxRq5GtxW"


class ConcertClub(Enum):
    FORM_ID = "myrTtah4"
    NAME_ID = "66kiPjhmAlEd"
    AGE_ID = "GOzm1JeJNWIT"
    CITY_ID = "BGXNzQcR30jC"
    PRODUCT_IDENTIFIER_FIELD_ID = "KIqZcWc2cGDp"
    CHRONICLE_ID = "D2osYjC96ZLI"
    DIFFUSIBLE_PERSONAL_DATA_QUESTION_ID = "f5Wzp0ALiCOZ"
    DIFFUSIBLE_PERSONAL_DATA_ANSWER_ID = "0tE7RXiVjiBt"
    SOCIAL_MEDIA_QUESTION_ID = "zE0vDQnI5TXq"
    SOCIAL_MEDIA_ANSWER_ID = "faYFjYraG1ae"
