#!/bin/bash

protected_branch='master'
warning='[WARNING] You are about to push to '$protected_branch', which requires pull request reviews before merging.'
warning_different_branch='[WARNING] It seems that you are about to push '$current_branch' (local branch) to the remote '$protected_branch' branch.'
confirmation_query='Are you sure ? [Y/n]'
YELLOW='\033[33m'
NOCOLOR='\033[0m'

# GET PUSH TARGET
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
push_command=$(ps -ocommand= -p $PPID)
push_only='git push'

# Case: git push origin master, on branch master
if [[ $push_command =~ $protected_branch ]] && [ $current_branch = $protected_branch ]; then
    echo -e "${YELLOW}$warning${NOCOLOR}"
    echo -e "$confirmation_query"
    read -r < /dev/tty
    if [[ $REPLY = 'Y' ]]; then
        exit 0
    else
        exit 1
    fi
# Case: git push, on branch master
elif [[ $push_command =~ $push_only ]] && [ $current_branch = $protected_branch ]; then
    echo -e "${YELLOW}$warning${NOCOLOR}"
    echo -e "$confirmation_query"
    read -r < /dev/tty
    if [[ $REPLY = 'Y' ]]; then
        exit 0
    else
        exit 1
    fi
# Case: git push origin master, on some other branch
elif [[ $push_command =~ $protected_branch ]] && [ $current_branch != $protected_branch ]; then
    echo -e "${YELLOW}$warning_different_branch${NOCOLOR}"
    echo -e "$confirmation_query"
    read -r < /dev/tty
    if [[ $REPLY = 'Y' ]]; then
        exit 0
    else
        exit 1
    fi
# Case: all other cases
else
    exit 0
fi