# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates

version: 2

updates:
  # Pro - Frontend
  - package-ecosystem: 'npm'
    directory: '/pro'
    schedule:
      # Sync with a new sherif week, starting on Thursday morning after tag
      interval: 'weekly'
      day: "thursday"
      time: '10:00'
      timezone: "Europe/Paris"
    open-pull-requests-limit: 15
    cooldown:
      default-days: 7
      semver-major-days: 14
    ignore:
      - dependency-name: "openapi-typescript-codegen"

  # Public API doc
  - package-ecosystem: 'npm'
    directory: '/api/documentation'
    schedule:
      interval: 'weekly'
      day: "thursday"
      time: '08:00'
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
      semver-major-days: 14

  # API - Backend
  - package-ecosystem: 'uv'
    directory: '/api'
    schedule:
      # Sync with a new sherif week, starting on Thursday morning
      interval: 'weekly'
      day: "thursday"
      time: '07:00'
      timezone: "Europe/Paris"
    open-pull-requests-limit: 15
    cooldown:
      default-days: 7
      semver-major-days: 14
    ignore:
      - dependency-name: 'flask'
        update-types:
          - "version-update:semver-major"
      - dependency-name: 'sqlalchemy'
        update-types:
          - "version-update:semver-major"
      - dependency-name: 'pydantic'
        update-types:
          - "version-update:semver-major"
      # boto3 updates very frequently
      - dependency-name: 'boto3'
        update-types:
          - "version-update:semver-patch"

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directories:
      - '.github/workflows'
      - '.github/actions/*'
    schedule:
      # first day og the month
      interval: 'monthly'
    open-pull-requests-limit: 10
    cooldown:
      # The property 'semver-major-days' is not supported for the package ecosystem 'github-actions'.
      default-days: 14
