export { ReactComponent as LogoPassCultureDarkIcon } from 'icons/logo-pass-culture-dark.svg'
export { ReactComponent as SearchIcon } from 'icons/ico-search.svg'
export { ReactComponent as TicketPlusFullIcon } from 'icons/ico-ticket-plus-full.svg'
export { ReactComponent as TrashFilledIcon } from 'icons/ico-trash-filled.svg'
export { ReactComponent as Venue2Icon } from 'icons/venue-2.svg'
export { ReactComponent as InstitutionIcon } from 'icons/ico-institution.svg'
