export const SAVE_RECOMMENDATIONS_REQUEST_TIMESTAMP = 'SAVE_RECOMMENDATIONS_REQUEST_TIMESTAMP'

export const saveLastRecommendationsRequestTimestamp = () => ({
  type: SAVE_RECOMMENDATIONS_REQUEST_TIMESTAMP,
})
