import dataclasses


@dataclasses.dataclass
class City:
    name: str
    departement_code: int
    postal_code: int | None = None


# Retrieved from staging with following query:
# select * from venue where city='<city>' and "isPermanent"=True
# then I only kept the first venue per venueTypeCode
paris_venues = [
    {
        "name": "QUAI DES SONGES",
        "latitude": "48.88387",
        "longitude": "2.37157",
        "address": "7 Quai de la Loire",
        "postalCode": "75019",
        "city": "PARIS",
        "departementCode": "75",
    },
    {
        "name": "DOMAINE NATIONAL DU PALAIS-ROYAL, entrée place Colette",
        "latitude": "48.86336",
        "longitude": "2.33607",
        "address": "Gal du Théâtre Français",
        "postalCode": "75001",
        "city": "PARIS",
        "departementCode": "75",
    },
    {
        "name": "Centre Paris Anim Rebeval",
        "latitude": "48.87438",
        "longitude": "2.37833",
        "address": "36 Rue Rébeval",
        "postalCode": "75019",
        "city": "PARIS",
        "departementCode": "75",
    },
    {
        "name": "THEATRE DE LA GAITE MONTPARNASSE",
        "latitude": "48.83932",
        "longitude": "2.32317",
        "address": "26 Rue de la Gaîté",
        "postalCode": "75014",
        "city": "PARIS",
        "departementCode": "75",
    },
    {
        "name": "WOODBRASS COM",
        "latitude": "48.88785",
        "longitude": "2.39018",
        "address": "182 Avenue Jean Jaurès",
        "postalCode": "75019",
        "city": "PARIS",
        "departementCode": "75",
    },
    {
        "name": "B'ZZ boutique et galerie au CENTQUATRE Paris",
        "latitude": "48.88998",
        "longitude": "2.37151",
        "address": "5 Rue Curial",
        "postalCode": "75019",
        "city": "PARIS",
        "departementCode": "75",
    },
    {
        "name": "Centre Paris Anim Daviel",
        "latitude": "48.82815",
        "longitude": "2.34483",
        "address": "24 Rue Daviel",
        "postalCode": "75013",
        "city": "PARIS",
        "departementCode": "75",
    },
    {
        "name": "BALADES SONORES",
        "latitude": "48.88171",
        "longitude": "2.34611",
        "address": "3 Avenue Trudaine",
        "postalCode": "75009",
        "city": "PARIS",
        "departementCode": "75",
    },
    {
        "name": "Médiation - Musée d'art et d'histoire du Judaïsme",
        "latitude": "48.86096",
        "longitude": "2.35562",
        "address": "71 Rue du Temple",
        "postalCode": "75003",
        "city": "PARIS",
        "departementCode": "75",
    },
    {
        "name": "ITABUNA",
        "latitude": "48.85643",
        "longitude": "2.35648",
        "address": "38 Rue de Rivoli",
        "postalCode": "75004",
        "city": "PARIS",
        "departementCode": "75",
    },
    {
        "name": "Virtual Room Paris",
        "latitude": "48.85801",
        "longitude": "2.37089",
        "address": "35 Boulevard Richard Lenoir",
        "postalCode": "75011",
        "city": "PARIS",
        "departementCode": "75",
    },
    {
        "name": "Site François Mitterrand",
        "latitude": "48.83309",
        "longitude": "2.37871",
        "address": "Quai François Mauriac",
        "postalCode": "75013",
        "city": "PARIS",
        "departementCode": "75",
    },
    {
        "name": "EDEN PLUS",
        "latitude": "48.87136",
        "longitude": "2.34490",
        "address": "24 Boulevard Poissonnière",
        "postalCode": "75009",
        "city": "PARIS",
        "departementCode": "75",
    },
    {
        "name": "PARC ZOOLOGIQUE DE PARIS",
        "latitude": "48.83333",
        "longitude": "2.41417",
        "address": "Angle avenue Daumesnil - Route de la ceinture du lac",
        "postalCode": "75012",
        "city": "PARIS",
        "departementCode": "75",
    },
    {
        "name": "VILLE DE PARIS",
        "latitude": "48.86008",
        "longitude": "2.34106",
        "address": "4 Place du Louvre",
        "postalCode": "75001",
        "city": "PARIS",
        "departementCode": "75",
    },
    {
        "name": "ADAM MONTPARNASSE - DALBE PARIS 14",
        "latitude": "48.84090",
        "longitude": "2.32488",
        "address": "11 Boulevard Edgar Quinet",
        "postalCode": "75014",
        "city": "PARIS",
        "departementCode": "75",
    },
    {
        "name": "QJ - Quartiers Jeunes",
        "latitude": "48.86008",
        "longitude": "2.34106",
        "address": "4 Place du Louvre",
        "postalCode": "75001",
        "city": "PARIS",
        "departementCode": "75",
    },
    {
        "name": "Festival We Love Green - Bois de Vincennes",
        "latitude": "48.83116",
        "longitude": "2.43942",
        "address": "Plaine de la Belle Etoile Route Dauphiné via L’Esplanade Saint Louis Bois de Vincennes",
        "postalCode": "75012",
        "city": "PARIS",
        "departementCode": "75",
    },
]

# I used `where "departementCode"='976'` to have more results
mayotte_venues = [
    {
        "name": "POLE CULTUREL DE CHIRONGUI",
        "latitude": "-12.93546",
        "longitude": "45.14915",
        "address": "425 rue Saïd VITTA",
        "postalCode": "97620",
        "city": "Chirongui",
        "departementCode": "976",
    },
    {
        "name": "ASSOCIATION MUSIQUE A MAYOTTE",
        "latitude": "-12.78114",
        "longitude": "45.22471",
        "address": "2 RUE DES 100 VILLAS",
        "postalCode": "97600",
        "city": "MAMOUDZOU",
        "departementCode": "976",
    },
    {
        "name": "LA BOUQUINERIE DE PASSAMAINTY",
        "latitude": "-12.80201",
        "longitude": "45.21202",
        "address": "15 RUE DE VAHIBE",
        "postalCode": "97600",
        "city": "MAMOUDZOU",
        "departementCode": "976",
    },
    {
        "name": "MAIRIE",
        "latitude": "-12.70421",
        "longitude": "45.12184",
        "address": "238 RUE DE L HOTEL DE VILLE",
        "postalCode": "97650",
        "city": "BANDRABOUA",
        "departementCode": "976",
    },
    {
        "name": "Musée de Mayotte (MUMA)",
        "latitude": "-12.78207",
        "longitude": "45.25710",
        "address": "Place de France",
        "postalCode": "97615",
        "city": "Dzaoudzi",
        "departementCode": "976",
    },
    {
        "name": "Le M'Haju",
        "latitude": "-12.91746",
        "longitude": "45.18540",
        "address": "2275 Boulevard Moida Said",
        "postalCode": "97660",
        "city": "Bandrele",
        "departementCode": "976",
    },
    {
        "name": "Site de Valarano entre Coconi et Kahani",
        "latitude": "-12.83082",
        "longitude": "45.13500",
        "address": "20 Rue Ibrahim Ramadani",
        "postalCode": "97670",
        "city": "Ouangani",
        "departementCode": "976",
    },
    {
        "name": "ESPACE FOURNITURES",
        "latitude": "-12.77588",
        "longitude": "45.22571",
        "address": "4000 f Route Nationale 1",
        "postalCode": "97600",
        "city": "Mamoudzou",
        "departementCode": "976",
    },
    {
        "name": "Cinéma De Chirongui",
        "latitude": "-12.93555",
        "longitude": "45.14910",
        "address": "425 Avenue Said Vitta",
        "postalCode": "97620",
        "city": "Chirongui",
        "departementCode": "976",
    },
    {
        "name": "AGENCE REGIONALE DU LIVRE ET DE LA LECTURE DE MAYOTTE",
        "latitude": "-12.83684",
        "longitude": "45.11327",
        "address": "6 RUE DE SICOTRAM",
        "postalCode": "97670",
        "city": "CHICONI",
        "departementCode": "976",
    },
    {
        "name": "KAMALDINE BEN AZALI",
        "latitude": "-12.79760",
        "longitude": "45.20087",
        "address": "Mamoudzou",
        "postalCode": "97600",
        "city": "Mamoudzou",
        "departementCode": "976",
    },
]

lyon_venues = [
    {
        "name": "PATHE CINEMAS FRANCE",
        "latitude": "45.78734",
        "longitude": "4.81211",
        "address": "43 Rue des Docks",
        "postalCode": "69009",
        "city": "Lyon",
        "departementCode": "69",
    },
    {
        "name": "LIBRAIRIE LES BIBLIOS",
        "latitude": "45.76675",
        "longitude": "4.84482",
        "address": "34 Rue Cuvier",
        "postalCode": "69006",
        "city": "Lyon",
        "departementCode": "69",
    },
    {
        "name": "Musée Lumière",
        "latitude": "45.74498",
        "longitude": "4.87047",
        "address": "25 Rue du Premier Film",
        "postalCode": "69008",
        "city": "Lyon",
        "departementCode": "69",
    },
    {
        "name": "BAILA CONMIGO",
        "latitude": "45.74960",
        "longitude": "4.84520",
        "address": "35 RUE CREUZET",
        "postalCode": "69007",
        "city": "LYON 7EME",
        "departementCode": "69",
    },
    {
        "name": "MAISON DES JEUNES ET DE LA CULTURE",
        "latitude": "45.74292",
        "longitude": "4.79925",
        "address": "112 AVENUE MARECHAL FOCH",
        "postalCode": "69110",
        "city": "SAINTE-FOY-LES-LYON",
        "departementCode": "69",
    },
    {
        "name": "Studio Ben",
        "latitude": "45.75660",
        "longitude": "4.87294",
        "address": "6 RUE SAINT EUSEBE",
        "postalCode": "69003",
        "city": "LYON 3EME",
        "departementCode": "69",
    },
    {
        "name": "LIVITY RECORDS",
        "latitude": "45.76672",
        "longitude": "4.82785",
        "address": "1 RUE DOCTEUR AUGROS",
        "postalCode": "69005",
        "city": "LYON 5EME",
        "departementCode": "69",
    },
    {
        "name": "CAPSULE CORP",
        "latitude": "45.77046",
        "longitude": "4.84224",
        "address": "10 RUE SULLY",
        "postalCode": "69006",
        "city": "LYON 6EME",
        "departementCode": "69",
    },
    {
        "name": "A B C G",
        "latitude": "45.76079",
        "longitude": "4.82832",
        "address": "27 QUAI ROMAIN ROLLAND",
        "postalCode": "69005",
        "city": "LYON 5EME",
        "departementCode": "69",
    },
    {
        "name": "BIBLIOTHEQUE DE LA PART-DIEU",
        "latitude": "45.76025",
        "longitude": "4.85786",
        "address": "30 Boulevard Marius Vivier-Merle",
        "postalCode": "69003",
        "city": "Lyon",
        "departementCode": "69",
    },
    {
        "name": "ONIGIRI RECORDS",
        "latitude": "45.74809",
        "longitude": "4.84091",
        "address": "40 RUE CHEVREUL",
        "postalCode": "69007",
        "city": "LYON 7EME",
        "departementCode": "69",
    },
    {
        "name": "Chapelle de la Trinité",
        "latitude": "45.76528",
        "longitude": "4.83700",
        "address": "31 Rue de la Bourse",
        "postalCode": "69002",
        "city": "Lyon",
        "departementCode": "69",
    },
    {
        "name": "THEATRE DE GERLAND",
        "latitude": "45.73847",
        "longitude": "4.83927",
        "address": "7 RUE RAVIER",
        "postalCode": "69007",
        "city": "LYON 7EME",
        "departementCode": "69",
    },
    {
        "name": "GERSTAECKER LYON LE GEANT DES BEAUX ARTS",
        "latitude": "45.76728",
        "longitude": "4.83680",
        "address": "3 RUE DU GARET",
        "postalCode": "69001",
        "city": "LYON 1ER",
        "departementCode": "69",
    },
    {
        "name": "SOIERIE VIVANTE",
        "latitude": "45.78020",
        "longitude": "4.83685",
        "address": "21 RUE RICHAN",
        "postalCode": "69004",
        "city": "LYON 4EME",
        "departementCode": "69",
    },
    {
        "name": "H7",
        "latitude": "45.73691",
        "longitude": "4.82021",
        "address": "70 Quai Perrache",
        "postalCode": "69002",
        "city": "Lyon",
        "departementCode": "69",
    },
    {
        "name": "THEATRE ISHTAR",
        "latitude": "45.74704",
        "longitude": "4.83580",
        "address": "14 Avenue Berthelot",
        "postalCode": "69007",
        "city": "Lyon",
        "departementCode": "69",
    },
    {
        "name": "COMMUNAUTE D'UNIVERSITES ET ETABLISSEMENTS (COMUE) UNIVERSITE DE LYON",
        "latitude": "45.72996",
        "longitude": "4.82796",
        "address": "1 Place de l'Ecole",
        "postalCode": "69007",
        "city": "Lyon",
        "departementCode": "69",
    },
    {
        "name": "S-A",
        "latitude": "45.75832",
        "longitude": "4.83463",
        "address": "85 Rue de la République",
        "postalCode": "69002",
        "city": "Lyon",
        "departementCode": "69",
    },
]

# Other venues extracted randomly from staging
venues = [
    {
        "name": "AGORA",
        "latitude": 46.66979,
        "longitude": -1.42979,
        "address": "11 RUE GEORGES CLEMENCEAU",
        "postalCode": "85000",
        "city": "LA ROCHE-SUR-YON",
        "departementCode": 85,
    },
    {
        "name": "LIS TES RATURES",
        "latitude": 45.91967,
        "longitude": 3.06504,
        "address": "13 AVENUE BARADUC",
        "postalCode": "63140",
        "city": "CHATEL-GUYON",
        "departementCode": 63,
    },
    {
        "name": "LES COCOTTES ROUSSES",
        "latitude": 45.63219,
        "longitude": 4.85595,
        "address": "3 PLACE DU MARCHE",
        "postalCode": "69360",
        "city": "SAINT SYMPHORIEN D'OZON",
        "departementCode": 69,
    },
    {
        "name": "FNAC Paris - Forum des Halles",
        "latitude": 48.86380,
        "longitude": 2.34546,
        "address": "IMPASSE SAINT EUSTACHE",
        "postalCode": "75001",
        "city": "PARIS 1",
        "departementCode": 75,
    },
    {
        "name": "librairie saint martin",
        "latitude": 44.43096,
        "longitude": -0.21206,
        "address": "2 Rue Saint-Martin",
        "postalCode": "33430",
        "city": "Bazas",
        "departementCode": 33,
    },
    {
        "name": "SGEC CORSE",
        "latitude": 41.91896,
        "longitude": 8.73888,
        "address": "2 Place Maréchal Foch",
        "postalCode": "20000",
        "city": "Ajaccio",
        "departementCode": 20,
    },
    {
        "name": "SOCULTUR",
        "latitude": 48.95016,
        "longitude": 2.67394,
        "address": "RUE VICTOR DROUET",
        "postalCode": "77410",
        "city": "CLAYE-SOUILLY",
        "departementCode": 77,
    },
    {
        "name": "LIBRAIRIE PAPETERIE CHRISTMANN SARL",
        "latitude": 48.87810,
        "longitude": 2.70487,
        "address": "15 RUE DES MARCHES",
        "postalCode": "77400",
        "city": "LAGNY-SUR-MARNE",
        "departementCode": 77,
    },
    {
        "name": "UN EN DEHORS",
        "latitude": 45.76941,
        "longitude": 4.83463,
        "address": "18 RUE DES CAPUCINS",
        "postalCode": "69001",
        "city": "LYON 1ER",
        "departementCode": 69,
    },
    {
        "name": "WH SMITH FRANCE",
        "latitude": 48.86622,
        "longitude": 2.32493,
        "address": "248 RUE DE RIVOLI",
        "postalCode": "75001",
        "city": "PARIS",
        "departementCode": "75",
    },
]
