venues = [
    {
        "name": "AGORA",
        "latitude": 46.66979,
        "longitude": -1.42979,
        "address": "11 RUE GEORGES CLEMENCEAU",
        "postalCode": "85000",
        "city": "LA ROCHE-SUR-YON",
        "departementCode": 85,
    },
    {
        "name": "LIS TES RATURES",
        "latitude": 45.91967,
        "longitude": 3.06504,
        "address": "13 AVENUE BARADUC        ",
        "postalCode": "63140",
        "city": "CHATEL-GUYON",
        "departementCode": 63,
    },
    {
        "name": "LES COCOTTES ROUSSES",
        "latitude": 45.63219,
        "longitude": 4.85595,
        "address": "3 PLACE DU MARCHE        ",
        "postalCode": "69360",
        "city": "SAINT SYMPHORIEN D'OZON",
        "departementCode": 69,
    },
    {
        "name": "FNAC Paris - Forum des Halles",
        "latitude": 48.86380,
        "longitude": 2.34546,
        "address": "IMPASSE SAINT EUSTACHE   ",
        "postalCode": "75001",
        "city": "PARIS 1",
        "departementCode": 75,
    },
    {
        "name": "librairie saint martin",
        "latitude": 44.43096,
        "longitude": -0.21206,
        "address": "2 Rue Saint-Martin       ",
        "postalCode": "33430",
        "city": "Bazas",
        "departementCode": 33,
    },
    {
        "name": "SGEC CORSE",
        "latitude": 41.91896,
        "longitude": 8.73888,
        "address": "2 Place Maréchal Foch    ",
        "postalCode": "20000",
        "city": "Ajaccio",
        "departementCode": 20,
    },
    {
        "name": "SOCULTUR",
        "latitude": 48.95016,
        "longitude": 2.67394,
        "address": "RUE VICTOR DROUET        ",
        "postalCode": "77410",
        "city": "CLAYE-SOUILLY",
        "departementCode": 77,
    },
    {
        "name": "LIBRAIRIE PAPETERIE CHRISTMANN SARL",
        "latitude": 48.87810,
        "longitude": 2.70487,
        "address": "15 RUE DES MARCHES       ",
        "postalCode": "77400",
        "city": "LAGNY-SUR-MARNE",
        "departementCode": 77,
    },
    {
        "name": "UN EN DEHORS",
        "latitude": 45.76941,
        "longitude": 4.83463,
        "address": "18 RUE DES CAPUCINS      ",
        "postalCode": "69001",
        "city": "LYON 1ER",
        "departementCode": 69,
    },
    {
        "name": "WH SMITH FRANCE",
        "latitude": 48.86622,
        "longitude": 2.32493,
        "address": "248 RUE DE RIVOLI        ",
        "postalCode": "75001",
        "city": "PARIS 1",
        "departementCode": 75,
    },
]
