export const CATEGORY_LABEL = 'Catégorie'
export const SUBCATEGORY_LABEL = 'Sous-catégorie'
export const TITLE_LABEL = 'Titre de l’offre'
export const DESCRIPTION_LABEL = 'Description'
export const DURATION_LABEL = 'Durée'
export const OFFERER_LABEL = 'Structure'
export const VENUE_LABEL = 'Lieu qui percevra le remboursement'
export const EVENT_ADDRESS_OFFERER_LABEL = 'Dans votre lieu'
export const EVENT_ADDRESS_SCHOOL_LABEL = 'Dans l’établissement scolaire'
export const EVENT_ADDRESS_OTHER_LABEL = 'Autre'
export const EVENT_ADDRESS_OFFERER_VENUE_SELECT_LABEL = 'Sélectionner le lieu'
export const EVENT_ADDRESS_OTHER_ADDRESS_LABEL = 'Adresse de l’évènement'
export const PHONE_LABEL = 'Téléphone'
export const EMAIL_LABEL = 'E-mail'
export const NOTIFICATIONS_LABEL = 'Être notifié par e-mail des réservations'
export const NOTIFICATIONS_EMAIL_LABEL =
  'E-mail auquel envoyer les notifications'
