export const CATEGORY_LABEL = 'Catégorie'
export const SUBCATEGORY_LABEL = 'Sous-catégorie'
export const TITLE_LABEL = 'Titre de l’offre'
export const DESCRIPTION_LABEL = 'Description'
export const DURATION_LABEL = 'Durée'
export const OFFERER_LABEL = 'Structure'
export const VENUE_LABEL = 'Lieu'
export const EVENT_ADDRESS_OFFERER_LABEL = 'Dans votre lieu'
export const EVENT_ADDRESS_SCHOOL_LABEL = 'Dans l’établissement scolaire'
export const EVENT_ADDRESS_OTHER_LABEL = 'Autre'
export const EVENT_ADDRESS_OFFERER_VENUE_SELECT_LABEL = 'Sélectionner le lieu'
export const EVENT_ADDRESS_OTHER_ADDRESS_LABEL = 'Adresse de l’évènement'
export const EMAIL_LABEL = 'Email'
export const NOTIFICATIONS_EMAIL_LABEL =
  'Email auquel envoyer les notifications'
export const INTERVENTION_AREA_LABEL = 'Zone de mobilité pour l’évènement'
export const INTERVENTION_AREA_PLURAL_LABEL =
  'Zones de mobilité pour l’évènement'
export const PRICE_INFORMATION = 'Informations sur le prix'
