import classnames from 'classnames'
import get from 'lodash.get'
import { closeModal } from 'pass-culture-shared'
import React, { Component, Fragment } from 'react'
import PropTypes from 'prop-types'

import StockItem from './StockItem'
import HeroSection from 'components/layout/HeroSection'

class RawStocksManager extends Component {
  constructor() {
    super()
    this.state = {
      errors: null,
      info: null,
    }
  }

  componentDidMount() {
    this.elem.focus()
    document.addEventListener('keydown', this.onKeydown)
  }

  componentWillUnmount() {
    document.removeEventListener('keydown', this.onKeydown)
  }

  handleEscKey() {
    const { query } = this.props
    const { id: stockId } = query.context('stock')
    if (!stockId) {
      this.onCloseClick()
    } else {
      const cancelButton = document.getElementsByClassName('cancel-step')[0]
      cancelButton.click()
    }
  }

  handleEnterKey() {
    const { query } = this.props
    const { id: stockId } = query.context('stock')
    // Dirty DOM selectors but...
    if (!stockId) {
      // This dom node is generated by react-router-dom's <NavLink /> component wich is
      // a 'Function component' and...
      // Warning: Function components cannot be given refs. Attempts to access this ref will fail.
      document.getElementById('add-stock').focus()
      query.changeToCreationUrl('stock')
    } else {
      // Could fetch ref from the included components, but it will be far more complex
      // as we would have to make the ref transit through callback props.
      // We could probably use context though, but I am not familiar enough with this yet
      // and done is better than perfect
      const submitButton = document.getElementsByClassName('submitStep')[0]
      submitButton.click()
    }
  }

  handleSetErrors = errors => {
    this.setState({ errors })
  }

  closeInfo = () => {
    this.setState({ info: null })
  }

  showInfo = info => {
    this.setState({ info })
  }

  onCloseClick = e => {
    const { dispatch, offer, history } = this.props
    dispatch(closeModal())
    history.push(`/offres/${get(offer, 'id')}`)
  }

  onKeydown = event => {
    if (event.key === 'Enter') {
      this.handleEnterKey()
    } else if (event.key === 'Escape') {
      this.handleEscKey()
    }
  }

  renderTableHead() {
    const { isEventStock } = this.props
    return (
      <thead>
        <tr>
          {isEventStock && (
            <Fragment>
              <td>Date</td>
              <td>
                Heure de
                <br />
                début
              </td>
              <td>
                Heure de
                <br />
                fin
              </td>
            </Fragment>
          )}
          <td>Prix</td>
          <td>Date Limite de Réservation</td>
          <td>{isEventStock ? 'Stock affecté' : 'Places affectées'}</td>
          <td>{isEventStock ? 'Stock restant' : 'Places restantes'}</td>
          <td>Modifier</td>
          <td>Supprimer</td>
        </tr>
      </thead>
    )
  }

  render() {
    const { event, isEventStock, provider, stocks, thing, query } = this.props
    const { errors, info } = this.state
    const { isCreatedEntity, readOnly } = query.context('stock')

    return (
      <div className="stocks-manager" ref={elem => (this.elem = elem)}>
        <div className={classnames('info', { 'is-invisible': !info })}>
          <div className="content">
            <div>{info}</div>
          </div>
        </div>

        {errors && (
          <div className="notification is-danger">
            {Object.keys(errors).map(key => (
              <p key={key}>
                {' '}
                {key} : {errors[key]}
              </p>
            ))}
          </div>
        )}
        <div className="stocks-table-wrapper">
          <HeroSection
            title={
              get(event, 'id')
                ? 'Dates, horaires et prix'
                : get(thing, 'id') && 'Prix'
            }
            subtitle={get(event, 'name') || get(thing, 'name')}
          />
          <table
            className={classnames('table is-hoverable stocks-table', {
              small: !isEventStock,
            })}>
            {this.renderTableHead()}
            {provider ? (
              <tbody>
                <tr>
                  <td colSpan="10">
                    <i>
                      Il n'est pas possible d'ajouter ni de supprimer d'horaires
                      pour cet événement {provider.name}
                    </i>
                  </td>
                </tr>
              </tbody>
            ) : (
              <tbody>
                <tr
                  className={classnames({
                    inactive: !isEventStock && stocks.length,
                  })}>
                  <td colSpan="10">
                    <button
                      className="button is-secondary"
                      disabled={!readOnly}
                      id="add-stock"
                      onClick={() => query.changeToCreationUrl('stock')}
                      type="button">
                      {isEventStock
                        ? '+ Ajouter une date'
                        : stocks.length
                        ? ''
                        : 'Renseigner le stock'}
                    </button>
                  </td>
                </tr>
              </tbody>
            )}

            {isCreatedEntity && (
              <StockItem
                closeInfo={this.closeInfo}
                handleSetErrors={this.handleSetErrors}
                isFullyEditable={!provider}
                isEventStock={isEventStock}
                showInfo={this.showInfo}
              />
            )}

            {stocks.map(stock => (
              <StockItem
                closeInfo={this.closeInfo}
                key={stock.id}
                handleSetErrors={this.handleSetErrors}
                isFullyEditable={!provider}
                isEventStock={isEventStock}
                showInfo={this.showInfo}
                stock={stock}
                stocks={stocks}
              />
            ))}

            {Math.max(get(stocks, 'length', 0)) > 12 && this.renderTableHead()}
          </table>
        </div>
        <button
          className="button is-secondary is-pulled-right"
          id="close-manager"
          onClick={this.onCloseClick}>
          Fermer
        </button>
      </div>
    )
  }
}

RawStocksManager.defaultProps = {
  stocks: [],
}

RawStocksManager.propTypes = {
  stocks: PropTypes.array,
}

export default RawStocksManager
