import { Option } from '@/ui-kit/MultiSelect/MultiSelect'

export const mainlandOptions: Option[] = [
  { id: '01', label: '01 - Ain' },
  { id: '02', label: '02 - Aisne' },
  { id: '03', label: '03 - Allier' },
  { id: '04', label: '04 - Alpes-de-Haute-Provence' },
  { id: '05', label: '05 - Hautes-Alpes' },
  { id: '06', label: '06 - Alpes-Maritimes' },
  { id: '07', label: '07 - Ardèche' },
  { id: '08', label: '08 - Ardennes' },
  { id: '09', label: '09 - Ariège' },
  { id: '10', label: '10 - Aube' },
  { id: '11', label: '11 - Aude' },
  { id: '12', label: '12 - Aveyron' },
  { id: '13', label: '13 - Bouches-du-Rhône' },
  { id: '14', label: '14 - Calvados' },
  { id: '15', label: '15 - Cantal' },
  { id: '16', label: '16 - Charente' },
  { id: '17', label: '17 - Charente-Maritime' },
  { id: '18', label: '18 - Cher' },
  { id: '19', label: '19 - Corrèze' },
  { id: '2A', label: '2A - Corse-du-Sud' },
  { id: '2B', label: '2B - Haute-Corse' },
  { id: '21', label: '21 - Côte-d’Or' },
  { id: '22', label: '22 - Côtes-d’Armor' },
  { id: '23', label: '23 - Creuse' },
  { id: '24', label: '24 - Dordogne' },
  { id: '25', label: '25 - Doubs' },
  { id: '26', label: '26 - Drôme' },
  { id: '27', label: '27 - Eure' },
  { id: '28', label: '28 - Eure-et-Loir' },
  { id: '29', label: '29 - Finistère' },
  { id: '30', label: '30 - Gard' },
  { id: '31', label: '31 - Haute-Garonne' },
  { id: '32', label: '32 - Gers' },
  { id: '33', label: '33 - Gironde' },
  { id: '34', label: '34 - Hérault' },
  { id: '35', label: '35 - Ille-et-Vilaine' },
  { id: '36', label: '36 - Indre' },
  { id: '37', label: '37 - Indre-et-Loire' },
  { id: '38', label: '38 - Isère' },
  { id: '39', label: '39 - Jura' },
  { id: '40', label: '40 - Landes' },
  { id: '41', label: '41 - Loir-et-Cher' },
  { id: '42', label: '42 - Loire' },
  { id: '43', label: '43 - Haute-Loire' },
  { id: '44', label: '44 - Loire-Atlantique' },
  { id: '45', label: '45 - Loiret' },
  { id: '46', label: '46 - Lot' },
  { id: '47', label: '47 - Lot-et-Garonne' },
  { id: '48', label: '48 - Lozère' },
  { id: '49', label: '49 - Maine-et-Loire' },
  { id: '50', label: '50 - Manche' },
  { id: '51', label: '51 - Marne' },
  { id: '52', label: '52 - Haute-Marne' },
  { id: '53', label: '53 - Mayenne' },
  { id: '54', label: '54 - Meurthe-et-Moselle' },
  { id: '55', label: '55 - Meuse' },
  { id: '56', label: '56 - Morbihan' },
  { id: '57', label: '57 - Moselle' },
  { id: '58', label: '58 - Nièvre' },
  { id: '59', label: '59 - Nord' },
  { id: '60', label: '60 - Oise' },
  { id: '61', label: '61 - Orne' },
  { id: '62', label: '62 - Pas de Calais' },
  { id: '63', label: '63 - Puy-de-Dôme' },
  { id: '64', label: '64 - Pyrénées-Atlantiques' },
  { id: '65', label: '65 - Hautes-Pyrénées' },
  { id: '66', label: '66 - Pyrénées-Orientales' },
  { id: '67', label: '67 - Bas-Rhin' },
  { id: '68', label: '68 - Haut-Rhin' },
  { id: '69', label: '69 - Rhône' },
  { id: '70', label: '70 - Haute-Saône' },
  { id: '71', label: '71 - Saône-et-Loire' },
  { id: '72', label: '72 - Sarthe' },
  { id: '73', label: '73 - Savoie' },
  { id: '74', label: '74 - Haute-Savoie' },
  { id: '75', label: '75 - Paris' },
  { id: '76', label: '76 - Seine-Maritime' },
  { id: '77', label: '77 - Seine-et-Marne' },
  { id: '78', label: '78 - Yvelines' },
  { id: '79', label: '79 - Deux-Sèvres' },
  { id: '80', label: '80 - Somme' },
  { id: '81', label: '81 - Tarn' },
  { id: '82', label: '82 - Tarn-et-Garonne' },
  { id: '83', label: '83 - Var' },
  { id: '84', label: '84 - Vaucluse' },
  { id: '85', label: '85 - Vendée' },
  { id: '86', label: '86 - Vienne' },
  { id: '87', label: '87 - Haute-Vienne' },
  { id: '88', label: '88 - Vosges' },
  { id: '89', label: '89 - Yonne' },
  { id: '90', label: '90 - Territoire de Belfort' },
  { id: '91', label: '91 - Essonne' },
  { id: '92', label: '92 - Hauts-de-Seine' },
  { id: '93', label: '93 - Seine-Saint-Denis' },
  { id: '94', label: '94 - Val-de-Marne' },
  { id: '95', label: '95 - Val-d’Oise' },
]

export const domtomOptions: Option[] = [
  { id: '971', label: '971 - Guadeloupe' },
  { id: '972', label: '972 - Martinique' },
  { id: '973', label: '973 - Guyane' },
  { id: '974', label: '974 - La Réunion' },
  { id: '975', label: '975 - Saint-Pierre-Et-Miquelon' },
  { id: '976', label: '976 - Mayotte' },
]

const MAINLAND_OPTION_VALUE = 'mainland'
const MAINLAND_OPTION_LABEL = 'France métropolitaine'

export const mainlandInterventionOption = {
  id: MAINLAND_OPTION_VALUE,
  label: MAINLAND_OPTION_LABEL,
}

export const offerInterventionOptions: Option[] = [
  mainlandInterventionOption,
  ...mainlandOptions,
  ...domtomOptions,
]
