/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * An enumeration.
 */
export enum VenueTypeEnum {
  ADMINISTRATIVE = 'ADMINISTRATIVE',
  ARTISTIC_COURSE = 'ARTISTIC_COURSE',
  BOOKSTORE = 'BOOKSTORE',
  CONCERT_HALL = 'CONCERT_HALL',
  CREATIVE_ARTS_STORE = 'CREATIVE_ARTS_STORE',
  CULTURAL_CENTRE = 'CULTURAL_CENTRE',
  DIGITAL = 'DIGITAL',
  DISTRIBUTION_STORE = 'DISTRIBUTION_STORE',
  FESTIVAL = 'FESTIVAL',
  GAMES = 'GAMES',
  LIBRARY = 'LIBRARY',
  MOVIE = 'MOVIE',
  MUSEUM = 'MUSEUM',
  MUSICAL_INSTRUMENT_STORE = 'MUSICAL_INSTRUMENT_STORE',
  OTHER = 'OTHER',
  PATRIMONY_TOURISM = 'PATRIMONY_TOURISM',
  PERFORMING_ARTS = 'PERFORMING_ARTS',
  RECORD_STORE = 'RECORD_STORE',
  SCIENTIFIC_CULTURE = 'SCIENTIFIC_CULTURE',
  TRAVELING_CINEMA = 'TRAVELING_CINEMA',
  VISUAL_ARTS = 'VISUAL_ARTS',
}
