export const musicOptionsTree = [
  {
    code: 501,
    label: 'Jazz',
    children: [
      { code: 502, label: 'Acid Jazz' },
      { code: 503, label: 'Avant-Garde Jazz' },
      { code: 504, label: 'Bebop' },
      { code: 505, label: 'Big Band' },
      { code: 506, label: 'Blue Note ' },
      { code: 507, label: 'Cool Jazz' },
      { code: 508, label: 'Crossover Jazz' },
      { code: 509, label: 'Dixieland' },
      { code: 510, label: 'Ethio Jazz' },
      { code: 511, label: 'Fusion' },
      { code: 512, label: 'Jazz Contemporain' },
      { code: 513, label: 'Jazz Funk' },
      { code: 514, label: 'Mainstream' },
      { code: 515, label: 'Manouche' },
      { code: 516, label: 'Traditionel' },
      { code: 517, label: 'Vocal Jazz' },
      { code: 518, label: 'Ragtime' },
      { code: 519, label: 'Smooth' },
      { code: -1, label: 'Autre' },
    ],
  },
  {
    code: 520,
    label: 'Blues',
    children: [
      { code: 521, label: 'Blues Accoustique' },
      { code: 522, label: 'Blues Contemporain' },
      { code: 523, label: 'Blues Électrique' },
      { code: 524, label: 'Blues Rock' },
      { code: 525, label: 'Chicago Blues' },
      { code: 526, label: 'Classic Blues' },
      { code: 527, label: 'Country Blues' },
      { code: 528, label: 'Delta Blues' },
      { code: 529, label: 'Ragtime' },
      { code: -1, label: 'Autre' },
    ],
  },
  {
    code: 530,
    label: 'Reggae',
    children: [
      { code: 531, label: '2-Tone' },
      { code: 532, label: 'Dancehall' },
      { code: 533, label: 'Dub' },
      { code: 534, label: 'Roots ' },
      { code: 535, label: 'Ska' },
      { code: 536, label: 'Zouk ' },
      { code: -1, label: 'Autre' },
    ],
  },
  {
    code: 600,
    label: 'Classique',
    children: [
      { code: 601, label: 'Avant-garde' },
      { code: 602, label: 'Baroque' },
      { code: 603, label: 'Chant' },
      { code: 604, label: 'Chorale' },
      { code: 605, label: 'Contemporain' },
      { code: 606, label: 'Expressioniste' },
      { code: 607, label: 'Impressioniste' },
      { code: 608, label: 'Médievale' },
      { code: 609, label: 'Minimaliste' },
      { code: 610, label: 'Moderne ' },
      { code: 611, label: 'Oratorio' },
      { code: 612, label: 'Opéra' },
      { code: 613, label: 'Renaissance' },
      { code: 614, label: 'Romantique' },
      { code: -1, label: 'Autre' },
    ],
  },
  {
    code: 700,
    label: 'Musique du Monde',
    children: [
      { code: 701, label: 'Africaine' },
      { code: 702, label: 'Afro Beat' },
      { code: 703, label: 'Afro Pop' },
      { code: 704, label: 'Alternativo ' },
      { code: 705, label: 'Amérique du Nord' },
      { code: 706, label: 'Amérique du Sud' },
      { code: 707, label: 'Asiatique' },
      { code: 708, label: 'Baladas y Boleros' },
      { code: 709, label: 'Bossa Nova' },
      { code: 710, label: 'Brésilienne' },
      { code: 711, label: 'Cajun' },
      { code: 712, label: 'Calypso' },
      { code: 713, label: 'Caribéenne' },
      { code: 714, label: 'Celtique' },
      { code: 715, label: 'Cumbia ' },
      { code: 716, label: 'Flamenco' },
      { code: 717, label: 'Grècque' },
      { code: 718, label: 'Indienne' },
      { code: 719, label: 'Latin Jazz' },
      { code: 720, label: 'Moyen-Orient' },
      { code: 721, label: 'Musique Latine Contemporaine' },
      { code: 722, label: 'Nuevo Flamenco' },
      { code: 723, label: 'Pop Latino' },
      { code: 724, label: 'Portuguese fado ' },
      { code: 725, label: 'Rai' },
      { code: 726, label: 'Salsa' },
      { code: 727, label: 'Tango Argentin' },
      { code: 728, label: 'Yiddish' },
      { code: -1, label: 'Autre' },
    ],
  },
  {
    code: 800,
    label: 'Pop',
    children: [
      { code: 801, label: 'Britpop' },
      { code: 802, label: 'Bubblegum ' },
      { code: 803, label: 'Dance Pop' },
      { code: 804, label: 'Dream Pop ' },
      { code: 805, label: 'Electro Pop' },
      { code: 806, label: 'Indie Pop' },
      { code: 808, label: 'J-Pop' },
      { code: 809, label: 'K-Pop' },
      { code: 810, label: 'Pop Punk ' },
      { code: 811, label: 'Pop/Rock' },
      { code: 812, label: 'Power Pop ' },
      { code: 813, label: 'Soft Rock' },
      { code: 814, label: 'Synthpop ' },
      { code: 815, label: 'Teen Pop' },
      { code: -1, label: 'Autre' },
    ],
  },
  {
    code: 820,
    label: 'Rock',
    children: [
      { code: 821, label: 'Acid Rock ' },
      { code: 822, label: 'Arena Rock' },
      { code: 823, label: 'Art Rock' },
      { code: 824, label: 'College Rock' },
      { code: 825, label: 'Glam Rock' },
      { code: 826, label: 'Grunge' },
      { code: 827, label: 'Hard Rock' },
      { code: 828, label: 'Indie Rock' },
      { code: 829, label: 'Lo-fi' },
      { code: 830, label: 'Prog-Rock' },
      { code: 831, label: 'Psychedelic' },
      { code: 832, label: 'Rock & Roll' },
      { code: 833, label: 'Rock Experimental' },
      { code: 834, label: 'Rockabilly' },
      { code: 835, label: 'Shoegaze' },
      { code: 836, label: 'Rock Electro' },
      { code: -1, label: 'Autre' },
    ],
  },
  {
    code: 840,
    label: 'Metal',
    children: [
      { code: 841, label: 'Black Metal' },
      { code: 842, label: 'Death Metal ' },
      { code: 843, label: 'Doom Metal' },
      { code: 844, label: 'Gothic ' },
      { code: 845, label: 'Metal Core' },
      { code: 846, label: 'Metal Progressif' },
      { code: 847, label: 'Trash Metal' },
      { code: 848, label: 'Metal Industriel' },
      { code: 849, label: 'Fusion' },
      { code: -1, label: 'Autre' },
    ],
  },
  {
    code: 850,
    label: 'Punk',
    children: [
      { code: 851, label: 'Post Punk ' },
      { code: 852, label: 'Hardcore Punk' },
      { code: 853, label: 'Afro Punk' },
      { code: 854, label: 'Grindcore' },
      { code: 855, label: 'Noise Rock ' },
      { code: -1, label: 'Autre' },
    ],
  },
  {
    code: 860,
    label: 'Folk',
    children: [
      { code: 861, label: 'Folk Contemporaine' },
      { code: 862, label: 'Indie Folk' },
      { code: 863, label: 'Folk Rock' },
      { code: 864, label: 'New Acoustic' },
      { code: 865, label: 'Folk Traditionelle' },
      { code: 866, label: 'Tex-Mex' },
      { code: -1, label: 'Autre' },
    ],
  },
  {
    code: 870,
    label: 'Country',
    children: [
      { code: 871, label: 'Country Alternative' },
      { code: 872, label: 'Americana' },
      { code: 873, label: 'Bluegrass' },
      { code: 874, label: 'Country Contemporaine' },
      { code: 875, label: 'Gospel Country' },
      { code: 876, label: 'Country Pop' },
      { code: -1, label: 'Autre' },
    ],
  },
  {
    code: 880,
    label: 'Electro',
    children: [
      { code: 881, label: 'Bitpop' },
      { code: 882, label: 'Breakbeat ' },
      { code: 883, label: 'Chillwave' },
      { code: 884, label: 'Dance' },
      { code: 885, label: 'Downtempo' },
      { code: 886, label: 'Drum & Bass ' },
      { code: 887, label: 'Dubstep' },
      { code: 888, label: 'Electro Experimental' },
      { code: 889, label: 'Electronica' },
      { code: 890, label: 'Garage' },
      { code: 891, label: 'Grime' },
      { code: 892, label: 'Hard Dance' },
      { code: 893, label: 'Hardcore' },
      { code: 894, label: 'House' },
      { code: 895, label: 'Industriel' },
      { code: 896, label: 'Lounge' },
      { code: 897, label: 'Techno' },
      { code: 898, label: 'Trance' },
      { code: -1, label: 'Autre' },
    ],
  },
  {
    code: 900,
    label: 'Hip-Hop/Rap',
    children: [
      { code: 901, label: 'Bounce' },
      { code: 902, label: 'Hip Hop' },
      { code: 903, label: 'Rap Alternatif' },
      { code: 905, label: 'Rap East Coast' },
      { code: 906, label: 'Rap Français' },
      { code: 907, label: 'Rap Gangsta' },
      { code: 908, label: 'Rap Hardcore' },
      { code: 909, label: 'Rap Latino' },
      { code: 910, label: 'Rap Old School' },
      { code: 911, label: 'Rap Underground' },
      { code: 912, label: 'Rap West Coast' },
      { code: 913, label: 'Trap' },
      { code: 914, label: 'Trip Hop' },
      { code: 921, label: 'R&B Contemporain' },
      { code: 922, label: 'Disco' },
      { code: 923, label: 'Doo Wop' },
      { code: 924, label: 'Funk' },
      { code: 925, label: 'Soul' },
      { code: 926, label: 'Motown' },
      { code: 927, label: 'Neo Soul' },
      { code: 928, label: 'Soul Psychedelique' },
      { code: -1, label: 'Autre' },
    ],
  },
  {
    code: 930,
    label: 'Gospel',
    children: [
      { code: 931, label: 'Spiritual Gospel' },
      { code: 932, label: 'Traditional Gospel' },
      { code: 933, label: 'Southern Gospel' },
      { code: 934, label: 'Contemporary Gospel' },
      { code: 935, label: 'Bluegrass Gospel' },
      { code: 936, label: 'Blues Gospel' },
      { code: 937, label: 'Country Gospel' },
      { code: 938, label: 'Hybrid Gospel' },
      { code: -1, label: 'Autre' },
    ],
  },
  {
    code: 1000,
    label: 'Chansons / Variétés',
    children: [
      { code: 1001, label: 'Musette' },
      { code: 1002, label: 'Chanson Française' },
      { code: 1003, label: 'Music Hall' },
      { code: 1004, label: 'Folklore français' },
      { code: 1005, label: 'Chanson à texte' },
      { code: 1006, label: 'Slam' },
      { code: -1, label: 'Autre' },
    ],
  },
  {
    code: -1,
    label: 'Autre',
    children: [{ code: -1, label: 'Autre' }],
  },
]

export const showOptionsTree = [
  {
    code: 100,
    label: 'Arts de la rue',
    children: [
      { code: 101, label: 'Carnaval' },
      { code: 102, label: 'Fanfare' },
      { code: 103, label: 'Mime' },
      { code: 104, label: 'Parade' },
      { code: 105, label: 'Théâtre de Rue' },
      { code: 106, label: 'Théâtre Promenade' },
    ],
  },
  {
    code: 200,
    label: 'Cirque',
    children: [
      { code: 201, label: 'Cirque Contemporain' },
      { code: 202, label: 'Cirque Hors les murs' },
      { code: 203, label: 'Cirque Traditionel' },
      { code: 204, label: 'Cirque Voyageur' },
      { code: 205, label: 'Clown' },
      { code: 206, label: 'Hypnose' },
      { code: 207, label: 'Mentaliste' },
      { code: 208, label: 'Spectacle de Magie' },
      { code: 209, label: 'Spectacle Équestre' },
    ],
  },
  {
    code: 300,
    label: 'Danse',
    children: [
      { code: 302, label: 'Ballet' },
      { code: 303, label: 'Cancan' },
      { code: 304, label: 'Claquette' },
      { code: 305, label: 'Classique' },
      { code: 306, label: 'Contemporaine' },
      { code: 307, label: 'Danse du Monde' },
      { code: 308, label: 'Flamenco' },
      { code: 309, label: 'Moderne Jazz' },
      { code: 311, label: 'Salsa' },
      { code: 312, label: 'Swing' },
      { code: 313, label: 'Tango' },
      { code: 314, label: 'Urbaine' },
    ],
  },
  {
    code: 400,
    label: 'Humour / Café-théâtre',
    children: [
      { code: 401, label: 'Café Théâtre' },
      { code: 402, label: 'Improvisation' },
      { code: 403, label: 'Seul.e en scène' },
      { code: 404, label: 'Sketch' },
      { code: 405, label: 'Stand Up' },
      { code: 406, label: 'Ventriloque' },
    ],
  },
  {
    code: 1100,
    label: 'Spectacle / Cabaret',
    children: [
      { code: 1101, label: 'Cabaret' },
      { code: 1102, label: 'Café Concert' },
      { code: 1103, label: 'Claquette' },
      { code: 1104, label: 'Comédie Musicale' },
      { code: 1109, label: 'Revue' },
      { code: 1111, label: 'Burlesque' },
      { code: 1112, label: 'Comédie-Ballet' },
      { code: 1115, label: 'Théâtre musical' },
    ],
  },
  {
    code: 1200,
    label: 'Spectacle Jeunesse',
    children: [
      { code: 1201, label: 'Conte' },
      { code: 1202, label: 'Théâtre jeunesse' },
      { code: 1203, label: 'Spectacle Petite Enfance' },
      { code: 1204, label: 'Magie Enfance' },
      { code: 1205, label: 'Spectacle pédagogique' },
      { code: 1206, label: 'Marionettes' },
      { code: 1207, label: 'Comédie musicale jeunesse' },
      { code: 1208, label: 'Théâtre d’Ombres' },
    ],
  },
  {
    code: 1300,
    label: 'Théâtre',
    children: [
      { code: 1301, label: 'Boulevard' },
      { code: 1302, label: 'Classique' },
      { code: 1303, label: 'Comédie' },
      { code: 1304, label: 'Contemporain' },
      { code: 1305, label: 'Lecture' },
      { code: 1306, label: 'Spectacle Scénographique' },
      { code: 1307, label: 'Théâtre Experimental' },
      { code: 1308, label: 'Théâtre d’Objet' },
      { code: 1309, label: 'Tragédie' },
    ],
  },
  {
    code: 1400,
    label: 'Pluridisciplinaire',
    children: [
      { code: 1401, label: 'Performance' },
      { code: 1402, label: 'Poésie' },
    ],
  },
  {
    code: 1500,
    label: 'Autre (spectacle sur glace, historique, aquatique…)  ',
    children: [
      { code: 1501, label: 'Son et lumière' },
      { code: 1502, label: 'Spectacle sur glace' },
      { code: 1503, label: 'Spectacle historique' },
      { code: 1504, label: 'Spectacle aquatique' },
    ],
  },
  {
    code: 1510,
    label: 'Opéra',
    children: [
      { code: 1511, label: 'Opéra série' },
      { code: 1512, label: 'Grand opéra' },
      { code: 1513, label: 'Opéra bouffe' },
      { code: 1514, label: 'Opéra comique' },
      { code: 1515, label: 'Opéra-ballet' },
      { code: 1516, label: 'Singspiel' },
    ],
  },
]
