import datetime


RESPONSE_SIREN_COMPANY = {
    "header": {"statut": 200, "message": "OK"},
    "uniteLegale": {
        "siren": "123456789",
        "statutDiffusionUniteLegale": "O",
        "dateCreationUniteLegale": "2022-05-24",
        "sigleUniteLegale": None,
        "sexeUniteLegale": None,
        "prenom1UniteLegale": None,
        "prenom2UniteLegale": None,
        "prenom3UniteLegale": None,
        "prenom4UniteLegale": None,
        "prenomUsuelUniteLegale": None,
        "pseudonymeUniteLegale": None,
        "identifiantAssociationUniteLegale": None,
        "trancheEffectifsUniteLegale": None,
        "anneeEffectifsUniteLegale": None,
        "dateDernierTraitementUniteLegale": "2022-07-14T08:37:54",
        "nombrePeriodesUniteLegale": 2,
        "categorieEntreprise": None,
        "anneeCategorieEntreprise": None,
        "periodesUniteLegale": [
            {
                "dateFin": None,
                "dateDebut": "2022-06-14",
                "etatAdministratifUniteLegale": "A",
                "changementEtatAdministratifUniteLegale": False,
                "nomUniteLegale": None,
                "changementNomUniteLegale": False,
                "nomUsageUniteLegale": None,
                "changementNomUsageUniteLegale": False,
                "denominationUniteLegale": "LE PETIT RINTINTIN",
                "changementDenominationUniteLegale": False,
                "denominationUsuelle1UniteLegale": None,
                "denominationUsuelle2UniteLegale": None,
                "denominationUsuelle3UniteLegale": None,
                "changementDenominationUsuelleUniteLegale": False,
                "categorieJuridiqueUniteLegale": "5499",
                "changementCategorieJuridiqueUniteLegale": False,
                "activitePrincipaleUniteLegale": "47.61Z",
                "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
                "changementActivitePrincipaleUniteLegale": True,
                "nicSiegeUniteLegale": "00017",
                "changementNicSiegeUniteLegale": False,
                "economieSocialeSolidaireUniteLegale": "N",
                "changementEconomieSocialeSolidaireUniteLegale": False,
                "societeMissionUniteLegale": None,
                "changementSocieteMissionUniteLegale": False,
                "caractereEmployeurUniteLegale": "O",
                "changementCaractereEmployeurUniteLegale": True,
            },
            {
                "dateFin": "2022-06-13",
                "dateDebut": "2022-05-24",
                "etatAdministratifUniteLegale": "A",
                "changementEtatAdministratifUniteLegale": False,
                "nomUniteLegale": None,
                "changementNomUniteLegale": False,
                "nomUsageUniteLegale": None,
                "changementNomUsageUniteLegale": False,
                "denominationUniteLegale": "LE PETIT RINTINTIN",
                "changementDenominationUniteLegale": False,
                "denominationUsuelle1UniteLegale": None,
                "denominationUsuelle2UniteLegale": None,
                "denominationUsuelle3UniteLegale": None,
                "changementDenominationUsuelleUniteLegale": False,
                "categorieJuridiqueUniteLegale": "5499",
                "changementCategorieJuridiqueUniteLegale": False,
                "activitePrincipaleUniteLegale": "00.00Z",
                "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
                "changementActivitePrincipaleUniteLegale": False,
                "nicSiegeUniteLegale": "00017",
                "changementNicSiegeUniteLegale": False,
                "economieSocialeSolidaireUniteLegale": "N",
                "changementEconomieSocialeSolidaireUniteLegale": False,
                "societeMissionUniteLegale": None,
                "changementSocieteMissionUniteLegale": False,
                "caractereEmployeurUniteLegale": "N",
                "changementCaractereEmployeurUniteLegale": False,
            },
        ],
    },
}

RESPONSE_SIREN_COMPANY_WITH_NON_PUBLIC_DATA = {
    "header": {"statut": 200, "message": "OK"},
    "uniteLegale": {
        "siren": "123456789",
        "statutDiffusionUniteLegale": "P",
        "dateCreationUniteLegale": "2022-01-01",
        "sigleUniteLegale": "[ND]",
        "sexeUniteLegale": "[ND]",
        "prenom1UniteLegale": "[ND]",
        "prenom2UniteLegale": "[ND]",
        "prenom3UniteLegale": "[ND]",
        "prenom4UniteLegale": "[ND]",
        "prenomUsuelUniteLegale": "[ND]",
        "pseudonymeUniteLegale": "[ND]",
        "identifiantAssociationUniteLegale": None,
        "trancheEffectifsUniteLegale": None,
        "anneeEffectifsUniteLegale": None,
        "dateDernierTraitementUniteLegale": "2022-01-01T12:34:56",
        "nombrePeriodesUniteLegale": 1,
        "categorieEntreprise": None,
        "anneeCategorieEntreprise": None,
        "periodesUniteLegale": [
            {
                "dateFin": None,
                "dateDebut": "2022-01-01",
                "etatAdministratifUniteLegale": "A",
                "changementEtatAdministratifUniteLegale": False,
                "nomUniteLegale": "[ND]",
                "changementNomUniteLegale": False,
                "nomUsageUniteLegale": "[ND]",
                "changementNomUsageUniteLegale": False,
                "denominationUniteLegale": "[ND]",
                "changementDenominationUniteLegale": False,
                "denominationUsuelle1UniteLegale": "[ND]",
                "denominationUsuelle2UniteLegale": "[ND]",
                "denominationUsuelle3UniteLegale": "[ND]",
                "changementDenominationUsuelleUniteLegale": False,
                "categorieJuridiqueUniteLegale": "1000",
                "changementCategorieJuridiqueUniteLegale": False,
                "activitePrincipaleUniteLegale": "88.99B",
                "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
                "changementActivitePrincipaleUniteLegale": False,
                "nicSiegeUniteLegale": "00001",
                "changementNicSiegeUniteLegale": False,
                "economieSocialeSolidaireUniteLegale": None,
                "changementEconomieSocialeSolidaireUniteLegale": False,
                "societeMissionUniteLegale": None,
                "changementSocieteMissionUniteLegale": False,
                "caractereEmployeurUniteLegale": "N",
                "changementCaractereEmployeurUniteLegale": False,
            }
        ],
    },
}


RESPONSE_SIREN_ENTREPRISE_INDIVIDUELLE = {
    "header": {"statut": 200, "message": "OK"},
    "uniteLegale": {
        "siren": "123456789",
        "statutDiffusionUniteLegale": "O",
        "dateCreationUniteLegale": "2016-01-05",
        "sigleUniteLegale": None,
        "sexeUniteLegale": "M",
        "prenom1UniteLegale": "PIERRE",
        "prenom2UniteLegale": None,
        "prenom3UniteLegale": None,
        "prenom4UniteLegale": None,
        "prenomUsuelUniteLegale": "PIERRE",
        "pseudonymeUniteLegale": None,
        "identifiantAssociationUniteLegale": None,
        "trancheEffectifsUniteLegale": None,
        "anneeEffectifsUniteLegale": None,
        "dateDernierTraitementUniteLegale": "2022-06-21T20:07:38",
        "nombrePeriodesUniteLegale": 4,
        "categorieEntreprise": "PME",
        "anneeCategorieEntreprise": "2019",
        "periodesUniteLegale": [
            {
                "dateFin": None,
                "dateDebut": "2021-04-08",
                "etatAdministratifUniteLegale": "A",
                "changementEtatAdministratifUniteLegale": False,
                "nomUniteLegale": "EXEMPLE",
                "changementNomUniteLegale": False,
                "nomUsageUniteLegale": None,
                "changementNomUsageUniteLegale": False,
                "denominationUniteLegale": None,
                "changementDenominationUniteLegale": False,
                "denominationUsuelle1UniteLegale": None,
                "denominationUsuelle2UniteLegale": None,
                "denominationUsuelle3UniteLegale": None,
                "changementDenominationUsuelleUniteLegale": False,
                "categorieJuridiqueUniteLegale": "1000",
                "changementCategorieJuridiqueUniteLegale": False,
                "activitePrincipaleUniteLegale": "90.03A",
                "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
                "changementActivitePrincipaleUniteLegale": False,
                "nicSiegeUniteLegale": "00045",
                "changementNicSiegeUniteLegale": True,
                "economieSocialeSolidaireUniteLegale": None,
                "changementEconomieSocialeSolidaireUniteLegale": False,
                "caractereEmployeurUniteLegale": "N",
                "changementCaractereEmployeurUniteLegale": False,
            },
            {
                "dateFin": "2021-04-07",
                "dateDebut": "2019-01-31",
                "etatAdministratifUniteLegale": "A",
                "changementEtatAdministratifUniteLegale": False,
                "nomUniteLegale": "EXEMPLE",
                "changementNomUniteLegale": False,
                "nomUsageUniteLegale": None,
                "changementNomUsageUniteLegale": False,
                "denominationUniteLegale": None,
                "changementDenominationUniteLegale": False,
                "denominationUsuelle1UniteLegale": None,
                "denominationUsuelle2UniteLegale": None,
                "denominationUsuelle3UniteLegale": None,
                "changementDenominationUsuelleUniteLegale": False,
                "categorieJuridiqueUniteLegale": "1000",
                "changementCategorieJuridiqueUniteLegale": False,
                "activitePrincipaleUniteLegale": "90.03A",
                "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
                "changementActivitePrincipaleUniteLegale": True,
                "nicSiegeUniteLegale": "00037",
                "changementNicSiegeUniteLegale": True,
                "economieSocialeSolidaireUniteLegale": None,
                "changementEconomieSocialeSolidaireUniteLegale": False,
                "caractereEmployeurUniteLegale": "N",
                "changementCaractereEmployeurUniteLegale": False,
            },
            {
                "dateFin": "2019-01-30",
                "dateDebut": "2016-04-24",
                "etatAdministratifUniteLegale": "A",
                "changementEtatAdministratifUniteLegale": False,
                "nomUniteLegale": "EXEMPLE",
                "changementNomUniteLegale": False,
                "nomUsageUniteLegale": None,
                "changementNomUsageUniteLegale": False,
                "denominationUniteLegale": None,
                "changementDenominationUniteLegale": False,
                "denominationUsuelle1UniteLegale": None,
                "denominationUsuelle2UniteLegale": None,
                "denominationUsuelle3UniteLegale": None,
                "changementDenominationUsuelleUniteLegale": False,
                "categorieJuridiqueUniteLegale": "1000",
                "changementCategorieJuridiqueUniteLegale": False,
                "activitePrincipaleUniteLegale": "74.10Z",
                "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
                "changementActivitePrincipaleUniteLegale": False,
                "nicSiegeUniteLegale": "00029",
                "changementNicSiegeUniteLegale": True,
                "economieSocialeSolidaireUniteLegale": None,
                "changementEconomieSocialeSolidaireUniteLegale": False,
                "caractereEmployeurUniteLegale": "N",
                "changementCaractereEmployeurUniteLegale": False,
            },
            {
                "dateFin": "2016-04-23",
                "dateDebut": "2016-01-05",
                "etatAdministratifUniteLegale": "A",
                "changementEtatAdministratifUniteLegale": False,
                "nomUniteLegale": "EXEMPLE",
                "changementNomUniteLegale": False,
                "nomUsageUniteLegale": None,
                "changementNomUsageUniteLegale": False,
                "denominationUniteLegale": None,
                "changementDenominationUniteLegale": False,
                "denominationUsuelle1UniteLegale": None,
                "denominationUsuelle2UniteLegale": None,
                "denominationUsuelle3UniteLegale": None,
                "changementDenominationUsuelleUniteLegale": False,
                "categorieJuridiqueUniteLegale": "1000",
                "changementCategorieJuridiqueUniteLegale": False,
                "activitePrincipaleUniteLegale": "74.10Z",
                "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
                "changementActivitePrincipaleUniteLegale": False,
                "nicSiegeUniteLegale": "00011",
                "changementNicSiegeUniteLegale": False,
                "economieSocialeSolidaireUniteLegale": None,
                "changementEconomieSocialeSolidaireUniteLegale": False,
                "caractereEmployeurUniteLegale": "N",
                "changementCaractereEmployeurUniteLegale": False,
            },
        ],
    },
}

RESPONSE_SIREN_INACTIVE_COMPANY = {
    "header": {"statut": 200, "message": "OK"},
    "uniteLegale": {
        "siren": "123456789",
        "statutDiffusionUniteLegale": "O",
        "unitePurgeeUniteLegale": True,
        "dateCreationUniteLegale": "1957-01-01",
        "sigleUniteLegale": None,
        "sexeUniteLegale": None,
        "prenom1UniteLegale": None,
        "prenom2UniteLegale": None,
        "prenom3UniteLegale": None,
        "prenom4UniteLegale": None,
        "prenomUsuelUniteLegale": None,
        "pseudonymeUniteLegale": None,
        "identifiantAssociationUniteLegale": None,
        "trancheEffectifsUniteLegale": None,
        "anneeEffectifsUniteLegale": None,
        "dateDernierTraitementUniteLegale": None,
        "nombrePeriodesUniteLegale": 1,
        "categorieEntreprise": None,
        "anneeCategorieEntreprise": None,
        "periodesUniteLegale": [
            {
                "dateFin": None,
                "dateDebut": "1995-01-01",
                "etatAdministratifUniteLegale": "C",
                "changementEtatAdministratifUniteLegale": True,
                "nomUniteLegale": None,
                "changementNomUniteLegale": False,
                "nomUsageUniteLegale": None,
                "changementNomUsageUniteLegale": False,
                "denominationUniteLegale": "LE PETIT RINTINTIN",
                "changementDenominationUniteLegale": False,
                "denominationUsuelle1UniteLegale": None,
                "denominationUsuelle2UniteLegale": None,
                "denominationUsuelle3UniteLegale": None,
                "changementDenominationUsuelleUniteLegale": False,
                "categorieJuridiqueUniteLegale": "5599",
                "changementCategorieJuridiqueUniteLegale": False,
                "activitePrincipaleUniteLegale": "74.7Z",
                "nomenclatureActivitePrincipaleUniteLegale": "NAF1993",
                "changementActivitePrincipaleUniteLegale": False,
                "nicSiegeUniteLegale": "00018",
                "changementNicSiegeUniteLegale": False,
                "economieSocialeSolidaireUniteLegale": None,
                "changementEconomieSocialeSolidaireUniteLegale": False,
                "societeMissionUniteLegale": None,
                "changementSocieteMissionUniteLegale": False,
                "caractereEmployeurUniteLegale": "N",
                "changementCaractereEmployeurUniteLegale": False,
            }
        ],
    },
}

RESPONSE_SIREN_WITHOUT_APE = {
    "header": {"statut": 200, "message": "OK"},
    "uniteLegale": {
        "siren": "194700936",
        "statutDiffusionUniteLegale": "O",
        "dateCreationUniteLegale": "1965-10-26",
        "sigleUniteLegale": "LPO LYC METIER",
        "sexeUniteLegale": None,
        "prenom1UniteLegale": None,
        "prenom2UniteLegale": None,
        "prenom3UniteLegale": None,
        "prenom4UniteLegale": None,
        "prenomUsuelUniteLegale": None,
        "pseudonymeUniteLegale": None,
        "identifiantAssociationUniteLegale": None,
        "trancheEffectifsUniteLegale": "NN",
        "anneeEffectifsUniteLegale": None,
        "dateDernierTraitementUniteLegale": "2023-03-16T09:51:37",
        "nombrePeriodesUniteLegale": 2,
        "categorieEntreprise": None,
        "anneeCategorieEntreprise": None,
        "periodesUniteLegale": [
            {
                "dateFin": None,
                "dateDebut": "1983-03-01",
                "etatAdministratifUniteLegale": "C",
                "changementEtatAdministratifUniteLegale": True,
                "nomUniteLegale": None,
                "changementNomUniteLegale": False,
                "nomUsageUniteLegale": None,
                "changementNomUsageUniteLegale": False,
                "denominationUniteLegale": "LYCEE D'ENSEIGNEMENT PROFESSIONNEL",
                "changementDenominationUniteLegale": False,
                "denominationUsuelle1UniteLegale": None,
                "denominationUsuelle2UniteLegale": None,
                "denominationUsuelle3UniteLegale": None,
                "changementDenominationUsuelleUniteLegale": False,
                "categorieJuridiqueUniteLegale": "7331",
                "changementCategorieJuridiqueUniteLegale": False,
                "activitePrincipaleUniteLegale": None,
                "nomenclatureActivitePrincipaleUniteLegale": None,
                "changementActivitePrincipaleUniteLegale": False,
                "nicSiegeUniteLegale": "00017",
                "changementNicSiegeUniteLegale": False,
                "economieSocialeSolidaireUniteLegale": None,
                "changementEconomieSocialeSolidaireUniteLegale": False,
                "societeMissionUniteLegale": None,
                "changementSocieteMissionUniteLegale": False,
                "caractereEmployeurUniteLegale": "N",
                "changementCaractereEmployeurUniteLegale": True,
            },
            {
                "dateFin": "1983-02-28",
                "dateDebut": "1965-10-26",
                "etatAdministratifUniteLegale": "A",
                "changementEtatAdministratifUniteLegale": False,
                "nomUniteLegale": None,
                "changementNomUniteLegale": False,
                "nomUsageUniteLegale": None,
                "changementNomUsageUniteLegale": False,
                "denominationUniteLegale": "LYCEE D'ENSEIGNEMENT PROFESSIONNEL",
                "changementDenominationUniteLegale": False,
                "denominationUsuelle1UniteLegale": None,
                "denominationUsuelle2UniteLegale": None,
                "denominationUsuelle3UniteLegale": None,
                "changementDenominationUsuelleUniteLegale": False,
                "categorieJuridiqueUniteLegale": "7331",
                "changementCategorieJuridiqueUniteLegale": False,
                "activitePrincipaleUniteLegale": None,
                "nomenclatureActivitePrincipaleUniteLegale": None,
                "changementActivitePrincipaleUniteLegale": False,
                "nicSiegeUniteLegale": "00017",
                "changementNicSiegeUniteLegale": False,
                "economieSocialeSolidaireUniteLegale": None,
                "changementEconomieSocialeSolidaireUniteLegale": False,
                "societeMissionUniteLegale": None,
                "changementSocieteMissionUniteLegale": False,
                "caractereEmployeurUniteLegale": None,
                "changementCaractereEmployeurUniteLegale": False,
            },
        ],
    },
}

RESPONSE_SIRET_COMPANY = {
    "header": {"statut": 200, "message": "ok"},
    "etablissement": {
        "siren": "123456789",
        "nic": "00017",
        "siret": "12345678900017",
        "statutDiffusionEtablissement": "O",
        "dateCreationEtablissement": "2022-05-24",
        "trancheEffectifsEtablissement": None,
        "anneeEffectifsEtablissement": None,
        "activitePrincipaleRegistreMetiersEtablissement": None,
        "dateDernierTraitementEtablissement": "2022-07-14T08:37:54",
        "etablissementSiege": True,
        "nombrePeriodesEtablissement": 2,
        "uniteLegale": {
            "etatAdministratifUniteLegale": "A",
            "statutDiffusionUniteLegale": "O",
            "dateCreationUniteLegale": "2022-05-24",
            "categorieJuridiqueUniteLegale": "5499",
            "denominationUniteLegale": "LE PETIT RINTINTIN",
            "sigleUniteLegale": None,
            "denominationUsuelle1UniteLegale": None,
            "denominationUsuelle2UniteLegale": None,
            "denominationUsuelle3UniteLegale": None,
            "sexeUniteLegale": None,
            "nomUniteLegale": None,
            "nomUsageUniteLegale": None,
            "prenom1UniteLegale": None,
            "prenom2UniteLegale": None,
            "prenom3UniteLegale": None,
            "prenom4UniteLegale": None,
            "prenomUsuelUniteLegale": None,
            "pseudonymeUniteLegale": None,
            "activitePrincipaleUniteLegale": "47.61Z",
            "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
            "identifiantAssociationUniteLegale": None,
            "economieSocialeSolidaireUniteLegale": "N",
            "societeMissionUniteLegale": None,
            "caractereEmployeurUniteLegale": "O",
            "trancheEffectifsUniteLegale": None,
            "anneeEffectifsUniteLegale": None,
            "nicSiegeUniteLegale": "00017",
            "dateDernierTraitementUniteLegale": "2022-07-14T08:37:54",
            "categorieEntreprise": None,
            "anneeCategorieEntreprise": None,
        },
        "adresseEtablissement": {
            "complementAdresseEtablissement": None,
            "numeroVoieEtablissement": "1",
            "indiceRepetitionEtablissement": None,
            "dernierNumeroVoieEtablissement": None,
            "indiceRepetitionDernierNumeroVoieEtablissement": None,
            "typeVoieEtablissement": "BD",
            "libelleVoieEtablissement": "POISSONIERE  ",
            "codePostalEtablissement": "75002  ",
            "libelleCommuneEtablissement": "PARIS 2  ",
            "libelleCommuneEtrangerEtablissement": None,
            "distributionSpecialeEtablissement": None,
            "codeCommuneEtablissement": "75102",
            "codeCedexEtablissement": None,
            "libelleCedexEtablissement": None,
            "codePaysEtrangerEtablissement": None,
            "libellePaysEtrangerEtablissement": None,
            "identifiantAdresseEtablissement": "751098393_B",
            "coordonneeLambertAbscisseEtablissement": "48.871274",
            "coordonneeLambertOrdonneeEtablissement": "2.345886",
        },
        "adresse2Etablissement": {
            "complementAdresse2Etablissement": None,
            "numeroVoie2Etablissement": None,
            "indiceRepetition2Etablissement": None,
            "typeVoie2Etablissement": None,
            "libelleVoie2Etablissement": None,
            "codePostal2Etablissement": None,
            "libelleCommune2Etablissement": None,
            "libelleCommuneEtranger2Etablissement": None,
            "distributionSpeciale2Etablissement": None,
            "codeCommune2Etablissement": None,
            "codeCedex2Etablissement": None,
            "libelleCedex2Etablissement": None,
            "codePaysEtranger2Etablissement": None,
            "libellePaysEtranger2Etablissement": None,
        },
        "periodesEtablissement": [
            {
                "dateFin": None,
                "dateDebut": "2022-06-14",
                "etatAdministratifEtablissement": "A",
                "changementEtatAdministratifEtablissement": False,
                "enseigne1Etablissement": "LE PETIT RINTINTINT",
                "enseigne2Etablissement": None,
                "enseigne3Etablissement": None,
                "changementEnseigneEtablissement": True,
                "denominationUsuelleEtablissement": "LE PETIT RINTINTIN",
                "changementDenominationUsuelleEtablissement": True,
                "activitePrincipaleEtablissement": "47.61Z",
                "nomenclatureActivitePrincipaleEtablissement": "NAFRev2",
                "changementActivitePrincipaleEtablissement": True,
                "caractereEmployeurEtablissement": "O",
                "changementCaractereEmployeurEtablissement": True,
            },
            {
                "dateFin": "2022-06-13",
                "dateDebut": "2022-05-24",
                "etatAdministratifEtablissement": "A",
                "changementEtatAdministratifEtablissement": False,
                "enseigne1Etablissement": None,
                "enseigne2Etablissement": None,
                "enseigne3Etablissement": None,
                "changementEnseigneEtablissement": False,
                "denominationUsuelleEtablissement": None,
                "changementDenominationUsuelleEtablissement": False,
                "activitePrincipaleEtablissement": "70.10Z",
                "nomenclatureActivitePrincipaleEtablissement": "NAFRev2",
                "changementActivitePrincipaleEtablissement": False,
                "caractereEmployeurEtablissement": "N",
                "changementCaractereEmployeurEtablissement": False,
            },
        ],
    },
}

RESPONSE_SIRET_COMPANY_WITH_NON_PUBLIC_DATA = {
    "header": {"statut": 200, "message": "ok"},
    "etablissement": {
        "siren": "123456789",
        "nic": "00001",
        "siret": "12345678900001",
        "statutDiffusionEtablissement": "P",
        "dateCreationEtablissement": "2022-01-01",
        "trancheEffectifsEtablissement": None,
        "anneeEffectifsEtablissement": None,
        "activitePrincipaleRegistreMetiersEtablissement": None,
        "dateDernierTraitementEtablissement": "2022-01-01T12:34:56",
        "etablissementSiege": True,
        "nombrePeriodesEtablissement": 1,
        "uniteLegale": {
            "etatAdministratifUniteLegale": "A",
            "statutDiffusionUniteLegale": "P",
            "dateCreationUniteLegale": "2022-01-01",
            "categorieJuridiqueUniteLegale": "1000",
            "denominationUniteLegale": "[ND]",
            "sigleUniteLegale": "[ND]",
            "denominationUsuelle1UniteLegale": "[ND]",
            "denominationUsuelle2UniteLegale": "[ND]",
            "denominationUsuelle3UniteLegale": "[ND]",
            "sexeUniteLegale": "[ND]",
            "nomUniteLegale": "[ND]",
            "nomUsageUniteLegale": "[ND]",
            "prenom1UniteLegale": "[ND]",
            "prenom2UniteLegale": "[ND]",
            "prenom3UniteLegale": "[ND]",
            "prenom4UniteLegale": "[ND]",
            "prenomUsuelUniteLegale": "[ND]",
            "pseudonymeUniteLegale": "[ND]",
            "activitePrincipaleUniteLegale": "88.99B",
            "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
            "identifiantAssociationUniteLegale": None,
            "economieSocialeSolidaireUniteLegale": None,
            "societeMissionUniteLegale": None,
            "caractereEmployeurUniteLegale": "N",
            "trancheEffectifsUniteLegale": None,
            "anneeEffectifsUniteLegale": None,
            "nicSiegeUniteLegale": "00011",
            "dateDernierTraitementUniteLegale": "2022-01-01T12:34:56",
            "categorieEntreprise": None,
            "anneeCategorieEntreprise": None,
        },
        "adresseEtablissement": {
            "complementAdresseEtablissement": "[ND]",
            "numeroVoieEtablissement": "[ND]",
            "indiceRepetitionEtablissement": "[ND]",
            "dernierNumeroVoieEtablissement": "[ND]",
            "indiceRepetitionDernierNumeroVoieEtablissement": "[ND]",
            "typeVoieEtablissement": "[ND]",
            "libelleVoieEtablissement": "[ND]",
            "codePostalEtablissement": "[ND]",
            "libelleCommuneEtablissement": "MARSEILLE 4",
            "libelleCommuneEtrangerEtablissement": None,
            "distributionSpecialeEtablissement": "[ND]",
            "codeCommuneEtablissement": "13204",
            "codeCedexEtablissement": "[ND]",
            "libelleCedexEtablissement": "[ND]",
            "codePaysEtrangerEtablissement": None,
            "libellePaysEtrangerEtablissement": None,
            "identifiantAdresseEtablissement": "[ND]",
            "coordonneeLambertAbscisseEtablissement": "[ND]",
            "coordonneeLambertOrdonneeEtablissement": "[ND]",
        },
        "adresse2Etablissement": {
            "complementAdresse2Etablissement": None,
            "numeroVoie2Etablissement": None,
            "indiceRepetition2Etablissement": None,
            "typeVoie2Etablissement": None,
            "libelleVoie2Etablissement": None,
            "codePostal2Etablissement": None,
            "libelleCommune2Etablissement": None,
            "libelleCommuneEtranger2Etablissement": None,
            "distributionSpeciale2Etablissement": None,
            "codeCommune2Etablissement": None,
            "codeCedex2Etablissement": None,
            "libelleCedex2Etablissement": None,
            "codePaysEtranger2Etablissement": None,
            "libellePaysEtranger2Etablissement": None,
        },
        "periodesEtablissement": [
            {
                "dateFin": None,
                "dateDebut": "2022-09-04",
                "etatAdministratifEtablissement": "A",
                "changementEtatAdministratifEtablissement": False,
                "enseigne1Etablissement": "[ND]",
                "enseigne2Etablissement": "[ND]",
                "enseigne3Etablissement": "[ND]",
                "changementEnseigneEtablissement": False,
                "denominationUsuelleEtablissement": "[ND]",
                "changementDenominationUsuelleEtablissement": False,
                "activitePrincipaleEtablissement": "88.99B",
                "nomenclatureActivitePrincipaleEtablissement": "NAFRev2",
                "changementActivitePrincipaleEtablissement": False,
                "caractereEmployeurEtablissement": "N",
                "changementCaractereEmployeurEtablissement": False,
            }
        ],
    },
}

RESPONSE_SIRET_ENTREPRISE_INDIVIDUELLE = {
    "header": {"statut": 200, "message": "ok"},
    "etablissement": {
        "siren": "123456789",
        "nic": "00045",
        "siret": "12345678900045",
        "statutDiffusionEtablissement": "O",
        "dateCreationEtablissement": "2021-04-08",
        "trancheEffectifsEtablissement": None,
        "anneeEffectifsEtablissement": None,
        "activitePrincipaleRegistreMetiersEtablissement": None,
        "dateDernierTraitementEtablissement": "2022-06-21T20:07:38",
        "etablissementSiege": True,
        "nombrePeriodesEtablissement": 1,
        "uniteLegale": {
            "etatAdministratifUniteLegale": "A",
            "statutDiffusionUniteLegale": "O",
            "dateCreationUniteLegale": "2016-01-05",
            "categorieJuridiqueUniteLegale": "1000",
            "denominationUniteLegale": None,
            "sigleUniteLegale": None,
            "denominationUsuelle1UniteLegale": None,
            "denominationUsuelle2UniteLegale": None,
            "denominationUsuelle3UniteLegale": None,
            "sexeUniteLegale": "M",
            "nomUniteLegale": "EXEMPLE",
            "nomUsageUniteLegale": None,
            "prenom1UniteLegale": "PIERRE",
            "prenom2UniteLegale": None,
            "prenom3UniteLegale": None,
            "prenom4UniteLegale": None,
            "prenomUsuelUniteLegale": "PIERRE",
            "pseudonymeUniteLegale": None,
            "activitePrincipaleUniteLegale": "90.03A",
            "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
            "identifiantAssociationUniteLegale": None,
            "economieSocialeSolidaireUniteLegale": None,
            "caractereEmployeurUniteLegale": "N",
            "trancheEffectifsUniteLegale": None,
            "anneeEffectifsUniteLegale": None,
            "nicSiegeUniteLegale": "00045",
            "dateDernierTraitementUniteLegale": "2022-06-21T20:07:38",
            "categorieEntreprise": "PME",
            "anneeCategorieEntreprise": "2019",
        },
        "adresseEtablissement": {
            "complementAdresseEtablissement": None,
            "numeroVoieEtablissement": "3",
            "indiceRepetitionEtablissement": None,
            "dernierNumeroVoieEtablissement": None,
            "indiceRepetitionDernierNumeroVoieEtablissement": None,
            "typeVoieEtablissement": "RUE",
            "libelleVoieEtablissement": "DE VALOIS",
            "codePostalEtablissement": "75001",
            "libelleCommuneEtablissement": "PARIS 1",
            "libelleCommuneEtrangerEtablissement": None,
            "distributionSpecialeEtablissement": None,
            "codeCommuneEtablissement": "75001",
            "codeCedexEtablissement": None,
            "libelleCedexEtablissement": None,
            "codePaysEtrangerEtablissement": None,
            "libellePaysEtrangerEtablissement": None,
            "identifiantAdresseEtablissement": "751098393_B",
            "coordonneeLambertAbscisseEtablissement": "48.871274",
            "coordonneeLambertOrdonneeEtablissement": "2.345886",
        },
        "adresse2Etablissement": {
            "complementAdresse2Etablissement": None,
            "numeroVoie2Etablissement": None,
            "indiceRepetition2Etablissement": None,
            "typeVoie2Etablissement": None,
            "libelleVoie2Etablissement": None,
            "codePostal2Etablissement": None,
            "libelleCommune2Etablissement": None,
            "libelleCommuneEtranger2Etablissement": None,
            "distributionSpeciale2Etablissement": None,
            "codeCommune2Etablissement": None,
            "codeCedex2Etablissement": None,
            "libelleCedex2Etablissement": None,
            "codePaysEtranger2Etablissement": None,
            "libellePaysEtranger2Etablissement": None,
        },
        "periodesEtablissement": [
            {
                "dateFin": None,
                "dateDebut": "2021-04-08",
                "etatAdministratifEtablissement": "A",
                "changementEtatAdministratifEtablissement": False,
                "enseigne1Etablissement": None,
                "enseigne2Etablissement": None,
                "enseigne3Etablissement": None,
                "changementEnseigneEtablissement": False,
                "denominationUsuelleEtablissement": None,
                "changementDenominationUsuelleEtablissement": False,
                "activitePrincipaleEtablissement": "90.03A",
                "nomenclatureActivitePrincipaleEtablissement": "NAFRev2",
                "changementActivitePrincipaleEtablissement": False,
                "caractereEmployeurEtablissement": "N",
                "changementCaractereEmployeurEtablissement": False,
            }
        ],
    },
}

RESPONSE_SIRET_INACTIVE_COMPANY = {
    "header": {"statut": 200, "message": "ok"},
    "etablissement": {
        "siren": "572003663",
        "nic": "00018",
        "siret": "57200366300018",
        "statutDiffusionEtablissement": "O",
        "dateCreationEtablissement": None,
        "trancheEffectifsEtablissement": "NN",
        "anneeEffectifsEtablissement": None,
        "activitePrincipaleRegistreMetiersEtablissement": None,
        "dateDernierTraitementEtablissement": None,
        "etablissementSiege": True,
        "nombrePeriodesEtablissement": 1,
        "uniteLegale": {
            "etatAdministratifUniteLegale": "C",
            "statutDiffusionUniteLegale": "O",
            "unitePurgeeUniteLegale": True,
            "dateCreationUniteLegale": "1957-01-01",
            "categorieJuridiqueUniteLegale": "5599",
            "denominationUniteLegale": "AIGLE AZUR",
            "sigleUniteLegale": None,
            "denominationUsuelle1UniteLegale": None,
            "denominationUsuelle2UniteLegale": None,
            "denominationUsuelle3UniteLegale": None,
            "sexeUniteLegale": None,
            "nomUniteLegale": None,
            "nomUsageUniteLegale": None,
            "prenom1UniteLegale": None,
            "prenom2UniteLegale": None,
            "prenom3UniteLegale": None,
            "prenom4UniteLegale": None,
            "prenomUsuelUniteLegale": None,
            "pseudonymeUniteLegale": None,
            "activitePrincipaleUniteLegale": "74.7Z",
            "nomenclatureActivitePrincipaleUniteLegale": "NAFRev1",
            "identifiantAssociationUniteLegale": None,
            "economieSocialeSolidaireUniteLegale": None,
            "societeMissionUniteLegale": None,
            "caractereEmployeurUniteLegale": "N",
            "trancheEffectifsUniteLegale": None,
            "anneeEffectifsUniteLegale": None,
            "nicSiegeUniteLegale": "00018",
            "dateDernierTraitementUniteLegale": None,
            "categorieEntreprise": None,
            "anneeCategorieEntreprise": None,
        },
        "adresseEtablissement": {
            "complementAdresseEtablissement": None,
            "numeroVoieEtablissement": "78",
            "indiceRepetitionEtablissement": None,
            "dernierNumeroVoieEtablissement": None,
            "indiceRepetitionDernierNumeroVoieEtablissement": None,
            "typeVoieEtablissement": "AV",
            "libelleVoieEtablissement": "DE FLANDRE",
            "codePostalEtablissement": "75019",
            "libelleCommuneEtablissement": "PARIS 19",
            "libelleCommuneEtrangerEtablissement": None,
            "distributionSpecialeEtablissement": None,
            "codeCommuneEtablissement": "75119",
            "codeCedexEtablissement": None,
            "libelleCedexEtablissement": None,
            "codePaysEtrangerEtablissement": None,
            "libellePaysEtrangerEtablissement": None,
            "identifiantAdresseEtablissement": "751098393_B",
            "coordonneeLambertAbscisseEtablissement": "48.871274",
            "coordonneeLambertOrdonneeEtablissement": "2.345886",
        },
        "adresse2Etablissement": {
            "complementAdresse2Etablissement": None,
            "numeroVoie2Etablissement": None,
            "indiceRepetition2Etablissement": None,
            "typeVoie2Etablissement": None,
            "libelleVoie2Etablissement": None,
            "codePostal2Etablissement": None,
            "libelleCommune2Etablissement": None,
            "libelleCommuneEtranger2Etablissement": None,
            "distributionSpeciale2Etablissement": None,
            "codeCommune2Etablissement": None,
            "codeCedex2Etablissement": None,
            "libelleCedex2Etablissement": None,
            "codePaysEtranger2Etablissement": None,
            "libellePaysEtranger2Etablissement": None,
        },
        "periodesEtablissement": [
            {
                "dateFin": None,
                "dateDebut": "1995-01-01",
                "etatAdministratifEtablissement": "F",
                "changementEtatAdministratifEtablissement": True,
                "enseigne1Etablissement": None,
                "enseigne2Etablissement": None,
                "enseigne3Etablissement": None,
                "changementEnseigneEtablissement": False,
                "denominationUsuelleEtablissement": None,
                "changementDenominationUsuelleEtablissement": False,
                "activitePrincipaleEtablissement": "74.7Z",
                "nomenclatureActivitePrincipaleEtablissement": "NAF1993",
                "changementActivitePrincipaleEtablissement": False,
                "caractereEmployeurEtablissement": "O",
                "changementCaractereEmployeurEtablissement": False,
            }
        ],
    },
}

RESPONSE_SIREN_SAINT_MARTIN_COMPANY_WITHOUT_POSTAL_CODE = {
    "header": {"statut": 200, "message": "OK"},
    "uniteLegale": {
        "siren": "123456789",
        "statutDiffusionUniteLegale": "O",
        "dateCreationUniteLegale": "2023-11-01",
        "sigleUniteLegale": None,
        "sexeUniteLegale": None,
        "prenom1UniteLegale": None,
        "prenom2UniteLegale": None,
        "prenom3UniteLegale": None,
        "prenom4UniteLegale": None,
        "prenomUsuelUniteLegale": None,
        "pseudonymeUniteLegale": None,
        "identifiantAssociationUniteLegale": "A1A1111111",
        "trancheEffectifsUniteLegale": None,
        "anneeEffectifsUniteLegale": None,
        "dateDernierTraitementUniteLegale": "2024-03-22T14:26:06.000",
        "nombrePeriodesUniteLegale": 1,
        "categorieEntreprise": None,
        "anneeCategorieEntreprise": None,
        "periodesUniteLegale": [
            {
                "dateFin": None,
                "dateDebut": "2023-11-01",
                "etatAdministratifUniteLegale": "A",
                "changementEtatAdministratifUniteLegale": False,
                "nomUniteLegale": None,
                "changementNomUniteLegale": False,
                "nomUsageUniteLegale": None,
                "changementNomUsageUniteLegale": False,
                "denominationUniteLegale": "ENTREPRISE SANS CODE POSTAL",
                "changementDenominationUniteLegale": False,
                "denominationUsuelle1UniteLegale": None,
                "denominationUsuelle2UniteLegale": None,
                "denominationUsuelle3UniteLegale": None,
                "changementDenominationUsuelleUniteLegale": False,
                "categorieJuridiqueUniteLegale": "9220",
                "changementCategorieJuridiqueUniteLegale": False,
                "activitePrincipaleUniteLegale": "94.99Z",
                "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
                "changementActivitePrincipaleUniteLegale": False,
                "nicSiegeUniteLegale": "00011",
                "changementNicSiegeUniteLegale": False,
                "economieSocialeSolidaireUniteLegale": "O",
                "changementEconomieSocialeSolidaireUniteLegale": False,
                "societeMissionUniteLegale": None,
                "changementSocieteMissionUniteLegale": False,
                "caractereEmployeurUniteLegale": None,
                "changementCaractereEmployeurUniteLegale": False,
            }
        ],
    },
}

RESPONSE_SIRET_SAINT_MARTIN_COMPANY_WITHOUT_POSTAL_CODE = {
    "header": {"statut": 200, "message": "ok"},
    "etablissement": {
        "siren": "123456789",
        "nic": "00011",
        "siret": "12345678900011",
        "statutDiffusionEtablissement": "O",
        "dateCreationEtablissement": "2023-11-01",
        "trancheEffectifsEtablissement": None,
        "anneeEffectifsEtablissement": None,
        "activitePrincipaleRegistreMetiersEtablissement": None,
        "dateDernierTraitementEtablissement": "2024-03-30T08:46:40.550",
        "etablissementSiege": True,
        "nombrePeriodesEtablissement": 1,
        "uniteLegale": {
            "etatAdministratifUniteLegale": "A",
            "statutDiffusionUniteLegale": "O",
            "dateCreationUniteLegale": "2023-11-01",
            "categorieJuridiqueUniteLegale": "9220",
            "denominationUniteLegale": "ENTREPRISE SANS CODE POSTAL",
            "sigleUniteLegale": None,
            "denominationUsuelle1UniteLegale": None,
            "denominationUsuelle2UniteLegale": None,
            "denominationUsuelle3UniteLegale": None,
            "sexeUniteLegale": None,
            "nomUniteLegale": None,
            "nomUsageUniteLegale": None,
            "prenom1UniteLegale": None,
            "prenom2UniteLegale": None,
            "prenom3UniteLegale": None,
            "prenom4UniteLegale": None,
            "prenomUsuelUniteLegale": None,
            "pseudonymeUniteLegale": None,
            "activitePrincipaleUniteLegale": "94.99Z",
            "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
            "identifiantAssociationUniteLegale": "W9G3005162",
            "economieSocialeSolidaireUniteLegale": "O",
            "societeMissionUniteLegale": None,
            "caractereEmployeurUniteLegale": None,
            "trancheEffectifsUniteLegale": None,
            "anneeEffectifsUniteLegale": None,
            "nicSiegeUniteLegale": "00017",
            "dateDernierTraitementUniteLegale": "2024-03-22T09:28:19.000",
            "categorieEntreprise": None,
            "anneeCategorieEntreprise": None,
        },
        "adresseEtablissement": {
            "complementAdresseEtablissement": "VILLA DE SAINT MARTIN - CUL DE SAC",
            "numeroVoieEtablissement": "1",
            "indiceRepetitionEtablissement": None,
            "dernierNumeroVoieEtablissement": None,
            "indiceRepetitionDernierNumeroVoieEtablissement": None,
            "typeVoieEtablissement": "RUE",
            "libelleVoieEtablissement": "DE SAINT MARTIN",
            "codePostalEtablissement": None,
            "libelleCommuneEtablissement": "SAINT-MARTIN",
            "libelleCommuneEtrangerEtablissement": None,
            "distributionSpecialeEtablissement": None,
            "codeCommuneEtablissement": "97801",
            "codeCedexEtablissement": None,
            "libelleCedexEtablissement": None,
            "codePaysEtrangerEtablissement": None,
            "libellePaysEtrangerEtablissement": None,
            "identifiantAdresseEtablissement": "12345689_B",
            "coordonneeLambertAbscisseEtablissement": "17.00000",
            "coordonneeLambertOrdonneeEtablissement": "-62.00000",
        },
        "adresse2Etablissement": {
            "complementAdresse2Etablissement": None,
            "numeroVoie2Etablissement": None,
            "indiceRepetition2Etablissement": None,
            "typeVoie2Etablissement": None,
            "libelleVoie2Etablissement": None,
            "codePostal2Etablissement": None,
            "libelleCommune2Etablissement": None,
            "libelleCommuneEtranger2Etablissement": None,
            "distributionSpeciale2Etablissement": None,
            "codeCommune2Etablissement": None,
            "codeCedex2Etablissement": None,
            "libelleCedex2Etablissement": None,
            "codePaysEtranger2Etablissement": None,
            "libellePaysEtranger2Etablissement": None,
        },
        "periodesEtablissement": [
            {
                "dateFin": None,
                "dateDebut": "2023-11-01",
                "etatAdministratifEtablissement": "A",
                "changementEtatAdministratifEtablissement": False,
                "enseigne1Etablissement": None,
                "enseigne2Etablissement": None,
                "enseigne3Etablissement": None,
                "changementEnseigneEtablissement": False,
                "denominationUsuelleEtablissement": None,
                "changementDenominationUsuelleEtablissement": False,
                "activitePrincipaleEtablissement": "94.99Z",
                "nomenclatureActivitePrincipaleEtablissement": "NAFRev2",
                "changementActivitePrincipaleEtablissement": False,
                "caractereEmployeurEtablissement": "N",
                "changementCaractereEmployeurEtablissement": False,
            }
        ],
    },
}

RESPONSE_CLOSED_SIREN_PAGE1 = {
    "header": {
        "statut": 200,
        "message": "OK",
        "total": 5,
        "debut": 0,
        "nombre": 3,
        "curseur": "*",
        "curseurSuivant": "AoEpODg5Mjg4Mzc5",
    },
    "unitesLegales": [
        {
            "siren": "111111118",
            "dateDernierTraitementUniteLegale": "2025-01-26T12:34:56.789",
            "periodesUniteLegale": [
                {"dateFin": None, "dateDebut": "2025-01-25", "etatAdministratifUniteLegale": "C"},
                {"dateFin": "2025-01-24", "dateDebut": "2024-01-01", "etatAdministratifUniteLegale": "A"},
            ],
        },
        {
            "siren": "222222226",
            "dateDernierTraitementUniteLegale": "2025-01-26T12:34:56.789",
            "periodesUniteLegale": [
                {"dateFin": None, "dateDebut": "2024-12-31", "etatAdministratifUniteLegale": "C"},
                {"dateFin": "2024-12-30", "dateDebut": "2024-01-01", "etatAdministratifUniteLegale": "A"},
            ],
        },
        {
            "siren": "333333334",
            "dateDernierTraitementUniteLegale": "2025-01-26T12:34:56.789",
            "periodesUniteLegale": [
                {"dateFin": None, "dateDebut": "2032-12-31", "etatAdministratifUniteLegale": "C"},
                {"dateFin": "2032-12-30", "dateDebut": "2024-01-01", "etatAdministratifUniteLegale": "A"},
            ],
        },
    ],
}

RESPONSE_CLOSED_SIREN_PAGE2 = {
    "header": {
        "statut": 200,
        "message": "OK",
        "total": 5,
        "debut": 3,
        "nombre": 2,
        "curseur": "AoEpODg5Mjg4Mzc5",
        "curseurSuivant": "AoEpODg5Mjg4Mzc5",
    },
    "unitesLegales": [
        {
            "siren": "444444442",
            "dateDernierTraitementUniteLegale": "2025-01-26T12:34:56.789",
            "periodesUniteLegale": [
                {"dateFin": None, "dateDebut": "2033-01-01", "etatAdministratifUniteLegale": "A"},
                {"dateFin": "2032-12-31", "dateDebut": "2025-02-17", "etatAdministratifUniteLegale": "C"},
                {"dateFin": "2025-02-16", "dateDebut": "2024-01-01", "etatAdministratifUniteLegale": "C"},
                {"dateFin": "2024-12-30", "dateDebut": "2024-01-01", "etatAdministratifUniteLegale": "A"},
            ],
        },
        {
            "siren": "555555556",
            "dateDernierTraitementUniteLegale": "2025-01-26T12:34:56.789",
            "periodesUniteLegale": [
                {"dateFin": None, "dateDebut": "2025-01-17", "etatAdministratifUniteLegale": "C"},
                {"dateFin": "2025-01-16", "dateDebut": "2024-01-01", "etatAdministratifUniteLegale": "C"},
                {"dateFin": "2024-12-30", "dateDebut": "2024-01-01", "etatAdministratifUniteLegale": "A"},
            ],
        },
    ],
}


RESPONSE_SIREN_CLOSED = {
    "header": {"statut": 200, "message": "OK"},
    "uniteLegale": {
        "siren": "11111118",
        "statutDiffusionUniteLegale": "O",
        "dateCreationUniteLegale": "2001-01-02",
        "sigleUniteLegale": None,
        "sexeUniteLegale": None,
        "prenom1UniteLegale": None,
        "prenom2UniteLegale": None,
        "prenom3UniteLegale": None,
        "prenom4UniteLegale": None,
        "prenomUsuelUniteLegale": None,
        "pseudonymeUniteLegale": None,
        "identifiantAssociationUniteLegale": None,
        "trancheEffectifsUniteLegale": None,
        "anneeEffectifsUniteLegale": None,
        "dateDernierTraitementUniteLegale": "2025-01-25T05:11:22.123",
        "nombrePeriodesUniteLegale": 3,
        "categorieEntreprise": None,
        "anneeCategorieEntreprise": None,
        "periodesUniteLegale": [
            {
                "dateFin": None,
                "dateDebut": "2025-01-24",
                "etatAdministratifUniteLegale": "C",
                "changementEtatAdministratifUniteLegale": True,
                "nomUniteLegale": None,
                "changementNomUniteLegale": False,
                "nomUsageUniteLegale": None,
                "changementNomUsageUniteLegale": False,
                "denominationUniteLegale": "ENTREPRISE FERMEE",
                "changementDenominationUniteLegale": False,
                "denominationUsuelle1UniteLegale": None,
                "denominationUsuelle2UniteLegale": None,
                "denominationUsuelle3UniteLegale": None,
                "changementDenominationUsuelleUniteLegale": False,
                "categorieJuridiqueUniteLegale": "5410",
                "changementCategorieJuridiqueUniteLegale": False,
                "activitePrincipaleUniteLegale": "90.01Z",
                "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
                "changementActivitePrincipaleUniteLegale": False,
                "nicSiegeUniteLegale": "00019",
                "changementNicSiegeUniteLegale": False,
                "economieSocialeSolidaireUniteLegale": None,
                "changementEconomieSocialeSolidaireUniteLegale": False,
                "societeMissionUniteLegale": None,
                "changementSocieteMissionUniteLegale": False,
                "caractereEmployeurUniteLegale": None,
                "changementCaractereEmployeurUniteLegale": False,
            },
            {
                "dateFin": "2025-01-23",
                "dateDebut": "2001-01-02",
                "etatAdministratifUniteLegale": "A",
                "changementEtatAdministratifUniteLegale": False,
                "nomUniteLegale": None,
                "changementNomUniteLegale": False,
                "nomUsageUniteLegale": None,
                "changementNomUsageUniteLegale": False,
                "denominationUniteLegale": "ENTREPRISE FERMEE",
                "changementDenominationUniteLegale": False,
                "denominationUsuelle1UniteLegale": None,
                "denominationUsuelle2UniteLegale": None,
                "denominationUsuelle3UniteLegale": None,
                "changementDenominationUsuelleUniteLegale": False,
                "categorieJuridiqueUniteLegale": "5410",
                "changementCategorieJuridiqueUniteLegale": False,
                "activitePrincipaleUniteLegale": "90.01Z",
                "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
                "changementActivitePrincipaleUniteLegale": False,
                "nicSiegeUniteLegale": "00019",
                "changementNicSiegeUniteLegale": False,
                "economieSocialeSolidaireUniteLegale": None,
                "changementEconomieSocialeSolidaireUniteLegale": False,
                "societeMissionUniteLegale": None,
                "changementSocieteMissionUniteLegale": False,
                "caractereEmployeurUniteLegale": None,
                "changementCaractereEmployeurUniteLegale": False,
            },
        ],
    },
}


RESPONSE_SIRET_CLOSED = {
    "header": {"statut": 200, "message": "ok"},
    "etablissement": {
        "siren": "111111118",
        "nic": "00048",
        "siret": "11111111800019",
        "statutDiffusionEtablissement": "O",
        "dateCreationEtablissement": "2001-01-02",
        "trancheEffectifsEtablissement": None,
        "anneeEffectifsEtablissement": None,
        "activitePrincipaleRegistreMetiersEtablissement": None,
        "dateDernierTraitementEtablissement": "2024-09-20T11:22:33.444",
        "etablissementSiege": True,
        "nombrePeriodesEtablissement": 3,
        "uniteLegale": {
            "etatAdministratifUniteLegale": "C",
            "statutDiffusionUniteLegale": "O",
            "dateCreationUniteLegale": "2001-01-02",
            "categorieJuridiqueUniteLegale": "5410",
            "denominationUniteLegale": "ENTREPRISE FERMEE",
            "sigleUniteLegale": None,
            "denominationUsuelle1UniteLegale": None,
            "denominationUsuelle2UniteLegale": None,
            "denominationUsuelle3UniteLegale": None,
            "sexeUniteLegale": None,
            "nomUniteLegale": None,
            "nomUsageUniteLegale": None,
            "prenom1UniteLegale": None,
            "prenom2UniteLegale": None,
            "prenom3UniteLegale": None,
            "prenom4UniteLegale": None,
            "prenomUsuelUniteLegale": None,
            "pseudonymeUniteLegale": None,
            "activitePrincipaleUniteLegale": "90.01Z",
            "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
            "identifiantAssociationUniteLegale": None,
            "economieSocialeSolidaireUniteLegale": None,
            "societeMissionUniteLegale": None,
            "caractereEmployeurUniteLegale": None,
            "trancheEffectifsUniteLegale": None,
            "anneeEffectifsUniteLegale": None,
            "nicSiegeUniteLegale": "00019",
            "dateDernierTraitementUniteLegale": "2025-01-25T05:11:22.123",
            "categorieEntreprise": None,
            "anneeCategorieEntreprise": None,
        },
        "adresseEtablissement": {
            "complementAdresseEtablissement": None,
            "numeroVoieEtablissement": "3",
            "indiceRepetitionEtablissement": None,
            "dernierNumeroVoieEtablissement": None,
            "indiceRepetitionDernierNumeroVoieEtablissement": None,
            "typeVoieEtablissement": "RUE",
            "libelleVoieEtablissement": "DE VALOIS",
            "codePostalEtablissement": "75001",
            "libelleCommuneEtablissement": "PARIS 1",
            "libelleCommuneEtrangerEtablissement": None,
            "distributionSpecialeEtablissement": None,
            "codeCommuneEtablissement": "75001",
            "codeCedexEtablissement": None,
            "libelleCedexEtablissement": None,
            "codePaysEtrangerEtablissement": None,
            "libellePaysEtrangerEtablissement": None,
            "identifiantAdresseEtablissement": "751098393_B",
            "coordonneeLambertAbscisseEtablissement": "48.871274",
            "coordonneeLambertOrdonneeEtablissement": "2.345886",
        },
        "adresse2Etablissement": {
            "complementAdresse2Etablissement": None,
            "numeroVoie2Etablissement": None,
            "indiceRepetition2Etablissement": None,
            "typeVoie2Etablissement": None,
            "libelleVoie2Etablissement": None,
            "codePostal2Etablissement": None,
            "libelleCommune2Etablissement": None,
            "libelleCommuneEtranger2Etablissement": None,
            "distributionSpeciale2Etablissement": None,
            "codeCommune2Etablissement": None,
            "codeCedex2Etablissement": None,
            "libelleCedex2Etablissement": None,
            "codePaysEtranger2Etablissement": None,
            "libellePaysEtranger2Etablissement": None,
        },
        "periodesEtablissement": [
            {
                "dateFin": None,
                "dateDebut": "2025-01-24",
                "etatAdministratifEtablissement": "F",
                "changementEtatAdministratifEtablissement": True,
                "enseigne1Etablissement": None,
                "enseigne2Etablissement": None,
                "enseigne3Etablissement": None,
                "changementEnseigneEtablissement": False,
                "denominationUsuelleEtablissement": None,
                "changementDenominationUsuelleEtablissement": False,
                "activitePrincipaleEtablissement": "90.01Z",
                "nomenclatureActivitePrincipaleEtablissement": "NAFRev2",
                "changementActivitePrincipaleEtablissement": False,
                "caractereEmployeurEtablissement": "O",
                "changementCaractereEmployeurEtablissement": False,
            },
            {
                "dateFin": "2025-01-23",
                "dateDebut": "2001-01-02",
                "etatAdministratifEtablissement": "A",
                "changementEtatAdministratifEtablissement": False,
                "enseigne1Etablissement": None,
                "enseigne2Etablissement": None,
                "enseigne3Etablissement": None,
                "changementEnseigneEtablissement": False,
                "denominationUsuelleEtablissement": None,
                "changementDenominationUsuelleEtablissement": False,
                "activitePrincipaleEtablissement": "90.01Z",
                "nomenclatureActivitePrincipaleEtablissement": "NAFRev2",
                "changementActivitePrincipaleEtablissement": False,
                "caractereEmployeurEtablissement": "O",
                "changementCaractereEmployeurEtablissement": False,
            },
        ],
    },
}

RESPONSE_FUTURE_SIREN = {
    "header": {"statut": 200, "message": "OK"},
    "uniteLegale": {
        "siren": "222222226",
        "statutDiffusionUniteLegale": "P",
        "dateCreationUniteLegale": (datetime.date.today() + datetime.timedelta(days=10)).isoformat(),
        "sigleUniteLegale": "[ND]",
        "sexeUniteLegale": "[ND]",
        "prenom1UniteLegale": "[ND]",
        "prenom2UniteLegale": "[ND]",
        "prenom3UniteLegale": "[ND]",
        "prenom4UniteLegale": "[ND]",
        "prenomUsuelUniteLegale": "[ND]",
        "pseudonymeUniteLegale": "[ND]",
        "identifiantAssociationUniteLegale": None,
        "trancheEffectifsUniteLegale": None,
        "anneeEffectifsUniteLegale": None,
        "dateDernierTraitementUniteLegale": "2025-01-27T11:22:33.444",
        "nombrePeriodesUniteLegale": 1,
        "categorieEntreprise": None,
        "anneeCategorieEntreprise": None,
        "periodesUniteLegale": [
            {
                "dateFin": None,
                "dateDebut": (datetime.date.today() + datetime.timedelta(days=10)).isoformat(),
                "etatAdministratifUniteLegale": "A",
                "changementEtatAdministratifUniteLegale": False,
                "nomUniteLegale": "[ND]",
                "changementNomUniteLegale": False,
                "nomUsageUniteLegale": "[ND]",
                "changementNomUsageUniteLegale": False,
                "denominationUniteLegale": "[ND]",
                "changementDenominationUniteLegale": False,
                "denominationUsuelle1UniteLegale": "[ND]",
                "denominationUsuelle2UniteLegale": "[ND]",
                "denominationUsuelle3UniteLegale": "[ND]",
                "changementDenominationUsuelleUniteLegale": False,
                "categorieJuridiqueUniteLegale": "1000",
                "changementCategorieJuridiqueUniteLegale": False,
                "activitePrincipaleUniteLegale": "90.01Z",
                "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
                "changementActivitePrincipaleUniteLegale": False,
                "nicSiegeUniteLegale": "00011",
                "changementNicSiegeUniteLegale": False,
                "economieSocialeSolidaireUniteLegale": None,
                "changementEconomieSocialeSolidaireUniteLegale": False,
                "societeMissionUniteLegale": None,
                "changementSocieteMissionUniteLegale": False,
                "caractereEmployeurUniteLegale": None,
                "changementCaractereEmployeurUniteLegale": False,
            }
        ],
    },
}

RESPONSE_SIRENE_WITHOUT_PERIOD_DATE = {
    "header": {"statut": 200, "message": "OK"},
    "uniteLegale": {
        "siren": "333333334",
        "statutDiffusionUniteLegale": "O",
        "unitePurgeeUniteLegale": True,
        "dateCreationUniteLegale": "1968-01-01",
        "sigleUniteLegale": None,
        "sexeUniteLegale": None,
        "prenom1UniteLegale": None,
        "prenom2UniteLegale": None,
        "prenom3UniteLegale": None,
        "prenom4UniteLegale": None,
        "prenomUsuelUniteLegale": None,
        "pseudonymeUniteLegale": None,
        "identifiantAssociationUniteLegale": None,
        "trancheEffectifsUniteLegale": None,
        "anneeEffectifsUniteLegale": None,
        "dateDernierTraitementUniteLegale": "2024-04-07T12:34:56.001",
        "nombrePeriodesUniteLegale": 1,
        "categorieEntreprise": None,
        "anneeCategorieEntreprise": None,
        "periodesUniteLegale": [
            {
                "dateFin": None,
                "dateDebut": None,
                "etatAdministratifUniteLegale": "C",
                "changementEtatAdministratifUniteLegale": False,
                "nomUniteLegale": None,
                "changementNomUniteLegale": False,
                "nomUsageUniteLegale": None,
                "changementNomUsageUniteLegale": False,
                "denominationUniteLegale": "NI DATE DEBUT NI DATE FIN",
                "changementDenominationUniteLegale": False,
                "denominationUsuelle1UniteLegale": None,
                "denominationUsuelle2UniteLegale": None,
                "denominationUsuelle3UniteLegale": None,
                "changementDenominationUsuelleUniteLegale": False,
                "categorieJuridiqueUniteLegale": "5499",
                "changementCategorieJuridiqueUniteLegale": False,
                "activitePrincipaleUniteLegale": "51.20",
                "nomenclatureActivitePrincipaleUniteLegale": "NAP",
                "changementActivitePrincipaleUniteLegale": False,
                "nicSiegeUniteLegale": "00014",
                "changementNicSiegeUniteLegale": False,
                "economieSocialeSolidaireUniteLegale": None,
                "changementEconomieSocialeSolidaireUniteLegale": False,
                "societeMissionUniteLegale": None,
                "changementSocieteMissionUniteLegale": False,
                "caractereEmployeurUniteLegale": None,
                "changementCaractereEmployeurUniteLegale": False,
            }
        ],
    },
}
