RESPONSE_SIREN_COMPANY = {
    "header": {"statut": 200, "message": "OK"},
    "uniteLegale": {
        "siren": "123456789",
        "statutDiffusionUniteLegale": "O",
        "dateCreationUniteLegale": "2022-05-24",
        "sigleUniteLegale": None,
        "sexeUniteLegale": None,
        "prenom1UniteLegale": None,
        "prenom2UniteLegale": None,
        "prenom3UniteLegale": None,
        "prenom4UniteLegale": None,
        "prenomUsuelUniteLegale": None,
        "pseudonymeUniteLegale": None,
        "identifiantAssociationUniteLegale": None,
        "trancheEffectifsUniteLegale": None,
        "anneeEffectifsUniteLegale": None,
        "dateDernierTraitementUniteLegale": "2022-07-14T08:37:54",
        "nombrePeriodesUniteLegale": 2,
        "categorieEntreprise": None,
        "anneeCategorieEntreprise": None,
        "periodesUniteLegale": [
            {
                "dateFin": None,
                "dateDebut": "2022-06-14",
                "etatAdministratifUniteLegale": "A",
                "changementEtatAdministratifUniteLegale": False,
                "nomUniteLegale": None,
                "changementNomUniteLegale": False,
                "nomUsageUniteLegale": None,
                "changementNomUsageUniteLegale": False,
                "denominationUniteLegale": "LE PETIT RINTINTIN",
                "changementDenominationUniteLegale": False,
                "denominationUsuelle1UniteLegale": None,
                "denominationUsuelle2UniteLegale": None,
                "denominationUsuelle3UniteLegale": None,
                "changementDenominationUsuelleUniteLegale": False,
                "categorieJuridiqueUniteLegale": "5499",
                "changementCategorieJuridiqueUniteLegale": False,
                "activitePrincipaleUniteLegale": "47.61Z",
                "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
                "changementActivitePrincipaleUniteLegale": True,
                "nicSiegeUniteLegale": "00017",
                "changementNicSiegeUniteLegale": False,
                "economieSocialeSolidaireUniteLegale": "N",
                "changementEconomieSocialeSolidaireUniteLegale": False,
                "caractereEmployeurUniteLegale": "O",
                "changementCaractereEmployeurUniteLegale": True,
            },
            {
                "dateFin": "2022-06-13",
                "dateDebut": "2022-05-24",
                "etatAdministratifUniteLegale": "A",
                "changementEtatAdministratifUniteLegale": False,
                "nomUniteLegale": None,
                "changementNomUniteLegale": False,
                "nomUsageUniteLegale": None,
                "changementNomUsageUniteLegale": False,
                "denominationUniteLegale": "LE PETIT RINTINTIN",
                "changementDenominationUniteLegale": False,
                "denominationUsuelle1UniteLegale": None,
                "denominationUsuelle2UniteLegale": None,
                "denominationUsuelle3UniteLegale": None,
                "changementDenominationUsuelleUniteLegale": False,
                "categorieJuridiqueUniteLegale": "5499",
                "changementCategorieJuridiqueUniteLegale": False,
                "activitePrincipaleUniteLegale": "00.00Z",
                "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
                "changementActivitePrincipaleUniteLegale": False,
                "nicSiegeUniteLegale": "00017",
                "changementNicSiegeUniteLegale": False,
                "economieSocialeSolidaireUniteLegale": "N",
                "changementEconomieSocialeSolidaireUniteLegale": False,
                "caractereEmployeurUniteLegale": "N",
                "changementCaractereEmployeurUniteLegale": False,
            },
        ],
    },
}

RESPONSE_SIREN_ENTREPRISE_INDIVIDUELLE = {
    "header": {"statut": 200, "message": "OK"},
    "uniteLegale": {
        "siren": "123456789",
        "statutDiffusionUniteLegale": "O",
        "dateCreationUniteLegale": "2016-01-05",
        "sigleUniteLegale": None,
        "sexeUniteLegale": "M",
        "prenom1UniteLegale": "PIERRE",
        "prenom2UniteLegale": None,
        "prenom3UniteLegale": None,
        "prenom4UniteLegale": None,
        "prenomUsuelUniteLegale": "PIERRE",
        "pseudonymeUniteLegale": None,
        "identifiantAssociationUniteLegale": None,
        "trancheEffectifsUniteLegale": None,
        "anneeEffectifsUniteLegale": None,
        "dateDernierTraitementUniteLegale": "2022-06-21T20:07:38",
        "nombrePeriodesUniteLegale": 4,
        "categorieEntreprise": "PME",
        "anneeCategorieEntreprise": "2019",
        "periodesUniteLegale": [
            {
                "dateFin": None,
                "dateDebut": "2021-04-08",
                "etatAdministratifUniteLegale": "A",
                "changementEtatAdministratifUniteLegale": False,
                "nomUniteLegale": "EXEMPLE",
                "changementNomUniteLegale": False,
                "nomUsageUniteLegale": None,
                "changementNomUsageUniteLegale": False,
                "denominationUniteLegale": None,
                "changementDenominationUniteLegale": False,
                "denominationUsuelle1UniteLegale": None,
                "denominationUsuelle2UniteLegale": None,
                "denominationUsuelle3UniteLegale": None,
                "changementDenominationUsuelleUniteLegale": False,
                "categorieJuridiqueUniteLegale": "1000",
                "changementCategorieJuridiqueUniteLegale": False,
                "activitePrincipaleUniteLegale": "90.03A",
                "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
                "changementActivitePrincipaleUniteLegale": False,
                "nicSiegeUniteLegale": "00045",
                "changementNicSiegeUniteLegale": True,
                "economieSocialeSolidaireUniteLegale": None,
                "changementEconomieSocialeSolidaireUniteLegale": False,
                "caractereEmployeurUniteLegale": "N",
                "changementCaractereEmployeurUniteLegale": False,
            },
            {
                "dateFin": "2021-04-07",
                "dateDebut": "2019-01-31",
                "etatAdministratifUniteLegale": "A",
                "changementEtatAdministratifUniteLegale": False,
                "nomUniteLegale": "EXEMPLE",
                "changementNomUniteLegale": False,
                "nomUsageUniteLegale": None,
                "changementNomUsageUniteLegale": False,
                "denominationUniteLegale": None,
                "changementDenominationUniteLegale": False,
                "denominationUsuelle1UniteLegale": None,
                "denominationUsuelle2UniteLegale": None,
                "denominationUsuelle3UniteLegale": None,
                "changementDenominationUsuelleUniteLegale": False,
                "categorieJuridiqueUniteLegale": "1000",
                "changementCategorieJuridiqueUniteLegale": False,
                "activitePrincipaleUniteLegale": "90.03A",
                "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
                "changementActivitePrincipaleUniteLegale": True,
                "nicSiegeUniteLegale": "00037",
                "changementNicSiegeUniteLegale": True,
                "economieSocialeSolidaireUniteLegale": None,
                "changementEconomieSocialeSolidaireUniteLegale": False,
                "caractereEmployeurUniteLegale": "N",
                "changementCaractereEmployeurUniteLegale": False,
            },
            {
                "dateFin": "2019-01-30",
                "dateDebut": "2016-04-24",
                "etatAdministratifUniteLegale": "A",
                "changementEtatAdministratifUniteLegale": False,
                "nomUniteLegale": "EXEMPLE",
                "changementNomUniteLegale": False,
                "nomUsageUniteLegale": None,
                "changementNomUsageUniteLegale": False,
                "denominationUniteLegale": None,
                "changementDenominationUniteLegale": False,
                "denominationUsuelle1UniteLegale": None,
                "denominationUsuelle2UniteLegale": None,
                "denominationUsuelle3UniteLegale": None,
                "changementDenominationUsuelleUniteLegale": False,
                "categorieJuridiqueUniteLegale": "1000",
                "changementCategorieJuridiqueUniteLegale": False,
                "activitePrincipaleUniteLegale": "74.10Z",
                "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
                "changementActivitePrincipaleUniteLegale": False,
                "nicSiegeUniteLegale": "00029",
                "changementNicSiegeUniteLegale": True,
                "economieSocialeSolidaireUniteLegale": None,
                "changementEconomieSocialeSolidaireUniteLegale": False,
                "caractereEmployeurUniteLegale": "N",
                "changementCaractereEmployeurUniteLegale": False,
            },
            {
                "dateFin": "2016-04-23",
                "dateDebut": "2016-01-05",
                "etatAdministratifUniteLegale": "A",
                "changementEtatAdministratifUniteLegale": False,
                "nomUniteLegale": "EXEMPLE",
                "changementNomUniteLegale": False,
                "nomUsageUniteLegale": None,
                "changementNomUsageUniteLegale": False,
                "denominationUniteLegale": None,
                "changementDenominationUniteLegale": False,
                "denominationUsuelle1UniteLegale": None,
                "denominationUsuelle2UniteLegale": None,
                "denominationUsuelle3UniteLegale": None,
                "changementDenominationUsuelleUniteLegale": False,
                "categorieJuridiqueUniteLegale": "1000",
                "changementCategorieJuridiqueUniteLegale": False,
                "activitePrincipaleUniteLegale": "74.10Z",
                "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
                "changementActivitePrincipaleUniteLegale": False,
                "nicSiegeUniteLegale": "00011",
                "changementNicSiegeUniteLegale": False,
                "economieSocialeSolidaireUniteLegale": None,
                "changementEconomieSocialeSolidaireUniteLegale": False,
                "caractereEmployeurUniteLegale": "N",
                "changementCaractereEmployeurUniteLegale": False,
            },
        ],
    },
}

RESPONSE_SIRET_COMPANY = {
    "header": {"statut": 200, "message": "ok"},
    "etablissement": {
        "siren": "123456789",
        "nic": "00017",
        "siret": "12345678900017",
        "statutDiffusionEtablissement": "O",
        "dateCreationEtablissement": "2022-05-24",
        "trancheEffectifsEtablissement": None,
        "anneeEffectifsEtablissement": None,
        "activitePrincipaleRegistreMetiersEtablissement": None,
        "dateDernierTraitementEtablissement": "2022-07-14T08:37:54",
        "etablissementSiege": True,
        "nombrePeriodesEtablissement": 2,
        "uniteLegale": {
            "etatAdministratifUniteLegale": "A",
            "statutDiffusionUniteLegale": "O",
            "dateCreationUniteLegale": "2022-05-24",
            "categorieJuridiqueUniteLegale": "5499",
            "denominationUniteLegale": "LE PETIT RINTINTIN",
            "sigleUniteLegale": None,
            "denominationUsuelle1UniteLegale": None,
            "denominationUsuelle2UniteLegale": None,
            "denominationUsuelle3UniteLegale": None,
            "sexeUniteLegale": None,
            "nomUniteLegale": None,
            "nomUsageUniteLegale": None,
            "prenom1UniteLegale": None,
            "prenom2UniteLegale": None,
            "prenom3UniteLegale": None,
            "prenom4UniteLegale": None,
            "prenomUsuelUniteLegale": None,
            "pseudonymeUniteLegale": None,
            "activitePrincipaleUniteLegale": "47.61Z",
            "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
            "identifiantAssociationUniteLegale": None,
            "economieSocialeSolidaireUniteLegale": "N",
            "caractereEmployeurUniteLegale": "O",
            "trancheEffectifsUniteLegale": None,
            "anneeEffectifsUniteLegale": None,
            "nicSiegeUniteLegale": "00017",
            "dateDernierTraitementUniteLegale": "2022-07-14T08:37:54",
            "categorieEntreprise": None,
            "anneeCategorieEntreprise": None,
        },
        "adresseEtablissement": {
            "complementAdresseEtablissement": None,
            "numeroVoieEtablissement": "1",
            "indiceRepetitionEtablissement": None,
            "typeVoieEtablissement": "BD",
            "libelleVoieEtablissement": "POISSONIERE  ",
            "codePostalEtablissement": "75002  ",
            "libelleCommuneEtablissement": "PARIS 2  ",
            "libelleCommuneEtrangerEtablissement": None,
            "distributionSpecialeEtablissement": None,
            "codeCommuneEtablissement": "75102",
            "codeCedexEtablissement": None,
            "libelleCedexEtablissement": None,
            "codePaysEtrangerEtablissement": None,
            "libellePaysEtrangerEtablissement": None,
        },
        "adresse2Etablissement": {
            "complementAdresse2Etablissement": None,
            "numeroVoie2Etablissement": None,
            "indiceRepetition2Etablissement": None,
            "typeVoie2Etablissement": None,
            "libelleVoie2Etablissement": None,
            "codePostal2Etablissement": None,
            "libelleCommune2Etablissement": None,
            "libelleCommuneEtranger2Etablissement": None,
            "distributionSpeciale2Etablissement": None,
            "codeCommune2Etablissement": None,
            "codeCedex2Etablissement": None,
            "libelleCedex2Etablissement": None,
            "codePaysEtranger2Etablissement": None,
            "libellePaysEtranger2Etablissement": None,
        },
        "periodesEtablissement": [
            {
                "dateFin": None,
                "dateDebut": "2022-06-14",
                "etatAdministratifEtablissement": "A",
                "changementEtatAdministratifEtablissement": False,
                "enseigne1Etablissement": "LE PETIT RINTINTINT",
                "enseigne2Etablissement": None,
                "enseigne3Etablissement": None,
                "changementEnseigneEtablissement": True,
                "denominationUsuelleEtablissement": "LE PETIT RINTINTIN",
                "changementDenominationUsuelleEtablissement": True,
                "activitePrincipaleEtablissement": "47.61Z",
                "nomenclatureActivitePrincipaleEtablissement": "NAFRev2",
                "changementActivitePrincipaleEtablissement": True,
                "caractereEmployeurEtablissement": "O",
                "changementCaractereEmployeurEtablissement": True,
            },
            {
                "dateFin": "2022-06-13",
                "dateDebut": "2022-05-24",
                "etatAdministratifEtablissement": "A",
                "changementEtatAdministratifEtablissement": False,
                "enseigne1Etablissement": None,
                "enseigne2Etablissement": None,
                "enseigne3Etablissement": None,
                "changementEnseigneEtablissement": False,
                "denominationUsuelleEtablissement": None,
                "changementDenominationUsuelleEtablissement": False,
                "activitePrincipaleEtablissement": "70.10Z",
                "nomenclatureActivitePrincipaleEtablissement": "NAFRev2",
                "changementActivitePrincipaleEtablissement": False,
                "caractereEmployeurEtablissement": "N",
                "changementCaractereEmployeurEtablissement": False,
            },
        ],
    },
}

RESPONSE_SIRET_ENTREPRISE_INDIVIDUELLE = {
    "header": {"statut": 200, "message": "ok"},
    "etablissement": {
        "siren": "123456789",
        "nic": "00045",
        "siret": "12345678900045",
        "statutDiffusionEtablissement": "O",
        "dateCreationEtablissement": "2021-04-08",
        "trancheEffectifsEtablissement": None,
        "anneeEffectifsEtablissement": None,
        "activitePrincipaleRegistreMetiersEtablissement": None,
        "dateDernierTraitementEtablissement": "2022-06-21T20:07:38",
        "etablissementSiege": True,
        "nombrePeriodesEtablissement": 1,
        "uniteLegale": {
            "etatAdministratifUniteLegale": "A",
            "statutDiffusionUniteLegale": "O",
            "dateCreationUniteLegale": "2016-01-05",
            "categorieJuridiqueUniteLegale": "1000",
            "denominationUniteLegale": None,
            "sigleUniteLegale": None,
            "denominationUsuelle1UniteLegale": None,
            "denominationUsuelle2UniteLegale": None,
            "denominationUsuelle3UniteLegale": None,
            "sexeUniteLegale": "M",
            "nomUniteLegale": "EXEMPLE",
            "nomUsageUniteLegale": None,
            "prenom1UniteLegale": "PIERRE",
            "prenom2UniteLegale": None,
            "prenom3UniteLegale": None,
            "prenom4UniteLegale": None,
            "prenomUsuelUniteLegale": "PIERRE",
            "pseudonymeUniteLegale": None,
            "activitePrincipaleUniteLegale": "90.03A",
            "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
            "identifiantAssociationUniteLegale": None,
            "economieSocialeSolidaireUniteLegale": None,
            "caractereEmployeurUniteLegale": "N",
            "trancheEffectifsUniteLegale": None,
            "anneeEffectifsUniteLegale": None,
            "nicSiegeUniteLegale": "00045",
            "dateDernierTraitementUniteLegale": "2022-06-21T20:07:38",
            "categorieEntreprise": "PME",
            "anneeCategorieEntreprise": "2019",
        },
        "adresseEtablissement": {
            "complementAdresseEtablissement": None,
            "numeroVoieEtablissement": "3",
            "indiceRepetitionEtablissement": None,
            "typeVoieEtablissement": "RUE",
            "libelleVoieEtablissement": "DE VALOIS",
            "codePostalEtablissement": "75001",
            "libelleCommuneEtablissement": "PARIS 1",
            "libelleCommuneEtrangerEtablissement": None,
            "distributionSpecialeEtablissement": None,
            "codeCommuneEtablissement": "75001",
            "codeCedexEtablissement": None,
            "libelleCedexEtablissement": None,
            "codePaysEtrangerEtablissement": None,
            "libellePaysEtrangerEtablissement": None,
        },
        "adresse2Etablissement": {
            "complementAdresse2Etablissement": None,
            "numeroVoie2Etablissement": None,
            "indiceRepetition2Etablissement": None,
            "typeVoie2Etablissement": None,
            "libelleVoie2Etablissement": None,
            "codePostal2Etablissement": None,
            "libelleCommune2Etablissement": None,
            "libelleCommuneEtranger2Etablissement": None,
            "distributionSpeciale2Etablissement": None,
            "codeCommune2Etablissement": None,
            "codeCedex2Etablissement": None,
            "libelleCedex2Etablissement": None,
            "codePaysEtranger2Etablissement": None,
            "libellePaysEtranger2Etablissement": None,
        },
        "periodesEtablissement": [
            {
                "dateFin": None,
                "dateDebut": "2021-04-08",
                "etatAdministratifEtablissement": "A",
                "changementEtatAdministratifEtablissement": False,
                "enseigne1Etablissement": None,
                "enseigne2Etablissement": None,
                "enseigne3Etablissement": None,
                "changementEnseigneEtablissement": False,
                "denominationUsuelleEtablissement": None,
                "changementDenominationUsuelleEtablissement": False,
                "activitePrincipaleEtablissement": "90.03A",
                "nomenclatureActivitePrincipaleEtablissement": "NAFRev2",
                "changementActivitePrincipaleEtablissement": False,
                "caractereEmployeurEtablissement": "N",
                "changementCaractereEmployeurEtablissement": False,
            }
        ],
    },
}
