PARAMETER_ERROR_RESPONSE = {
    "account_email": "a.test@example.com",
    "account_login": "a.test",
    "api_call_datetime": "2021-06-07 12:48:34.041",
    "api_caller_ip": "90.127.244.104",
    "error_detail": "api_key",
    "event_datetime": "2021-06-07 12:48:34.041",
    "event_type": "payment",
    "org_id": "7jp6vj36",
    "password_hash": "4241b68fbc12414a94df141761614813",
    "request_id": "CD07E0DB-692C-43A4-A588-D612777862F2",
    "request_result": "fail_invalid_parameter",
    "service_type": "session-policy",
}
CORRECT_RESPONSE = {
    "account_date_of_birth": "20210607",
    "account_email": "user.email@example.net",
    "account_email_contains_dot": "yes",
    "account_email_domain": "example.net",
    "account_email_first_seen": "2021-06-07",
    "account_email_last_event": "2021-06-07",
    "account_email_last_update": "2021-06-07",
    "account_email_result": "success",
    "account_email_score": "0",
    "account_email_worst_score": "0",
    "account_telephone": "+33601234232",
    "account_telephone_country_code": "33",
    "account_telephone_first_seen": "2021-06-07",
    "account_telephone_geo": "FR",
    "account_telephone_is_possible": "yes",
    "account_telephone_is_valid": "yes",
    "account_telephone_last_event": "2021-06-07",
    "account_telephone_last_update": "2021-06-07",
    "account_telephone_result": "success",
    "account_telephone_score": "0",
    "account_telephone_type": "MOBILE",
    "account_telephone_worst_score": "0",
    "api_call_datetime": "2021-06-07 20:49:37.927",
    "api_caller_ip": "90.127.244.104",
    "api_type": "session-query",
    "api_version": "12.2.2",
    "bb_assessment": "174.51",
    "bb_assessment_rating": "low",
    "bb_bot_rating": "low",
    "bb_bot_score": "500.00",
    "bb_fraud_rating": "neutral",
    "bb_fraud_score": "500.00",
    "champion_request_duration": "10",
    "condition_attrib_5": "agent_mobile",
    "customer_event_type": "agent_mobile",
    "device_first_seen": "2021-11-23",
    "device_id": "d79bd1bf24b94ffd8ad79c092c54cd53",
    "device_id_confidence": "100",
    "device_last_event": "2021-11-24",
    "device_last_update": "2021-11-24",
    "device_match_result": "success",
    "device_memory": "8",
    "device_result": "success",
    "device_score": "0",
    "device_worst_score": "0",
    "digital_id": "c1e6e1d538924d6f94a01b17a60e90ea",
    "digital_id_confidence": "8557",
    "digital_id_confidence_rating": "very_high",
    "digital_id_first_seen": "2021-06-15",
    "digital_id_last_event": "2021-06-15",
    "digital_id_last_update": "2021-06-15",
    "digital_id_result": "success",
    "digital_id_trust_score": "40.00",
    "digital_id_trust_score_rating": "low",
    "digital_id_trust_score_reason_code": [
        "_ts_neutral_conf_score",
        "_ts_gbl_email_black",
        "_ts_gbl_email_white",
        "_ts_inputip_black",
        "_ts_high_entity_age_score",
        "_ts_gbl_high_vel",
        "_ts_very_low_did_age_score",
        "_ts_very_short_did_distance",
        "_ts_very_low_graph_compusp",
        "_ts_unknown_sess",
        "_ts_did_2_or_more_email",
        "_ts_did_white",
        "_ts_did_black",
    ],
    "enabled_services": ["USP100"],
    "event_datetime": "2021-06-15 08:33:01.749",
    "event_type": "account_creation",
    "input_ip_address": "127.0.0.1",
    "line_of_business": "b2b",
    "org_id": "16khy574",
    "policy": "beneficiary_validation_rules",
    "policy_details_api": {
        "policy_detail_api": [
            {
                "customer": {
                    "pvid": "1000050213",
                    "review_status": "pass",
                    "risk_rating": "low",
                    "rules": [
                        {
                            "pvid": "1000050207",
                            "reason_code": "Call " "Policy " "Set " "Tags",
                            "rid": "1032397205",
                            "score": "0",
                        },
                        {"reason_code": "InputIP " "in " "Global " "Blocklist", "rid": "1032397334", "score": "-3"},
                        {
                            "pvid": "1000050210",
                            "reason_code": "Application " "Supplementary " "Rules",
                            "rid": "1032397433",
                            "rules": [
                                {
                                    "reason_code": "5 " "or " "More " "Applications " "Submitted_uspDID_hr",
                                    "rid": "1032396863",
                                    "score": "0",
                                },
                                {
                                    "reason_code": "DigitalID " "in " "USP " "Network " "New " "- " "1Day",
                                    "rid": "1032396952",
                                    "score": "0",
                                },
                                {
                                    "reason_code": "Email " "in " "USP " "Network " "New " "- " "1Day",
                                    "rid": "1032396960",
                                    "score": "0",
                                },
                                {
                                    "reason_code": "Telephone " "in " "USP " "Network " "New " "- " "1Day",
                                    "rid": "1032396968",
                                    "score": "0",
                                },
                                {
                                    "reason_code": "First " "Time " "Login " "with " "Browser " "was " "this " "Hour",
                                    "rid": "1032396987",
                                    "score": "0",
                                },
                                {"reason_code": "uspID " "Trust " "Low", "rid": "1032397006", "score": "0"},
                            ],
                            "score": "0",
                            "vars": [
                                {"rid": "1032396209", "value": "0", "variable": "agenttypes_per_custid_excurrent"},
                                {"rid": "1032396223", "value": "0", "variable": "browsers_per_custid_1day_excurrent"},
                                {"rid": "1032396222", "value": "0", "variable": "browsers_per_custid_1hr_excurrent"},
                                {"rid": "1032396500", "value": "0", "variable": "count_accept_1day_excurrent"},
                                {"rid": "1032396499", "value": "0", "variable": "count_accept_1hr_excurrent"},
                                {"rid": "1032396502", "value": "0", "variable": "count_accept_1mth_excurrent"},
                                {"rid": "1032396498", "value": "0", "variable": "count_accept_30min_excurrent"},
                                {"rid": "1032396503", "value": "0", "variable": "count_accept_excurrent"},
                                {"rid": "1032396501", "value": "0", "variable": "count_accept_wk_excurrent"},
                                {"rid": "1032396418", "value": "0", "variable": "count_amy_count_excurrent"},
                                {"rid": "1032396415", "value": "0", "variable": "count_any_count_excurrent"},
                                {"rid": "1032396424", "value": "0", "variable": "count_apc_count_excurrent"},
                                {"rid": "1032396421", "value": "0", "variable": "count_aro_count_excurrent"},
                                {"rid": "1032396312", "value": "6", "variable": "count_email_app_1day"},
                                {"rid": "1032396310", "value": "6", "variable": "count_email_app_1hr"},
                                {"rid": "1032396314", "value": "6", "variable": "count_email_app_1mth"},
                                {"rid": "1032396311", "value": "6", "variable": "count_email_app_6hrs"},
                                {"rid": "1032396313", "value": "6", "variable": "count_email_app_wk"},
                                {"rid": "1032396549", "value": "0", "variable": "count_email_fraud"},
                                {"rid": "1032396546", "value": "0", "variable": "count_email_fraud_1day"},
                                {"rid": "1032396548", "value": "0", "variable": "count_email_fraud_1mth"},
                                {"rid": "1032396547", "value": "0", "variable": "count_email_fraud_wk"},
                                {"rid": "1032396557", "value": "0", "variable": "count_fraud"},
                                {"rid": "1032396554", "value": "0", "variable": "count_fraud_1day"},
                                {"rid": "1032396556", "value": "0", "variable": "count_fraud_1mth"},
                                {"rid": "1032396555", "value": "0", "variable": "count_fraud_wk"},
                                {"rid": "1032396302", "value": "9", "variable": "count_uspiddig_app_1day"},
                                {"rid": "1032396300", "value": "9", "variable": "count_uspiddig_app_1hr"},
                                {"rid": "1032396304", "value": "9", "variable": "count_uspiddig_app_1mth"},
                                {"rid": "1032396301", "value": "9", "variable": "count_uspiddig_app_6hrs"},
                                {"rid": "1032396303", "value": "9", "variable": "count_uspiddig_app_wk"},
                                {"rid": "1032396540", "value": "0", "variable": "count_uspiddig_fraud_1day"},
                                {"rid": "1032396542", "value": "0", "variable": "count_uspiddig_fraud_2wks_excurrent"},
                                {"rid": "1032396543", "value": "0", "variable": "count_uspiddig_fraud_3wks_excurrent"},
                                {"rid": "1032396544", "value": "0", "variable": "count_uspiddig_fraud_4wks_excurrent"},
                                {"rid": "1032396545", "value": "0", "variable": "count_uspiddig_fraud_excurrent"},
                                {"rid": "1032396541", "value": "0", "variable": "count_uspiddig_fraud_wk_excurrent"},
                                {"rid": "1032396317", "value": "9", "variable": "count_phone_app_1day"},
                                {"rid": "1032396315", "value": "9", "variable": "count_phone_app_1hr"},
                                {"rid": "1032396319", "value": "9", "variable": "count_phone_app_1mth"},
                                {"rid": "1032396316", "value": "9", "variable": "count_phone_app_6hrs"},
                                {"rid": "1032396318", "value": "9", "variable": "count_phone_app_wk"},
                                {"rid": "1032396553", "value": "0", "variable": "count_phone_fraud"},
                                {"rid": "1032396550", "value": "0", "variable": "count_phone_fraud_1day"},
                                {"rid": "1032396552", "value": "0", "variable": "count_phone_fraud_1mth"},
                                {"rid": "1032396551", "value": "0", "variable": "count_phone_fraud_wk"},
                                {"rid": "1032396198", "value": "0", "variable": "count_privatebrowsing_1day_excurrent"},
                                {"rid": "1032396427", "value": "0", "variable": "count_rdp_count_excurrent"},
                                {"rid": "1032396435", "value": "0", "variable": "count_reject_sdk_1day_excurrent"},
                                {"rid": "1032396433", "value": "0", "variable": "count_reject_sdk_1hr_excurrent"},
                                {"rid": "1032396436", "value": "0", "variable": "count_reject_sdk_2days_excurrent"},
                                {"rid": "1032396434", "value": "0", "variable": "count_reject_sdk_2hrs_excurrent"},
                                {"rid": "1032396432", "value": "0", "variable": "count_reject_sdk_30min_excurrent"},
                                {"rid": "1032396440", "value": "0", "variable": "count_reject_web_1day_excurrent"},
                                {"rid": "1032396438", "value": "0", "variable": "count_reject_web_1hr_excurrent"},
                                {"rid": "1032396441", "value": "0", "variable": "count_reject_web_2days_excurrent"},
                                {"rid": "1032396439", "value": "0", "variable": "count_reject_web_2hrs_excurrent"},
                                {"rid": "1032396437", "value": "0", "variable": "count_reject_web_30min_excurrent"},
                                {"rid": "1032396445", "value": "0", "variable": "count_review_sdk_1day_excurrent"},
                                {"rid": "1032396443", "value": "0", "variable": "count_review_sdk_1hr_excurrent"},
                                {"rid": "1032396446", "value": "0", "variable": "count_review_sdk_2days_excurrent"},
                                {"rid": "1032396444", "value": "0", "variable": "count_review_sdk_2hrs_excurrent"},
                                {"rid": "1032396442", "value": "0", "variable": "count_review_sdk_30min_excurrent"},
                                {"rid": "1032396450", "value": "0", "variable": "count_review_web_1day_excurrent"},
                                {"rid": "1032396448", "value": "0", "variable": "count_review_web_1hr_excurrent"},
                                {"rid": "1032396451", "value": "0", "variable": "count_review_web_2days_excurrent"},
                                {"rid": "1032396449", "value": "0", "variable": "count_review_web_2hrs_excurrent"},
                                {"rid": "1032396447", "value": "0", "variable": "count_review_web_30min_excurrent"},
                                {"rid": "1032396493", "value": "0", "variable": "count_smartid_reject_2wks_excurrent"},
                                {"rid": "1032396494", "value": "0", "variable": "count_smartid_reject_3wks_excurrent"},
                                {"rid": "1032396495", "value": "0", "variable": "count_smartid_reject_4wks_excurrent"},
                                {"rid": "1032396496", "value": "0", "variable": "count_smartid_reject_excurrent"},
                                {"rid": "1032396492", "value": "0", "variable": "count_smartid_reject_wk_excurrent"},
                                {"rid": "1032396409", "value": "0", "variable": "count_tv_count_excurrent"},
                                {"rid": "1032396412", "value": "0", "variable": "count_vnc_count_excurrent"},
                                {"rid": "1032396180", "value": "8", "variable": "custid"},
                                {"rid": "1032396347", "value": "1", "variable": "custids_per_email_app_1day"},
                                {"rid": "1032396346", "value": "1", "variable": "custids_per_email_app_1hr"},
                                {"rid": "1032396345", "value": "1", "variable": "custids_per_email_app_30min"},
                                {"rid": "1032396344", "value": "1", "variable": "custids_per_email_app_5mins"},
                                {"rid": "1032396348", "value": "1", "variable": "custids_per_email_app_wk"},
                                {"rid": "1032396263", "value": "1", "variable": "custids_per_uspiddig_3mths_excurrent"},
                                {"rid": "1032396262", "value": "1", "variable": "custids_per_uspiddig_wk_excurrent"},
                                {"rid": "1032396352", "value": "1", "variable": "custids_per_phone_app_1day"},
                                {"rid": "1032396351", "value": "1", "variable": "custids_per_phone_app_1hr"},
                                {"rid": "1032396350", "value": "1", "variable": "custids_per_phone_app_30min"},
                                {"rid": "1032396349", "value": "1", "variable": "custids_per_phone_app_5mins"},
                                {"rid": "1032396353", "value": "1", "variable": "custids_per_phone_app_wk"},
                                {"rid": "1032396211", "value": "0", "variable": "domains_per_custid_15mins_excurrent"},
                                {"rid": "1032396212", "value": "0", "variable": "domains_per_custid_30min_excurrent"},
                                {"rid": "1032396210", "value": "0", "variable": "domains_per_custid_5mins_excurrent"},
                                {"rid": "1032396226", "value": "0", "variable": "exactids_per_custid_1day_excurrent"},
                                {"rid": "1032396225", "value": "0", "variable": "exactids_per_custid_1hr_excurrent"},
                                {"rid": "1032396224", "value": "0", "variable": "exactids_per_custid_30min_excurrent"},
                                {"rid": "1032396227", "value": "0", "variable": "exactids_per_custid_wk_excurrent"},
                                {"rid": "1032396228", "value": "0", "variable": "exactids_per_custid_wk_lag_1wk"},
                                {"rid": "1032396229", "value": "0", "variable": "exactids_per_custid_wk_lag_2wks"},
                                {"rid": "1032396230", "value": "0", "variable": "exactids_per_custid_wk_lag_3wks"},
                                {"rid": "1032396231", "value": "0", "variable": "exactids_per_custid_wk_lag_4wks"},
                                {"rid": "1032396265", "value": "0", "variable": "exactids_per_uspiddig_1day"},
                                {"rid": "1032396264", "value": "0", "variable": "exactids_per_uspiddig_1hr"},
                                {"rid": "1032396270", "value": "0", "variable": "exactids_per_uspiddig_3mths"},
                                {"rid": "1032396266", "value": "0", "variable": "exactids_per_uspiddig_wk"},
                                {
                                    "rid": "1032396267",
                                    "value": "0",
                                    "variable": "exactids_per_uspiddig_wk_lag_1wk_excurrent",
                                },
                                {
                                    "rid": "1032396268",
                                    "value": "0",
                                    "variable": "exactids_per_uspiddig_wk_lag_2wks_excurrent",
                                },
                                {
                                    "rid": "1032396269",
                                    "value": "0",
                                    "variable": "exactids_per_uspiddig_wk_lag_3wks_excurrent",
                                },
                                {"rid": "1032396665", "value": "0", "variable": "global_avg_score_uspiddig_1day"},
                                {"rid": "1032396662", "value": "0", "variable": "global_avg_score_uspiddig_1hr"},
                                {
                                    "rid": "1032396671",
                                    "value": "0",
                                    "variable": "global_avg_score_uspiddig_1mth_lag_1day",
                                },
                                {
                                    "rid": "1032396674",
                                    "value": "0",
                                    "variable": "global_avg_score_uspiddig_2mths_lag_1day",
                                },
                                {
                                    "rid": "1032396677",
                                    "value": "0",
                                    "variable": "global_avg_score_uspiddig_3mths_lag_1day",
                                },
                                {
                                    "rid": "1032396668",
                                    "value": "0",
                                    "variable": "global_avg_score_uspiddig_wk_lag_1day",
                                },
                                {"rid": "1032396578", "value": "0", "variable": "global_count_email_fraud_1mth"},
                                {"rid": "1032396780", "value": "0", "variable": "global_count_uspiddig_1day"},
                                {"rid": "1032396779", "value": "0", "variable": "global_count_uspiddig_1hr"},
                                {"rid": "1032396782", "value": "0", "variable": "global_count_uspiddig_1mth"},
                                {"rid": "1032396783", "value": "0", "variable": "global_count_uspiddig_2mths"},
                                {"rid": "1032396784", "value": "0", "variable": "global_count_uspiddig_3mths"},
                                {"rid": "1032396577", "value": "0", "variable": "global_count_uspiddig_fraud"},
                                {"rid": "1032396574", "value": "0", "variable": "global_count_uspiddig_fraud_2wks"},
                                {"rid": "1032396575", "value": "0", "variable": "global_count_uspiddig_fraud_3wks"},
                                {"rid": "1032396576", "value": "0", "variable": "global_count_uspiddig_fraud_4wks"},
                                {"rid": "1032396573", "value": "0", "variable": "global_count_uspiddig_fraud_wk"},
                                {"rid": "1032396708", "value": "0", "variable": "global_count_uspiddig_reject_1day"},
                                {"rid": "1032396707", "value": "0", "variable": "global_count_uspiddig_reject_1hr"},
                                {"rid": "1032396710", "value": "0", "variable": "global_count_uspiddig_reject_1mth"},
                                {"rid": "1032396711", "value": "0", "variable": "global_count_uspiddig_reject_2mths"},
                                {"rid": "1032396712", "value": "0", "variable": "global_count_uspiddig_reject_3mths"},
                                {"rid": "1032396709", "value": "0", "variable": "global_count_uspiddig_reject_wk"},
                                {"rid": "1032396736", "value": "0", "variable": "global_count_uspiddig_review_1day"},
                                {"rid": "1032396735", "value": "0", "variable": "global_count_uspiddig_review_1hr"},
                                {"rid": "1032396738", "value": "0", "variable": "global_count_uspiddig_review_1mth"},
                                {"rid": "1032396739", "value": "0", "variable": "global_count_uspiddig_review_2mths"},
                                {"rid": "1032396740", "value": "0", "variable": "global_count_uspiddig_review_3mths"},
                                {"rid": "1032396737", "value": "0", "variable": "global_count_uspiddig_review_wk"},
                                {"rid": "1032396781", "value": "0", "variable": "global_count_uspiddig_wk"},
                                {"rid": "1032396579", "value": "0", "variable": "global_count_phone_fraud_1mth"},
                                {
                                    "rid": "1032396694",
                                    "value": "0",
                                    "variable": "global_count_smartid_reject_2wks_excurrent",
                                },
                                {
                                    "rid": "1032396695",
                                    "value": "0",
                                    "variable": "global_count_smartid_reject_3wks_excurrent",
                                },
                                {
                                    "rid": "1032396696",
                                    "value": "0",
                                    "variable": "global_count_smartid_reject_4wks_excurrent",
                                },
                                {
                                    "rid": "1032396697",
                                    "value": "0",
                                    "variable": "global_count_smartid_reject_excurrent",
                                },
                                {"rid": "1032396747", "value": "0", "variable": "global_dobs_per_email"},
                                {"rid": "1032396746", "value": "0", "variable": "global_dobs_per_uspiddig"},
                                {"rid": "1032396745", "value": "0", "variable": "global_emails_per_uspiddig"},
                                {"rid": "1032396742", "value": "0", "variable": "global_exactids_per_uspiddig"},
                                {"rid": "1032396666", "value": "0", "variable": "global_max_score_uspiddig_1day"},
                                {"rid": "1032396663", "value": "0", "variable": "global_max_score_uspiddig_1hr"},
                                {
                                    "rid": "1032396672",
                                    "value": "0",
                                    "variable": "global_max_score_uspiddig_1mth_lag_1day",
                                },
                                {
                                    "rid": "1032396675",
                                    "value": "0",
                                    "variable": "global_max_score_uspiddig_2mths_lag_1day",
                                },
                                {
                                    "rid": "1032396678",
                                    "value": "0",
                                    "variable": "global_max_score_uspiddig_3mths_lag_1day",
                                },
                                {
                                    "rid": "1032396669",
                                    "value": "0",
                                    "variable": "global_max_score_uspiddig_wk_lag_1day",
                                },
                                {"rid": "1032396667", "value": "0", "variable": "global_min_score_uspiddig_1day"},
                                {"rid": "1032396664", "value": "0", "variable": "global_min_score_uspiddig_1hr"},
                                {
                                    "rid": "1032396673",
                                    "value": "0",
                                    "variable": "global_min_score_uspiddig_1mth_lag_1day",
                                },
                                {
                                    "rid": "1032396676",
                                    "value": "0",
                                    "variable": "global_min_score_uspiddig_2mths_lag_1day",
                                },
                                {
                                    "rid": "1032396679",
                                    "value": "0",
                                    "variable": "global_min_score_uspiddig_3mths_lag_1day",
                                },
                                {
                                    "rid": "1032396670",
                                    "value": "0",
                                    "variable": "global_min_score_uspiddig_wk_lag_1day",
                                },
                                {"rid": "1032396749", "value": "0", "variable": "global_names_per_uspiddig"},
                                {
                                    "rid": "1032396593",
                                    "value": "0",
                                    "variable": "global_orgids_per_email_fraud_3mths_excurrent",
                                },
                                {
                                    "rid": "1032396594",
                                    "value": "0",
                                    "variable": "global_orgids_per_phone_fraud_3mths_excurrent",
                                },
                                {"rid": "1032396744", "value": "0", "variable": "global_phones_per_uspiddig"},
                                {"rid": "1032396752", "value": "0", "variable": "global_routerids_per_uspiddig"},
                                {"rid": "1032396753", "value": "0", "variable": "global_routernames_per_uspiddig"},
                                {"rid": "1032396743", "value": "0", "variable": "global_smartids_per_uspiddig"},
                                {"rid": "1032396751", "value": "0", "variable": "global_trueipgeos_per_uspiddig"},
                                {"rid": "1032396750", "value": "0", "variable": "global_trueisps_per_uspiddig"},
                                {"rid": "1032396271", "value": "0", "variable": "uspiddigs_per_custid_6mths"},
                                {"rid": "1032396221", "value": "0", "variable": "os_per_custid_1day_excurrent"},
                                {"rid": "1032396220", "value": "0", "variable": "os_per_custid_1hr_excurrent"},
                                {"rid": "1032396219", "value": "0", "variable": "routerids_per_custid_excurrent"},
                                {"rid": "1032396207", "value": "0", "variable": "smartids_per_custid_15mins_excurrent"},
                                {"rid": "1032396234", "value": "0", "variable": "smartids_per_custid_1day_excurrent"},
                                {"rid": "1032396233", "value": "0", "variable": "smartids_per_custid_1hr_excurrent"},
                                {"rid": "1032396208", "value": "0", "variable": "smartids_per_custid_30min_excurrent"},
                                {"rid": "1032396206", "value": "0", "variable": "smartids_per_custid_5mins_excurrent"},
                                {"rid": "1032396235", "value": "0", "variable": "smartids_per_custid_wk_excurrent"},
                                {"rid": "1032396236", "value": "0", "variable": "smartids_per_custid_wk_lag_1wk"},
                                {"rid": "1032396237", "value": "0", "variable": "smartids_per_custid_wk_lag_2wks"},
                                {"rid": "1032396238", "value": "0", "variable": "smartids_per_custid_wk_lag_3wks"},
                                {"rid": "1032396239", "value": "0", "variable": "smartids_per_custid_wk_lag_4wks"},
                                {"rid": "1032396273", "value": "0", "variable": "smartids_per_uspiddig_1day"},
                                {"rid": "1032396272", "value": "0", "variable": "smartids_per_uspiddig_1hr"},
                                {
                                    "rid": "1032396278",
                                    "value": "0",
                                    "variable": "smartids_per_uspiddig_3mths_excurrent",
                                },
                                {"rid": "1032396274", "value": "0", "variable": "smartids_per_uspiddig_wk_excurrent"},
                                {
                                    "rid": "1032396275",
                                    "value": "0",
                                    "variable": "smartids_per_uspiddig_wk_lag_1wk_excurrent",
                                },
                                {
                                    "rid": "1032396276",
                                    "value": "0",
                                    "variable": "smartids_per_uspiddig_wk_lag_2wks_excurrent",
                                },
                                {
                                    "rid": "1032396277",
                                    "value": "0",
                                    "variable": "smartids_per_uspiddig_wk_lag_3wks_excurrent",
                                },
                                {
                                    "rid": "1032396356",
                                    "value": "23",
                                    "variable": "timesincefirst_custid_event_excurrent",
                                },
                                {
                                    "rid": "1032396359",
                                    "value": "23",
                                    "variable": "timesincefirst_custid_uspiddig_event_excurrent",
                                },
                                {"rid": "1032396429", "value": "0", "variable": "timesincefirst_custid_smartid_rdp"},
                                {
                                    "rid": "1032396430",
                                    "value": "0",
                                    "variable": "timesincefirst_custid_smartid_unusual_rdp",
                                },
                                {
                                    "rid": "1032396362",
                                    "value": "23",
                                    "variable": "timesincefirst_inputip_event_excurrent",
                                },
                                {
                                    "rid": "1032396370",
                                    "value": "23",
                                    "variable": "timesincefirst_uspiddig_event_excurrent",
                                },
                                {"rid": "1032396377", "value": "7", "variable": "timesincelast_custid_app_excurrent"},
                                {"rid": "1032396375", "value": "7", "variable": "timesincelast_custid_event_excurrent"},
                                {"rid": "1032396288", "value": "0", "variable": "timesincelast_domain_event_excurrent"},
                                {"rid": "1032396214", "value": "0", "variable": "trueips_per_custid_15mins_excurrent"},
                                {"rid": "1032396242", "value": "0", "variable": "trueips_per_custid_1day_excurrent"},
                                {"rid": "1032396241", "value": "0", "variable": "trueips_per_custid_1hr_excurrent"},
                                {"rid": "1032396215", "value": "0", "variable": "trueips_per_custid_30min_excurrent"},
                                {"rid": "1032396213", "value": "0", "variable": "trueips_per_custid_5mins_excurrent"},
                                {"rid": "1032396243", "value": "0", "variable": "trueips_per_custid_wk_excurrent"},
                                {"rid": "1032396244", "value": "0", "variable": "trueips_per_custid_wk_lag_1wk"},
                                {"rid": "1032396245", "value": "0", "variable": "trueips_per_custid_wk_lag_2wks"},
                                {"rid": "1032396246", "value": "0", "variable": "trueips_per_custid_wk_lag_3wks"},
                                {"rid": "1032396247", "value": "0", "variable": "trueips_per_custid_wk_lag_4wks"},
                                {"rid": "1032396281", "value": "0", "variable": "trueips_per_uspiddig_1day"},
                                {"rid": "1032396280", "value": "0", "variable": "trueips_per_uspiddig_1hr"},
                                {"rid": "1032396286", "value": "0", "variable": "trueips_per_uspiddig_3mths"},
                                {"rid": "1032396282", "value": "0", "variable": "trueips_per_uspiddig_wk"},
                                {
                                    "rid": "1032396283",
                                    "value": "0",
                                    "variable": "trueips_per_uspiddig_wk_lag_1wk_excurrent",
                                },
                                {
                                    "rid": "1032396284",
                                    "value": "0",
                                    "variable": "trueips_per_uspiddig_wk_lag_2wks_excurrent",
                                },
                                {
                                    "rid": "1032396285",
                                    "value": "0",
                                    "variable": "trueips_per_uspiddig_wk_lag_3wks_excurrent",
                                },
                                {"rid": "1032396217", "value": "0", "variable": "trueisps_per_custid_15mins_excurrent"},
                                {"rid": "1032396250", "value": "0", "variable": "trueisps_per_custid_1day_excurrent"},
                                {"rid": "1032396249", "value": "0", "variable": "trueisps_per_custid_1hr_excurrent"},
                                {"rid": "1032396218", "value": "0", "variable": "trueisps_per_custid_30min_excurrent"},
                                {"rid": "1032396216", "value": "0", "variable": "trueisps_per_custid_5mins_excurrent"},
                                {"rid": "1032396251", "value": "0", "variable": "trueisps_per_custid_wk_excurrent"},
                                {"rid": "1032396252", "value": "0", "variable": "trueisps_per_custid_wk_lag_1wk"},
                                {"rid": "1032396253", "value": "0", "variable": "trueisps_per_custid_wk_lag_2wks"},
                                {"rid": "1032396254", "value": "0", "variable": "trueisps_per_custid_wk_lag_3wks"},
                                {"rid": "1032396255", "value": "0", "variable": "trueisps_per_custid_wk_lag_4wks"},
                                {
                                    "rid": "1032396195",
                                    "value": "0",
                                    "variable": "websessionids_per_custid_1hr_excurrent",
                                },
                            ],
                        },
                    ],
                    "score": "-3",
                    "vars": [
                        {"rid": "1032397182", "value": "0", "variable": "count_email_fraud"},
                        {"rid": "1032397179", "value": "0", "variable": "count_email_fraud_1day"},
                        {"rid": "1032397181", "value": "0", "variable": "count_email_fraud_1mth"},
                        {"rid": "1032397180", "value": "0", "variable": "count_email_fraud_wk"},
                        {"rid": "1032397190", "value": "0", "variable": "count_fraud"},
                        {"rid": "1032397187", "value": "0", "variable": "count_fraud_1day"},
                        {"rid": "1032397189", "value": "0", "variable": "count_fraud_1mth"},
                        {"rid": "1032397188", "value": "0", "variable": "count_fraud_wk"},
                        {"rid": "1032397186", "value": "0", "variable": "count_phone_fraud"},
                        {"rid": "1032397183", "value": "0", "variable": "count_phone_fraud_1day"},
                        {"rid": "1032397185", "value": "0", "variable": "count_phone_fraud_1mth"},
                        {"rid": "1032397184", "value": "0", "variable": "count_phone_fraud_wk"},
                        {"rid": "1032397155", "value": "8", "variable": "custid"},
                        {"rid": "1032397162", "value": "0", "variable": "domains_per_custid_15mins"},
                        {"rid": "1032397163", "value": "0", "variable": "domains_per_custid_30min"},
                        {"rid": "1032397161", "value": "0", "variable": "domains_per_custid_5mins"},
                        {"rid": "1032397192", "value": "0", "variable": "global_count_email_fraud_1mth"},
                        {"rid": "1032397193", "value": "0", "variable": "global_count_phone_fraud_1mth"},
                        {"rid": "1032397159", "value": "0", "variable": "smartids_per_custid_15mins_excurrent"},
                        {"rid": "1032397160", "value": "0", "variable": "smartids_per_custid_30min_excurrent"},
                        {"rid": "1032397158", "value": "0", "variable": "smartids_per_custid_5mins_excurrent"},
                        {"rid": "1032397168", "value": "23", "variable": "timesincefirst_custid_event_excurrent"},
                        {"rid": "1032397171", "value": "0", "variable": "timesincefirst_custid_smartid_rdp"},
                        {"rid": "1032397172", "value": "0", "variable": "timesincefirst_custid_smartid_unusual_rdp"},
                        {"rid": "1032397170", "value": "7", "variable": "timesincelast_custid_event_excurrent"},
                        {"rid": "1032397167", "value": "0", "variable": "timesincelast_domain_event_excurrent"},
                        {"rid": "1032397165", "value": "0", "variable": "trueisps_per_custid_15mins_excurrent"},
                        {"rid": "1032397166", "value": "0", "variable": "trueisps_per_custid_30min_excurrent"},
                        {"rid": "1032397164", "value": "0", "variable": "trueisps_per_custid_5mins_excurrent"},
                    ],
                },
                "id": "0",
                "type": "champion",
            }
        ]
    },
    "policy_engine_version": "12.2.1",
    "policy_score": "-3",
    "primary_industry": "government",
    "reason_code": [
        "InputIP in Global Blocklist",
        "5 or More Applications Submitted_uspDID_hr",
        "DigitalID in USP Network New - 1Day",
        "Email in USP Network New - 1Day",
        "Telephone in USP Network New - 1Day",
        "First Time Login with Browser was this Hour",
        "uspID Trust Low",
    ],
    "request_duration": "21",
    "request_id": "df35ac9d-3d57-46a8-907d-de640bf773f7",
    "request_result": "success",
    "review_status": "pass",
    "risk_rating": "low",
    "secondary_industry": "civilian",
    "service_type": "all",
    "session_id": "session-id",
    "session_id_query_count": "12",
    "summary_risk_score": "-3",
    "USP_reason_code": [
        "_ACC_EMAIL_GBL_VEL_6_6_6_6",
        "_ACC_EMAIL_GBL_AGE_LT_HR",
        "_ACC_LOGIN_GBL_VEL_25_120_120_120",
        "_ACC_LOGIN_GBL_AGE_GT_3MTHS",
        "_ACC_TEL_GBL_VEL_9_9_9_9",
        "_ACC_TEL_GBL_AGE_LT_HR",
        "_DIG_ID_GBL_VEL_9_9_9_9",
        "_DIG_ID_GBL_AGE_LT_HR",
        "_ACC_EMAIL_LCL_VEL_6_6_6_6",
        "_ACC_EMAIL_LCL_AGE_LT_HR",
        "_ACC_LOGIN_LCL_VEL_9_9_9_9",
        "_ACC_LOGIN_LCL_AGE_LT_HR",
        "_ACC_TEL_LCL_VEL_9_9_9_9",
        "_ACC_TEL_LCL_AGE_LT_HR",
        "_DIG_ID_LCL_VEL_9_9_9_9",
        "_DIG_ID_LCL_AGE_LT_HR",
        "PID_LCL_AGE_ACC_EMAIL_LT_DAY",
        "PID_LCL_RLTD_ACC_EMAIL_PASSED_5",
        "_EXPRESSION_ERROR",
        "_InputIP_Global_Whitelist",
        "_InputIP_Global_Blacklist",
        "_Session_Replay_High",
        "_USP_GBL_TT_LIMIT_REACHED_ACC_LOGIN",
    ],
    "tmx_risk_rating": "neutral",
    "tmx_summary_reason_code": ["IP_Negative_History"],
    "USP_variables": {
        "____age___": "1",
        "____constant_values____": "1",
        "____distance____": "1",
        "____distinct_entity____": "1",
        "____feedback____": "1",
        "____global_age____": "1",
        "____global_fraud____": "1",
        "____global_policy_score____": "1",
        "____global_risk____": "1",
        "____global_velocities____": "1",
        "____local_risk___": "1",
        "____nao___": "1",
        "____profiling_attribute_velocities____": "1",
        "____rdp____": "1",
        "_accemail_gbl_velocity_hour": "5",
        "_accemail_local_velocity_hour": "5",
        "_acclogin_local_velocity_hour": "0",
        "_accphone_gbl_velocity_hour": "8",
        "_exactid_per_email_gbl_hour": "0",
        "age_of_customer": "36.68",
        "agenttypes_per_custid_excurrent": "0",
        "browsers_per_custid_1day_excurrent": "0",
        "browsers_per_custid_1hr_excurrent": "0",
        "count_accept_1day_excurrent": "0",
        "count_accept_1hr_excurrent": "0",
        "count_accept_1mth_excurrent": "0",
        "count_accept_30min_excurrent": "0",
        "count_accept_excurrent": "0",
        "count_accept_wk_excurrent": "0",
        "count_amy_count_excurrent": "0",
        "count_any_count_excurrent": "0",
        "count_apc_count_excurrent": "0",
        "count_aro_count_excurrent": "0",
        "count_email_app_1day": "6",
        "count_email_app_1hr": "6",
        "count_email_app_1mth": "6",
        "count_email_app_6hrs": "6",
        "count_email_app_wk": "6",
        "count_email_fraud": "0",
        "count_email_fraud_1day": "0",
        "count_email_fraud_1mth": "0",
        "count_email_fraud_wk": "0",
        "count_fraud": "0",
        "count_fraud_1day": "0",
        "count_fraud_1mth": "0",
        "count_fraud_wk": "0",
        "count_uspiddig_app_1day": "9",
        "count_uspiddig_app_1hr": "9",
        "count_uspiddig_app_1mth": "9",
        "count_uspiddig_app_6hrs": "9",
        "count_uspiddig_app_wk": "9",
        "count_uspiddig_fraud_1day": "0",
        "count_uspiddig_fraud_2wks_excurrent": "0",
        "count_uspiddig_fraud_3wks_excurrent": "0",
        "count_uspiddig_fraud_4wks_excurrent": "0",
        "count_uspiddig_fraud_excurrent": "0",
        "count_uspiddig_fraud_wk_excurrent": "0",
        "count_phone_app_1day": "9",
        "count_phone_app_1hr": "9",
        "count_phone_app_1mth": "9",
        "count_phone_app_6hrs": "9",
        "count_phone_app_wk": "9",
        "count_phone_fraud": "0",
        "count_phone_fraud_1day": "0",
        "count_phone_fraud_1mth": "0",
        "count_phone_fraud_wk": "0",
        "count_privatebrowsing_1day_excurrent": "0",
        "count_rdp_count_excurrent": "0",
        "count_reject_sdk_1day_excurrent": "0",
        "count_reject_sdk_1hr_excurrent": "0",
        "count_reject_sdk_2days_excurrent": "0",
        "count_reject_sdk_2hrs_excurrent": "0",
        "count_reject_sdk_30min_excurrent": "0",
        "count_reject_web_1day_excurrent": "0",
        "count_reject_web_1hr_excurrent": "0",
        "count_reject_web_2days_excurrent": "0",
        "count_reject_web_2hrs_excurrent": "0",
        "count_reject_web_30min_excurrent": "0",
        "count_review_sdk_1day_excurrent": "0",
        "count_review_sdk_1hr_excurrent": "0",
        "count_review_sdk_2days_excurrent": "0",
        "count_review_sdk_2hrs_excurrent": "0",
        "count_review_sdk_30min_excurrent": "0",
        "count_review_web_1day_excurrent": "0",
        "count_review_web_1hr_excurrent": "0",
        "count_review_web_2days_excurrent": "0",
        "count_review_web_2hrs_excurrent": "0",
        "count_review_web_30min_excurrent": "0",
        "count_smartid_reject_2wks_excurrent": "0",
        "count_smartid_reject_3wks_excurrent": "0",
        "count_smartid_reject_4wks_excurrent": "0",
        "count_smartid_reject_excurrent": "0",
        "count_smartid_reject_wk_excurrent": "0",
        "count_tv_count_excurrent": "0",
        "count_vnc_count_excurrent": "0",
        "custid": "8",
        "custids_per_email_app_1day": "1",
        "custids_per_email_app_1hr": "1",
        "custids_per_email_app_30min": "1",
        "custids_per_email_app_5mins": "1",
        "custids_per_email_app_wk": "1",
        "custids_per_uspiddig_3mths_excurrent": "1",
        "custids_per_uspiddig_wk_excurrent": "1",
        "custids_per_phone_app_1day": "1",
        "custids_per_phone_app_1hr": "1",
        "custids_per_phone_app_30min": "1",
        "custids_per_phone_app_5mins": "1",
        "custids_per_phone_app_wk": "1",
        "day": "1440",
        "domains_per_custid_15mins": "0",
        "domains_per_custid_15mins_excurrent": "0",
        "domains_per_custid_30min": "0",
        "domains_per_custid_30min_excurrent": "0",
        "domains_per_custid_5mins": "0",
        "domains_per_custid_5mins_excurrent": "0",
        "exactids_per_custid_1day_excurrent": "0",
        "exactids_per_custid_1hr_excurrent": "0",
        "exactids_per_custid_30min_excurrent": "0",
        "exactids_per_custid_wk_excurrent": "0",
        "exactids_per_custid_wk_lag_1wk": "0",
        "exactids_per_custid_wk_lag_2wks": "0",
        "exactids_per_custid_wk_lag_3wks": "0",
        "exactids_per_custid_wk_lag_4wks": "0",
        "exactids_per_uspiddig_1day": "0",
        "exactids_per_uspiddig_1hr": "0",
        "exactids_per_uspiddig_3mths": "0",
        "exactids_per_uspiddig_wk": "0",
        "exactids_per_uspiddig_wk_lag_1wk_excurrent": "0",
        "exactids_per_uspiddig_wk_lag_2wks_excurrent": "0",
        "exactids_per_uspiddig_wk_lag_3wks_excurrent": "0",
        "global_avg_score_uspiddig_1day": "0",
        "global_avg_score_uspiddig_1hr": "0",
        "global_avg_score_uspiddig_1mth_lag_1day": "0",
        "global_avg_score_uspiddig_2mths_lag_1day": "0",
        "global_avg_score_uspiddig_3mths_lag_1day": "0",
        "global_avg_score_uspiddig_wk_lag_1day": "0",
        "global_count_email_fraud_1mth": "0",
        "global_count_uspiddig_1day": "0",
        "global_count_uspiddig_1hr": "0",
        "global_count_uspiddig_1mth": "0",
        "global_count_uspiddig_2mths": "0",
        "global_count_uspiddig_3mths": "0",
        "global_count_uspiddig_fraud": "0",
        "global_count_uspiddig_fraud_2wks": "0",
        "global_count_uspiddig_fraud_3wks": "0",
        "global_count_uspiddig_fraud_4wks": "0",
        "global_count_uspiddig_fraud_wk": "0",
        "global_count_uspiddig_reject_1day": "0",
        "global_count_uspiddig_reject_1hr": "0",
        "global_count_uspiddig_reject_1mth": "0",
        "global_count_uspiddig_reject_2mths": "0",
        "global_count_uspiddig_reject_3mths": "0",
        "global_count_uspiddig_reject_wk": "0",
        "global_count_uspiddig_review_1day": "0",
        "global_count_uspiddig_review_1hr": "0",
        "global_count_uspiddig_review_1mth": "0",
        "global_count_uspiddig_review_2mths": "0",
        "global_count_uspiddig_review_3mths": "0",
        "global_count_uspiddig_review_wk": "0",
        "global_count_uspiddig_wk": "0",
        "global_count_phone_fraud_1mth": "0",
        "global_count_smartid_reject_2wks_excurrent": "0",
        "global_count_smartid_reject_3wks_excurrent": "0",
        "global_count_smartid_reject_4wks_excurrent": "0",
        "global_count_smartid_reject_excurrent": "0",
        "global_dobs_per_email": "0",
        "global_dobs_per_uspiddig": "0",
        "global_emails_per_uspiddig": "0",
        "global_exactids_per_uspiddig": "0",
        "global_max_score_uspiddig_1day": "0",
        "global_max_score_uspiddig_1hr": "0",
        "global_max_score_uspiddig_1mth_lag_1day": "0",
        "global_max_score_uspiddig_2mths_lag_1day": "0",
        "global_max_score_uspiddig_3mths_lag_1day": "0",
        "global_max_score_uspiddig_wk_lag_1day": "0",
        "global_min_score_uspiddig_1day": "0",
        "global_min_score_uspiddig_1hr": "0",
        "global_min_score_uspiddig_1mth_lag_1day": "0",
        "global_min_score_uspiddig_2mths_lag_1day": "0",
        "global_min_score_uspiddig_3mths_lag_1day": "0",
        "global_min_score_uspiddig_wk_lag_1day": "0",
        "global_names_per_uspiddig": "0",
        "global_orgids_per_email_fraud_3mths_excurrent": "0",
        "global_orgids_per_phone_fraud_3mths_excurrent": "0",
        "global_phones_per_uspiddig": "0",
        "global_routerids_per_uspiddig": "0",
        "global_routernames_per_uspiddig": "0",
        "global_smartids_per_uspiddig": "0",
        "global_trueipgeos_per_uspiddig": "0",
        "global_trueisps_per_uspiddig": "0",
        "hour": "60",
        "uspiddigs_per_custid_6mths": "0",
        "max_weekly_exactids_per_custid_last_mth": "0",
        "max_weekly_smartids_per_custid_last_mth": "0",
        "max_weekly_trueips_per_custid_last_mth": "0",
        "month": "40320",
        "os_per_custid_1day_excurrent": "0",
        "os_per_custid_1hr_excurrent": "0",
        "routerids_per_custid_excurrent": "0",
        "smartids_per_custid_15mins_excurrent": "0",
        "smartids_per_custid_1day_excurrent": "0",
        "smartids_per_custid_1hr_excurrent": "0",
        "smartids_per_custid_30min_excurrent": "0",
        "smartids_per_custid_5mins_excurrent": "0",
        "smartids_per_custid_wk_excurrent": "0",
        "smartids_per_custid_wk_lag_1wk": "0",
        "smartids_per_custid_wk_lag_2wks": "0",
        "smartids_per_custid_wk_lag_3wks": "0",
        "smartids_per_custid_wk_lag_4wks": "0",
        "smartids_per_uspiddig_1day": "0",
        "smartids_per_uspiddig_1hr": "0",
        "smartids_per_uspiddig_3mths_excurrent": "0",
        "smartids_per_uspiddig_wk_excurrent": "0",
        "smartids_per_uspiddig_wk_lag_1wk_excurrent": "0",
        "smartids_per_uspiddig_wk_lag_2wks_excurrent": "0",
        "smartids_per_uspiddig_wk_lag_3wks_excurrent": "0",
        "timesincefirst_custid_event_excurrent": "23",
        "timesincefirst_custid_uspiddig_event_excurrent": "23",
        "timesincefirst_custid_smartid_rdp": "0",
        "timesincefirst_custid_smartid_unusual_rdp": "0",
        "timesincefirst_inputip_event_excurrent": "23",
        "timesincefirst_uspiddig_event_excurrent": "23",
        "timesincelast_custid_app_excurrent": "7",
        "timesincelast_custid_event_excurrent": "7",
        "timesincelast_domain_event_excurrent": "0",
        "trueips_per_custid_15mins_excurrent": "0",
        "trueips_per_custid_1day_excurrent": "0",
        "trueips_per_custid_1hr_excurrent": "0",
        "trueips_per_custid_30min_excurrent": "0",
        "trueips_per_custid_5mins_excurrent": "0",
        "trueips_per_custid_wk_excurrent": "0",
        "trueips_per_custid_wk_lag_1wk": "0",
        "trueips_per_custid_wk_lag_2wks": "0",
        "trueips_per_custid_wk_lag_3wks": "0",
        "trueips_per_custid_wk_lag_4wks": "0",
        "trueips_per_uspiddig_1day": "0",
        "trueips_per_uspiddig_1hr": "0",
        "trueips_per_uspiddig_3mths": "0",
        "trueips_per_uspiddig_wk": "0",
        "trueips_per_uspiddig_wk_lag_1wk_excurrent": "0",
        "trueips_per_uspiddig_wk_lag_2wks_excurrent": "0",
        "trueips_per_uspiddig_wk_lag_3wks_excurrent": "0",
        "trueisps_per_custid_15mins_excurrent": "0",
        "trueisps_per_custid_1day_excurrent": "0",
        "trueisps_per_custid_1hr_excurrent": "0",
        "trueisps_per_custid_30min_excurrent": "0",
        "trueisps_per_custid_5mins_excurrent": "0",
        "trueisps_per_custid_wk_excurrent": "0",
        "trueisps_per_custid_wk_lag_1wk": "0",
        "trueisps_per_custid_wk_lag_2wks": "0",
        "trueisps_per_custid_wk_lag_3wks": "0",
        "trueisps_per_custid_wk_lag_4wks": "0",
        "websessionids_per_custid_1hr_excurrent": "0",
        "week": "10080",
    },
    "transaction_id": "transaction-id",
}

INVALID_PROFILING_RESPONSE = {
    "date_of_birth": "20210607",
    "email": "user.email@example.net",
    "email_contains_dot": "yes",
    "email_domain": "example.net",
    "email_first_seen": "2021-06-07",
    "email_last_event": "2021-06-07",
    "email_last_update": "2021-06-07",
    "email_result": "success",
    "email_score": "0",
    "email_worst_score": "0",
}
