import logging

from pcapi.core.offers.models import OfferCategory
from pcapi.core.offers.models import OfferSubcategory
from pcapi.repository import repository


logger = logging.getLogger(__name__)

FILM_VIDEO = "Films, vidéos"
CINEMA = "Cinéma"
CONFERENCE = "Conférences, rencontres, découverte des métiers"
JEUX = "Jeux (événements, rencontres, concours)"
LIVRE = "Livre"
MUSEE = "Musée, patrimoine, architecture, arts visuels ou contemporains"
MUSIQUE_LIVE = "Musique live"
MUSIQUE_ENREGISTREE = "Musique enregistrée"
PRATIQUE = "Pratique artistique"
MEDIAS = "Médias"
SPECTACLE = "Spectacle vivant"
INSTRUMENT_MUSIQUE = "Instrument de musique"
BEAUX_ARTS = "Beaux-Arts"

CATEGORIES = [
    {
        "name": FILM_VIDEO,
        "proLabel": FILM_VIDEO,
        "appLabel": FILM_VIDEO,
    },
    {
        "name": CINEMA,
        "proLabel": CINEMA,
        "appLabel": CINEMA,
    },
    {
        "name": CONFERENCE,
        "proLabel": CONFERENCE,
        "appLabel": CONFERENCE,
    },
    {
        "name": JEUX,
        "proLabel": JEUX,
        "appLabel": JEUX,
    },
    {
        "name": LIVRE,
        "proLabel": LIVRE,
        "appLabel": LIVRE,
    },
    {
        "name": MUSEE,
        "proLabel": MUSEE,
        "appLabel": MUSEE,
    },
    {
        "name": MUSIQUE_LIVE,
        "proLabel": MUSIQUE_LIVE,
        "appLabel": MUSIQUE_LIVE,
    },
    {
        "name": MUSIQUE_ENREGISTREE,
        "proLabel": MUSIQUE_ENREGISTREE,
        "appLabel": MUSIQUE_ENREGISTREE,
    },
    {
        "name": PRATIQUE,
        "proLabel": PRATIQUE,
        "appLabel": PRATIQUE,
    },
    {
        "name": MEDIAS,
        "proLabel": MEDIAS,
        "appLabel": MEDIAS,
    },
    {
        "name": SPECTACLE,
        "proLabel": SPECTACLE,
        "appLabel": SPECTACLE,
    },
    {
        "name": INSTRUMENT_MUSIQUE,
        "proLabel": INSTRUMENT_MUSIQUE,
        "appLabel": INSTRUMENT_MUSIQUE,
    },
    {
        "name": BEAUX_ARTS,
        "proLabel": BEAUX_ARTS,
        "appLabel": BEAUX_ARTS,
    },
]

SUB_CATEGORIES = [
    {
        "name": "Support physique (DVD, Bluray...)",
        "isEvent": False,
        "proLabel": "Support physique (DVD, Bluray...)",
        "appLabel": "Support physique (DVD, Bluray...)",
        "conditionalFields": [],
        "canExpire": True,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": True,
        "canBeDuo": False,
        "category": FILM_VIDEO,
    },
    {
        "name": "Abonnement médiathèque",
        "isEvent": False,
        "proLabel": "Abonnement médiathèque",
        "appLabel": "Abonnement médiathèque",
        "conditionalFields": [],
        "canExpire": True,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": True,
        "canBeDuo": False,
        "category": FILM_VIDEO,
    },
    {
        "name": "Vidéo à la demande",
        "isEvent": False,
        "proLabel": "Vidéo à la demande",
        "appLabel": "Vidéo à la demande",
        "conditionalFields": [],
        "canExpire": False,
        "isDigital": True,
        "isDigitalDeposit": True,
        "isPhysicalDeposit": False,
        "canBeDuo": False,
        "category": FILM_VIDEO,
    },
    {
        "name": "Abonnement à une plateforme",
        "isEvent": False,
        "proLabel": "Abonnement à une plateforme",
        "appLabel": "Abonnement à une plateforme",
        "conditionalFields": [],
        "canExpire": False,
        "isDigital": True,
        "isDigitalDeposit": True,
        "isPhysicalDeposit": False,
        "canBeDuo": False,
        "category": FILM_VIDEO,
    },
    {
        "name": "Autre support numérique",
        "isEvent": False,
        "proLabel": "Autre support numérique",
        "appLabel": "Autre support numérique",
        "conditionalFields": [],
        "canExpire": False,
        "isDigital": True,
        "isDigitalDeposit": True,
        "isPhysicalDeposit": False,
        "canBeDuo": False,
        "category": FILM_VIDEO,
    },
    {
        "name": "Carte cinéma multi-séances",
        "isEvent": False,
        "proLabel": "Carte cinéma multi-séances",
        "appLabel": "Carte cinéma multi-séances",
        "conditionalFields": [],
        "canExpire": True,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": True,
        "canBeDuo": False,
        "category": CINEMA,
    },
    {
        "name": "Carte cinéma illimité",
        "isEvent": False,
        "proLabel": "Carte cinéma illimité",
        "appLabel": "Carte cinéma illimité",
        "conditionalFields": [],
        "canExpire": True,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": True,
        "canBeDuo": False,
        "category": CINEMA,
    },
    {
        "name": "Séance de cinéma",
        "isEvent": True,
        "proLabel": "Séance de cinéma",
        "appLabel": "Séance de cinéma",
        "conditionalFields": ["author", "visa", "stageDirector"],
        "canExpire": False,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": True,
        "category": CINEMA,
    },
    {
        "name": "Événement cinématographique",
        "isEvent": True,
        "proLabel": "Événement cinématographique",
        "appLabel": "Événement cinéma",
        "conditionalFields": ["author", "visa", "stageDirector"],
        "canExpire": False,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": True,
        "category": CINEMA,
    },
    {
        "name": "Festival de cinéma",
        "isEvent": True,
        "proLabel": "Festival de cinéma",
        "appLabel": "Festival de cinéma",
        "conditionalFields": ["author", "visa", "stageDirector"],
        "canExpire": False,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": True,
        "category": CINEMA,
    },
    {
        "name": "Conférence",
        "isEvent": True,
        "proLabel": "Conférence",
        "appLabel": "Conférence",
        "conditionalFields": ["speaker"],
        "canExpire": False,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": True,
        "category": CONFERENCE,
    },
    {
        "name": "Rencontre",
        "isEvent": True,
        "proLabel": "Rencontre",
        "appLabel": "Rencontre",
        "conditionalFields": ["speaker"],
        "canExpire": False,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": True,
        "category": CONFERENCE,
    },
    {
        "name": "Découverte des métiers",
        "isEvent": True,
        "proLabel": "Découverte des métiers",
        "appLabel": "Découverte des métiers",
        "conditionalFields": ["speaker"],
        "canExpire": False,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": True,
        "category": CONFERENCE,
    },
    {
        "name": "Salon / Convention",
        "isEvent": True,
        "proLabel": "Salon / Convention",
        "appLabel": "Salon / Convention",
        "conditionalFields": ["speaker"],
        "canExpire": False,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": True,
        "category": CONFERENCE,
    },
    {
        "name": "Concours - jeux",
        "isEvent": True,
        "proLabel": "Concours - jeux",
        "appLabel": "Concours - jeux",
        "conditionalFields": [],
        "canExpire": False,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": True,
        "category": JEUX,
    },
    {
        "name": "Rencontres - jeux",
        "isEvent": True,
        "proLabel": "Rencontres - jeux",
        "appLabel": "Rencontres - jeux",
        "conditionalFields": [],
        "canExpire": False,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": True,
        "category": JEUX,
    },
    {
        "name": "Escape game",
        "isEvent": True,
        "proLabel": "Escape game",
        "appLabel": "Escape game",
        "conditionalFields": [],
        "canExpire": False,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": True,
        "category": JEUX,
    },
    {
        "name": "Événements - jeux",
        "isEvent": True,
        "proLabel": "Événements - jeux",
        "appLabel": "Événements - jeux",
        "conditionalFields": [],
        "canExpire": False,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": True,
        "category": JEUX,
    },
    {
        "name": "Jeux en ligne",
        "isEvent": False,
        "proLabel": "Jeux en ligne",
        "appLabel": "Jeux en ligne",
        "conditionalFields": [],
        "canExpire": False,
        "isDigital": True,
        "isDigitalDeposit": True,
        "isPhysicalDeposit": False,
        "canBeDuo": False,
        "category": JEUX,
    },
    {
        "name": "Abonnement jeux vidéos",
        "isEvent": False,
        "proLabel": "Abonnement jeux vidéos",
        "appLabel": "Abonnement jeux vidéos",
        "conditionalFields": [],
        "canExpire": False,
        "isDigital": True,
        "isDigitalDeposit": True,
        "isPhysicalDeposit": False,
        "canBeDuo": False,
        "category": JEUX,
    },
    {
        "name": "Abonnement ludothèque",
        "isEvent": False,
        "proLabel": "Abonnement ludothèque",
        "appLabel": "Abonnement ludothèque",
        "conditionalFields": [],
        "canExpire": True,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": True,
        "canBeDuo": False,
        "category": JEUX,
    },
    {
        "name": "Livre papier",
        "isEvent": False,
        "proLabel": "Livre papier",
        "appLabel": "Livre",
        "conditionalFields": ["author", "isbn"],
        "canExpire": True,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": True,
        "canBeDuo": False,
        "category": LIVRE,
    },
    {
        "name": "Livre numérique, e-book",
        "isEvent": False,
        "proLabel": "Livre numérique, e-book",
        "appLabel": "Livre numérique, e-book",
        "conditionalFields": ["author", "isbn"],
        "canExpire": False,
        "isDigital": True,
        "isDigitalDeposit": True,
        "isPhysicalDeposit": False,
        "canBeDuo": False,
        "category": LIVRE,
    },
    {
        "name": "Livre audio à télécharger",
        "isEvent": False,
        "proLabel": "Livre audio à télécharger",
        "appLabel": "Livre audio à télécharger",
        "conditionalFields": ["author"],
        "canExpire": False,
        "isDigital": True,
        "isDigitalDeposit": True,
        "isPhysicalDeposit": False,
        "canBeDuo": False,
        "category": LIVRE,
    },
    {
        "name": "Livre audio sur support physique",
        "isEvent": False,
        "proLabel": "Livre audio sur support physique",
        "appLabel": "Livre audio sur support physique",
        "conditionalFields": ["author", "isbn"],
        "canExpire": True,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": True,
        "canBeDuo": False,
        "category": LIVRE,
    },
    {
        "name": "Abonnement (bibliothèques, médiathèques...)",
        "isEvent": False,
        "proLabel": "Abonnement (bibliothèques, médiathèques...)",
        "appLabel": "Abonnement (bibliothèques, médiathèques...)",
        "conditionalFields": [],
        "canExpire": True,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": True,
        "canBeDuo": False,
        "category": LIVRE,
    },
    {
        "name": "Abonnement (livres numériques)",
        "isEvent": False,
        "proLabel": "Abonnement (livres numériques)",
        "appLabel": "Abonnement (livres numériques)",
        "conditionalFields": [],
        "canExpire": True,
        "isDigital": True,
        "isDigitalDeposit": True,
        "isPhysicalDeposit": False,
        "canBeDuo": False,
        "category": LIVRE,
    },
    {
        "name": "Festival et salon du livre",
        "isEvent": True,
        "proLabel": "Festival et salon du livre",
        "appLabel": "Festival et salon du livre",
        "conditionalFields": [],
        "canExpire": False,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": True,
        "category": LIVRE,
    },
    {
        "name": "Cartes musées, patrimoine, architecture, arts visuels ou contemporains",
        "isEvent": False,
        "proLabel": "Cartes musées, patrimoine, architecture, arts visuels ou contemporains",
        "appLabel": "Cartes musées, patrimoine...",
        "conditionalFields": [],
        "canExpire": True,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": True,
        "canBeDuo": True,
        "category": MUSEE,
    },
    {
        "name": "Abonnement musée, patrimoine...",
        "isEvent": False,
        "proLabel": "Abonnement musée, patrimoine...",
        "appLabel": "Abonnement musée, patrimoine...",
        "conditionalFields": [],
        "canExpire": True,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": True,
        "canBeDuo": True,
        "category": MUSEE,
    },
    {
        "name": "Visite",
        "isEvent": True,
        "proLabel": "Visite",
        "appLabel": "Visite",
        "conditionalFields": [],
        "canExpire": False,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": True,
        "category": MUSEE,
    },
    {
        "name": "Visite guidée",
        "isEvent": True,
        "proLabel": "Visite guidée",
        "appLabel": "Visite guidée",
        "conditionalFields": [],
        "canExpire": False,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": True,
        "category": MUSEE,
    },
    {
        "name": "Événement et atelier patrimoine",
        "isEvent": True,
        "proLabel": "Événement et atelier patrimoine",
        "appLabel": "Événement et atelier patrimoine",
        "conditionalFields": [],
        "canExpire": False,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": True,
        "category": MUSEE,
    },
    {
        "name": "Visite virtuelle",
        "isEvent": False,
        "proLabel": "Visite virtuelle",
        "appLabel": "Visite virtuelle",
        "conditionalFields": [],
        "canExpire": False,
        "isDigital": True,
        "isDigitalDeposit": True,
        "isPhysicalDeposit": False,
        "canBeDuo": False,
        "category": MUSEE,
    },
    {
        "name": "Concert",
        "isEvent": True,
        "proLabel": "Concert",
        "appLabel": "Concert",
        "conditionalFields": ["author", "musicType", "performer"],
        "canExpire": False,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": True,
        "category": MUSIQUE_LIVE,
    },
    {
        "name": "Festival de musique",
        "isEvent": True,
        "proLabel": "Festival de musique",
        "appLabel": "Festival de musique",
        "conditionalFields": ["author", "musicType", "performer"],
        "canExpire": False,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": True,
        "category": MUSIQUE_LIVE,
    },
    {
        "name": "Autre type d'événement musical",
        "isEvent": True,
        "proLabel": "Autre type d'événement musical",
        "appLabel": "Autre type d'événement musical",
        "conditionalFields": ["author", "musicType", "performer"],
        "canExpire": False,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": True,
        "category": MUSIQUE_LIVE,
    },
    {
        "name": "Livestream musical",
        "isEvent": True,
        "proLabel": "Livestream musical",
        "appLabel": "Livestream musical",
        "conditionalFields": ["author", "musicType", "performer"],
        "canExpire": False,
        "isDigital": True,
        "isDigitalDeposit": True,
        "isPhysicalDeposit": False,
        "canBeDuo": False,
        "category": MUSIQUE_LIVE,
    },
    {
        "name": "Abonnement concert",
        "isEvent": False,
        "proLabel": "Abonnement concert",
        "appLabel": "Abonnement concert",
        "conditionalFields": ["musicType"],
        "canExpire": True,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": False,
        "category": MUSIQUE_LIVE,
    },
    {
        "name": "Support physique (CD, vinyle...)",
        "isEvent": False,
        "proLabel": "Support physique (CD, vinyle...)",
        "appLabel": "Support physique (CD, vinyle...)",
        "conditionalFields": ["author", "musicType", "performer"],
        "canExpire": True,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": True,
        "canBeDuo": False,
        "category": MUSIQUE_ENREGISTREE,
    },
    {
        "name": "Téléchargement de musique",
        "isEvent": False,
        "proLabel": "Téléchargement de musique",
        "appLabel": "Téléchargement de musique",
        "conditionalFields": ["author", "musicType", "performer"],
        "canExpire": False,
        "isDigital": True,
        "isDigitalDeposit": True,
        "isPhysicalDeposit": False,
        "canBeDuo": False,
        "category": MUSIQUE_ENREGISTREE,
    },
    {
        "name": "Abonnement plateforme musicale",
        "isEvent": False,
        "proLabel": "Abonnement plateforme musicale",
        "appLabel": "Abonnement plateforme musicale",
        "conditionalFields": [],
        "canExpire": False,
        "isDigital": True,
        "isDigitalDeposit": True,
        "isPhysicalDeposit": False,
        "canBeDuo": False,
        "category": MUSIQUE_ENREGISTREE,
    },
    {
        "name": "Captation musicale",
        "isEvent": False,
        "proLabel": "Captation musicale",
        "appLabel": "Captation musicale",
        "conditionalFields": ["author", "musicType", "performer"],
        "canExpire": False,
        "isDigital": True,
        "isDigitalDeposit": True,
        "isPhysicalDeposit": False,
        "canBeDuo": False,
        "category": MUSIQUE_ENREGISTREE,
    },
    {
        "name": "Séance d'essai",
        "isEvent": True,
        "proLabel": "Séance d'essai",
        "appLabel": "Séance d'essai",
        "conditionalFields": ["speaker"],
        "canExpire": True,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": True,
        "category": PRATIQUE,
    },
    {
        "name": "Atelier, stage de pratique artistique",
        "isEvent": True,
        "proLabel": "Atelier, stage de pratique artistique",
        "appLabel": "Atelier, stage de pratique artistique",
        "conditionalFields": ["speaker"],
        "canExpire": False,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": True,
        "category": PRATIQUE,
    },
    {
        "name": "Abonnement pratique artistique",
        "isEvent": False,
        "proLabel": "Abonnement pratique artistique",
        "appLabel": "Abonnement pratique artistique",
        "conditionalFields": [],
        "canExpire": True,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": True,
        "canBeDuo": False,
        "category": PRATIQUE,
    },
    {
        "name": "Abonnement presse en ligne",
        "isEvent": False,
        "proLabel": "Abonnement presse en ligne",
        "appLabel": "Abonnement presse en ligne",
        "conditionalFields": [],
        "canExpire": False,
        "isDigital": True,
        "isDigitalDeposit": True,
        "isPhysicalDeposit": False,
        "canBeDuo": False,
        "category": MEDIAS,
    },
    {
        "name": "Article de presse",
        "isEvent": False,
        "proLabel": "Article de presse",
        "appLabel": "Article de presse",
        "conditionalFields": [],
        "canExpire": False,
        "isDigital": True,
        "isDigitalDeposit": True,
        "isPhysicalDeposit": False,
        "canBeDuo": False,
        "category": MEDIAS,
    },
    {
        "name": "Podcast",
        "isEvent": False,
        "proLabel": "Podcast",
        "appLabel": "Podcast",
        "conditionalFields": [],
        "canExpire": False,
        "isDigital": True,
        "isDigitalDeposit": True,
        "isPhysicalDeposit": False,
        "canBeDuo": False,
        "category": MEDIAS,
    },
    {
        "name": "Application culturelle",
        "isEvent": False,
        "proLabel": "Application culturelle",
        "appLabel": "Application culturelle",
        "conditionalFields": [],
        "canExpire": False,
        "isDigital": True,
        "isDigitalDeposit": True,
        "isPhysicalDeposit": False,
        "canBeDuo": False,
        "category": MEDIAS,
    },
    {
        "name": "Spectacle, représentation",
        "isEvent": True,
        "proLabel": "Spectacle, représentation",
        "appLabel": "Spectacle, représentation",
        "conditionalFields": ["author", "showType", "stageDirector", "performer"],
        "canExpire": False,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": True,
        "category": SPECTACLE,
    },
    {
        "name": "Spectacle enregistré",
        "isEvent": False,
        "proLabel": "Spectacle enregistré",
        "appLabel": "Spectacle enregistré",
        "conditionalFields": ["author", "showType", "stageDirector", "performer"],
        "canExpire": False,
        "isDigital": True,
        "isDigitalDeposit": True,
        "isPhysicalDeposit": False,
        "canBeDuo": False,
        "category": SPECTACLE,
    },
    {
        "name": "Livestream d'événement",
        "isEvent": True,
        "proLabel": "Livestream d'événement",
        "appLabel": "Livestream d'événement",
        "conditionalFields": ["author", "showType", "stageDirector", "performer"],
        "canExpire": False,
        "isDigital": True,
        "isDigitalDeposit": True,
        "isPhysicalDeposit": False,
        "canBeDuo": False,
        "category": SPECTACLE,
    },
    {
        "name": "Festival",
        "isEvent": True,
        "proLabel": "Festival",
        "appLabel": "Festival",
        "conditionalFields": ["author", "showType", "stageDirector", "performer"],
        "canExpire": False,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": True,
        "category": SPECTACLE,
    },
    {
        "name": "Abonnement spectacle",
        "isEvent": False,
        "proLabel": "Abonnement spectacle",
        "appLabel": "Abonnement spectacle",
        "conditionalFields": ["showType"],
        "canExpire": True,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": False,
        "canBeDuo": False,
        "category": SPECTACLE,
    },
    {
        "name": "Achat instrument",
        "isEvent": False,
        "proLabel": "Achat instrument",
        "appLabel": "Achat instrument",
        "conditionalFields": [],
        "canExpire": True,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": True,
        "canBeDuo": False,
        "category": INSTRUMENT_MUSIQUE,
    },
    {
        "name": "Bon d'achat instrument",
        "isEvent": False,
        "proLabel": "Bon d'achat instrument",
        "appLabel": "Bon d'achat instrument",
        "conditionalFields": [],
        "canExpire": True,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": True,
        "canBeDuo": False,
        "category": INSTRUMENT_MUSIQUE,
    },
    {
        "name": "Location instrument",
        "isEvent": False,
        "proLabel": "Location instrument",
        "appLabel": "Location instrument",
        "conditionalFields": [],
        "canExpire": True,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": True,
        "canBeDuo": False,
        "category": INSTRUMENT_MUSIQUE,
    },
    {
        "name": "Partition",
        "isEvent": False,
        "proLabel": "Partition",
        "appLabel": "Partition",
        "conditionalFields": [],
        "canExpire": True,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": True,
        "canBeDuo": False,
        "category": INSTRUMENT_MUSIQUE,
    },
    {
        "name": "Matériel arts créatifs",
        "isEvent": False,
        "proLabel": "Matériel arts créatifs",
        "appLabel": "Matériel arts créatifs",
        "conditionalFields": [],
        "canExpire": True,
        "isDigital": False,
        "isDigitalDeposit": False,
        "isPhysicalDeposit": True,
        "canBeDuo": False,
        "category": BEAUX_ARTS,
    },
]


def create_industrial_categories() -> None:
    logger.info("create_industrial_categories")

    new_categories = []
    for category in CATEGORIES:
        new_category = OfferCategory()
        new_category.name = category["name"]
        new_category.proLabel = category["proLabel"]
        new_category.appLabel = category["appLabel"]
        new_categories.append(new_category)
    repository.save(*new_categories)

    logger.info("created %d categories", OfferCategory.query.count())

    new_sub_categories = []
    categories = OfferCategory.query.all()
    for category in categories:
        for sub_category in SUB_CATEGORIES:
            if category.name == sub_category["category"]:
                new_sub_category = OfferSubcategory()
                new_sub_category.name = sub_category["name"]
                new_sub_category.isEvent = sub_category["isEvent"]
                new_sub_category.proLabel = sub_category["proLabel"]
                new_sub_category.appLabel = sub_category["appLabel"]
                new_sub_category.conditionalFields = sub_category["conditionalFields"]
                new_sub_category.canExpire = sub_category["canExpire"]
                new_sub_category.isDigital = sub_category["isDigital"]
                new_sub_category.isDigitalDeposit = sub_category["isDigitalDeposit"]
                new_sub_category.isPhysicalDeposit = sub_category["isPhysicalDeposit"]
                new_sub_category.canBeDuo = sub_category["canBeDuo"]
                new_sub_category.categoryId = category.id
                new_sub_categories.append(new_sub_category)
    repository.save(*new_sub_categories)

    logger.info("created %d sub categories ", OfferSubcategory.query.count())
