BOOK_MACRO_SECTIONS = {
    "Géographie, cartographie",
    "Poèsie, théâtre et spectacle",
    "Bandes dessinées",
    "Carrière/Concours",
    "Sport",
    "Policier",
    "Histoire",
    "Science-fiction, fantastique & terreur",
    "Littérature Etrangère",
    "Sociologie",
    "Gestion/entreprise",
    "Littérature française",
    "Littérature Europééne",
    "Scolaire & Parascolaire",
    "Sciences Humaines, Encyclopédie, dictionnaire",
    "Langue",
    "Religions, spiritualitées",
    "Vie pratique",
    "Art",
    "Santé",
    "Sciences, vie & Nature",
    "Informatique",
    "Jeunesse",
    "Sexualité",
    "Psychanalyse, psychologie",
    "Humour",
    "Manga",
    "Arts Culinaires",
    "Tourisme",
    "Jeux",
    "Droit",
    "Marketing et audio-visuel",
    "Faits, temoignages",
    "Economie",
    "Loisirs",
}
