MOVIE_TYPES = {
    "ACTION": "Action",
    "ADVENTURE": "Aventure",
    "ANIMATION": "Animation",
    "BIOPIC": "Biopic",
    "BOLLYWOOD": "Bollywood",
    "COMEDY": "Comédie",
    "COMEDY_DRAMA": "Comédie dramatique",
    "CONCERT": "Concert",
    "DETECTIVE": "Policier",
    "DIVERS": "Divers",
    "DOCUMENTARY": "Documentaire",
    "DRAMA": "Drame",
    "EROTIC": "Érotique",
    "EXPERIMENTAL": "Expérimental",
    "FAMILY": "Familial",
    "FANTASY": "Fantastique",
    "HISTORICAL": "Historique",
    "HISTORICAL_EPIC": "Historique-épique",
    "HORROR": "Horreur",
    "JUDICIAL": "Judiciaire",
    "KOREAN_DRAMA": "Drame coréen",
    "MARTIAL_ARTS": "Arts martiaux",
    "MUSIC": "Musique",
    "MUSICAL": "Comédie musicale",
    "OPERA": "Opéra",
    "PERFORMANCE": "Performance",
    "ROMANCE": "Romance",
    "SCIENCE_FICTION": "Science-fiction",
    "SPORT_EVENT": "Sport",
    "SPY": "Espionnage",
    "THRILLER": "Thriller",
    "WARMOVIE": "Guerre",
    "WESTERN": "Western",
}
