from dataclasses import dataclass


@dataclass
class MusicSubType:
    code: int
    label: str


@dataclass
class MusicType(MusicSubType):
    children: list[MusicSubType]


# WARNING: the list below MUST be kept in sync with the list at pro/src/components/pages/Offers/Offer/OfferDetails/OfferForm/OfferCategories/subTypes.js
music_types = [
    MusicType(
        code=501,
        label="Jazz",
        children=[
            MusicSubType(code=502, label="Acid Jazz"),
            MusicSubType(code=503, label="Avant-Garde Jazz"),
            MusicSubType(code=504, label="Bebop"),
            MusicSubType(code=505, label="Big Band"),
            MusicSubType(code=506, label="Blue Note"),
            MusicSubType(code=507, label="Cool Jazz"),
            MusicSubType(code=508, label="Crossover Jazz"),
            MusicSubType(code=509, label="Dixieland"),
            MusicSubType(code=510, label="Ethio Jazz"),
            MusicSubType(code=511, label="Fusion"),
            MusicSubType(code=512, label="Jazz Contemporain"),
            MusicSubType(code=513, label="Jazz Funk"),
            MusicSubType(code=514, label="Mainstream"),
            MusicSubType(code=515, label="Manouche"),
            MusicSubType(code=516, label="Traditionel"),
            MusicSubType(code=517, label="Vocal Jazz"),
            MusicSubType(code=518, label="Ragtime"),
            MusicSubType(code=519, label="Smooth"),
            MusicSubType(code=-1, label="Autre"),
        ],
    ),
    MusicType(
        code=520,
        label="Blues",
        children=[
            MusicSubType(code=521, label="Blues Accoustique"),
            MusicSubType(code=522, label="Blues Contemporain"),
            MusicSubType(code=523, label="Blues Électrique"),
            MusicSubType(code=524, label="Blues Rock"),
            MusicSubType(code=525, label="Chicago Blues"),
            MusicSubType(code=526, label="Classic Blues"),
            MusicSubType(code=527, label="Country Blues"),
            MusicSubType(code=528, label="Delta Blues"),
            MusicSubType(code=529, label="Ragtime"),
            MusicSubType(code=-1, label="Autre"),
        ],
    ),
    MusicType(
        code=530,
        label="Reggae",
        children=[
            MusicSubType(code=531, label="2-Tone"),
            MusicSubType(code=532, label="Dancehall"),
            MusicSubType(code=533, label="Dub"),
            MusicSubType(code=534, label="Roots "),
            MusicSubType(code=535, label="Ska"),
            MusicSubType(code=536, label="Zouk "),
            MusicSubType(code=-1, label="Autre"),
        ],
    ),
    MusicType(
        code=600,
        label="Classique",
        children=[
            MusicSubType(code=601, label="Avant-garde"),
            MusicSubType(code=602, label="Baroque"),
            MusicSubType(code=603, label="Chant"),
            MusicSubType(code=604, label="Chorale"),
            MusicSubType(code=605, label="Contemporain"),
            MusicSubType(code=606, label="Expressioniste"),
            MusicSubType(code=607, label="Impressioniste"),
            MusicSubType(code=608, label="Médievale"),
            MusicSubType(code=609, label="Minimaliste"),
            MusicSubType(code=610, label="Moderne "),
            MusicSubType(code=611, label="Oratorio"),
            MusicSubType(code=612, label="Opéra"),
            MusicSubType(code=613, label="Renaissance"),
            MusicSubType(code=614, label="Romantique"),
            MusicSubType(code=-1, label="Autre"),
        ],
    ),
    MusicType(
        code=700,
        label="Musique du Monde",
        children=[
            MusicSubType(code=701, label="Africaine"),
            MusicSubType(code=702, label="Afro Beat"),
            MusicSubType(code=703, label="Afro Pop"),
            MusicSubType(code=704, label="Alternativo "),
            MusicSubType(code=705, label="Amérique du Nord"),
            MusicSubType(code=706, label="Amérique du Sud"),
            MusicSubType(code=707, label="Asiatique"),
            MusicSubType(code=708, label="Baladas y Boleros"),
            MusicSubType(code=709, label="Bossa Nova"),
            MusicSubType(code=710, label="Brésilienne"),
            MusicSubType(code=711, label="Cajun"),
            MusicSubType(code=712, label="Calypso"),
            MusicSubType(code=713, label="Caribéenne"),
            MusicSubType(code=714, label="Celtique"),
            MusicSubType(code=715, label="Cumbia "),
            MusicSubType(code=716, label="Flamenco"),
            MusicSubType(code=717, label="Grècque"),
            MusicSubType(code=718, label="Indienne"),
            MusicSubType(code=719, label="Latin Jazz"),
            MusicSubType(code=720, label="Moyen-Orient"),
            MusicSubType(code=721, label="Musique Latine Contemporaine"),
            MusicSubType(code=722, label="Nuevo Flamenco"),
            MusicSubType(code=723, label="Pop Latino"),
            MusicSubType(code=724, label="Portuguese fado "),
            MusicSubType(code=725, label="Rai"),
            MusicSubType(code=726, label="Salsa"),
            MusicSubType(code=727, label="Tango Argentin"),
            MusicSubType(code=728, label="Yiddish"),
            MusicSubType(code=-1, label="Autre"),
        ],
    ),
    MusicType(
        code=800,
        label="Pop",
        children=[
            MusicSubType(code=801, label="Britpop"),
            MusicSubType(code=802, label="Bubblegum "),
            MusicSubType(code=803, label="Dance Pop"),
            MusicSubType(code=804, label="Dream Pop "),
            MusicSubType(code=805, label="Electro Pop"),
            MusicSubType(code=806, label="Indie Pop"),
            MusicSubType(code=808, label="J-Pop"),
            MusicSubType(code=809, label="K-Pop"),
            MusicSubType(code=810, label="Pop Punk "),
            MusicSubType(code=811, label="Pop/Rock"),
            MusicSubType(code=812, label="Power Pop "),
            MusicSubType(code=813, label="Soft Rock"),
            MusicSubType(code=814, label="Synthpop "),
            MusicSubType(code=815, label="Teen Pop"),
            MusicSubType(code=-1, label="Autre"),
        ],
    ),
    MusicType(
        code=820,
        label="Rock",
        children=[
            MusicSubType(code=821, label="Acid Rock "),
            MusicSubType(code=822, label="Arena Rock"),
            MusicSubType(code=823, label="Art Rock"),
            MusicSubType(code=824, label="College Rock"),
            MusicSubType(code=825, label="Glam Rock"),
            MusicSubType(code=826, label="Grunge"),
            MusicSubType(code=827, label="Hard Rock"),
            MusicSubType(code=828, label="Indie Rock"),
            MusicSubType(code=829, label="Lo-fi"),
            MusicSubType(code=830, label="Prog-Rock"),
            MusicSubType(code=831, label="Psychedelic"),
            MusicSubType(code=832, label="Rock & Roll"),
            MusicSubType(code=833, label="Rock Experimental"),
            MusicSubType(code=834, label="Rockabilly"),
            MusicSubType(code=835, label="Shoegaze"),
            MusicSubType(code=836, label="Rock Electro"),
            MusicSubType(code=-1, label="Autre"),
        ],
    ),
    MusicType(
        code=840,
        label="Metal",
        children=[
            MusicSubType(code=841, label="Black Metal"),
            MusicSubType(code=842, label="Death Metal "),
            MusicSubType(code=843, label="Doom Metal"),
            MusicSubType(code=844, label="Gothic "),
            MusicSubType(code=845, label="Metal Core"),
            MusicSubType(code=846, label="Metal Progressif"),
            MusicSubType(code=847, label="Trash Metal"),
            MusicSubType(code=848, label="Metal Industriel"),
            MusicSubType(code=849, label="Fusion"),
            MusicSubType(code=-1, label="Autre"),
        ],
    ),
    MusicType(
        code=850,
        label="Punk",
        children=[
            MusicSubType(code=851, label="Post Punk "),
            MusicSubType(code=852, label="Hardcore Punk"),
            MusicSubType(code=853, label="Afro Punk"),
            MusicSubType(code=854, label="Grindcore"),
            MusicSubType(code=855, label="Noise Rock "),
            MusicSubType(code=-1, label="Autre"),
        ],
    ),
    MusicType(
        code=860,
        label="Folk",
        children=[
            MusicSubType(code=861, label="Folk Contemporaine"),
            MusicSubType(code=862, label="Indie Folk"),
            MusicSubType(code=863, label="Folk Rock"),
            MusicSubType(code=864, label="New Acoustic"),
            MusicSubType(code=865, label="Folk Traditionelle"),
            MusicSubType(code=866, label="Tex-Mex"),
            MusicSubType(code=-1, label="Autre"),
        ],
    ),
    MusicType(
        code=870,
        label="Country",
        children=[
            MusicSubType(code=871, label="Country Alternative"),
            MusicSubType(code=872, label="Americana"),
            MusicSubType(code=873, label="Bluegrass"),
            MusicSubType(code=874, label="Country Contemporaine"),
            MusicSubType(code=875, label="Gospel Country"),
            MusicSubType(code=876, label="Country Pop"),
            MusicSubType(code=-1, label="Autre"),
        ],
    ),
    MusicType(
        code=880,
        label="Electro",
        children=[
            MusicSubType(code=881, label="Bitpop"),
            MusicSubType(code=882, label="Breakbeat "),
            MusicSubType(code=883, label="Chillwave"),
            MusicSubType(code=884, label="Dance"),
            MusicSubType(code=885, label="Downtempo"),
            MusicSubType(code=886, label="Drum & Bass "),
            MusicSubType(code=887, label="Dubstep"),
            MusicSubType(code=888, label="Electro Experimental"),
            MusicSubType(code=889, label="Electronica"),
            MusicSubType(code=890, label="Garage"),
            MusicSubType(code=891, label="Grime"),
            MusicSubType(code=892, label="Hard Dance"),
            MusicSubType(code=893, label="Hardcore"),
            MusicSubType(code=894, label="House"),
            MusicSubType(code=895, label="Industriel"),
            MusicSubType(code=896, label="Lounge"),
            MusicSubType(code=897, label="Techno"),
            MusicSubType(code=898, label="Trance"),
            MusicSubType(code=-1, label="Autre"),
        ],
    ),
    MusicType(
        code=900,
        label="Hip-Hop/Rap",
        children=[
            MusicSubType(code=901, label="Bounce"),
            MusicSubType(code=902, label="Hip Hop"),
            MusicSubType(code=903, label="Rap Alternatif"),
            MusicSubType(code=905, label="Rap East Coast"),
            MusicSubType(code=906, label="Rap Français"),
            MusicSubType(code=907, label="Rap Gangsta"),
            MusicSubType(code=908, label="Rap Hardcore"),
            MusicSubType(code=909, label="Rap Latino"),
            MusicSubType(code=910, label="Rap Old School"),
            MusicSubType(code=911, label="Rap Underground"),
            MusicSubType(code=912, label="Rap West Coast"),
            MusicSubType(code=913, label="Trap"),
            MusicSubType(code=914, label="Trip Hop"),
            MusicSubType(code=921, label="R&B Contemporain"),
            MusicSubType(code=922, label="Disco"),
            MusicSubType(code=923, label="Doo Wop"),
            MusicSubType(code=924, label="Funk"),
            MusicSubType(code=925, label="Soul"),
            MusicSubType(code=926, label="Motown"),
            MusicSubType(code=927, label="Neo Soul"),
            MusicSubType(code=928, label="Soul Psychedelique"),
            MusicSubType(code=-1, label="Autre"),
        ],
    ),
    MusicType(
        code=930,
        label="Gospel",
        children=[
            MusicSubType(code=931, label="Spiritual Gospel"),
            MusicSubType(code=932, label="Traditional Gospel"),
            MusicSubType(code=933, label="Southern Gospel"),
            MusicSubType(code=934, label="Contemporary Gospel"),
            MusicSubType(code=935, label="Bluegrass Gospel"),
            MusicSubType(code=936, label="Blues Gospel"),
            MusicSubType(code=937, label="Country Gospel"),
            MusicSubType(code=938, label="Hybrid Gospel"),
            MusicSubType(code=-1, label="Autre"),
        ],
    ),
    MusicType(
        code=1000,
        label="Chansons / Variétés",
        children=[
            MusicSubType(code=1001, label="Musette"),
            MusicSubType(code=1002, label="Chanson Française"),
            MusicSubType(code=1003, label="Music Hall"),
            MusicSubType(code=1004, label="Folklore français"),
            MusicSubType(code=1005, label="Chanson à texte"),
            MusicSubType(code=1006, label="Slam"),
            MusicSubType(code=-1, label="Autre"),
        ],
    ),
    MusicType(
        code=-1,
        label="Autre",
        children=[MusicSubType(code=-1, label="Autre")],
    ),
]

MUSIC_TYPES_DICT = {vars(music_type)["code"]: vars(music_type)["label"] for music_type in music_types}

MUSIC_SUB_TYPES_DICT = {
    vars(music_sub_type)["code"]: vars(music_sub_type)["label"]
    for music_type in music_types
    for music_sub_type in music_type.children
}
