const state = {
  data: {
    offers: [
      {
        id: 'UU',
      },
    ],
    stocks: [
      {
        id: 'MU',
        available: 10,
        bookingLimitDatetime: null,
        bookingRecapSent: null,
        dateModified: '2019-03-07T10:40:07.318721Z',
        dateModifiedAtLastProvider: '2019-03-07T10:40:07.318695Z',
        eventOccurrence: null,
        groupSize: 1,
        idAtProviders: null,
        isSoftDeleted: false,
        lastProvider: null,
        modelName: 'Stock',
        offer: 'UU',
        price: 17,
      },
      {
        id: 'MQ',
        available: 10,
        bookingLimitDatetime: null,
        bookingRecapSent: null,
        dateModified: '2019-03-07T10:40:07.315722Z',
        dateModifiedAtLastProvider: '2019-03-07T10:40:07.315702Z',
        eventOccurrence: null,
        groupSize: 1,
        idAtProviders: null,
        isSoftDeleted: false,
        lastProvider: null,
        modelName: 'Stock',
        offer: 'UM',
        price: 16,
      },
      {
        id: 'MM',
        available: 10,
        bookingLimitDatetime: null,
        bookingRecapSent: null,
        dateModified: '2019-03-07T10:40:07.312234Z',
        dateModifiedAtLastProvider: '2019-03-07T10:40:07.312216Z',
        eventOccurrence: null,
        groupSize: 1,
        idAtProviders: null,
        isSoftDeleted: false,
        lastProvider: null,
        modelName: 'Stock',
        offer: 'U9',
        price: 51,
      },
      {
        id: 'M9',
        available: 10,
        bookingLimitDatetime: null,
        bookingRecapSent: null,
        dateModified: '2019-03-07T10:40:07.309108Z',
        dateModifiedAtLastProvider: '2019-03-07T10:40:07.309075Z',
        eventOccurrence: null,
        groupSize: 1,
        idAtProviders: null,
        isSoftDeleted: false,
        lastProvider: null,
        modelName: 'Stock',
        offer: 'UA',
        price: 50,
      },
      {
        id: 'ME',
        available: 10,
        bookingLimitDatetime: null,
        bookingRecapSent: null,
        dateModified: '2019-03-07T10:40:07.306052Z',
        dateModifiedAtLastProvider: '2019-03-07T10:40:07.306033Z',
        eventOccurrence: null,
        groupSize: 1,
        idAtProviders: null,
        isSoftDeleted: false,
        lastProvider: null,
        modelName: 'Stock',
        offer: 'T4',
        price: 28,
      },
      {
        id: 'MA',
        available: 10,
        bookingLimitDatetime: null,
        bookingRecapSent: null,
        dateModified: '2019-03-07T10:40:07.303564Z',
        dateModifiedAtLastProvider: '2019-03-07T10:40:07.303546Z',
        eventOccurrence: null,
        groupSize: 1,
        idAtProviders: null,
        isSoftDeleted: false,
        lastProvider: null,
        modelName: 'Stock',
        offer: 'TU',
        price: 15,
      },
      {
        id: 'L4',
        available: 10,
        bookingLimitDatetime: null,
        bookingRecapSent: null,
        dateModified: '2019-03-07T10:40:07.300968Z',
        dateModifiedAtLastProvider: '2019-03-07T10:40:07.300950Z',
        eventOccurrence: null,
        groupSize: 1,
        idAtProviders: null,
        isSoftDeleted: false,
        lastProvider: null,
        modelName: 'Stock',
        offer: 'TQ',
        price: 11,
      },
    ],
  },
}

export default state
