CINEMA_PROVIDER_NAMES = [
    "CDSStocks",
    "BoostStocks",
    "CGRStocks",
]

PASS_CULTURE_STOCKS_FAKE_CLASS_NAME = "PCAPIStocks"
INDIVIDUAL_OFFERS_API_FAKE_CLASS_NAME = "IndividualOffersPublicAPI"
INDIVIDUAL_OFFERS_API_PROVIDER_NAME = "Individual Offers public API"
