export const validatedCriteria = [
  "1.1 – Le service numérique a-t-il été évalué favorablement en termes d'utilité en tenant compte de ses impacts environnementaux ?",
  '1.2 – Le service numérique a-t-il défini ses cibles utilisatrices, les besoins métiers et les attentes réelles des utilisateurs cibles ?',
  '1.3 – Le service numérique a-t-il au moins un référent identifié en écoconception numérique ?',
  '1.6 – Le service numérique collecte-t-il la donnée de façon responsable et raisonnée ?',
  '1.7 – Le service numérique a-t-il recours à un niveau de chiffrement adapté à ses besoins ?',
  "1.8 – Le service numérique a-t-il mis en place des efforts d'open source ?",
  '1.9 – Le service numérique a-t-il été conçu avec des technologies standard interopérables plutôt que des technologies spécifiques et fermées ?',
  '1.10 – Le service numérique repose-t-il sur des API documentées et ouvertes pour interagir avec le matériel ?',
  '2.1 – Le service numérique a-t-il défini la liste des profils de matériels que les utilisateurs vont pouvoir employer pour y accéder ?',
  "2.2 – Le service numérique est-il utilisable sur d'anciens modèles de terminaux ?",
  "2.4 – Le service numérique est-il utilisable sur d'anciennes versions de système d'exploitation et de navigateurs web ?",
  "2.5 – Le service numérique s'adapte-t-il à différents types de terminaux d'affichage ?",
  '2.7 – Le service numérique a-t-il prévu une stratégie de maintenance et de décommissionnement ?',
  '2.10 – Le service numérique a-t-il pris en compte les impacts environnementaux des services tiers utilisés lors de leur sélection ?',
  '3.1 – Le service numérique repose-t-il sur une architecture, des ressources ou des composants conçus pour réduire leurs propres impacts environnementaux ?',
  '3.2 – Le service numérique fonctionne-t-il sur une architecture pouvant adapter la quantité de ressources utilisées à la consommation du service ?',
  '7.1 – Le service numérique a-t-il recours à un système de cache serveur pour les données les plus utilisées ?',
  "3.3 – Le service numérique est-il en mesure de supporter l'évolution technique des protocoles ?",
  '3.4 – Le service numérique garantit-il la mise à disposition de mises à jour correctives pendant toute la durée de vie prévue des équipements et des logiciels liés au service ?',
  "3.5 – Le service numérique propose-t-il d'installer des mises à jour correctives indépendamment des mises à jour évolutives de façon transparente ?",
  '3.6 – Le service numérique propose-t-il les mises à jour incrémentielles, afin de ne pas remplacer tout le code à chaque mise à jour ?',
  '3.7 – Le service numérique optimise-t-il la sollicitation des environnements de développement, de préproduction ou de test en fonction de ses besoins ?',
  '4.1 – Le service numérique comporte-t-il uniquement des animations, vidéos et sons dont la lecture automatique est désactivée ?',
  '4.2 – Le service numérique affiche-t-il uniquement des contenus sans défilement infini ?',
  '4.3 – Le service numérique optimise-t-il le parcours de navigation pour chaque fonctionnalité principale ?',
  "4.4 – Le service numérique permet-il à l'utilisateur de décider de l'activation d'un service tiers ?",
  "4.5 – Le service numérique utilise-t-il majoritairement des composants fonctionnels natifs du système d'exploitation, du navigateur ou du langage utilisé ?",
  "4.6 – Le service numérique utilise-t-il uniquement du contenu vidéo, audio et animé porteur d'informations ?",
  "4.7 – Le service numérique opte-t-il pour les choix les plus sobres entre le texte, l'image, l'audio ou la vidéo, selon les besoins utilisateurs ?",
  '4.8 – Le service numérique limite-t-il le nombre des polices de caractères téléchargées ?',
  "4.10 – Le service numérique informe-t-il l'utilisateur du format de saisie attendu, en évitant les requêtes serveur inutiles pour la soumission d'un formulaire ?",
  "4.13 – Le service numérique limite-t-il le recours aux notifications, tout en laissant la possibilité à l'utilisateur de les désactiver ?",
  '4.14 – Le service numérique évite-t-il le recours à des procédés manipulatoires dans son interface utilisateur ?',
  '5.1 – Le service numérique utilise-t-il un format de fichier adapté au contenu et au contexte de visualisation de chaque image ?',
  '5.2 – Le service numérique propose-t-il des images dont le niveau de compression est adapté au contenu et au contexte de visualisation ?',
  '5.3 – Le service numérique utilise-t-il, pour chaque vidéo, une définition adaptée au contenu et au contexte de visualisation ?',
  '5.4 – Le service numérique propose-t-il des vidéos dont le mode de compression est efficace et adapté au contenu et au contexte de visualisation ?',
  "5.6 – Le service numérique propose-t-il des contenus audios dont le mode de compression est adapté au contenu et au contexte d'écoute ?",
  "5.7 – Le service numérique utilise-t-il un format de fichier adapté au contenu et au contexte d'utilisation pour chaque document ?",
  "5.8 – Le service numérique a-t-il une stratégie d'archivage et de suppression, automatique ou manuelle, des contenus obsolètes ou périmés ?",
  '6.2 – Le service numérique utilise-t-il des mécanismes de mise en cache pour la totalité des contenus transférés dont il a le contrôle ?',
  "6.6 – Le service numérique restreint-il l'usage des capteurs des terminaux utilisateurs au besoin du service ?",
  '7.2 – Le service numérique met-il en place des durées de conservation sur les données et documents en vue de leur suppression ou archivage passé ce délai ?',
  "7.4 – Le service numérique s'appuie-t-il sur un mécanisme de consensus qui minimise sa consommation de ressources ?",
  '8.1 – Le service numérique utilise-t-il un hébergement signataire du Code de Conduite européen sur les Datacentres ?',
  '8.2 – Le service numérique utilise-t-il un hébergement qui fournit une politique de gestion durable des équipements ?',
  '8.3 – Le service numérique utilise-t-il un hébergement qui fournit une politique de gestion durable des équipements ?',
  "8.5 – Le service numérique utilise-t-il un hébergement dont l'origine de consommation d'électricité est documentée et majoritairement d'origine renouvelable ?",
  '8.6 – Le service numérique utilise-t-il un hébergement dont le WUE (Water Usage Effectiveness) est communiqué ?',
  '8.7 – Le service numérique utilise-t-il un hébergement qui traite efficacement la chaleur produite par les serveurs ?',
  "9.1 – Le service numérique a-t-il interrogé la nécessité d'une phase d'entraînement pour éviter un usage non justifié et déraisonné ?",
  "9.2 – Le service numérique utilise-t-il une phase d'apprentissage avec un niveau de complexité minimisé et proportionné à l'usage effectif du service ?",
  "9.3 – Le service numérique a-t-il mis en place des mécanismes visant à limiter la quantité d'entraînement nécessaire à son fonctionnement ?",
  "9.4 – Le service numérique limite-t-il la quantité de données utilisées pour la phase d'apprentissage au strict nécessaire ?",
  "9.5 – Le service numérique optimise-t-il l'occurrence de mise à jour et de réentraînement des modèles en fonction de ses besoins et des cibles utilisatrices ?",
  "9.6 – Le service numérique utilise-t-il des techniques de compression pour les modèles utilisés lors de la phase d'entraînement ?",
  "9.7 – Le service numérique utilise-t-il une stratégie d'inférence optimisée en termes de consommation de ressources et des cibles utilisatrices ?",
]

export const nonValidatedCriteria = [
  "1.4 – Le service numérique réalise-t-il régulièrement des revues pour s'assurer du respect de sa démarche d'écoconception ?",
  "1.5 – Le service numérique s'est-il fixé des objectifs en matière de réduction ou de limitation de ses propres impacts environnementaux ?",
  '2.3 – Le service numérique est-il utilisable via une connexion bas débit ou hors connexion ?',
  '2.6 – Le service numérique a-t-il été conçu avec une revue de conception et une revue de code comprenant parmi ses objectifs la réduction des impacts environnementaux de chaque fonctionnalité ?',
  '2.8 – Le service numérique impose-t-il à ses fournisseurs de garantir une démarche de réduction de leurs impacts environnementaux ?',
  "2.9 – Le service numérique a-t-il pris en compte les impacts environnementaux des composants d'interface prêts à l'emploi utilisés ?",
  '4.9 – Le service numérique limite-t-il les requêtes serveur lors de la saisie utilisateur ?',
  "4.11 – Le service numérique informe-t-il l'utilisateur, avant le transfert, des poids et formats de fichier attendus ?",
  "4.12 – Le service numérique indique-t-il à l'utilisateur que l'utilisation d'une fonctionnalité a des impacts environnementaux importants ?",
  "4.15 – Le service numérique fournit-il à l'utilisateur un moyen de contrôle sur ses usages afin de suivre et de réduire les impacts environnementaux associés ?",
  '5.5 – Le service numérique propose-t-il un mode « écoute seule » pour ses vidéos ?',
  "6.1 – Le service numérique s'astreint-il à un poids maximum et une limite de requête par écran ?",
  '6.3 – Le service numérique a-t-il mis en place des techniques de compression pour les ressources transférées dont il a le contrôle ?',
  "6.4 – Le service numérique affiche-t-il majoritairement des images dont les dimensions d'origine correspondent aux dimensions du contexte d'affichage ?",
  '6.5 – Le service numérique évite-t-il de déclencher le chargement de ressources et de contenus inutilisés pour chaque fonctionnalité ?',
  "6.7 – Le service numérique héberge-t-il toutes les ressources statiques transférées dont il est l'émetteur sur un même domaine ?",
  "7.3 – Le service numérique informe-t-il l'utilisateur d'un traitement en cours en arrière-plan ?",
  '8.4 – Le service numérique utilise-t-il un hébergement dont son WUE (Water Usage Effectiveness) est minimisé ?',
  '8.8 – Le service numérique héberge-t-il de façon distincte les données « chaudes » et « froides » ?',
  '8.9 – Le service numérique duplique-t-il les données uniquement lorsque cela est nécessaire ?',
  "8.10 – Le service numérique tient-il compte des contraintes externes pour minimiser l'impact environnemental des calculs et transferts de données asynchrones ?",
]
