from pcapi.core.finance.utils import CurrencyEnum


PRICE_TABLE_ENTRY_MAX_PRICE_IN_XPF = 23865
PRICE_TABLE_ENTRY_MAX_PRICE_IN_EUR = 300

PRICE_TABLE_ENTRY_MAX_PRICE_BY_CURRENCY = {
    CurrencyEnum.EUR: PRICE_TABLE_ENTRY_MAX_PRICE_IN_EUR,
    CurrencyEnum.XPF: PRICE_TABLE_ENTRY_MAX_PRICE_IN_XPF,
}
