import routes.bookings
import routes.client_errors
import routes.error_handlers
import routes.event_occurrences
import routes.events
import routes.export
import routes.mediations
import routes.offers
import routes.offerers
import routes.stocks
import routes.providers
import routes.recommendations
# TODO
# if IS_DEV:
import routes.storage
import routes.things
import routes.types
import routes.user_offerers
import routes.users
import routes.validate
import routes.venue_providers
import routes.venues
