FILM_207 = {
    "id": 207,
    "titleCnc": "BLACK PANTHER : WAKANDA FOREVER",
    "numVisa": 158026,
    "posterUrl": "http://example.com/images/158026.jpg",
    "thumbUrl": "http://example.com/img/thumb/film/158026.jpg",
    "duration": 162,
    "isHfr": False,
    "isHearingImpaired": False,
    "hasAudioDescription": False,
    "is4K": False,
    "idFilmAllocine": 263242,
    "isLightVibes": False,
    "isEclairColor": False,
}
FILM_210 = {
    "id": 210,
    "titleCnc": "CHARLOTTE",
    "numVisa": 149489,
    "posterUrl": "http://example.com/images/149489.jpg",
    "thumbUrl": "http://example.com/img/thumb/film/149489.jpg",
    "duration": 92,
    "isHfr": False,
    "isHearingImpaired": False,
    "hasAudioDescription": False,
    "is4K": False,
    "idFilmAllocine": 277733,
    "isLightVibes": False,
    "isEclairColor": False,
}
FILM_147 = {
    "id": 147,
    "titleCnc": "CASSE NOISETTE ROH 2021",
    "numVisa": 2021001414,
    "posterUrl": "http://example.com/images/2021001414.jpg",
    "thumbUrl": "http://example.com/img/thumb/film/2021001414.jpg",
    "duration": 100,
    "isHfr": False,
    "isHearingImpaired": False,
    "hasAudioDescription": False,
    "is4K": False,
    "idFilmAllocine": 296664,
    "isLightVibes": False,
    "isEclairColor": False,
}
SHOWTIME_36683 = {
    "id": 36683,
    "showDate": "2022-11-28T09:00:00+01:00",
    "showEndDate": "2022-11-28T11:52:00+01:00",
    "soldOut": False,
    "authorizedAccess": False,
    "vfstfr": False,
    "preview": False,
    "numberSeatsRemaining": 136,
    "numberRemainingSeatsForOnlineSale": 96,
    "film": FILM_207,
    "format": {"id": 1, "title": "2D"},
    "version": {"id": 3, "title": "Film Etranger en Langue Française", "code": "VF"},
    "screen": {
        "id": 1,
        "auditoriumNumber": 1,
        "name": "SALLE CINEMAX",
        "capacity": 136,
        "HFR": False,
        "is4K": False,
        "ice": True,
        "lightVibes": False,
        "eclairColor": False,
        "hearingImpaired": False,
        "audioDescription": False,
        "seatingAllowed": False,
    },
}
SHOWTIME_36848 = {
    "id": 36848,
    "showDate": "2022-11-28T09:00:00+01:00",
    "showEndDate": "2022-11-28T10:42:00+01:00",
    "soldOut": False,
    "authorizedAccess": False,
    "vfstfr": False,
    "preview": False,
    "numberSeatsRemaining": 177,
    "numberRemainingSeatsForOnlineSale": 177,
    "film": FILM_210,
    "format": {"id": 1, "title": "2D"},
    "version": {"id": 1, "title": "Film Français", "code": "VF"},
    "screen": {
        "id": 5,
        "auditoriumNumber": 5,
        "name": "SALLE 05",
        "capacity": 177,
        "HFR": False,
        "is4K": False,
        "ice": False,
        "lightVibes": False,
        "eclairColor": False,
        "hearingImpaired": False,
        "audioDescription": False,
        "seatingAllowed": True,
    },
}
SHOWTIME_36932 = {
    "id": 36932,
    "showDate": "2022-11-28T13:05:00+01:00",
    "showEndDate": "2022-11-28T14:55:00+01:00",
    "soldOut": False,
    "authorizedAccess": False,
    "vfstfr": False,
    "preview": False,
    "numberSeatsRemaining": 174,
    "numberRemainingSeatsForOnlineSale": 122,
    "film": {
        "id": 147,
        "titleCnc": "CASSE NOISETTE ROH 2021",
        "numVisa": 2021001414,
        "posterUrl": "http://example.com/images/2021001414.jpg",
        "thumbUrl": "http://example.com/img/thumb/film/2021001414.jpg",
        "duration": 100,
        "isHfr": False,
        "isHearingImpaired": False,
        "hasAudioDescription": False,
        "is4K": False,
        "idFilmAllocine": 296664,
        "isLightVibes": False,
        "isEclairColor": False,
    },
    "format": {"id": 1, "title": "2D"},
    "version": {"id": 3, "title": "Film Etranger en Langue Française", "code": "VF"},
    "screen": {
        "id": 6,
        "auditoriumNumber": 6,
        "name": "SALLE 06",
        "capacity": 174,
        "HFR": False,
        "is4K": False,
        "ice": False,
        "lightVibes": False,
        "eclairColor": False,
        "hearingImpaired": False,
        "audioDescription": False,
        "seatingAllowed": True,
    },
}


class ShowtimesEndpointResponse:
    PAGE_1_JSON_DATA = {
        "data": [SHOWTIME_36683, SHOWTIME_36848],
        "message": "OK",
        "page": 1,
        "previousPage": 1,
        "nextPage": 2,
        "totalPages": 19,
        "totalCount": 38,
    }
    PAGE_2_JSON_DATA = {
        "data": [SHOWTIME_36932],
        "message": "OK",
        "page": 2,
        "previousPage": 1,
        "nextPage": 2,
        "totalPages": 2,
        "totalCount": 3,
    }
    NO_PC_PRICING_JSON_DATA = {
        "data": [SHOWTIME_36932],
        "message": "OK",
        "page": 1,
        "previousPage": 1,
        "nextPage": 1,
        "totalPages": 1,
        "totalCount": 1,
    }
    ONE_FILM_PAGE_1_JSON_DATA = {
        "data": [SHOWTIME_36683],
        "message": "OK",
        "page": 1,
        "previousPage": 1,
        "nextPage": 1,
        "totalPages": 1,
        "totalCount": 1,
    }


class ShowtimeDetailsEndpointResponse:
    SHOWTIME_36683_DATA = {
        "message": "OK",
        "data": {
            "id": 36683,
            "idSeatingConfiguration": 0,
            "idProjectionLocation": 0,
            "showDate": "2022-11-28T09:00:00+01:00",
            "showEndDate": "2022-11-28T11:52:00+01:00",
            "dateCNC": "2022-11-28",
            "earlyInterruptionTime": "00:00:00",
            "interruptionReason": None,
            "preSelling": True,
            "inDisplayPanel": True,
            "soldOut": False,
            "hidden": False,
            "schoolPricingPermitted": False,
            "hasIntermission": False,
            "priorityTitle": False,
            "authorizedAccess": False,
            "withoutAdditionalRate": True,
            "withoutSeating": False,
            "vfstfr": False,
            "preview": False,
            "draftMode": False,
            "durationFirstPart": 10,
            "numberSeatsRemaining": 136,
            "numberSeatsForOnlineSale": 96,
            "numberSeatsBlocked": 0,
            "numberRemainingSeatsForOnlineSale": 96,
            "numberSeatsSold": 0,
            "cinema": {
                "id": 5,
                "name": "Toulousain Showroom",
                "alloCineId": "G01G8",
                "numberScreens": 9,
                "userLastModification": "boost",
                "lastModification": "2022-11-22T09:28:11+01:00",
            },
            "event": {
                "id": 3345,
                "dateFrom": "2022-11-23T00:00:00+01:00",
                "dateTo": "2022-11-29T00:00:00+01:00",
                "distributorPercentage": 50,
                "eventType": 0,
                "planPrice": 0,
                "complements": [],
                "deletable": True,
                "editable": True,
                "userLastModification": "boost",
                "lastModification": None,
                "numCinema": 5,
            },
            "film": {
                "id": 207,
                "titleCnc": "BLACK PANTHER : WAKANDA FOREVER",
                "numVisa": 158026,
                "duration": 162,
                "type": {
                    "id": 1,
                    "title": "CNC",
                    "numCinema": 5,
                    "userLastModification": "CINESYSTEM",
                    "lastModification": None,
                },
                "isHfr": False,
                "isHearingImpaired": False,
                "hasAudioDescription": False,
                "is4K": False,
                "displayColor": "814BAF",
                "idFilmAllocine": 263242,
                "isLightVibes": False,
                "isEclairColor": False,
                "posterUrl": "http://example.com/images/158026.jpg",
                "thumbUrl": "http://example.com/img/thumb/film/158026.jpg",
                "numCinema": 5,
                "userLastModification": "boost",
                "lastModification": "2022-11-10T11:31:13+01:00",
            },
            "format": {"id": 1, "title": "2D"},
            "version": {"id": 3, "title": "Film Etranger en Langue Française", "code": "VF"},
            "screen": {
                "id": 1,
                "auditoriumNumber": 1,
                "name": "SALLE CINEMAX",
                "capacity": 136,
                "is4K": False,
                "ice": True,
                "lightVibes": False,
                "eclairColor": False,
                "hearingImpaired": False,
                "audioDescription": False,
                "seatingAllowed": False,
                "cinema": {
                    "id": 5,
                    "name": "Toulousain Showroom",
                    "alloCineId": "G01G8",
                    "numberScreens": 9,
                    "userLastModification": "boost",
                    "lastModification": "2022-11-22T09:28:11+01:00",
                },
                "userLastModification": "boost",
                "lastModification": "2022-10-05T13:59:01+02:00",
                "HFR": False,
            },
            "showtimePricing": [
                {
                    "id": 1114163,
                    "title": "PASS CULTURE",
                    "amountTaxesIncluded": 6,
                    "idSequencePresale": 0,
                    "idSequenceImmediate": 0,
                    "idConcessionCountermark": 0,
                    "includedLeaseAmount": 0,
                    "idPricingCategory": 4,
                    "saleCountermarks": [],
                    "onlineSale": False,
                    "cashierSelling": True,
                    "kioskSelling": True,
                    "pricingCode": "PCU",
                    "displayPosX": 0,
                    "displayPosY": 0,
                    "editable": True,
                    "deletable": True,
                    "numCinema": 5,
                    "lastModification": "2022-11-23T09:48:55+01:00",
                    "userLastModification": "boost",
                    "displayColor": "",
                    "idPrimaryPrice": 62,
                    "typePayment": "external:credit:passculture",
                    "typeCards": [],
                }
            ],
            "onlineSale": True,
            "cashierSelling": True,
            "kioskSelling": True,
            "deletable": True,
            "editable": True,
            "numCinema": 5,
            "lastModification": "2022-11-23T09:48:54+01:00",
            "userLastModification": "boost",
        },
    }
    SHOWTIME_36848_DATA = {
        "message": "OK",
        "data": {
            "id": 36848,
            "idSeatingConfiguration": 0,
            "idProjectionLocation": 0,
            "showDate": "2022-11-28T09:00:00+01:00",
            "showEndDate": "2022-11-28T10:42:00+01:00",
            "dateCNC": "2022-11-28",
            "earlyInterruptionTime": "00:00:00",
            "interruptionReason": None,
            "preSelling": True,
            "inDisplayPanel": True,
            "soldOut": False,
            "hidden": False,
            "schoolPricingPermitted": False,
            "hasIntermission": False,
            "priorityTitle": False,
            "authorizedAccess": False,
            "withoutAdditionalRate": False,
            "withoutSeating": False,
            "vfstfr": False,
            "preview": False,
            "draftMode": False,
            "durationFirstPart": 10,
            "numberSeatsRemaining": 177,
            "numberSeatsForOnlineSale": 177,
            "numberSeatsBlocked": 0,
            "numberRemainingSeatsForOnlineSale": 177,
            "numberSeatsSold": 0,
            "cinema": {
                "id": 5,
                "name": "Toulousain Showroom",
                "alloCineId": "G01G8",
                "numberScreens": 9,
                "userLastModification": "boost",
                "lastModification": "2022-11-22T09:28:11+01:00",
            },
            "event": {
                "id": 3349,
                "dateFrom": "2022-11-23T00:00:00+01:00",
                "dateTo": "2022-11-29T00:00:00+01:00",
                "distributorPercentage": 50,
                "eventType": 0,
                "planPrice": 0,
                "complements": [
                    {
                        "id": 2009,
                        "title": "VIP",
                        "amountTaxesIncluded": 3,
                        "isIncludedCNC": False,
                        "isFreeForShowtimeWithFreeAdmission": True,
                        "excludedByPricing": [{"idPrimaryPrice": 62}],
                        "displayPosX": 4,
                        "displayPosY": 2,
                        "numCinema": 5,
                        "lastModification": None,
                        "userLastModification": "boost",
                        "displayColor": "",
                        "required": True,
                    }
                ],
                "deletable": True,
                "editable": True,
                "userLastModification": "boost",
                "lastModification": None,
                "numCinema": 5,
            },
            "film": {
                "id": 210,
                "titleCnc": "CHARLOTTE",
                "numVisa": 149489,
                "duration": 92,
                "type": {
                    "id": 1,
                    "title": "CNC",
                    "numCinema": 5,
                    "userLastModification": "CINESYSTEM",
                    "lastModification": None,
                },
                "isHfr": False,
                "isHearingImpaired": False,
                "hasAudioDescription": False,
                "is4K": False,
                "displayColor": "A52669",
                "idFilmAllocine": 277733,
                "isLightVibes": False,
                "isEclairColor": False,
                "posterUrl": "http://example.com/images/149489.jpg",
                "thumbUrl": "http://example.com/img/thumb/film/149489.jpg",
                "numCinema": 5,
                "userLastModification": "boost",
                "lastModification": "2022-11-21T13:25:28+01:00",
            },
            "format": {"id": 1, "title": "2D"},
            "version": {"id": 1, "title": "Film Français", "code": "VF"},
            "screen": {
                "id": 5,
                "auditoriumNumber": 5,
                "name": "SALLE 05",
                "capacity": 177,
                "is4K": False,
                "ice": False,
                "lightVibes": False,
                "eclairColor": False,
                "hearingImpaired": False,
                "audioDescription": False,
                "seatingAllowed": True,
                "cinema": {
                    "id": 5,
                    "name": "Toulousain Showroom",
                    "alloCineId": "G01G8",
                    "numberScreens": 9,
                    "userLastModification": "boost",
                    "lastModification": "2022-11-22T09:28:11+01:00",
                },
                "userLastModification": "boost",
                "lastModification": "2022-08-03T15:52:24+02:00",
                "HFR": False,
            },
            "showtimePricing": [
                {
                    "id": 1117628,
                    "title": "PASS CULTURE",
                    "amountTaxesIncluded": 6,
                    "idSequencePresale": 0,
                    "idSequenceImmediate": 0,
                    "idConcessionCountermark": 0,
                    "includedLeaseAmount": 0,
                    "idPricingCategory": 4,
                    "saleCountermarks": [],
                    "onlineSale": False,
                    "cashierSelling": True,
                    "kioskSelling": True,
                    "pricingCode": "PCU",
                    "displayPosX": 0,
                    "displayPosY": 0,
                    "editable": True,
                    "deletable": True,
                    "numCinema": 5,
                    "lastModification": "2022-11-23T09:49:21+01:00",
                    "userLastModification": "boost",
                    "displayColor": "",
                    "idPrimaryPrice": 62,
                    "typePayment": "external:credit:passculture",
                    "typeCards": [],
                }
            ],
            "onlineSale": True,
            "cashierSelling": True,
            "kioskSelling": True,
            "deletable": True,
            "editable": True,
            "numCinema": 5,
            "lastModification": "2022-11-23T09:49:21+01:00",
            "userLastModification": "boost",
        },
    }
    SHOWTIME_36932_DATA_NO_PC_PRICING = {
        "message": "OK",
        "data": {
            "id": 36932,
            "idSeatingConfiguration": 0,
            "idProjectionLocation": 0,
            "showDate": "2022-11-28T13:05:00+01:00",
            "showEndDate": "2022-11-28T14:55:00+01:00",
            "dateCNC": "2022-11-28",
            "earlyInterruptionTime": "00:00:00",
            "interruptionReason": None,
            "preSelling": True,
            "inDisplayPanel": True,
            "soldOut": False,
            "hidden": False,
            "schoolPricingPermitted": False,
            "hasIntermission": False,
            "priorityTitle": False,
            "authorizedAccess": False,
            "withoutAdditionalRate": False,
            "withoutSeating": False,
            "vfstfr": False,
            "preview": False,
            "draftMode": False,
            "durationFirstPart": 10,
            "numberSeatsRemaining": 174,
            "numberSeatsForOnlineSale": 122,
            "numberSeatsBlocked": 0,
            "numberRemainingSeatsForOnlineSale": 122,
            "numberSeatsSold": 0,
            "cinema": {
                "id": 5,
                "name": "Toulousain Showroom",
                "alloCineId": "G01G8",
                "numberScreens": 9,
                "userLastModification": "boost",
                "lastModification": "2022-11-22T09:28:11+01:00",
            },
            "event": {
                "id": 3350,
                "dateFrom": "2022-11-23T00:00:00+01:00",
                "dateTo": "2022-11-29T00:00:00+01:00",
                "distributorPercentage": 50,
                "eventType": 0,
                "planPrice": 0,
                "complements": [],
                "deletable": True,
                "editable": True,
                "userLastModification": "boost",
                "lastModification": None,
                "numCinema": 5,
            },
            "film": FILM_147,
            "format": {"id": 1, "title": "2D"},
            "version": {"id": 3, "title": "Film Etranger en Langue Française", "code": "VF"},
            "screen": {
                "id": 6,
                "auditoriumNumber": 6,
                "name": "SALLE 06",
                "capacity": 174,
                "is4K": False,
                "ice": False,
                "lightVibes": False,
                "eclairColor": False,
                "hearingImpaired": False,
                "audioDescription": False,
                "seatingAllowed": True,
                "cinema": {
                    "id": 5,
                    "name": "Toulousain Showroom",
                    "alloCineId": "G01G8",
                    "numberScreens": 9,
                    "userLastModification": "boost",
                    "lastModification": "2022-11-22T09:28:11+01:00",
                },
                "userLastModification": "Boost",
                "lastModification": "2021-01-06T10:21:40+01:00",
                "HFR": False,
            },
            "showtimePricing": [],
            "onlineSale": True,
            "cashierSelling": True,
            "kioskSelling": True,
            "deletable": True,
            "editable": True,
            "numCinema": 5,
            "lastModification": "2022-11-23T09:49:32+01:00",
            "userLastModification": "boost",
        },
    }


class FilmsEndpointResponse:
    PAGE_1_JSON_DATA = {
        "data": [FILM_207, FILM_210],
        "message": "OK",
        "page": 1,
        "previousPage": 1,
        "nextPage": 2,
        "totalPages": 2,
        "totalCount": 3,
    }
    PAGE_2_JSON_DATA = {
        "data": [FILM_147],
        "message": "OK",
        "page": 2,
        "previousPage": 1,
        "nextPage": 2,
        "totalPages": 2,
        "totalCount": 3,
    }


class ConfirmedSaleEndpointResponse:
    DATA = {
        "code": 201,
        "message": "Confirmed sale",
        "data": {
            "id": 90474,
            "code": "sale-90474",
            "saleBarcode": None,
            "candystoreSaleBarcode": None,
            "type": "PAX",
            "date": "2022-11-27T16:35:08+01:00",
            "amountTaxesIncluded": 12,
            "giveBackChange": 0,
            "items": [
                {
                    "id": 191460,
                    "type": "ENT",
                    "order": 1,
                    "pricingCode": None,
                    "pricingTitle": None,
                    "idTicket": 164514,
                    "isCancelled": False,
                    "isControlled": False,
                    "isControlRequired": False,
                    "saleDate": "2022-11-27T16:35:08+01:00",
                    "amountPerUnit": 6,
                    "quantityCancelled": 0,
                    "quantityOnlineControlled": 0,
                    "seat": None,
                    "idSale": None,
                    "barcode": "0",
                },
                {
                    "id": 191461,
                    "type": "ENT",
                    "order": 2,
                    "pricingCode": None,
                    "pricingTitle": None,
                    "idTicket": 164515,
                    "isCancelled": False,
                    "isControlled": False,
                    "isControlRequired": False,
                    "saleDate": "2022-11-27T16:35:08+01:00",
                    "amountPerUnit": 6,
                    "quantityCancelled": 0,
                    "quantityOnlineControlled": 0,
                    "seat": None,
                    "idSale": None,
                    "barcode": "0",
                },
            ],
            "tickets": [
                {
                    "id": 164514,
                    "idCnc": 7174057,
                    "ticketReference": "PCU-000001-7174057",
                    "pricingCode": "PCU",
                    "idSaleCountermark": 0,
                    "amount": 6,
                    "idSale": 90474,
                    "seat": None,
                    "numCinema": 5,
                    "isCancelled": False,
                    "isControlled": False,
                    "isCNC": True,
                    "isFid": False,
                    "authorizedAccess": False,
                    "pricingTitle": "PASS CULTURE",
                    "isControlRequired": False,
                    "withdrawType": "PAX Mobile",
                    "showtimeInfo": {
                        "idShowtime": 36683,
                        "auditoriumNumber": 1,
                        "filmTitle": "BLACK PANTHER : WAKANDA FOREVER",
                        "filmVersion": "VF",
                        "filmFormat": "2D",
                        "filmPoster": "http://example.com/images/158026.jpg",
                        "filmPosterThumb": "http://example.com/img/thumb/film/158026.jpg",
                        "showStartDateTime": "2022-11-28T09:00:00+01:00",
                        "showEndDateTime": "2022-11-28T11:52:00+01:00",
                        "isAuthorizedAccess": False,
                    },
                    "saleTicketWithCard": False,
                    "complementsCncMandatory": [
                        {
                            "id": 164514,
                            "idComplement": 2006,
                            "title": "Cinemax",
                            "quantity": 1,
                            "quantityOnlineControlled": 0,
                            "quantityCancelled": 0,
                            "isControlRequired": True,
                            "isCnc": True,
                            "amountPerUnit": 2,
                            "complementIsRefundable": False,
                        }
                    ],
                    "complementsNoCncMandatory": [],
                },
                {
                    "id": 164515,
                    "idCnc": 7174058,
                    "ticketReference": "PCU-000002-7174058",
                    "pricingCode": "PCU",
                    "idSaleCountermark": 0,
                    "amount": 6,
                    "idSale": 90474,
                    "seat": None,
                    "numCinema": 5,
                    "isCancelled": False,
                    "isControlled": False,
                    "isCNC": True,
                    "isFid": False,
                    "authorizedAccess": False,
                    "pricingTitle": "PASS CULTURE",
                    "isControlRequired": False,
                    "withdrawType": "PAX Mobile",
                    "showtimeInfo": {
                        "idShowtime": 36683,
                        "auditoriumNumber": 1,
                        "filmTitle": "BLACK PANTHER : WAKANDA FOREVER",
                        "filmVersion": "VF",
                        "filmFormat": "2D",
                        "filmPoster": "http://example.com/images/158026.jpg",
                        "filmPosterThumb": "http://example.com/img/thumb/film/158026.jpg",
                        "showStartDateTime": "2022-11-28T09:00:00+01:00",
                        "showEndDateTime": "2022-11-28T11:52:00+01:00",
                        "isAuthorizedAccess": False,
                    },
                    "saleTicketWithCard": False,
                    "complementsCncMandatory": [
                        {
                            "id": 164515,
                            "idComplement": 2006,
                            "title": "Cinemax",
                            "quantity": 1,
                            "quantityOnlineControlled": 0,
                            "quantityCancelled": 0,
                            "isControlRequired": True,
                            "isCnc": True,
                            "amountPerUnit": 2,
                            "complementIsRefundable": False,
                        }
                    ],
                    "complementsNoCncMandatory": [],
                },
            ],
            "complements": [],
        },
    }
