FILM_207 = {
    "id": 207,
    "titleCnc": "BLACK PANTHER : WAKANDA FOREVER",
    "numVisa": 158026,
    "posterUrl": "http://example.com/images/158026.jpg",
    "thumbUrl": "http://example.com/img/thumb/film/158026.jpg",
    "duration": 162,
    "isHfr": False,
    "isHearingImpaired": False,
    "hasAudioDescription": False,
    "is4K": False,
    "idFilmAllocine": 263242,
    "isLightVibes": False,
    "isEclairColor": False,
}
FILM_210 = {
    "id": 210,
    "titleCnc": "CHARLOTTE",
    "numVisa": 149489,
    "posterUrl": "http://example.com/images/149489.jpg",
    "thumbUrl": "http://example.com/img/thumb/film/149489.jpg",
    "duration": 92,
    "isHfr": False,
    "isHearingImpaired": False,
    "hasAudioDescription": False,
    "is4K": False,
    "idFilmAllocine": 277733,
    "isLightVibes": False,
    "isEclairColor": False,
}
FILM_147 = {
    "id": 147,
    "titleCnc": "CASSE NOISETTE ROH 2021",
    "numVisa": 2021001414,
    "posterUrl": "http://example.com/images/2021001414.jpg",
    "thumbUrl": "http://example.com/img/thumb/film/2021001414.jpg",
    "duration": 100,
    "isHfr": False,
    "isHearingImpaired": False,
    "hasAudioDescription": False,
    "is4K": False,
    "idFilmAllocine": 296664,
    "isLightVibes": False,
    "isEclairColor": False,
}
SHOWTIME_36683 = {
    "id": 36683,
    "showDate": "2022-11-28T09:00:00+01:00",
    "showEndDate": "2022-11-28T11:52:00+01:00",
    "soldOut": False,
    "authorizedAccess": False,
    "vfstfr": False,
    "preview": False,
    "numberSeatsRemaining": 96,
    "numberRemainingSeatsForOnlineSale": 96,
    "film": FILM_207,
    "format": {"id": 1, "title": "2D"},
    "version": {"id": 3, "title": "Film Etranger en Langue Française", "code": "VF"},
    "screen": {
        "id": 1,
        "auditoriumNumber": 1,
        "name": "SALLE CINEMAX",
        "capacity": 136,
        "HFR": False,
        "is4K": False,
        "ice": True,
        "lightVibes": False,
        "eclairColor": False,
        "hearingImpaired": False,
        "audioDescription": False,
        "seatingAllowed": False,
    },
}
SHOWTIME_36684 = {
    "id": 36684,
    "showDate": "2022-11-29T09:00:00+01:00",
    "showEndDate": "2022-11-29T11:52:00+01:00",
    "soldOut": False,
    "authorizedAccess": False,
    "vfstfr": False,
    "preview": False,
    "numberSeatsRemaining": 0,
    "numberRemainingSeatsForOnlineSale": 0,
    "film": FILM_207,
    "format": {"id": 1, "title": "2D"},
    "version": {"id": 3, "title": "Film Etranger en Langue Française", "code": "VF"},
    "screen": {
        "id": 1,
        "auditoriumNumber": 1,
        "name": "SALLE CINEMAX",
        "capacity": 136,
        "HFR": False,
        "is4K": False,
        "ice": True,
        "lightVibes": False,
        "eclairColor": False,
        "hearingImpaired": False,
        "audioDescription": False,
        "seatingAllowed": False,
    },
}
SHOWTIME_36685 = {
    "id": 36685,
    "showDate": "2022-11-30T09:00:00+01:00",
    "showEndDate": "2022-11-30T11:52:00+01:00",
    "soldOut": False,
    "authorizedAccess": False,
    "vfstfr": False,
    "preview": False,
    "numberSeatsRemaining": 12,
    "numberRemainingSeatsForOnlineSale": 12,
    "film": FILM_207,
    "format": {"id": 1, "title": "2D"},
    "version": {"id": 3, "title": "Film Etranger en Langue Française", "code": "VF"},
    "screen": {
        "id": 1,
        "auditoriumNumber": 1,
        "name": "SALLE CINEMAX",
        "capacity": 136,
        "HFR": False,
        "is4K": False,
        "ice": True,
        "lightVibes": False,
        "eclairColor": False,
        "hearingImpaired": False,
        "audioDescription": False,
        "seatingAllowed": False,
    },
}
SHOWTIME_36848 = {
    "id": 36848,
    "showDate": "2022-11-28T09:00:00+01:00",
    "showEndDate": "2022-11-28T10:42:00+01:00",
    "soldOut": False,
    "authorizedAccess": False,
    "vfstfr": False,
    "preview": False,
    "numberSeatsRemaining": 177,
    "numberRemainingSeatsForOnlineSale": 177,
    "film": FILM_210,
    "format": {"id": 1, "title": "2D"},
    "version": {"id": 1, "title": "Film Français", "code": "VF"},
    "screen": {
        "id": 5,
        "auditoriumNumber": 5,
        "name": "SALLE 05",
        "capacity": 177,
        "HFR": False,
        "is4K": False,
        "ice": False,
        "lightVibes": False,
        "eclairColor": False,
        "hearingImpaired": False,
        "audioDescription": False,
        "seatingAllowed": True,
    },
}
SHOWTIME_36932 = {
    "id": 36932,
    "showDate": "2022-11-28T13:05:00+01:00",
    "showEndDate": "2022-11-28T14:55:00+01:00",
    "soldOut": False,
    "authorizedAccess": False,
    "vfstfr": False,
    "preview": False,
    "numberSeatsRemaining": 122,
    "numberRemainingSeatsForOnlineSale": 122,
    "film": {
        "id": 147,
        "titleCnc": "CASSE NOISETTE ROH 2021",
        "numVisa": 2021001414,
        "posterUrl": "http://example.com/images/2021001414.jpg",
        "thumbUrl": "http://example.com/img/thumb/film/2021001414.jpg",
        "duration": 100,
        "isHfr": False,
        "isHearingImpaired": False,
        "hasAudioDescription": False,
        "is4K": False,
        "idFilmAllocine": 296664,
        "isLightVibes": False,
        "isEclairColor": False,
    },
    "format": {"id": 1, "title": "2D"},
    "version": {"id": 3, "title": "Film Etranger en Langue Française", "code": "VF"},
    "screen": {
        "id": 6,
        "auditoriumNumber": 6,
        "name": "SALLE 06",
        "capacity": 174,
        "HFR": False,
        "is4K": False,
        "ice": False,
        "lightVibes": False,
        "eclairColor": False,
        "hearingImpaired": False,
        "audioDescription": False,
        "seatingAllowed": True,
    },
}


class ShowtimesWithFilmIdEndpointResponse:
    PAGE_1_JSON_DATA = {
        "data": [SHOWTIME_36683, SHOWTIME_36684],
        "message": "OK",
        "page": 1,
        "previousPage": 1,
        "nextPage": 1,
        "totalPages": 1,
        "totalCount": 2,
    }
    PAGE_1_JSON_DATA_3_SHOWTIMES = {
        "data": [SHOWTIME_36683, SHOWTIME_36684, SHOWTIME_36685],
        "message": "OK",
        "page": 1,
        "previousPage": 1,
        "nextPage": 1,
        "totalPages": 1,
        "totalCount": 3,
    }


class ShowtimesEndpointResponse:
    PAGE_1_JSON_DATA = {
        "data": [SHOWTIME_36683, SHOWTIME_36848],
        "message": "OK",
        "page": 1,
        "previousPage": 1,
        "nextPage": 2,
        "totalPages": 19,
        "totalCount": 38,
    }
    PAGE_2_JSON_DATA = {
        "data": [SHOWTIME_36932],
        "message": "OK",
        "page": 2,
        "previousPage": 1,
        "nextPage": 2,
        "totalPages": 2,
        "totalCount": 3,
    }
    NO_PC_PRICING_JSON_DATA = {
        "data": [SHOWTIME_36932],
        "message": "OK",
        "page": 1,
        "previousPage": 1,
        "nextPage": 1,
        "totalPages": 1,
        "totalCount": 1,
    }
    ONE_FILM_PAGE_1_JSON_DATA = {
        "data": [SHOWTIME_36683],
        "message": "OK",
        "page": 1,
        "previousPage": 1,
        "nextPage": 1,
        "totalPages": 1,
        "totalCount": 1,
    }
    SAME_FILM_TWICE_JSON_DATA = {
        "data": [SHOWTIME_36683, SHOWTIME_36684],
        "message": "OK",
        "page": 1,
        "previousPage": 1,
        "nextPage": 1,
        "totalPages": 1,
        "totalCount": 1,
    }


class ShowtimeDetailsEndpointResponse:
    PCU_PRICING = {
        "id": 1117628,
        "title": "PASS CULTURE",
        "amountTaxesIncluded": 6.9,
        "idSequencePresale": 0,
        "idSequenceImmediate": 0,
        "idConcessionCountermark": 0,
        "includedLeaseAmount": 0,
        "idPricingCategory": 4,
        "saleCountermarks": [],
        "onlineSale": False,
        "cashierSelling": True,
        "kioskSelling": True,
        "pricingCode": "PCU",
        "displayPosX": 0,
        "displayPosY": 0,
        "editable": True,
        "deletable": True,
        "numCinema": 5,
        "lastModification": "2022-11-23T09:49:21+01:00",
        "userLastModification": "boost",
        "displayColor": "",
        "idPrimaryPrice": 62,
        "typePayment": "external:credit:passculture",
        "typeCards": [],
    }
    PC2_PRICING = {
        "id": 1114163,
        "title": "PASS CULTURE 1",
        "amountTaxesIncluded": 18,
        "idSequencePresale": 0,
        "idSequenceImmediate": 0,
        "idConcessionCountermark": 0,
        "includedLeaseAmount": 0,
        "idPricingCategory": 4,
        "saleCountermarks": [],
        "onlineSale": False,
        "cashierSelling": True,
        "kioskSelling": True,
        "pricingCode": "PC2",
        "displayPosX": 0,
        "displayPosY": 0,
        "editable": True,
        "deletable": True,
        "numCinema": 5,
        "lastModification": "2022-11-23T09:48:55+01:00",
        "userLastModification": "boost",
        "displayColor": "",
        "idPrimaryPrice": 63,
        "typePayment": "external:credit:passculture",
        "typeCards": [],
    }
    FULL_PRICING = {
        "id": 1225351,
        "title": "PLEIN TARIF",
        "amountTaxesIncluded": 12,
        "idSequencePresale": 0,
        "idSequenceImmediate": 0,
        "idConcessionCountermark": 0,
        "includedLeaseAmount": 0,
        "idPricingCategory": 4,
        "saleCountermarks": [
            {
                "id": 8,
                "title": "CM prix a payer",
                "amount": 3,
                "expiration": None,
                "color": "9B3838",
                "active": True,
                "lastModification": None,
                "userLastModification": "boost",
                "type": "Price",
            },
            {
                "id": 13,
                "title": "Cm reduction sur ple",
                "amount": 5,
                "expiration": "2024-03-31T00:00:00+01:00",
                "color": "0033CC",
                "active": True,
                "lastModification": None,
                "userLastModification": "boost",
                "type": "Discount",
            },
        ],
        "onlineSale": True,
        "cashierSelling": True,
        "kioskSelling": True,
        "pricingCode": "PLE",
        "displayPosX": 1,
        "displayPosY": 1,
        "editable": True,
        "deletable": True,
        "numCinema": 5,
        "lastModification": "2023-01-20T11:36:43+01:00",
        "userLastModification": "boost",
        "displayColor": "27C827",
        "idPrimaryPrice": 1,
        "typePayment": "cash_or_credit_card",
        "typeCards": [],
        "hidden": False,
    }

    THREE_PRICINGS_SHOWTIME_36683_DATA = {
        "message": "OK",
        "data": {
            "id": 36683,
            "idSeatingConfiguration": 0,
            "idProjectionLocation": 0,
            "showDate": "2022-11-28T09:00:00+01:00",
            "showEndDate": "2022-11-28T11:52:00+01:00",
            "dateCNC": "2022-11-28",
            "earlyInterruptionTime": "00:00:00",
            "interruptionReason": None,
            "preSelling": True,
            "inDisplayPanel": True,
            "soldOut": False,
            "hidden": False,
            "schoolPricingPermitted": False,
            "hasIntermission": False,
            "priorityTitle": False,
            "authorizedAccess": False,
            "withoutAdditionalRate": True,
            "withoutSeating": False,
            "vfstfr": False,
            "preview": False,
            "draftMode": False,
            "durationFirstPart": 10,
            "numberSeatsRemaining": 96,
            "numberSeatsForOnlineSale": 96,
            "numberSeatsBlocked": 0,
            "numberRemainingSeatsForOnlineSale": 96,
            "numberSeatsSold": 0,
            "cinema": {
                "id": 5,
                "name": "Toulousain Showroom",
                "alloCineId": "G01G8",
                "numberScreens": 9,
                "userLastModification": "boost",
                "lastModification": "2022-11-22T09:28:11+01:00",
            },
            "event": {
                "id": 3345,
                "dateFrom": "2022-11-23T00:00:00+01:00",
                "dateTo": "2022-11-29T00:00:00+01:00",
                "distributorPercentage": 50,
                "eventType": 0,
                "planPrice": 0,
                "complements": [],
                "deletable": True,
                "editable": True,
                "userLastModification": "boost",
                "lastModification": None,
                "numCinema": 5,
            },
            "film": {
                "id": 207,
                "titleCnc": "BLACK PANTHER : WAKANDA FOREVER",
                "numVisa": 158026,
                "duration": 162,
                "type": {
                    "id": 1,
                    "title": "CNC",
                    "numCinema": 5,
                    "userLastModification": "CINESYSTEM",
                    "lastModification": None,
                },
                "isHfr": False,
                "isHearingImpaired": False,
                "hasAudioDescription": False,
                "is4K": False,
                "displayColor": "814BAF",
                "idFilmAllocine": 263242,
                "isLightVibes": False,
                "isEclairColor": False,
                "posterUrl": "http://example.com/images/158026.jpg",
                "thumbUrl": "http://example.com/img/thumb/film/158026.jpg",
                "numCinema": 5,
                "userLastModification": "boost",
                "lastModification": "2022-11-10T11:31:13+01:00",
            },
            "format": {"id": 1, "title": "2D"},
            "version": {"id": 3, "title": "Film Etranger en Langue Française", "code": "VF"},
            "screen": {
                "id": 1,
                "auditoriumNumber": 1,
                "name": "SALLE CINEMAX",
                "capacity": 136,
                "is4K": False,
                "ice": True,
                "lightVibes": False,
                "eclairColor": False,
                "hearingImpaired": False,
                "audioDescription": False,
                "seatingAllowed": False,
                "cinema": {
                    "id": 5,
                    "name": "Toulousain Showroom",
                    "alloCineId": "G01G8",
                    "numberScreens": 9,
                    "userLastModification": "boost",
                    "lastModification": "2022-11-22T09:28:11+01:00",
                },
                "userLastModification": "boost",
                "lastModification": "2022-10-05T13:59:01+02:00",
                "HFR": False,
            },
            "showtimePricing": [FULL_PRICING, PC2_PRICING, PCU_PRICING],
            "onlineSale": True,
            "cashierSelling": True,
            "kioskSelling": True,
            "deletable": True,
            "editable": True,
            "numCinema": 5,
            "lastModification": "2022-11-23T09:48:54+01:00",
            "userLastModification": "boost",
        },
    }
    SOLD_OUT_SHOWTIME_36683_DATA = {
        "message": "OK",
        "data": {
            "id": 36683,
            "idSeatingConfiguration": 0,
            "idProjectionLocation": 0,
            "showDate": "2022-11-28T09:00:00+01:00",
            "showEndDate": "2022-11-28T11:52:00+01:00",
            "dateCNC": "2022-11-28",
            "earlyInterruptionTime": "00:00:00",
            "interruptionReason": None,
            "preSelling": True,
            "inDisplayPanel": True,
            "soldOut": True,
            "hidden": False,
            "schoolPricingPermitted": False,
            "hasIntermission": False,
            "priorityTitle": False,
            "authorizedAccess": False,
            "withoutAdditionalRate": True,
            "withoutSeating": False,
            "vfstfr": False,
            "preview": False,
            "draftMode": False,
            "durationFirstPart": 10,
            "numberSeatsRemaining": 0,
            "numberSeatsForOnlineSale": 0,
            "numberSeatsBlocked": 0,
            "numberRemainingSeatsForOnlineSale": 0,
            "numberSeatsSold": 2,
            "cinema": {
                "id": 5,
                "name": "Toulousain Showroom",
                "alloCineId": "G01G8",
                "numberScreens": 9,
                "userLastModification": "boost",
                "lastModification": "2022-11-22T09:28:11+01:00",
            },
            "event": {
                "id": 3345,
                "dateFrom": "2022-11-23T00:00:00+01:00",
                "dateTo": "2022-11-29T00:00:00+01:00",
                "distributorPercentage": 50,
                "eventType": 0,
                "planPrice": 0,
                "complements": [],
                "deletable": True,
                "editable": True,
                "userLastModification": "boost",
                "lastModification": None,
                "numCinema": 5,
            },
            "film": {
                "id": 207,
                "titleCnc": "BLACK PANTHER : WAKANDA FOREVER",
                "numVisa": 158026,
                "duration": 162,
                "type": {
                    "id": 1,
                    "title": "CNC",
                    "numCinema": 5,
                    "userLastModification": "CINESYSTEM",
                    "lastModification": None,
                },
                "isHfr": False,
                "isHearingImpaired": False,
                "hasAudioDescription": False,
                "is4K": False,
                "displayColor": "814BAF",
                "idFilmAllocine": 263242,
                "isLightVibes": False,
                "isEclairColor": False,
                "posterUrl": "http://example.com/images/158026.jpg",
                "thumbUrl": "http://example.com/img/thumb/film/158026.jpg",
                "numCinema": 5,
                "userLastModification": "boost",
                "lastModification": "2022-11-10T11:31:13+01:00",
            },
            "format": {"id": 1, "title": "2D"},
            "version": {"id": 3, "title": "Film Etranger en Langue Française", "code": "VF"},
            "screen": {
                "id": 1,
                "auditoriumNumber": 1,
                "name": "SALLE CINEMAX",
                "capacity": 136,
                "is4K": False,
                "ice": True,
                "lightVibes": False,
                "eclairColor": False,
                "hearingImpaired": False,
                "audioDescription": False,
                "seatingAllowed": False,
                "cinema": {
                    "id": 5,
                    "name": "Toulousain Showroom",
                    "alloCineId": "G01G8",
                    "numberScreens": 9,
                    "userLastModification": "boost",
                    "lastModification": "2022-11-22T09:28:11+01:00",
                },
                "userLastModification": "boost",
                "lastModification": "2022-10-05T13:59:01+02:00",
                "HFR": False,
            },
            "showtimePricing": [PCU_PRICING],
            "onlineSale": True,
            "cashierSelling": True,
            "kioskSelling": True,
            "deletable": True,
            "editable": True,
            "numCinema": 5,
            "lastModification": "2022-11-23T09:48:54+01:00",
            "userLastModification": "boost",
        },
    }
    PC2_AND_FULL_PRICINGS_SHOWTIME_36684_DATA = {
        "message": "OK",
        "data": {
            "id": 36684,
            "idSeatingConfiguration": 0,
            "idProjectionLocation": 0,
            "showDate": "2022-11-29T09:00:00+01:00",
            "showEndDate": "2022-11-29T11:52:00+01:00",
            "dateCNC": "2022-11-29",
            "earlyInterruptionTime": "00:00:00",
            "interruptionReason": None,
            "preSelling": True,
            "inDisplayPanel": True,
            "soldOut": False,
            "hidden": False,
            "schoolPricingPermitted": False,
            "hasIntermission": False,
            "priorityTitle": False,
            "authorizedAccess": False,
            "withoutAdditionalRate": True,
            "withoutSeating": False,
            "vfstfr": False,
            "preview": False,
            "draftMode": False,
            "durationFirstPart": 10,
            "numberSeatsRemaining": 130,
            "numberSeatsForOnlineSale": 96,
            "numberSeatsBlocked": 0,
            "numberRemainingSeatsForOnlineSale": 96,
            "numberSeatsSold": 0,
            "cinema": {
                "id": 5,
                "name": "Toulousain Showroom",
                "alloCineId": "G01G8",
                "numberScreens": 10,
                "userLastModification": "boost",
                "lastModification": "2022-11-29T10:40:19+01:00",
            },
            "event": {
                "id": 3345,
                "dateFrom": "2022-11-23T00:00:00+01:00",
                "dateTo": "2022-11-29T00:00:00+01:00",
                "distributorPercentage": 50.0,
                "eventType": 1,
                "planPrice": 0.0,
                "complements": [
                    {
                        "id": 2352,
                        "title": "MAJORATION 3D",
                        "amountTaxesIncluded": 1.5,
                        "isIncludedCNC": True,
                        "isFreeForShowtimeWithFreeAdmission": False,
                        "excludedByPricing": [
                            {"idPrimaryPrice": 52},
                            {"idPrimaryPrice": 10},
                            {"idPrimaryPrice": 60},
                            {"idPrimaryPrice": 61},
                            {"idPrimaryPrice": 62},
                        ],
                        "displayPosX": 2,
                        "displayPosY": 3,
                        "numCinema": 5,
                        "lastModification": None,
                        "userLastModification": "boost",
                        "displayColor": "FFFFFF",
                        "required": True,
                    },
                    {
                        "id": 2353,
                        "title": "LUNETTES 3D",
                        "amountTaxesIncluded": 1.0,
                        "isIncludedCNC": False,
                        "isFreeForShowtimeWithFreeAdmission": False,
                        "excludedByPricing": [],
                        "displayPosX": 2,
                        "displayPosY": 3,
                        "numCinema": 5,
                        "lastModification": None,
                        "userLastModification": "boost",
                        "displayColor": "FF0000",
                        "required": False,
                    },
                ],
                "deletable": True,
                "editable": True,
                "userLastModification": "",
                "lastModification": None,
                "numCinema": 5,
            },
            "film": FILM_207,
            "format": {"id": 1, "title": "2D"},
            "version": {"id": 3, "title": "Film Etranger en Langue Française", "code": "VF"},
            "screen": {
                "id": 1,
                "auditoriumNumber": 1,
                "name": "GRAND REX",
                "capacity": 2700,
                "is4K": False,
                "ice": False,
                "lightVibes": False,
                "eclairColor": False,
                "hearingImpaired": False,
                "audioDescription": False,
                "seatingAllowed": True,
                "cinema": {
                    "id": 5,
                    "name": "Toulousain Showroom",
                    "alloCineId": "G01G8",
                    "numberScreens": 10,
                    "userLastModification": "boost",
                    "lastModification": "2022-11-29T10:40:19+01:00",
                },
                "userLastModification": "boost",
                "lastModification": "2023-02-01T17:33:20+01:00",
                "HFR": False,
            },
            "showtimePricing": [FULL_PRICING, PC2_PRICING],
            "onlineSale": True,
            "cashierSelling": True,
            "kioskSelling": True,
            "deletable": False,
            "editable": True,
            "numCinema": 5,
            "lastModification": "2022-11-23T09:48:55+01:00",
            "userLastModification": "boost",
        },
    }
    ONE_PCU_PRICING_SHOWTIME_36848_DATA = {
        "message": "OK",
        "data": {
            "id": 36848,
            "idSeatingConfiguration": 0,
            "idProjectionLocation": 0,
            "showDate": "2022-11-28T09:00:00+01:00",
            "showEndDate": "2022-11-28T10:42:00+01:00",
            "dateCNC": "2022-11-28",
            "earlyInterruptionTime": "00:00:00",
            "interruptionReason": None,
            "preSelling": True,
            "inDisplayPanel": True,
            "soldOut": False,
            "hidden": False,
            "schoolPricingPermitted": False,
            "hasIntermission": False,
            "priorityTitle": False,
            "authorizedAccess": False,
            "withoutAdditionalRate": False,
            "withoutSeating": False,
            "vfstfr": False,
            "preview": False,
            "draftMode": False,
            "durationFirstPart": 10,
            "numberSeatsRemaining": 177,
            "numberSeatsForOnlineSale": 177,
            "numberSeatsBlocked": 0,
            "numberRemainingSeatsForOnlineSale": 177,
            "numberSeatsSold": 0,
            "cinema": {
                "id": 5,
                "name": "Toulousain Showroom",
                "alloCineId": "G01G8",
                "numberScreens": 9,
                "userLastModification": "boost",
                "lastModification": "2022-11-22T09:28:11+01:00",
            },
            "event": {
                "id": 3349,
                "dateFrom": "2022-11-23T00:00:00+01:00",
                "dateTo": "2022-11-29T00:00:00+01:00",
                "distributorPercentage": 50,
                "eventType": 0,
                "planPrice": 0,
                "complements": [
                    {
                        "id": 2009,
                        "title": "VIP",
                        "amountTaxesIncluded": 3,
                        "isIncludedCNC": False,
                        "isFreeForShowtimeWithFreeAdmission": True,
                        "excludedByPricing": [{"idPrimaryPrice": 62}],
                        "displayPosX": 4,
                        "displayPosY": 2,
                        "numCinema": 5,
                        "lastModification": None,
                        "userLastModification": "boost",
                        "displayColor": "",
                        "required": True,
                    }
                ],
                "deletable": True,
                "editable": True,
                "userLastModification": "boost",
                "lastModification": None,
                "numCinema": 5,
            },
            "film": {
                "id": 210,
                "titleCnc": "CHARLOTTE",
                "numVisa": 149489,
                "duration": 92,
                "type": {
                    "id": 1,
                    "title": "CNC",
                    "numCinema": 5,
                    "userLastModification": "CINESYSTEM",
                    "lastModification": None,
                },
                "isHfr": False,
                "isHearingImpaired": False,
                "hasAudioDescription": False,
                "is4K": False,
                "displayColor": "A52669",
                "idFilmAllocine": 277733,
                "isLightVibes": False,
                "isEclairColor": False,
                "posterUrl": "http://example.com/images/149489.jpg",
                "thumbUrl": "http://example.com/img/thumb/film/149489.jpg",
                "numCinema": 5,
                "userLastModification": "boost",
                "lastModification": "2022-11-21T13:25:28+01:00",
            },
            "format": {"id": 1, "title": "2D"},
            "version": {"id": 1, "title": "Film Français", "code": "VF"},
            "screen": {
                "id": 5,
                "auditoriumNumber": 5,
                "name": "SALLE 05",
                "capacity": 177,
                "is4K": False,
                "ice": False,
                "lightVibes": False,
                "eclairColor": False,
                "hearingImpaired": False,
                "audioDescription": False,
                "seatingAllowed": True,
                "cinema": {
                    "id": 5,
                    "name": "Toulousain Showroom",
                    "alloCineId": "G01G8",
                    "numberScreens": 9,
                    "userLastModification": "boost",
                    "lastModification": "2022-11-22T09:28:11+01:00",
                },
                "userLastModification": "boost",
                "lastModification": "2022-08-03T15:52:24+02:00",
                "HFR": False,
            },
            "showtimePricing": [
                PCU_PRICING,
            ],
            "onlineSale": True,
            "cashierSelling": True,
            "kioskSelling": True,
            "deletable": True,
            "editable": True,
            "numCinema": 5,
            "lastModification": "2022-11-23T09:49:21+01:00",
            "userLastModification": "boost",
        },
    }
    SHOWTIME_36932_DATA_NO_PC_PRICING = {
        "message": "OK",
        "data": {
            "id": 36932,
            "idSeatingConfiguration": 0,
            "idProjectionLocation": 0,
            "showDate": "2022-11-28T13:05:00+01:00",
            "showEndDate": "2022-11-28T14:55:00+01:00",
            "dateCNC": "2022-11-28",
            "earlyInterruptionTime": "00:00:00",
            "interruptionReason": None,
            "preSelling": True,
            "inDisplayPanel": True,
            "soldOut": False,
            "hidden": False,
            "schoolPricingPermitted": False,
            "hasIntermission": False,
            "priorityTitle": False,
            "authorizedAccess": False,
            "withoutAdditionalRate": False,
            "withoutSeating": False,
            "vfstfr": False,
            "preview": False,
            "draftMode": False,
            "durationFirstPart": 10,
            "numberSeatsRemaining": 122,
            "numberSeatsForOnlineSale": 122,
            "numberSeatsBlocked": 0,
            "numberRemainingSeatsForOnlineSale": 122,
            "numberSeatsSold": 0,
            "cinema": {
                "id": 5,
                "name": "Toulousain Showroom",
                "alloCineId": "G01G8",
                "numberScreens": 9,
                "userLastModification": "boost",
                "lastModification": "2022-11-22T09:28:11+01:00",
            },
            "event": {
                "id": 3350,
                "dateFrom": "2022-11-23T00:00:00+01:00",
                "dateTo": "2022-11-29T00:00:00+01:00",
                "distributorPercentage": 50,
                "eventType": 0,
                "planPrice": 0,
                "complements": [],
                "deletable": True,
                "editable": True,
                "userLastModification": "boost",
                "lastModification": None,
                "numCinema": 5,
            },
            "film": FILM_147,
            "format": {"id": 1, "title": "2D"},
            "version": {"id": 3, "title": "Film Etranger en Langue Française", "code": "VF"},
            "screen": {
                "id": 6,
                "auditoriumNumber": 6,
                "name": "SALLE 06",
                "capacity": 174,
                "is4K": False,
                "ice": False,
                "lightVibes": False,
                "eclairColor": False,
                "hearingImpaired": False,
                "audioDescription": False,
                "seatingAllowed": True,
                "cinema": {
                    "id": 5,
                    "name": "Toulousain Showroom",
                    "alloCineId": "G01G8",
                    "numberScreens": 9,
                    "userLastModification": "boost",
                    "lastModification": "2022-11-22T09:28:11+01:00",
                },
                "userLastModification": "Boost",
                "lastModification": "2021-01-06T10:21:40+01:00",
                "HFR": False,
            },
            "showtimePricing": [FULL_PRICING],
            "onlineSale": True,
            "cashierSelling": True,
            "kioskSelling": True,
            "deletable": True,
            "editable": True,
            "numCinema": 5,
            "lastModification": "2022-11-23T09:49:32+01:00",
            "userLastModification": "boost",
        },
    }


class FilmsEndpointResponse:
    PAGE_1_JSON_DATA = {
        "data": [FILM_207, FILM_210],
        "message": "OK",
        "page": 1,
        "previousPage": 1,
        "nextPage": 2,
        "totalPages": 2,
        "totalCount": 3,
    }
    PAGE_2_JSON_DATA = {
        "data": [FILM_147],
        "message": "OK",
        "page": 2,
        "previousPage": 1,
        "nextPage": 2,
        "totalPages": 2,
        "totalCount": 3,
    }


class ConfirmedSaleEndpointResponse:
    DATA = {
        "code": 201,
        "message": "Confirmed sale",
        "data": {
            "id": 90474,
            "code": "sale-90474",
            "saleBarcode": None,
            "candystoreSaleBarcode": None,
            "type": "PAX",
            "date": "2022-11-27T16:35:08+01:00",
            "amountTaxesIncluded": 12,
            "giveBackChange": 0,
            "items": [
                {
                    "id": 191460,
                    "type": "ENT",
                    "order": 1,
                    "pricingCode": None,
                    "pricingTitle": None,
                    "idTicket": 164514,
                    "isCancelled": False,
                    "isControlled": False,
                    "isControlRequired": False,
                    "saleDate": "2022-11-27T16:35:08+01:00",
                    "amountPerUnit": 6,
                    "quantityCancelled": 0,
                    "quantityOnlineControlled": 0,
                    "seat": None,
                    "idSale": None,
                    "barcode": "0",
                },
                {
                    "id": 191461,
                    "type": "ENT",
                    "order": 2,
                    "pricingCode": None,
                    "pricingTitle": None,
                    "idTicket": 164515,
                    "isCancelled": False,
                    "isControlled": False,
                    "isControlRequired": False,
                    "saleDate": "2022-11-27T16:35:08+01:00",
                    "amountPerUnit": 6,
                    "quantityCancelled": 0,
                    "quantityOnlineControlled": 0,
                    "seat": None,
                    "idSale": None,
                    "barcode": "0",
                },
            ],
            "tickets": [
                {
                    "id": 164514,
                    "idCnc": 7174057,
                    "ticketReference": "PCU-000001-7174057",
                    "pricingCode": "PCU",
                    "idSaleCountermark": 0,
                    "amount": 6,
                    "idSale": 90474,
                    "seat": None,
                    "numCinema": 5,
                    "isCancelled": False,
                    "isControlled": False,
                    "isCNC": True,
                    "isFid": False,
                    "authorizedAccess": False,
                    "pricingTitle": "PASS CULTURE",
                    "isControlRequired": False,
                    "withdrawType": "PAX Mobile",
                    "showtimeInfo": {
                        "idShowtime": 36683,
                        "auditoriumNumber": 1,
                        "filmTitle": "BLACK PANTHER : WAKANDA FOREVER",
                        "filmVersion": "VF",
                        "filmFormat": "2D",
                        "filmPoster": "http://example.com/images/158026.jpg",
                        "filmPosterThumb": "http://example.com/img/thumb/film/158026.jpg",
                        "showStartDateTime": "2022-11-28T09:00:00+01:00",
                        "showEndDateTime": "2022-11-28T11:52:00+01:00",
                        "isAuthorizedAccess": False,
                    },
                    "saleTicketWithCard": False,
                    "complementsCncMandatory": [
                        {
                            "id": 164514,
                            "idComplement": 2006,
                            "title": "Cinemax",
                            "quantity": 1,
                            "quantityOnlineControlled": 0,
                            "quantityCancelled": 0,
                            "isControlRequired": True,
                            "isCnc": True,
                            "amountPerUnit": 2,
                            "complementIsRefundable": False,
                        }
                    ],
                    "complementsNoCncMandatory": [],
                },
                {
                    "id": 164515,
                    "idCnc": 7174058,
                    "ticketReference": "PCU-000002-7174058",
                    "pricingCode": "PCU",
                    "idSaleCountermark": 0,
                    "amount": 6,
                    "idSale": 90474,
                    "seat": None,
                    "numCinema": 5,
                    "isCancelled": False,
                    "isControlled": False,
                    "isCNC": True,
                    "isFid": False,
                    "authorizedAccess": False,
                    "pricingTitle": "PASS CULTURE",
                    "isControlRequired": False,
                    "withdrawType": "PAX Mobile",
                    "showtimeInfo": {
                        "idShowtime": 36683,
                        "auditoriumNumber": 1,
                        "filmTitle": "BLACK PANTHER : WAKANDA FOREVER",
                        "filmVersion": "VF",
                        "filmFormat": "2D",
                        "filmPoster": "http://example.com/images/158026.jpg",
                        "filmPosterThumb": "http://example.com/img/thumb/film/158026.jpg",
                        "showStartDateTime": "2022-11-28T09:00:00+01:00",
                        "showEndDateTime": "2022-11-28T11:52:00+01:00",
                        "isAuthorizedAccess": False,
                    },
                    "saleTicketWithCard": False,
                    "complementsCncMandatory": [
                        {
                            "id": 164515,
                            "idComplement": 2006,
                            "title": "Cinemax",
                            "quantity": 1,
                            "quantityOnlineControlled": 0,
                            "quantityCancelled": 0,
                            "isControlRequired": True,
                            "isCnc": True,
                            "amountPerUnit": 2,
                            "complementIsRefundable": False,
                        }
                    ],
                    "complementsNoCncMandatory": [],
                },
            ],
            "complements": [],
        },
    }


CANCEL_ORDER_SALE_90577 = {
    "message": "OK",
    "data": {
        "id": 90577,
        "code": "sale-90577",
        "saleBarcode": None,
        "candystoreSaleBarcode": None,
        "type": "PAX",
        "date": "2022-12-02T18:11:23+01:00",
        "cancelled": True,
        "amountTaxesIncluded": 12,
        "giveBackChange": 0,
        "payments": [
            {
                "id": 130993,
                "amountReceived": 12,
                "info1": "Vente émis par BB-Api",
                "info2": None,
                "taxRate": 0,
                "idTicket": 0,
                "idCredit": 0,
                "numberOfDebitedSeats": 0,
                "timestamp": "2022-12-02T18:11:23+01:00",
                "signature": "C0 F8 B1 00 3D D6 B1 9B 29 7D 1B A4 03 FE FE DE\r\nEB 60 E9 AD D9 EF 78 5A 44 BA A4 46 EC E9 69 1E\r\n86 A3 00 60 C2 AB 2C 6E 21 F1 ED 56 DA 0B AA 1C\r\n2B 00 02 CC BF B1 9D 68 8B 2C FA 9E 65 9E C8 C4\r\n6B 70 A8 5E 53 7D 31 78 C9 CB DD 85 09 E9 87 DC\r\n48 53 99 A3 3C 60 9E E4 DB 84 22 31 2B 63 78 A7\r\nB7 F6 F1 8B CC 3E 1B F9 68 D0 E3 57 78 42 4F 7E\r\nB1 8A DA EC 57 9F 65 C3 41 F2 8D 7E 0F 3A 50 9C\r\n63 F7 70 AC B7 5C C8 A3 8D A0 B9 B9 06 B0 66 AA\r\n5B AB 17 0F 20 DA 11 11 99 8E CC 9B D4 F1 DC 1A\r\n84 DA 31 A8 2C 6F FA D2 51 C6 C2 AA 1B DE 99 06\r\n2A 2E 95 37 BF 41 54 C3 24 CA 0C F3 4C ED A6 CB\r\nF8 D9 FA 39 B5 DF 40 42 80 23 99 D7 22 85 E0 08\r\nEE 11 96 3B 5C 85 19 39 89 CD 6C 30 3C DC 6D A7\r\n59 A7 4F 80 7D E7 BC 55 F1 45 FC 8E AF 1F 03 52\r\n9D F5 AF 3D C1 EC F5 CE 95 9E 6E 49 28 BE D2 4F",
            }
        ],
        "customer": None,
        "station": {
            "id": 183,
            "name": "Poste de PASS CULTURE (PAX)",
            "isTicketing": True,
            "isConcessions": True,
            "numCinema": 5,
            "lastModification": "2022-12-01T17:37:28+01:00",
            "userLastModification": "PASS CULTURE",
        },
        "vendor": {
            "id": 121,
            "codeEAN": "6513062051087",
            "username": "PASS CULTURE",
            "isAllowedOnKiosk": True,
            "isAllowedOnConcessions": False,
            "isAllowedOnAdmin": False,
            "isFreeConcession": False,
            "active": True,
            "numCinema": 5,
        },
        "items": [
            {
                "id": 191609,
                "type": "ENT",
                "order": 1,
                "pricingCode": None,
                "pricingTitle": None,
                "idTicket": 164607,
                "isCancelled": True,
                "isControlled": False,
                "isControlRequired": False,
                "saleDate": "2022-12-02T18:11:23+01:00",
                "amountPerUnit": 6,
                "quantityCancelled": 1,
                "quantityOnlineControlled": 0,
                "seat": None,
                "idSale": 90577,
                "barcode": "0",
                "lastModification": None,
                "userLastModification": None,
            },
            {
                "id": 191610,
                "type": "ENT",
                "order": 2,
                "pricingCode": None,
                "pricingTitle": None,
                "idTicket": 164608,
                "isCancelled": True,
                "isControlled": False,
                "isControlRequired": False,
                "saleDate": "2022-12-02T18:11:23+01:00",
                "amountPerUnit": 6,
                "quantityCancelled": 1,
                "quantityOnlineControlled": 0,
                "seat": None,
                "idSale": 90577,
                "barcode": "0",
                "lastModification": None,
                "userLastModification": None,
            },
        ],
        "tickets": [
            {
                "id": 164607,
                "idCnc": 7176241,
                "ticketReference": "PCU-000001-7176241",
                "pricingCode": "PCU",
                "idSaleCountermark": 0,
                "amount": 6,
                "idSale": 90577,
                "seat": None,
                "numCinema": 5,
                "isCancelled": True,
                "isControlled": False,
                "isCNC": True,
                "isFid": False,
                "authorizedAccess": False,
                "pricingTitle": "PASS CULTURE",
                "isControlRequired": False,
                "withdrawType": "PAX Mobile",
                "showtimeInfo": {
                    "idShowtime": 37041,
                    "auditoriumNumber": 2,
                    "filmTitle": "FUMER FAIT TOUSSER",
                    "filmVersion": "VF",
                    "filmFormat": "2D",
                    "filmPoster": "http://example.com/images/155372.jpg",
                    "filmPosterThumb": "http://example.com/img/thumb/film/155372.jpg",
                    "showStartDateTime": "2022-12-02T20:35:00+01:00",
                    "showEndDateTime": "2022-12-02T22:05:00+01:00",
                    "isAuthorizedAccess": False,
                },
                "saleTicketWithCard": False,
                "complementsCncMandatory": [],
                "complementsNoCncMandatory": [],
                "lastModification": "2022-12-05T14:45:35+01:00",
                "userLastModification": "PASS CULTURE",
            },
            {
                "id": 164608,
                "idCnc": 7176242,
                "ticketReference": "PCU-000002-7176242",
                "pricingCode": "PCU",
                "idSaleCountermark": 0,
                "amount": 6,
                "idSale": 90577,
                "seat": None,
                "numCinema": 5,
                "isCancelled": True,
                "isControlled": False,
                "isCNC": True,
                "isFid": False,
                "authorizedAccess": False,
                "pricingTitle": "PASS CULTURE",
                "isControlRequired": False,
                "withdrawType": "PAX Mobile",
                "showtimeInfo": {
                    "idShowtime": 37041,
                    "auditoriumNumber": 2,
                    "filmTitle": "FUMER FAIT TOUSSER",
                    "filmVersion": "VF",
                    "filmFormat": "2D",
                    "filmPoster": "http://example.com/images/155372.jpg",
                    "filmPosterThumb": "http://example.com/img/thumb/film/155372.jpg",
                    "showStartDateTime": "2022-12-02T20:35:00+01:00",
                    "showEndDateTime": "2022-12-02T22:05:00+01:00",
                    "isAuthorizedAccess": False,
                },
                "saleTicketWithCard": False,
                "complementsCncMandatory": [],
                "complementsNoCncMandatory": [],
                "lastModification": "2022-12-05T14:45:35+01:00",
                "userLastModification": "PASS CULTURE",
            },
        ],
    },
}
