class FilmsEndpointResponse:
    PAGE_1_JSON_DATA = {
        "data": [
            {
                "id": 52,
                "titleCnc": "#JESUISLA",
                "numVisa": 147956,
                "posterUrl": "http://example.com/images/147956.jpg",
                "thumbUrl": "http://example.com/img/thumb/film/147956.jpg",
                "idFilmAllocine": 267615,
            },
            {
                "id": 62,
                "titleCnc": "10 JOURS SANS MAMAN",
                "numVisa": 151172,
                "posterUrl": "http://example.com/images/151172.jpg",
                "thumbUrl": "http://example.com/img/thumb/film/151172.jpg",
                "idFilmAllocine": 273882,
            },
        ],
        "message": "OK",
        "page": 1,
        "previousPage": 1,
        "nextPage": 2,
        "totalPages": 2,
        "totalCount": 4,
    }
    PAGE_2_JSON_DATA = {
        "data": [
            {
                "id": 134,
                "titleCnc": "100 % LOUP",
                "numVisa": 2020002189,
                "posterUrl": "http://example.com/images/2020002189.jpg",
                "thumbUrl": "http://example.com/img/thumb/film/2020002189.jpg",
                "idFilmAllocine": 264648,
            },
            {
                "id": 40,
                "titleCnc": "1917",
                "numVisa": 152284,
                "posterUrl": "http://example.com/images/152284.jpg",
                "thumbUrl": "http://example.com/img/thumb/film/152284.jpg",
                "idFilmAllocine": 265567,
            },
        ],
        "message": "OK",
        "page": 2,
        "previousPage": 1,
        "nextPage": 2,
        "totalPages": 2,
        "totalCount": 4,
    }


class ShowtimesEndpointResponse:
    PAGE_1_JSON_DATA = {
        "data": [
            {
                "id": 34709,
                "showDate": "2022-10-17T09:00:00+02:00",
                "showEndDate": "2022-10-17T12:10:00+02:00",
                "soldOut": False,
                "authorizedAccess": False,
                "numberSeatsRemaining": 136,
                "film": {
                    "id": 189,
                    "titleCnc": "Avatar : La Voie De L'eau",
                    "numVisa": 123456,
                    "posterUrl": "http://example.com/images/Tmpd188acaa73008cd5bb4f182a82cd3f36.jpg",
                    "thumbUrl": "http://example.com/img/thumb/film/Tmpd188acaa73008cd5bb4f182a82cd3f36.jpg",
                    "idFilmAllocine": 178014,
                },
                "format": {"id": 2, "title": "3D"},
                "version": {"id": 2, "title": "Film Etranger en Langue Etrangère", "code": "VO"},
                "screen": {
                    "id": 1,
                    "auditoriumNumber": 1,
                    "name": "SALLE CINEMAX",
                    "capacity": 136,
                    "seatingAllowed": False,
                },
            },
            {
                "id": 34772,
                "showDate": "2022-10-17T09:10:00+02:00",
                "showEndDate": "2022-10-17T11:01:00+02:00",
                "soldOut": False,
                "authorizedAccess": False,
                "numberSeatsRemaining": 136,
                "film": {
                    "id": 190,
                    "titleCnc": "UNE BELLE COURSE",
                    "numVisa": 153041,
                    "posterUrl": "http://example.com/images/153041.jpg",
                    "thumbUrl": "http://example.com/img/thumb/film/153041.jpg",
                    "idFilmAllocine": 292290,
                },
                "format": {"id": 1, "title": "2D"},
                "version": {"id": 1, "title": "Film Français", "code": "VF"},
                "screen": {
                    "id": 3,
                    "auditoriumNumber": 3,
                    "name": "SALLE 03",
                    "capacity": 136,
                    "seatingAllowed": True,
                },
            },
        ],
        "message": "OK",
        "page": 1,
        "previousPage": 1,
        "nextPage": 2,
        "totalPages": 2,
        "totalCount": 4,
    }
    PAGE_2_JSON_DATA = {
        "data": [
            {
                "id": 34877,
                "showDate": "2022-10-17T09:30:00+02:00",
                "showEndDate": "2022-10-17T11:26:00+02:00",
                "soldOut": False,
                "authorizedAccess": False,
                "numberSeatsRemaining": 177,
                "film": {
                    "id": 192,
                    "titleCnc": "JACK MIMOUN ET LES SECRETS DE VAL VERDE",
                    "numVisa": 155104,
                    "posterUrl": "http://example.com/images/155104.jpg",
                    "thumbUrl": "http://example.com/img/thumb/film/155104.jpg",
                    "idFilmAllocine": 271293,
                },
                "format": {"id": 1, "title": "2D"},
                "version": {"id": 1, "title": "Film Français", "code": "VF"},
                "screen": {
                    "id": 5,
                    "auditoriumNumber": 5,
                    "name": "SALLE 05",
                    "capacity": 177,
                    "seatingAllowed": True,
                },
            },
            {
                "id": 34926,
                "showDate": "2022-10-17T09:40:00+02:00",
                "showEndDate": "2022-10-17T11:20:00+02:00",
                "soldOut": False,
                "authorizedAccess": False,
                "numberSeatsRemaining": 174,
                "film": {
                    "id": 193,
                    "titleCnc": "LE NOUVEAU JOUET",
                    "numVisa": 155775,
                    "posterUrl": "http://example.com/images/155775.jpg",
                    "thumbUrl": "http://example.com/img/thumb/film/155775.jpg",
                    "idFilmAllocine": 286890,
                },
                "format": {"id": 1, "title": "2D"},
                "version": {"id": 1, "title": "Film Français", "code": "VF"},
                "screen": {
                    "id": 6,
                    "auditoriumNumber": 6,
                    "name": "SALLE 06",
                    "capacity": 174,
                    "seatingAllowed": True,
                },
            },
        ],
        "message": "OK",
        "page": 2,
        "previousPage": 1,
        "nextPage": 2,
        "totalPages": 2,
        "totalCount": 4,
    }


class ShowtimeDetailsEndpointResponse:
    DATA = {
        "message": "OK",
        "data": {
            "id": 35278,
            "idSeatingConfiguration": 0,
            "idProjectionLocation": 0,
            "showDate": "2022-10-19T09:40:00+02:00",
            "showEndDate": "2022-10-19T11:20:00+02:00",
            "dateCNC": "2022-10-19",
            "earlyInterruptionTime": "00:00:00",
            "interruptionReason": None,
            "preSelling": True,
            "inDisplayPanel": True,
            "soldOut": False,
            "hidden": False,
            "schoolPricingPermitted": False,
            "hasIntermission": False,
            "priorityTitle": False,
            "authorizedAccess": False,
            "withoutAdditionalRate": False,
            "withoutSeating": False,
            "vfstfr": False,
            "preview": False,
            "draftMode": False,
            "durationFirstPart": 10,
            "numberSeatsRemaining": 174,
            "numberSeatsForOnlineSale": 122,
            "numberSeatsBlocked": 0,
            "numberRemainingSeatsForOnlineSale": 122,
            "numberSeatsSold": 0,
            "cinema": {
                "id": 5,
                "name": "Toulousain Showroom",
                "alloCineId": "",
                "numberScreens": 9,
                "userLastModification": "boost",
                "lastModification": "2022-10-04T16:51:39+02:00",
            },
            "event": {
                "id": 3277,
                "dateFrom": "2022-10-19T00:00:00+02:00",
                "dateTo": "2022-10-25T00:00:00+02:00",
                "distributorPercentage": 50,
                "eventType": 0,
                "planPrice": 0,
                "complements": [],
                "deletable": True,
                "editable": True,
                "userLastModification": "boost",
                "lastModification": None,
                "numCinema": 5,
            },
            "film": {
                "id": 193,
                "titleCnc": "LE NOUVEAU JOUET",
                "numVisa": 155775,
                "type": {
                    "id": 1,
                    "title": "CNC",
                    "numCinema": 5,
                    "userLastModification": "CINESYSTEM",
                    "lastModification": None,
                },
                "displayColor": "CCFF99",
                "idFilmAllocine": 286890,
                "posterUrl": "http://example.com/images/155775.jpg",
                "thumbUrl": "http://example.com/img/thumb/film/155775.jpg",
                "numCinema": 5,
                "userLastModification": "boost",
                "lastModification": "2022-10-07T16:38:14+02:00",
            },
            "format": {"id": 1, "title": "2D"},
            "version": {"id": 1, "title": "Film Français", "code": "VF"},
            "screen": {
                "id": 6,
                "auditoriumNumber": 6,
                "name": "SALLE 06",
                "capacity": 174,
                "seatingAllowed": True,
                "cinema": {
                    "id": 5,
                    "name": "Toulousain Showroom",
                    "alloCineId": "",
                    "numberScreens": 9,
                    "userLastModification": "boost",
                    "lastModification": "2022-10-04T16:51:39+02:00",
                },
                "userLastModification": "Boost",
                "lastModification": "2021-01-06T10:21:40+01:00",
            },
            "showtimePricing": [
                {
                    "id": 1080565,
                    "title": "PLEIN TARIF",
                    "amountTaxesIncluded": 8,
                    "idSequencePresale": 0,
                    "idSequenceImmediate": 0,
                    "idConcessionCountermark": 0,
                    "includedLeaseAmount": 0,
                    "idPricingCategory": 4,
                    "onlineSale": True,
                    "cashierSelling": True,
                    "kioskSelling": True,
                    "pricingCode": "PLE",
                    "displayPosX": 1,
                    "displayPosY": 1,
                    "editable": True,
                    "deletable": True,
                    "numCinema": 5,
                    "lastModification": "2022-10-06T16:31:24+02:00",
                    "userLastModification": "boost",
                    "displayColor": "27C827",
                    "idPrimaryPrice": 1,
                    "typePayment": "cash_or_credit_card",
                    "typeCards": [],
                },
                {
                    "id": 1080580,
                    "title": "PASS CULTURE",
                    "amountTaxesIncluded": 6,
                    "idSequencePresale": 0,
                    "idSequenceImmediate": 0,
                    "idConcessionCountermark": 0,
                    "includedLeaseAmount": 0,
                    "idPricingCategory": 4,
                    "onlineSale": False,
                    "cashierSelling": True,
                    "kioskSelling": True,
                    "pricingCode": "PCU",
                    "displayPosX": 0,
                    "displayPosY": 0,
                    "editable": True,
                    "deletable": True,
                    "numCinema": 5,
                    "lastModification": "2022-10-06T16:31:24+02:00",
                    "userLastModification": "boost",
                    "displayColor": "",
                    "idPrimaryPrice": 62,
                    "typePayment": "external:credit:passculture",
                    "typeCards": [],
                },
            ],
            "onlineSale": True,
            "cashierSelling": True,
            "kioskSelling": True,
            "deletable": True,
            "editable": True,
            "numCinema": 5,
            "lastModification": "2022-10-07T16:38:17+02:00",
            "userLastModification": "boost",
        },
    }


class ConfirmedSaleEndpointResponse:
    DATA = {
        "code": 201,
        "message": "Confirmed sale",
        "data": {
            "id": 90308,
            "code": "sale-90308",
            "saleBarcode": None,
            "candystoreSaleBarcode": None,
            "type": "PAX",
            "date": "2022-11-08T15:21:17+01:00",
            "amountTaxesIncluded": 15,
            "giveBackChange": 0,
            "items": [
                {
                    "id": 191168,
                    "type": "ENT",
                    "order": 1,
                    "pricingCode": None,
                    "pricingTitle": None,
                    "idTicket": 164384,
                    "isCancelled": False,
                    "isControlled": False,
                    "isControlRequired": False,
                    "saleDate": "2022-11-08T15:21:17+01:00",
                    "amountPerUnit": 7.5,
                    "quantityCancelled": 0,
                    "quantityOnlineControlled": 0,
                    "seat": None,
                    "idSale": None,
                    "barcode": "0",
                },
                {
                    "id": 191169,
                    "type": "ENT",
                    "order": 2,
                    "pricingCode": None,
                    "pricingTitle": None,
                    "idTicket": 164385,
                    "isCancelled": False,
                    "isControlled": False,
                    "isControlRequired": False,
                    "saleDate": "2022-11-08T15:21:17+01:00",
                    "amountPerUnit": 7.5,
                    "quantityCancelled": 0,
                    "quantityOnlineControlled": 0,
                    "seat": None,
                    "idSale": None,
                    "barcode": "0",
                },
            ],
            "tickets": [
                {
                    "id": 164384,
                    "idCnc": 7171980,
                    "ticketReference": "PCU-000001-7171980",
                    "pricingCode": "PCU",
                    "amount": 7.5,
                    "idSale": 90308,
                    "seat": None,
                    "numCinema": 5,
                    "isCancelled": False,
                    "isControlled": False,
                    "isCNC": True,
                    "isFid": False,
                    "authorizedAccess": False,
                    "pricingTitle": "PASS CULTURE",
                    "isControlRequired": False,
                    "withdrawType": "PAX Mobile",
                    "showtimeInfo": {
                        "idShowtime": 35805,
                        "auditoriumNumber": 1,
                        "filmTitle": "Avatar : La Voie De L'eau",
                        "filmVersion": "VO",
                        "filmFormat": "3D",
                        "filmPoster": "http://example.com/images/Tmpd188acaa73008cd5bb4f182a82cd3f36.jpg",
                        "filmPosterThumb": "http://example.com/img/thumb/film/Tmpd188acaa73008cd5bb4f182a82cd3f36.jpg",
                        "showStartDateTime": "2022-11-08T09:00:00+01:00",
                        "showEndDateTime": "2022-11-08T12:10:00+01:00",
                        "isAuthorizedAccess": False,
                    },
                    "saleTicketWithCard": False,
                    "complementsCncMandatory": [
                        {
                            "id": 164384,
                            "idComplement": 1976,
                            "title": "MAJORATION 3D",
                            "quantity": 1,
                            "quantityOnlineControlled": 0,
                            "quantityCancelled": 0,
                            "isControlRequired": True,
                            "isCnc": True,
                            "amountPerUnit": 1.5,
                            "complementIsRefundable": False,
                        },
                        {
                            "id": 164384,
                            "idComplement": 1978,
                            "title": "Cinemax",
                            "quantity": 1,
                            "quantityOnlineControlled": 0,
                            "quantityCancelled": 0,
                            "isControlRequired": True,
                            "isCnc": True,
                            "amountPerUnit": 2,
                            "complementIsRefundable": False,
                        },
                    ],
                    "complementsNoCncMandatory": [],
                },
                {
                    "id": 164385,
                    "idCnc": 7171981,
                    "ticketReference": "PCU-000002-7171981",
                    "pricingCode": "PCU",
                    "amount": 7.5,
                    "idSale": 90308,
                    "seat": None,
                    "numCinema": 5,
                    "isCancelled": False,
                    "isControlled": False,
                    "isCNC": True,
                    "isFid": False,
                    "authorizedAccess": False,
                    "pricingTitle": "PASS CULTURE",
                    "isControlRequired": False,
                    "withdrawType": "PAX Mobile",
                    "showtimeInfo": {
                        "idShowtime": 35805,
                        "auditoriumNumber": 1,
                        "filmTitle": "Avatar : La Voie De L'eau",
                        "filmVersion": "VO",
                        "filmFormat": "3D",
                        "filmPoster": "http://example.com/images/Tmpd188acaa73008cd5bb4f182a82cd3f36.jpg",
                        "filmPosterThumb": "http://example.com/img/thumb/film/Tmpd188acaa73008cd5bb4f182a82cd3f36.jpg",
                        "showStartDateTime": "2022-11-08T09:00:00+01:00",
                        "showEndDateTime": "2022-11-08T12:10:00+01:00",
                        "isAuthorizedAccess": False,
                    },
                    "saleTicketWithCard": False,
                    "complementsCncMandatory": [
                        {
                            "id": 164385,
                            "idComplement": 1976,
                            "title": "MAJORATION 3D",
                            "quantity": 1,
                            "quantityOnlineControlled": 0,
                            "quantityCancelled": 0,
                            "isControlRequired": True,
                            "isCnc": True,
                            "amountPerUnit": 1.5,
                            "complementIsRefundable": False,
                        },
                        {
                            "id": 164385,
                            "idComplement": 1978,
                            "title": "Cinemax",
                            "quantity": 1,
                            "quantityOnlineControlled": 0,
                            "quantityCancelled": 0,
                            "isControlRequired": True,
                            "isCnc": True,
                            "amountPerUnit": 2,
                            "complementIsRefundable": False,
                        },
                    ],
                    "complementsNoCncMandatory": [],
                },
            ],
            "complements": [],
        },
    }
