import { TICKET_WITHDRAWAL_DEFAULT_VALUES } from './TicketWithdrawal'
import { VENUE_DEFAULT_VALUES } from './Venue'

export const USEFUL_INFORMATIONS_DEFAULT_VALUES = {
  ...VENUE_DEFAULT_VALUES,
  ...TICKET_WITHDRAWAL_DEFAULT_VALUES,
  isNational: false,
}

export const WITHDRAWAL_TYPE_COMPATIBLE_SUBCATEGORIE = [
  'FESTIVAL_MUSIQUE',
  'CONCERT',
  'EVENEMENT_MUSIQUE',
  'FESTIVAL_SPECTACLE',
  'SPECTACLE_REPRESENTATION',
]
