import { INFORMATIONS_DEFAULT_VALUES } from './Informations/constants'
import { USEFUL_INFORMATIONS_DEFAULT_VALUES } from './UsefulInformations'
import { CATEGORIES_DEFAULT_VALUES, MUSIC_SUBTYPES_DEFAULT_VALUES, SHOW_SUBTYPES_DEFAULT_VALUES } from './Categories/constants'

export const FORM_DEFAULT_VALUES = {
  ...INFORMATIONS_DEFAULT_VALUES,
  ...CATEGORIES_DEFAULT_VALUES,
  ...USEFUL_INFORMATIONS_DEFAULT_VALUES,
  ...MUSIC_SUBTYPES_DEFAULT_VALUES,
  ...SHOW_SUBTYPES_DEFAULT_VALUES,
}