import { INFORMATIONS_DEFAULT_VALUES } from './Informations/constants'
import { USEFUL_INFORMATIONS_DEFAULT_VALUES } from './UsefulInformations'
export const FORM_DEFAULT_VALUES = {
  ...INFORMATIONS_DEFAULT_VALUES,
  ...USEFUL_INFORMATIONS_DEFAULT_VALUES,
}
