"""empty message

Revision ID: e8c43e6dc0d8
Revises: 11d603462200
Create Date: 2018-07-26 11:52:17.853134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c43e6dc0d8'
down_revision = '11d603462200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    op.add_column('booking', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('event_occurence', sa.Column('occasionId', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_event_occurence_occasionId'), 'event_occurence', ['occasionId'], unique=False)
    op.drop_index('ix_event_occurence_eventId', table_name='event_occurence')
    op.drop_index('ix_event_occurence_venueId', table_name='event_occurence')
    op.drop_constraint('event_occurence_eventId_fkey', 'event_occurence', type_='foreignkey')
    op.drop_constraint('event_occurence_venueId_fkey', 'event_occurence', type_='foreignkey')
    op.create_foreign_key(None, 'event_occurence', 'occasion', ['occasionId'], ['id'])
    op.drop_column('event_occurence', 'venueId')
    op.drop_column('event_occurence', 'eventId')
    op.add_column('mediation', sa.Column('occasionId', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_mediation_occasionId'), 'mediation', ['occasionId'], unique=False)
    op.drop_index('ix_mediation_eventId', table_name='mediation')
    op.drop_index('ix_mediation_thingId', table_name='mediation')
    op.drop_constraint('mediation_offererId_fkey', 'mediation', type_='foreignkey')
    op.drop_constraint('mediation_eventId_fkey', 'mediation', type_='foreignkey')
    op.drop_constraint('mediation_thingId_fkey', 'mediation', type_='foreignkey')
    op.create_foreign_key(None, 'mediation', 'occasion', ['occasionId'], ['id'])
    op.drop_column('mediation', 'eventId')
    op.drop_column('mediation', 'offererId')
    op.drop_column('mediation', 'thingId')
    op.add_column('offer', sa.Column('occasionId', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_offer_occasionId'), 'offer', ['occasionId'], unique=False)
    op.drop_index('ix_offer_offererId', table_name='offer')
    op.drop_index('ix_offer_thingId', table_name='offer')
    op.drop_index('ix_offer_venueId', table_name='offer')
    op.drop_constraint('offer_venueId_fkey', 'offer', type_='foreignkey')
    op.drop_constraint('offer_offererId_fkey', 'offer', type_='foreignkey')
    op.drop_constraint('offer_thingId_fkey', 'offer', type_='foreignkey')
    op.create_foreign_key(None, 'offer', 'occasion', ['occasionId'], ['id'])
    op.drop_column('offer', 'venueId')
    op.drop_column('offer', 'offererId')
    op.drop_column('offer', 'thingId')
    op.create_unique_constraint(None, 'offerer', ['validationToken'])
    op.add_column('recommendation', sa.Column('occasionId', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_recommendation_occasionId'), 'recommendation', ['occasionId'], unique=False)
    op.drop_index('ix_recommendation_eventId', table_name='recommendation')
    op.drop_index('ix_recommendation_thingId', table_name='recommendation')
    op.drop_constraint('recommendation_eventId_fkey', 'recommendation', type_='foreignkey')
    op.drop_constraint('recommendation_thingId_fkey', 'recommendation', type_='foreignkey')
    op.create_foreign_key(None, 'recommendation', 'occasion', ['occasionId'], ['id'])
    op.drop_column('recommendation', 'eventId')
    op.drop_column('recommendation', 'thingId')
    op.alter_column('thing', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'user_offerer', ['validationToken'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_offerer', type_='unique')
    op.alter_column('thing', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('recommendation', sa.Column('thingId', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('recommendation', sa.Column('eventId', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recommendation', type_='foreignkey')
    op.create_foreign_key('recommendation_thingId_fkey', 'recommendation', 'thing', ['thingId'], ['id'])
    op.create_foreign_key('recommendation_eventId_fkey', 'recommendation', 'event', ['eventId'], ['id'])
    op.create_index('ix_recommendation_thingId', 'recommendation', ['thingId'], unique=False)
    op.create_index('ix_recommendation_eventId', 'recommendation', ['eventId'], unique=False)
    op.drop_index(op.f('ix_recommendation_occasionId'), table_name='recommendation')
    op.drop_column('recommendation', 'occasionId')
    op.drop_constraint(None, 'offerer', type_='unique')
    op.add_column('offer', sa.Column('thingId', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('offer', sa.Column('offererId', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('offer', sa.Column('venueId', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.create_foreign_key('offer_thingId_fkey', 'offer', 'thing', ['thingId'], ['id'])
    op.create_foreign_key('offer_offererId_fkey', 'offer', 'offerer', ['offererId'], ['id'])
    op.create_foreign_key('offer_venueId_fkey', 'offer', 'venue', ['venueId'], ['id'])
    op.create_index('ix_offer_venueId', 'offer', ['venueId'], unique=False)
    op.create_index('ix_offer_thingId', 'offer', ['thingId'], unique=False)
    op.create_index('ix_offer_offererId', 'offer', ['offererId'], unique=False)
    op.drop_index(op.f('ix_offer_occasionId'), table_name='offer')
    op.drop_column('offer', 'occasionId')
    op.add_column('mediation', sa.Column('thingId', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('mediation', sa.Column('offererId', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('mediation', sa.Column('eventId', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mediation', type_='foreignkey')
    op.create_foreign_key('mediation_thingId_fkey', 'mediation', 'thing', ['thingId'], ['id'])
    op.create_foreign_key('mediation_eventId_fkey', 'mediation', 'event', ['eventId'], ['id'])
    op.create_foreign_key('mediation_offererId_fkey', 'mediation', 'offerer', ['offererId'], ['id'])
    op.create_index('ix_mediation_thingId', 'mediation', ['thingId'], unique=False)
    op.create_index('ix_mediation_eventId', 'mediation', ['eventId'], unique=False)
    op.drop_index(op.f('ix_mediation_occasionId'), table_name='mediation')
    op.drop_column('mediation', 'occasionId')
    op.add_column('event_occurence', sa.Column('eventId', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('event_occurence', sa.Column('venueId', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'event_occurence', type_='foreignkey')
    op.create_foreign_key('event_occurence_venueId_fkey', 'event_occurence', 'venue', ['venueId'], ['id'])
    op.create_foreign_key('event_occurence_eventId_fkey', 'event_occurence', 'event', ['eventId'], ['id'])
    op.create_index('ix_event_occurence_venueId', 'event_occurence', ['venueId'], unique=False)
    op.create_index('ix_event_occurence_eventId', 'event_occurence', ['eventId'], unique=False)
    op.drop_index(op.f('ix_event_occurence_occasionId'), table_name='event_occurence')
    op.drop_column('event_occurence', 'occasionId')
    op.drop_column('booking', 'amount')
    op.create_table('account',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='account_pkey')
    )
    # ### end Alembic commands ###
