allowBuilds:
  '@firebase/util': false
  '@parcel/watcher': false
  esbuild: false
  storybook-addon-remix-react-router: false

overrides:
  esbuild@>=0.17.0 <0.28.1: '>=0.28.1'
  esbuild@>=0.27.3 <0.28.1: '>=0.28.1'
