# https://support.atlassian.com/jira-cloud-administration/docs/link-github-workflows-and-deployments-to-jira-issues/#Map-your-deployment-environments

deployments:
  environmentMapping:
    development:
      - "pcapi-preview"
    testing:
      - "testing"
    staging:
      - "staging"
    production:
      - "production"
