export enum OfferStatus {
  OFFER_STATUS_ACTIVE = 'ACTIVE',
  OFFER_STATUS_INACTIVE = 'INACTIVE',
  OFFER_STATUS_SOLD_OUT = 'SOLD_OUT',
  OFFER_STATUS_EXPIRED = 'EXPIRED',
  OFFER_STATUS_PENDING = 'PENDING',
  OFFER_STATUS_REJECTED = 'REJECTED',
  OFFER_STATUS_DRAFT = 'DRAFT',
}
