export { default as filterAvailableStocks } from './filterAvailableStocks'
export * from './getDepartementByCode'
export * from './getMobileOperatingSystem'
export * from './getPrice'
export { default as getPriceRangeFromStocks } from './getPriceRangeFromStocks'
export * from './getQueryParams'
export * from './getShareURL'
export { default as getRouterParamByKey } from './getRouterParamByKey'
export { default as getRouterQueryByKey } from './getRouterQueryByKey'
export * from './discovery'
export { default as isSameDayInEachTimezone } from './isSameDayInEachTimezone'
