export { default as filterAvailableStocks } from './filterAvailableStocks'
export * from './getDepartementByCode'
export * from './getMobileOperatingSystem'
export * from './getPrice'
export { default as getPriceRangeFromStocks } from './getPriceRangeFromStocks'
export * from './getQueryParams'
export * from './getShareURL'
export { default as isRecommendationFinished } from './isRecommendationFinished'
export { default as isSameDayInEachTimezone } from './isSameDayInEachTimezone'
