BOOST_PASS_CULTURE_PRICING_CODES = ["PCU", "PC2", "PC3", "PC4", "PC5"]  # the order matters
BOOST_PASS_CULTURE_REFUND_TYPE = "pcu"
BOOST_PASS_CULTURE_CODE_PAYMENT = "PCU"
BOOST_SHOWS_INTERVAL_DAYS = 60
BOOST_PASS_CULTURE_PAYMENT_METHOD = "external:credit:passculture"
BOOST_HIDE_FULL_RESERVATION = 1
BOOST_SHOWTIMES_STOCKS_CACHE_KEY = "api:cinema_provider:boost:stocks:%s:%s"
BOOST_SHOWTIMES_STOCKS_CACHE_TIMEOUT = 60
