BOOST_PASS_CULTURE_PRICING_CODES = ["PCU", "PC2", "PC3", "PC4", "PC5"]  # the order matters
BOOST_PASS_CULTURE_REFUND_TYPE = "pcu"
BOOST_PASS_CULTURE_CODE_PAYMENT = "PCU"
BOOST_SHOWS_INTERVAL_DAYS = 60
