export const PRICE_TABLE_ENTRY_MAX_LABEL_LENGTH = 50
export const PRICE_TABLE_ENTRY_MAX_PRICE_IN_EUR = 300
export const PRICE_TABLE_ENTRY_MAX_PRICE_IN_XPF = 20_000
export const PRICE_TABLE_ENTRY_MAX_QUANTITY = 1_000_000
