PARAMETER_ERROR_RESPONSE = {
    "account_email": "a.test@example.com",
    "account_login": "a.test",
    "api_call_datetime": "2021-06-07 12:48:34.041",
    "api_caller_ip": "90.127.244.104",
    "error_detail": "api_key",
    "event_datetime": "2021-06-07 12:48:34.041",
    "event_type": "payment",
    "org_id": "7jp6vj36",
    "password_hash": "4241b68fbc12414a94df141761614813",
    "request_id": "CD07E0DB-692C-43A4-A588-D612777862F2",
    "request_result": "fail_invalid_parameter",
    "service_type": "session-policy",
}
CORRECT_RESPONSE = {
    "account_date_of_birth": "20210607",
    "account_email": "user.email@example.net",
    "account_email_contains_dot": "yes",
    "account_email_domain": "example.net",
    "account_email_first_seen": "2021-06-07",
    "account_email_last_event": "2021-06-07",
    "account_email_last_update": "2021-06-07",
    "account_email_result": "success",
    "account_email_score": "0",
    "account_email_worst_score": "0",
    "account_telephone": "+33601234232",
    "account_telephone_country_code": "33",
    "account_telephone_first_seen": "2021-06-07",
    "account_telephone_geo": "FR",
    "account_telephone_is_possible": "yes",
    "account_telephone_is_valid": "yes",
    "account_telephone_last_event": "2021-06-07",
    "account_telephone_last_update": "2021-06-07",
    "account_telephone_result": "success",
    "account_telephone_score": "0",
    "account_telephone_type": "MOBILE",
    "account_telephone_worst_score": "0",
    "api_call_datetime": "2021-06-07 20:49:37.927",
    "api_caller_ip": "90.127.244.104",
    "api_type": "session-query",
    "api_version": "12.2.2",
    "bb_assessment": "174.51",
    "bb_assessment_rating": "low",
    "bb_bot_rating": "low",
    "bb_bot_score": "500.00",
    "bb_fraud_rating": "neutral",
    "bb_fraud_score": "500.00",
    "champion_request_duration": "3",
    "digital_id": "d89e177de2f846ac97f117717be7ff1e",
    "digital_id_confidence": "8477",
    "digital_id_confidence_rating": "very_high",
    "digital_id_first_seen": "2021-06-07",
    "digital_id_last_event": "2021-06-07",
    "digital_id_last_update": "2021-06-07",
    "digital_id_result": "success",
    "digital_id_trust_score": "70.00",
    "digital_id_trust_score_rating": "neutral",
    "digital_id_trust_score_reason_code": [
        "_ts_low_conf_score",
        "_ts_very_low_entity_age_score",
        "_ts_very_low_did_age_score",
        "_ts_very_short_did_distance",
        "_ts_very_low_graph_complex",
        "_ts_unknown_sess",
    ],
    "enabled_services": ["UP100"],
    "event_datetime": "2021-06-07 20:49:37.927",
    "event_type": "account_creation",
    "org_id": "16khy574",
    "policy": "beneficiary_validation_rules",
    "policy_details_api": {
        "policy_detail_api": [
            {
                "type": "champion",
                "id": "0",
                "customer": {"score": "0", "pvid": "1000049717", "review_status": "pass", "risk_rating": "neutral"},
            }
        ]
    },
    "policy_engine_version": "12.2.1",
    "policy_score": "0",
    "primary_industry": "government",
    "request_duration": "9",
    "request_id": "f63afc4e-f370-4b52-8ec8-8e2bf2a25a47",
    "request_result": "success",
    "review_status": "pass",
    "risk_rating": "neutral",
    "secondary_industry": "civilian",
    "service_type": "all",
    "session_id": "session-id",
    "session_id_query_count": "4",
    "summary_risk_score": "0",
    "up_reason_code": [
        "_ACC_EMAIL_GBL_VEL_1_4_4_4",
        "_ACC_EMAIL_GBL_AGE_LT_DY",
        "_ACC_TEL_GBL_VEL_1_4_4_4",
        "_ACC_TEL_GBL_AGE_LT_DY",
        "_DIG_ID_GBL_VEL_1_4_4_4",
        "_DIG_ID_GBL_AGE_LT_DY",
        "_ACC_EMAIL_LCL_VEL_1_4_4_4",
        "_ACC_EMAIL_LCL_AGE_LT_DY",
        "_ACC_TEL_LCL_VEL_1_4_4_4",
        "_ACC_TEL_LCL_AGE_LT_DY",
        "_DIG_ID_LCL_VEL_1_4_4_4",
        "_DIG_ID_LCL_AGE_LT_DY",
        "PID_LCL_AGE_ACC_EMAIL_LT_DAY",
        "PID_LCL_RLTD_ACC_EMAIL_PASSED_3",
        "_EXPRESSION_ERROR",
    ],
    "up_risk_rating": "neutral",
    "up_variables": {
        "_accemail_gbl_velocity_hour": "0",
        "_accemail_local_velocity_hour": "0",
        "_accphone_gbl_velocity_hour": "0",
        "_exactid_per_email_gbl_hour": "0",
    },
    "unknown_session": "yes",
}

INVALID_PROFILING_RESPONSE = {
    "date_of_birth": "20210607",
    "email": "user.email@example.net",
    "email_contains_dot": "yes",
    "email_domain": "example.net",
    "email_first_seen": "2021-06-07",
    "email_last_event": "2021-06-07",
    "email_last_update": "2021-06-07",
    "email_result": "success",
    "email_score": "0",
    "email_worst_score": "0",
}
