export const DEFAULT_DETAILS_INTITIAL_VALUES = {
  name: '',
  description: '',
  venueId: '',
  categoryId: '',
  subcategoryId: '',
  gtl_id: '',
  showType: '',
  showSubType: '',
  speaker: '',
  author: '',
  visa: '',
  stageDirector: '',
  performer: '',
  ean: '',
  durationMinutes: '',
  subcategoryConditionalFields: [],
}
