"""Add notificationSubscriptions default

Revision ID: 4a0337b7cbbc
Revises: 100648792e74
Create Date: 2021-03-25 15:39:51.516966

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "4a0337b7cbbc"
down_revision = "100648792e74"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.alter_column(
        "user",
        "notificationSubscriptions",
        server_default='{"marketing_push": true, "marketing_email": true}',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.alter_column(
        "user",
        "notificationSubscriptions",
        server_default=None,
    )
    # ### end Alembic commands ###
