"""user_notification_subscriptions

Revision ID: 9531102bcb21
Revises: 021d3f2434f0
Create Date: 2021-02-26 10:55:56.163918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "9531102bcb21"
down_revision = "021d3f2434f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic  ###
    op.add_column(
        "user", sa.Column("notificationSubscriptions", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic  ###
    op.drop_column("user", "notificationSubscriptions")
    # ### end Alembic commands ###
