"""Add offer.rankingWeight column

Revision ID: c83abec806af
Revises: e442fb5ac4e6
Create Date: 2021-05-19 09:09:51.376288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c83abec806af"
down_revision = "e442fb5ac4e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column("offer", sa.Column("rankingWeight", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column("offer", "rankingWeight")
    # ### end Alembic commands ###
