"""migrate_id_at_provider_part_1

Revision ID: 20290f0b5d4f
Revises: 9908a2709641
Create Date: 2021-04-30 14:11:44.426573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20290f0b5d4f"
down_revision = "9908a2709641"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("offer", sa.Column("idAtProvider", sa.Text, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("offer", "idAtProvider")
    # ### end Alembic commands ###
