"""has_completed_id_check

Revision ID: 6999a11484ba
Revises: 5d6f3407546c
Create Date: 2021-05-23 09:27:35.125371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6999a11484ba"
down_revision = "5d6f3407546c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic
    op.add_column("user", sa.Column("hasCompletedIdCheck", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic
    op.drop_column("user", "hasCompletedIdCheck")
    # ### end Alembic commands ###
