"""add_unique_constraint_for_activation_codes

Revision ID: ff04dc8fe18e
Revises: ddd5b5980f31
Create Date: 2021-04-27 14:02:40.018153

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "ff04dc8fe18e"
down_revision = "ddd5b5980f31"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_code_in_stock", "activation_code", ["stockId", "code"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_code_in_stock", "activation_code", type_="unique")
    # ### end Alembic commands ###
