"""Add beneficiary_fraud_check table

Revision ID: 212db74b847d
Revises: 3d9c82930092
Create Date: 2021-06-09 06:46:44.698631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "212db74b847d"
down_revision = "3d9c82930092"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table(
        "beneficiary_fraud_check",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("dateCreated", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("userId", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.TEXT(), nullable=False),
        sa.Column("thirdPartyId", sa.TEXT(), nullable=False),
        sa.Column("resultContent", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_beneficiary_fraud_check_userId"), "beneficiary_fraud_check", ["userId"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f("ix_beneficiary_fraud_check_userId"), table_name="beneficiary_fraud_check")
    op.drop_table("beneficiary_fraud_check")
    # ### end Alembic commands ###
