"""create_activation_code_table

Revision ID: ddd5b5980f31
Revises: 2f3af262e528
Create Date: 2021-04-19 14:55:09.619714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ddd5b5980f31"
down_revision = "2f3af262e528"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activation_code",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("expirationDate", sa.DateTime(), nullable=True),
        sa.Column("stockId", sa.BigInteger(), nullable=False),
        sa.Column("bookingId", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bookingId"],
            ["booking.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stockId"],
            ["stock.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_activation_code_bookingId"), "activation_code", ["bookingId"], unique=False)
    op.create_index(op.f("ix_activation_code_stockId"), "activation_code", ["stockId"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activation_code_stockId"), table_name="activation_code")
    op.drop_index(op.f("ix_activation_code_bookingId"), table_name="activation_code")
    op.drop_table("activation_code")
    # ### end Alembic commands ###
