"""un_nullable_fields_for_collective_booking
"""
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "24321401ffaa"
down_revision = "71e86ae4d410"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("collective_booking", "cancellationLimitDate", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column("collective_booking", "confirmationLimitDate", existing_type=postgresql.TIMESTAMP(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("collective_booking", "confirmationLimitDate", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("collective_booking", "cancellationLimitDate", existing_type=postgresql.TIMESTAMP(), nullable=True)
    # ### end Alembic commands ###
