"""FIXME: Cher auteur de cette migration : le message ci-dessous
apparaît dans la sortie de `alembic history`. Tu dois supprimer ce
FIXME et faire en sorte que le message ci-dessous soit en anglais,
clair, en une seule ligne et lisible (un peu comme un message de
commit). Exemple : Add "blob" column to "offer" table.

test-latt-lont
"""

from alembic import op
import sqlalchemy as sa


# pre/post deployment: pre
# revision identifiers, used by Alembic.
revision = "e032dae05965"
down_revision = "6c12bca98549"
branch_labels: tuple[str] | None = None
depends_on: list[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("venue", "longitude")
    op.drop_column("venue", "latitude")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("venue", sa.Column("latitude", sa.NUMERIC(precision=8, scale=5), autoincrement=False, nullable=True))
    op.add_column("venue", sa.Column("longitude", sa.NUMERIC(precision=8, scale=5), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
