"""FIXME: Cher·e auteur·ice de cette migration : le message ci-dessous
apparaît dans la sortie de `alembic history`. Tu dois supprimer ce
FIXME et faire en sorte que le message ci-dessous soit en anglais,
clair, en une seule ligne et lisible (un peu comme un message de
commit). Exemple : Add "blob" column to "offer" table.

empty message"""

import sqlalchemy as sa
from alembic import op


# pre/post deployment: pre
# revision identifiers, used by Alembic.
revision = '8d87812fe991'
down_revision = 'ab84d232f9b1'
branch_labels: tuple[str] | None = None
depends_on: list[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_jwt_perfs',
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('deviceId', sa.BigInteger(), nullable=False),
    sa.Column('refresh', sa.UUID(), nullable=False),
    sa.Column('access', sa.UUID(), nullable=False),
    sa.Column('expirationDatetime', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_jwt_perfs_access'), 'user_jwt_perfs', ['access'], unique=True)
    op.create_index(op.f('ix_user_jwt_perfs_expirationDatetime'), 'user_jwt_perfs', ['expirationDatetime'], unique=False)
    op.create_index(op.f('ix_user_jwt_perfs_refresh'), 'user_jwt_perfs', ['refresh'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_jwt_perfs_refresh'), table_name='user_jwt_perfs')
    op.drop_index(op.f('ix_user_jwt_perfs_expirationDatetime'), table_name='user_jwt_perfs')
    op.drop_index(op.f('ix_user_jwt_perfs_access'), table_name='user_jwt_perfs')
    op.drop_table('user_jwt_perfs')
    # ### end Alembic commands ###
