from pcapi.core.permissions import factories as perm_factories
from pcapi.core.permissions import models as perm_models
from pcapi.models import db


ROLE_PERMISSIONS: dict[str, list[perm_models.Permissions]] = {
    "admin": [
        perm_models.Permissions.READ_PERMISSIONS,
        perm_models.Permissions.READ_ADMIN_ACCOUNTS,
        perm_models.Permissions.MANAGE_ADMIN_ACCOUNTS,
        perm_models.Permissions.READ_TAGS,
        perm_models.Permissions.MANAGE_ACCOUNT_TAGS,
        perm_models.Permissions.MANAGE_ACCOUNT_TAGS_N2,
        perm_models.Permissions.MANAGE_TAGS_N2,
        perm_models.Permissions.MANAGE_OFFERER_TAG,
        perm_models.Permissions.MANAGE_OFFERS_AND_VENUES_TAGS,
        perm_models.Permissions.ANONYMIZE_PUBLIC_ACCOUNT,
        perm_models.Permissions.READ_USER_PROFILE_REFRESH_CAMPAIGN,
        perm_models.Permissions.MANAGE_USER_PROFILE_REFRESH_CAMPAIGN,
    ],
    "codir_admin": [
        perm_models.Permissions.READ_INCIDENTS,
        perm_models.Permissions.VALIDATE_COMMERCIAL_GESTURE,
    ],
    "support_n1": [
        perm_models.Permissions.READ_PUBLIC_ACCOUNT,
    ],
    "support_n2": [
        perm_models.Permissions.READ_PUBLIC_ACCOUNT,
        perm_models.Permissions.MANAGE_PUBLIC_ACCOUNT,
        perm_models.Permissions.SUSPEND_USER,
        perm_models.Permissions.EXTRACT_PUBLIC_ACCOUNT,
        perm_models.Permissions.MANAGE_ACCOUNT_UPDATE_REQUEST,
        perm_models.Permissions.CREATE_INCIDENTS,
        perm_models.Permissions.READ_FRAUDULENT_BOOKING_INFO,
    ],
    "support_n3": [
        perm_models.Permissions.ANONYMIZE_PUBLIC_ACCOUNT,
    ],
    "support_pro": [
        perm_models.Permissions.READ_PRO_ENTITY,
        perm_models.Permissions.READ_PRO_ENTREPRISE_INFO,
        perm_models.Permissions.READ_PRO_AE_INFO,
        perm_models.Permissions.MANAGE_PRO_ENTITY,
        perm_models.Permissions.DELETE_PRO_ENTITY,
        perm_models.Permissions.CREATE_PRO_ENTITY,
        perm_models.Permissions.CONNECT_AS_PRO,
        perm_models.Permissions.MANAGE_BOOKINGS,
        perm_models.Permissions.READ_BOOKINGS,
        perm_models.Permissions.READ_OFFERS,
        perm_models.Permissions.READ_REIMBURSEMENT_RULES,
        perm_models.Permissions.READ_INCIDENTS,
        perm_models.Permissions.READ_TECH_PARTNERS,
        perm_models.Permissions.CREATE_INCIDENTS,
        perm_models.Permissions.READ_FRAUDULENT_BOOKING_INFO,
        perm_models.Permissions.CLOSE_OFFERER,
        perm_models.Permissions.READ_NON_PAYMENT_NOTICES,
    ],
    "support_pro_n2": [
        perm_models.Permissions.MOVE_SIRET,
        perm_models.Permissions.ADVANCED_PRO_SUPPORT,
        perm_models.Permissions.CREATE_INCIDENTS,
        perm_models.Permissions.MANAGE_INCIDENTS,
        perm_models.Permissions.READ_NON_PAYMENT_NOTICES,
        perm_models.Permissions.MANAGE_NON_PAYMENT_NOTICES,
    ],
    "support_partenaires_techniques": [
        perm_models.Permissions.READ_PRO_ENTITY,
        perm_models.Permissions.MANAGE_PRO_ENTITY,
        perm_models.Permissions.CONNECT_AS_PRO,
        perm_models.Permissions.READ_BOOKINGS,
        perm_models.Permissions.READ_OFFERS,
        perm_models.Permissions.READ_REIMBURSEMENT_RULES,
        perm_models.Permissions.READ_INCIDENTS,
        perm_models.Permissions.READ_TECH_PARTNERS,
        perm_models.Permissions.MANAGE_TECH_PARTNERS,
    ],
    "fraude_conformite": [
        perm_models.Permissions.PRO_FRAUD_ACTIONS,
        perm_models.Permissions.READ_PUBLIC_ACCOUNT,
        perm_models.Permissions.READ_PRO_ENTITY,
        perm_models.Permissions.READ_PRO_ENTREPRISE_INFO,
        perm_models.Permissions.READ_PRO_SENSITIVE_INFO,
        perm_models.Permissions.READ_PRO_AE_INFO,
        perm_models.Permissions.VALIDATE_OFFERER,
        perm_models.Permissions.MANAGE_BOOKINGS,
        perm_models.Permissions.READ_BOOKINGS,
        perm_models.Permissions.MANAGE_OFFERS,
        perm_models.Permissions.READ_OFFERS,
        perm_models.Permissions.MULTIPLE_OFFERS_ACTIONS,
        perm_models.Permissions.CREATE_INCIDENTS,
        perm_models.Permissions.READ_FRAUDULENT_BOOKING_INFO,
        perm_models.Permissions.MANAGE_FRAUDULENT_BOOKING_INFO,
    ],
    "fraude_jeunes": [
        perm_models.Permissions.READ_PUBLIC_ACCOUNT,
        perm_models.Permissions.SUSPEND_USER,
        perm_models.Permissions.UNSUSPEND_USER,
        perm_models.Permissions.BENEFICIARY_FRAUD_ACTIONS,
        perm_models.Permissions.MANAGE_BOOKINGS,
        perm_models.Permissions.READ_BOOKINGS,
        perm_models.Permissions.READ_FRAUDULENT_BOOKING_INFO,
        perm_models.Permissions.MANAGE_FRAUDULENT_BOOKING_INFO,
    ],
    "daf": [
        perm_models.Permissions.READ_REIMBURSEMENT_RULES,
        perm_models.Permissions.READ_INCIDENTS,
        perm_models.Permissions.CREATE_INCIDENTS,
        perm_models.Permissions.MANAGE_INCIDENTS,
    ],
    "responsable_daf": [
        perm_models.Permissions.READ_REIMBURSEMENT_RULES,
        perm_models.Permissions.CREATE_REIMBURSEMENT_RULES,
    ],
    "partenaire_technique": [
        perm_models.Permissions.READ_TECH_PARTNERS,
        perm_models.Permissions.MANAGE_TECH_PARTNERS,
    ],
    "programmation_market": [
        perm_models.Permissions.READ_PUBLIC_ACCOUNT,
        perm_models.Permissions.READ_PRO_ENTITY,
        perm_models.Permissions.MANAGE_ACCOUNT_TAGS,
        perm_models.Permissions.MANAGE_PRO_ENTITY,
        perm_models.Permissions.CONNECT_AS_PRO,
        perm_models.Permissions.VALIDATE_OFFERER,
        perm_models.Permissions.MANAGE_OFFERS,
        perm_models.Permissions.READ_OFFERS,
        perm_models.Permissions.MULTIPLE_OFFERS_ACTIONS,
        perm_models.Permissions.READ_TAGS,
        perm_models.Permissions.READ_CHRONICLE,
        perm_models.Permissions.MANAGE_CHRONICLE,
        perm_models.Permissions.READ_HIGHLIGHT,
        perm_models.Permissions.MANAGE_HIGHLIGHT,
    ],
    "homologation": [
        perm_models.Permissions.READ_PRO_ENTITY,
        perm_models.Permissions.READ_PRO_ENTREPRISE_INFO,
        perm_models.Permissions.READ_PRO_SENSITIVE_INFO,
        perm_models.Permissions.MANAGE_PRO_ENTITY,
        perm_models.Permissions.CONNECT_AS_PRO,
        perm_models.Permissions.VALIDATE_OFFERER,
    ],
    "homologation_pro": [
        perm_models.Permissions.CREATE_PRO_ENTITY,
    ],
    "product_management": [
        perm_models.Permissions.FEATURE_FLIPPING,
        perm_models.Permissions.CONNECT_AS_PRO,
    ],
    "charge_developpement": [
        perm_models.Permissions.READ_PRO_ENTITY,
        perm_models.Permissions.READ_SPECIAL_EVENTS,
        perm_models.Permissions.MANAGE_SPECIAL_EVENTS,
        perm_models.Permissions.READ_TECH_PARTNERS,
    ],
    "lecture_seule": [
        perm_models.Permissions.READ_ADMIN_ACCOUNTS,
        perm_models.Permissions.READ_PUBLIC_ACCOUNT,
        perm_models.Permissions.READ_PRO_ENTITY,
        perm_models.Permissions.READ_BOOKINGS,
        perm_models.Permissions.READ_OFFERS,
        perm_models.Permissions.READ_TAGS,
        perm_models.Permissions.READ_CHRONICLE,
        perm_models.Permissions.READ_SPECIAL_EVENTS,
        perm_models.Permissions.READ_TECH_PARTNERS,
        perm_models.Permissions.READ_USER_PROFILE_REFRESH_CAMPAIGN,
    ],
    "qa": [
        perm_models.Permissions.READ_PERMISSIONS,
        perm_models.Permissions.MANAGE_PERMISSIONS,
        perm_models.Permissions.READ_ADMIN_ACCOUNTS,
        perm_models.Permissions.MANAGE_ADMIN_ACCOUNTS,
        perm_models.Permissions.FEATURE_FLIPPING,
        perm_models.Permissions.PRO_FRAUD_ACTIONS,
        perm_models.Permissions.READ_FRAUDULENT_BOOKING_INFO,
        perm_models.Permissions.MANAGE_FRAUDULENT_BOOKING_INFO,
        perm_models.Permissions.BENEFICIARY_FRAUD_ACTIONS,
        perm_models.Permissions.READ_PUBLIC_ACCOUNT,
        perm_models.Permissions.MANAGE_PUBLIC_ACCOUNT,
        perm_models.Permissions.SUSPEND_USER,
        perm_models.Permissions.UNSUSPEND_USER,
        perm_models.Permissions.READ_PRO_ENTITY,
        perm_models.Permissions.READ_PRO_ENTREPRISE_INFO,
        perm_models.Permissions.READ_PRO_SENSITIVE_INFO,
        perm_models.Permissions.READ_PRO_AE_INFO,
        perm_models.Permissions.MANAGE_PRO_ENTITY,
        perm_models.Permissions.DELETE_PRO_ENTITY,
        perm_models.Permissions.CREATE_PRO_ENTITY,
        perm_models.Permissions.CONNECT_AS_PRO,
        perm_models.Permissions.MOVE_SIRET,
        perm_models.Permissions.ADVANCED_PRO_SUPPORT,
        perm_models.Permissions.MANAGE_BOOKINGS,
        perm_models.Permissions.READ_BOOKINGS,
        perm_models.Permissions.READ_OFFERS,
        perm_models.Permissions.MANAGE_OFFERS,
        perm_models.Permissions.MULTIPLE_OFFERS_ACTIONS,
        perm_models.Permissions.VALIDATE_OFFERER,
        perm_models.Permissions.READ_TAGS,
        perm_models.Permissions.MANAGE_ACCOUNT_TAGS,
        perm_models.Permissions.MANAGE_ACCOUNT_TAGS_N2,
        perm_models.Permissions.MANAGE_OFFERER_TAG,
        perm_models.Permissions.MANAGE_TAGS_N2,
        perm_models.Permissions.MANAGE_OFFERS_AND_VENUES_TAGS,
        perm_models.Permissions.READ_REIMBURSEMENT_RULES,
        perm_models.Permissions.CREATE_REIMBURSEMENT_RULES,
        perm_models.Permissions.READ_INCIDENTS,
        perm_models.Permissions.MANAGE_INCIDENTS,
        perm_models.Permissions.READ_TECH_PARTNERS,
        perm_models.Permissions.MANAGE_TECH_PARTNERS,
        perm_models.Permissions.READ_CHRONICLE,
        perm_models.Permissions.MANAGE_CHRONICLE,
        perm_models.Permissions.READ_HIGHLIGHT,
        perm_models.Permissions.MANAGE_HIGHLIGHT,
        perm_models.Permissions.MANAGE_ACCOUNT_UPDATE_REQUEST,
        perm_models.Permissions.CREATE_INCIDENTS,
        perm_models.Permissions.CLOSE_OFFERER,
        perm_models.Permissions.READ_NON_PAYMENT_NOTICES,
        perm_models.Permissions.MANAGE_NON_PAYMENT_NOTICES,
        perm_models.Permissions.READ_USER_PROFILE_REFRESH_CAMPAIGN,
        perm_models.Permissions.MANAGE_USER_PROFILE_REFRESH_CAMPAIGN,
    ],
    "global_access": [
        perm_models.Permissions.READ_ADMIN_ACCOUNTS,
        perm_models.Permissions.MANAGE_ADMIN_ACCOUNTS,
        perm_models.Permissions.FEATURE_FLIPPING,
        perm_models.Permissions.PRO_FRAUD_ACTIONS,
        perm_models.Permissions.READ_FRAUDULENT_BOOKING_INFO,
        perm_models.Permissions.MANAGE_FRAUDULENT_BOOKING_INFO,
        perm_models.Permissions.BENEFICIARY_FRAUD_ACTIONS,
        perm_models.Permissions.READ_PUBLIC_ACCOUNT,
        perm_models.Permissions.MANAGE_PUBLIC_ACCOUNT,
        perm_models.Permissions.SUSPEND_USER,
        perm_models.Permissions.UNSUSPEND_USER,
        perm_models.Permissions.READ_PRO_ENTITY,
        perm_models.Permissions.READ_PRO_ENTREPRISE_INFO,
        perm_models.Permissions.READ_PRO_SENSITIVE_INFO,
        perm_models.Permissions.READ_PRO_AE_INFO,
        perm_models.Permissions.MANAGE_PRO_ENTITY,
        perm_models.Permissions.DELETE_PRO_ENTITY,
        perm_models.Permissions.CREATE_PRO_ENTITY,
        perm_models.Permissions.CONNECT_AS_PRO,
        perm_models.Permissions.MOVE_SIRET,
        perm_models.Permissions.ADVANCED_PRO_SUPPORT,
        perm_models.Permissions.MANAGE_BOOKINGS,
        perm_models.Permissions.READ_BOOKINGS,
        perm_models.Permissions.READ_OFFERS,
        perm_models.Permissions.MANAGE_OFFERS,
        perm_models.Permissions.MULTIPLE_OFFERS_ACTIONS,
        perm_models.Permissions.VALIDATE_OFFERER,
        perm_models.Permissions.READ_TAGS,
        perm_models.Permissions.MANAGE_ACCOUNT_TAGS,
        perm_models.Permissions.MANAGE_ACCOUNT_TAGS_N2,
        perm_models.Permissions.MANAGE_OFFERER_TAG,
        perm_models.Permissions.MANAGE_TAGS_N2,
        perm_models.Permissions.MANAGE_OFFERS_AND_VENUES_TAGS,
        perm_models.Permissions.READ_REIMBURSEMENT_RULES,
        perm_models.Permissions.CREATE_REIMBURSEMENT_RULES,
        perm_models.Permissions.READ_INCIDENTS,
        perm_models.Permissions.MANAGE_INCIDENTS,
        perm_models.Permissions.READ_TECH_PARTNERS,
        perm_models.Permissions.MANAGE_TECH_PARTNERS,
        perm_models.Permissions.READ_CHRONICLE,
        perm_models.Permissions.MANAGE_CHRONICLE,
        perm_models.Permissions.READ_HIGHLIGHT,
        perm_models.Permissions.MANAGE_HIGHLIGHT,
        perm_models.Permissions.MANAGE_ACCOUNT_UPDATE_REQUEST,
        perm_models.Permissions.BENEFICIARY_MANUAL_REVIEW,
        perm_models.Permissions.READ_BENEFICIARY_BONUS_CREDIT,
        perm_models.Permissions.REQUEST_BENEFICIARY_BONUS_CREDIT,
        perm_models.Permissions.CREATE_INCIDENTS,
        perm_models.Permissions.CLOSE_OFFERER,
        perm_models.Permissions.READ_NON_PAYMENT_NOTICES,
        perm_models.Permissions.MANAGE_NON_PAYMENT_NOTICES,
        perm_models.Permissions.READ_USER_PROFILE_REFRESH_CAMPAIGN,
        perm_models.Permissions.MANAGE_USER_PROFILE_REFRESH_CAMPAIGN,
    ],
    "dpo": [
        perm_models.Permissions.ANONYMIZE_PUBLIC_ACCOUNT,
        perm_models.Permissions.READ_PUBLIC_ACCOUNT,
        perm_models.Permissions.EXTRACT_PUBLIC_ACCOUNT,
    ],
    "gestionnaire_des_droits": [
        perm_models.Permissions.READ_PERMISSIONS,
        perm_models.Permissions.MANAGE_PERMISSIONS,
    ],
    "connect_as_pro": [
        perm_models.Permissions.CONNECT_AS_PRO,
    ],
}


def create_roles_with_permissions() -> None:
    # Roles have already been created from enum in sync_db_roles()
    roles_ids_in_db = {role.name: role.id for role in db.session.query(perm_models.Role).all()}
    perm_ids_in_db = {perm.name: perm.id for perm in db.session.query(perm_models.Permission).all()}

    for role_name, perms in ROLE_PERMISSIONS.items():
        for perm in perms:
            perm_factories.RolePermissionFactory.create(
                roleId=roles_ids_in_db[role_name], permissionId=perm_ids_in_db[perm.name]
            )
