from os import getenv
import random
import string

SOURCE_PROJECT = getenv("SOURCE_PROJECT")
SOURCE_INSTANCE = getenv("SOURCE_INSTANCE")
SOURCE_INSTANCE_REGION = getenv("SOURCE_INSTANCE_REGION")
SOURCE_USER = getenv("SOURCE_USER")
SOURCE_USER_TEMP_PASSWORD = getenv("SOURCE_USER_TEMP_PASSWORD",
                                   ''.join(random.choice(string.ascii_letters + string.digits) for i in range(13)))
SOURCE_DATABASE_NAME = getenv("SOURCE_DATABASE_NAME", SOURCE_USER)

DEST_PROJECT = getenv("DEST_PROJECT")
DEST_INSTANCE = getenv("DEST_INSTANCE")
DEST_INSTANCE_REGION = getenv("DEST_INSTANCE_REGION")
DEST_INSTANCE_IP_ADDRESS_TYPE = getenv("DEST_INSTANCE_IP_ADDRESS_TYPE", "PRIVATE").upper()
DEST_DATABASE_HOST = getenv("DEST_DATABASE_HOST")
DEST_DATABASE_PORT = getenv("DEST_DATABASE_PORT", 5432)
DEST_NEW_USER = getenv("DEST_NEW_USER")
DEST_NEW_USER_PASSWORD = getenv("DEST_NEW_USER_PASSWORD")
DEST_DATABASE_NAME = getenv("DEST_DATABASE_NAME", DEST_NEW_USER)

ANONYMIZE_SQL_SCRIPT_PATH = getenv("ANONYMIZE_SQL_SCRIPT_PATH")
PCAPI_ROOT_PATH = getenv("PCAPI_ROOT_PATH")
IMPORT_USERS_SCRIPT_PATH = getenv("IMPORT_USERS_SCRIPT_PATH")
USERS_CSV_PATH = getenv("USERS_CSV_PATH")

TABLES_TO_EMPTY = getenv("TABLES_TO_EMPTY", "").split(" ") if getenv("TABLES_TO_EMPTY") != "" else []
DUMP_BUCKET = getenv("DUMP_BUCKET")
