import { selectOfferById } from '../offer'
import state from './mockState'

const mockState = {
  data: {
    bookings: [],
    events: [
      {
        id: 'AUHA',
        accessibility: '\u0000',
        ageMax: null,
        ageMin: null,
        conditions: null,
        dateModifiedAtLastProvider: '2018-11-13T09:38:55.047968Z',
        description:
          "Venez vivre l'expérience de la culture du vin dans l'Antiquité !\n\nTous les jeudi à 15h00.\nChaussures adaptées, se présenter à la billetterie un quart d'heure avant.",
        durationMinutes: 60,
        extraData: null,
        firstThumbDominantColor: null,
        idAtProviders: null,
        isNational: false,
        lastProviderId: null,
        mediaUrls: [],
        modelName: 'Event',
        name: 'Visite guidée',
        thumbCount: 0,
        type: 'EventType.MUSEES_PATRIMOINE',
      },
      {
        id: 'AUGQ',
        accessibility: '\u0000',
        ageMax: null,
        ageMin: null,
        conditions: null,
        dateModifiedAtLastProvider: '2018-11-12T10:01:50.320801Z',
        description: 'blavlavla',
        durationMinutes: 120,
        extraData: null,
        firstThumbDominantColor: null,
        idAtProviders: null,
        isNational: false,
        lastProviderId: null,
        mediaUrls: [],
        modelName: 'Event',
        name: 'Expositions',
        thumbCount: 0,
        type: 'EventType.MUSEES_PATRIMOINE',
      },
      {
        id: 'AUGA',
        accessibility: '\u0000',
        ageMax: null,
        ageMin: null,
        conditions: null,
        dateModifiedAtLastProvider: '2018-11-09T17:46:09.404655Z',
        description: null,
        durationMinutes: 75,
        extraData: {
          author: 'Les couloirs du temps ',
          musicSubType: '512',
          musicType: '501',
          performer: 'Michael Alizon et Jean René Mourot ',
        },
        firstThumbDominantColor: null,
        idAtProviders: null,
        isNational: false,
        lastProviderId: null,
        mediaUrls: [],
        modelName: 'Event',
        name: 'Les couloirs du Temps ',
        thumbCount: 0,
        type: 'EventType.MUSIQUE',
      },
      {
        id: 'AUFQ',
        accessibility: '\u0000',
        ageMax: null,
        ageMin: null,
        conditions: null,
        dateModifiedAtLastProvider: '2018-11-09T16:38:22.652992Z',
        description: null,
        durationMinutes: 75,
        extraData: {
          author: 'TOXIC PISTOLEROS ',
          musicSubType: '832',
          musicType: '820',
        },
        firstThumbDominantColor: null,
        idAtProviders: null,
        isNational: false,
        lastProviderId: null,
        mediaUrls: [],
        modelName: 'Event',
        name: 'SAISON 2018',
        thumbCount: 0,
        type: 'EventType.MUSIQUE',
      },
      {
        id: 'AUFA',
        accessibility: '\u0000',
        ageMax: null,
        ageMin: null,
        conditions: null,
        dateModifiedAtLastProvider: '2018-11-09T14:12:37.956923Z',
        description:
          'Freestyle revient pour sa quatrième édition avec son énergie ultra-participative et son esprit défricheur de nouvelles tendances. « Choisis ton style » est le mot d’ordre de ce week-end : mode, glisse, battle et workshop de danse, marché de créateurs, sports urbains, jams, training autour de nombreuses pratiques artistiques issues de la street culture. \n\nParce que l’art permet de réinventer l’urbain, pousser les murs et transformer le béton, Freestyle laisse place à un espace libre, créatif et ouvert à tous. http://bit.ly/FreestyleVillette18',
        durationMinutes: 450,
        extraData: null,
        firstThumbDominantColor: null,
        idAtProviders: null,
        isNational: false,
        lastProviderId: null,
        mediaUrls: [],
        modelName: 'Event',
        name: 'Freestyle',
        thumbCount: 0,
        type: 'EventType.PRATIQUE_ARTISTIQUE',
      },
      {
        id: 'AUEQ',
        accessibility: '\u0000',
        ageMax: null,
        ageMin: null,
        conditions: null,
        dateModifiedAtLastProvider: '2018-11-09T13:55:42.386565Z',
        description:
          'Courez visiter !\nEn compagnie d’un « running » guide, vous découvrirez le patrimoine au gré de votre course. Le parcours a été conçu afin de permettre la course en ville, et les points d’arrêts choisis auprès de sites remarquables qui vous seront présentés.\nC’est aussi un regard inédit que vous porterez sur votre environnement familier ou non. Ce parcours reste une balade découverte accessible à toutes et à tous, même aux débutants !\n\nParcours Street-Art sur le canal Saint-Denis et au Parc de la Villette (5 à 6 kilomètres)\n\nUne collation de fin de course vous sera offerte\n\nhttps://lavillette.com/programmation/running-visites_e227',
        durationMinutes: 60,
        extraData: {
          speaker: "Sébastien d'Anjou",
        },
        firstThumbDominantColor: null,
        idAtProviders: null,
        isNational: false,
        lastProviderId: null,
        mediaUrls: [],
        modelName: 'Event',
        name: 'Running visites',
        thumbCount: 0,
        type: 'EventType.PRATIQUE_ARTISTIQUE',
      },
    ],
    eventOccurrences: [
      {
        id: 'F9WQ',
        accessibility: '\u0000',
        beginningDatetime: '2018-11-29T14:00:13Z',
        dateModifiedAtLastProvider: '2018-11-13T09:40:28.391907Z',
        endDatetime: '2018-11-30T15:00:13Z',
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'EventOccurrence',
        offerId: 'AXBQ',
        type: null,
      },
      {
        id: 'F9WA',
        accessibility: '\u0000',
        beginningDatetime: '2018-11-22T14:00:13Z',
        dateModifiedAtLastProvider: '2018-11-13T09:40:04.355358Z',
        endDatetime: '2018-11-23T15:00:13Z',
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'EventOccurrence',
        offerId: 'AXBQ',
        type: null,
      },
      {
        id: 'F9VQ',
        accessibility: '\u0000',
        beginningDatetime: '2018-11-15T14:00:13Z',
        dateModifiedAtLastProvider: '2018-11-13T09:39:19.071411Z',
        endDatetime: '2018-11-16T15:00:13Z',
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'EventOccurrence',
        offerId: 'AXBQ',
        type: null,
      },
      {
        id: 'F9VA',
        accessibility: '\u0000',
        beginningDatetime: '2019-04-02T09:00:53Z',
        dateModifiedAtLastProvider: '2018-11-12T10:02:59.638640Z',
        endDatetime: '2019-04-02T10:00:53Z',
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'EventOccurrence',
        offerId: 'AXAQ',
        type: null,
      },
      {
        id: 'F9UQ',
        accessibility: '\u0000',
        beginningDatetime: '2019-04-01T09:00:53Z',
        dateModifiedAtLastProvider: '2018-11-12T10:02:31.569972Z',
        endDatetime: '2019-04-02T16:00:53Z',
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'EventOccurrence',
        offerId: 'AXAQ',
        type: null,
      },
      {
        id: 'F9TQ',
        accessibility: '\u0000',
        beginningDatetime: '2018-11-30T19:30:00Z',
        dateModifiedAtLastProvider: '2018-11-09T17:46:29.713160Z',
        endDatetime: '2018-12-01T21:00:00Z',
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'EventOccurrence',
        offerId: 'AXAA',
        type: null,
      },
      {
        id: 'F9TA',
        accessibility: '\u0000',
        beginningDatetime: '2018-11-16T19:30:00Z',
        dateModifiedAtLastProvider: '2018-11-09T16:38:50.982074Z',
        endDatetime: '2018-11-17T21:00:00Z',
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'EventOccurrence',
        offerId: 'AW7Q',
        type: null,
      },
      {
        id: 'F9SA',
        accessibility: '\u0000',
        beginningDatetime: '2018-12-15T12:00:48Z',
        dateModifiedAtLastProvider: '2018-11-09T14:14:02.318907Z',
        endDatetime: '2018-12-15T19:30:48Z',
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'EventOccurrence',
        offerId: 'AW6Q',
        type: null,
      },
      {
        id: 'F9RQ',
        accessibility: '\u0000',
        beginningDatetime: '2018-12-14T20:00:48Z',
        dateModifiedAtLastProvider: '2018-11-09T14:13:36.841907Z',
        endDatetime: '2018-12-14T23:00:48Z',
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'EventOccurrence',
        offerId: 'AW6Q',
        type: null,
      },
      {
        id: 'F9SQ',
        accessibility: '\u0000',
        beginningDatetime: '2018-12-16T12:00:48Z',
        dateModifiedAtLastProvider: '2018-11-09T14:14:20.674829Z',
        endDatetime: '2018-12-16T19:30:48Z',
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'EventOccurrence',
        offerId: 'AW6Q',
        type: null,
      },
      {
        id: 'F9QQ',
        accessibility: '\u0000',
        beginningDatetime: '2018-11-10T10:00:44Z',
        dateModifiedAtLastProvider: '2018-11-09T13:56:05.407050Z',
        endDatetime: '2018-11-11T10:00:44Z',
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'EventOccurrence',
        offerId: 'AW6A',
        type: null,
      },
      {
        id: 'F9RA',
        accessibility: '\u0000',
        beginningDatetime: '2018-12-08T10:00:44Z',
        dateModifiedAtLastProvider: '2018-11-09T13:58:12.855236Z',
        endDatetime: '2018-12-09T11:00:44Z',
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'EventOccurrence',
        offerId: 'AW6A',
        type: null,
      },
    ],
    mediations: [
      {
        id: 'AXMQ',
        authorId: 'AQ',
        backText: null,
        credit: 'undefined',
        dateCreated: '2018-11-13T09:46:58.484769Z',
        dateModifiedAtLastProvider: '2018-11-13T09:46:58.484754Z',
        firstThumbDominantColor: [143, 151, 166],
        frontText: null,
        idAtProviders: null,
        isActive: true,
        lastProviderId: null,
        modelName: 'Mediation',
        offerId: 'AXBQ',
        thumbCount: 1,
        tutoIndex: null,
      },
      {
        id: 'AXMA',
        authorId: 'AUNA',
        backText: null,
        credit: 'undefined',
        dateCreated: '2018-11-09T17:48:12.034115Z',
        dateModifiedAtLastProvider: '2018-11-09T17:48:12.034104Z',
        firstThumbDominantColor: [20, 20, 20],
        frontText: null,
        idAtProviders: null,
        isActive: true,
        lastProviderId: null,
        modelName: 'Mediation',
        offerId: 'AXAA',
        thumbCount: 1,
        tutoIndex: null,
      },
      {
        id: 'AXLQ',
        authorId: 'AUNA',
        backText: null,
        credit: 'undefined',
        dateCreated: '2018-11-09T16:40:58.783118Z',
        dateModifiedAtLastProvider: '2018-11-09T16:40:58.783107Z',
        firstThumbDominantColor: [27, 28, 29],
        frontText: null,
        idAtProviders: null,
        isActive: true,
        lastProviderId: null,
        modelName: 'Mediation',
        offerId: 'AW7Q',
        thumbCount: 1,
        tutoIndex: null,
      },
      {
        id: 'AXLA',
        authorId: 'AUMQ',
        backText: null,
        credit: 'undefined',
        dateCreated: '2018-11-09T14:53:04.878330Z',
        dateModifiedAtLastProvider: '2018-11-09T14:53:04.878317Z',
        firstThumbDominantColor: [54, 53, 99],
        frontText: null,
        idAtProviders: null,
        isActive: true,
        lastProviderId: null,
        modelName: 'Mediation',
        offerId: 'AW7A',
        thumbCount: 1,
        tutoIndex: null,
      },
      {
        id: 'AXKQ',
        authorId: 'AHVA',
        backText: null,
        credit: 'DR',
        dateCreated: '2018-11-09T14:16:54.797731Z',
        dateModifiedAtLastProvider: '2018-11-09T14:16:54.797720Z',
        firstThumbDominantColor: [16, 37, 44],
        frontText: null,
        idAtProviders: null,
        isActive: true,
        lastProviderId: null,
        modelName: 'Mediation',
        offerId: 'AW6Q',
        thumbCount: 1,
        tutoIndex: null,
      },
      {
        id: 'AXKA',
        authorId: 'AHVA',
        backText: null,
        credit: 'DR',
        dateCreated: '2018-11-09T14:10:20.048948Z',
        dateModifiedAtLastProvider: '2018-11-09T14:10:20.048926Z',
        firstThumbDominantColor: [214, 109, 109],
        frontText: null,
        idAtProviders: null,
        isActive: true,
        lastProviderId: null,
        modelName: 'Mediation',
        offerId: 'AW6A',
        thumbCount: 1,
        tutoIndex: null,
      },
      {
        id: 'AXJQ',
        authorId: 'AFWQ',
        backText: null,
        credit: 'undefined',
        dateCreated: '2018-11-09T09:12:30.745614Z',
        dateModifiedAtLastProvider: '2018-11-09T09:12:30.745603Z',
        firstThumbDominantColor: [202, 178, 165],
        frontText: null,
        idAtProviders: null,
        isActive: true,
        lastProviderId: null,
        modelName: 'Mediation',
        offerId: 'AW5Q',
        thumbCount: 1,
        tutoIndex: null,
      },
    ],
    offers: [
      {
        id: 'AXCA',
        bookingEmail: null,
        dateCreated: '2018-11-13T09:54:56.103080Z',
        dateModifiedAtLastProvider: '2018-11-13T09:54:56.103073Z',
        eventId: null,
        idAtProviders: null,
        isActive: true,
        lastProviderId: null,
        modelName: 'Offer',
        thingId: 'V4',
        venueId: 'AYJA',
        eventOccurrencesIds: [],
        mediationsIds: [],
        stocksIds: ['DCRA'],
      },
      {
        id: 'AXBQ',
        bookingEmail: null,
        dateCreated: '2018-11-13T09:38:55.050315Z',
        dateModifiedAtLastProvider: '2018-11-13T09:38:55.050308Z',
        eventId: 'AUHA',
        idAtProviders: null,
        isActive: true,
        lastProviderId: null,
        modelName: 'Offer',
        thingId: null,
        venueId: 'AYJA',
        eventOccurrencesIds: ['F9WQ', 'F9WA', 'F9VQ'],
        mediationsIds: ['AXMQ'],
        stocksIds: ['DCQQ', 'DCQA', 'DCPQ'],
      },
      {
        id: 'AXBA',
        bookingEmail: null,
        dateCreated: '2018-11-12T10:12:08.367935Z',
        dateModifiedAtLastProvider: '2018-11-12T10:12:08.367924Z',
        eventId: null,
        idAtProviders: null,
        isActive: false,
        lastProviderId: null,
        modelName: 'Offer',
        thingId: 'VY',
        venueId: 'AVQQ',
        eventOccurrencesIds: [],
        mediationsIds: [],
        stocksIds: ['DCPA'],
      },
      {
        id: 'AXAQ',
        bookingEmail: null,
        dateCreated: '2018-11-12T10:01:50.351230Z',
        dateModifiedAtLastProvider: '2018-11-12T10:01:50.351220Z',
        eventId: 'AUGQ',
        idAtProviders: null,
        isActive: false,
        lastProviderId: null,
        modelName: 'Offer',
        thingId: null,
        venueId: 'AVQQ',
        eventOccurrencesIds: ['F9VA', 'F9UQ'],
        mediationsIds: [],
        stocksIds: ['DC8Q', 'DC8A'],
      },
      {
        id: 'AXAA',
        bookingEmail: null,
        dateCreated: '2018-11-09T17:46:09.429789Z',
        dateModifiedAtLastProvider: '2018-11-09T17:46:09.429776Z',
        eventId: 'AUGA',
        idAtProviders: null,
        isActive: true,
        lastProviderId: null,
        modelName: 'Offer',
        thingId: null,
        venueId: 'AYHA',
        eventOccurrencesIds: ['F9TQ'],
        mediationsIds: ['AXMA'],
        stocksIds: ['DCMQ'],
      },
      {
        id: 'AW7Q',
        bookingEmail: null,
        dateCreated: '2018-11-09T16:38:22.656928Z',
        dateModifiedAtLastProvider: '2018-11-09T16:38:22.656913Z',
        eventId: 'AUFQ',
        idAtProviders: null,
        isActive: true,
        lastProviderId: null,
        modelName: 'Offer',
        thingId: null,
        venueId: 'AYHA',
        eventOccurrencesIds: ['F9TA'],
        mediationsIds: ['AXLQ'],
        stocksIds: ['DCMA'],
      },
      {
        id: 'AW7A',
        bookingEmail: null,
        dateCreated: '2018-11-09T14:48:17.211139Z',
        dateModifiedAtLastProvider: '2018-11-09T14:48:17.211122Z',
        eventId: null,
        idAtProviders: null,
        isActive: false,
        lastProviderId: null,
        modelName: 'Offer',
        thingId: 'VU',
        venueId: 'AYGA',
        eventOccurrencesIds: [],
        mediationsIds: ['AXLA'],
        stocksIds: ['DCLQ'],
      },
      {
        id: 'AW6Q',
        bookingEmail: null,
        dateCreated: '2018-11-09T14:12:37.961493Z',
        dateModifiedAtLastProvider: '2018-11-09T14:12:37.961483Z',
        eventId: 'AUFA',
        idAtProviders: null,
        isActive: true,
        lastProviderId: null,
        modelName: 'Offer',
        thingId: null,
        venueId: '5E',
        eventOccurrencesIds: ['F9SA', 'F9RQ', 'F9SQ'],
        mediationsIds: ['AXKQ'],
        stocksIds: ['DCKQ', 'DCKA', 'DCLA'],
      },
      {
        id: 'AW6A',
        bookingEmail: null,
        dateCreated: '2018-11-09T13:55:42.391056Z',
        dateModifiedAtLastProvider: '2018-11-09T13:55:42.391040Z',
        eventId: 'AUEQ',
        idAtProviders: null,
        isActive: true,
        lastProviderId: null,
        modelName: 'Offer',
        thingId: null,
        venueId: '5E',
        eventOccurrencesIds: ['F9QQ', 'F9RA'],
        mediationsIds: ['AXKA'],
        stocksIds: ['DCJA', 'DCJQ'],
      },
      {
        id: 'AW5Q',
        bookingEmail: null,
        dateCreated: '2018-11-09T09:12:10.259068Z',
        dateModifiedAtLastProvider: '2018-11-09T09:12:10.259054Z',
        eventId: null,
        idAtProviders: null,
        isActive: false,
        lastProviderId: null,
        modelName: 'Offer',
        thingId: 'VQ',
        venueId: 'AQQQ',
        eventOccurrencesIds: [],
        mediationsIds: ['AXJQ'],
        stocksIds: [],
      },
    ],
    offerers: [
      {
        id: 'ANYQ',
        address: '2 RUE JEAN PERRIN',
        bic: null,
        city: 'COLOMBELLES',
        dateCreated: '2018-10-20T13:43:58.668348Z',
        dateModifiedAtLastProvider: '2018-10-20T13:43:58.668341Z',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isActive: true,
        isValidated: true,
        lastProviderId: null,
        modelName: 'Offerer',
        nOffers: 0,
        name: '180G',
        postalCode: '14460',
        siren: '824368385',
        thumbCount: 0,
        managedVenuesIds: ['AUJA', 'AU9Q'],
      },
      {
        id: 'AFRQ',
        address: '5 RUE JAVELIN PAGNON',
        bic: null,
        city: 'SAINT ETIENNE',
        dateCreated: '2018-08-24T09:10:27.373786Z',
        dateModifiedAtLastProvider: '2018-08-24T09:10:27.373774Z',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isActive: true,
        isValidated: true,
        lastProviderId: null,
        modelName: 'Offerer',
        nOffers: 2,
        name: '1D LAB',
        postalCode: '42000',
        siren: '752710715',
        thumbCount: 0,
        managedVenuesIds: ['AEKQ', 'AGBQ'],
      },
      {
        id: 'UQ',
        address: '2750 route de Remire,',
        bic: null,
        city: 'Remire-Monjoly',
        dateCreated: '2018-06-27T11:28:40.344582Z',
        dateModifiedAtLastProvider: '2018-06-26T09:51:00Z',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: '167',
        isActive: true,
        isValidated: true,
        lastProviderId: 'AY',
        modelName: 'Offerer',
        nOffers: 1,
        name: '50s fifties',
        postalCode: '97354',
        siren: null,
        thumbCount: 0,
        managedVenuesIds: ['AKPA', 'UQ'],
      },
      {
        id: 'AJLQ',
        address: '6 RUE BLERIOT',
        bic: null,
        city: 'BREST',
        dateCreated: '2018-09-16T09:29:54.965298Z',
        dateModifiedAtLastProvider: '2018-09-16T09:29:54.965292Z',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isActive: true,
        isValidated: true,
        lastProviderId: null,
        modelName: 'Offerer',
        nOffers: 1,
        name: 'ACOUSTIC ATTACK',
        postalCode: '29200',
        siren: '790654123',
        thumbCount: 0,
        managedVenuesIds: ['AN2A', 'A8LA'],
      },
      {
        id: 'AHEQ',
        address: '124 AVENUE DE LA REPUBLIQUE',
        bic: null,
        city: 'PARIS 11',
        dateCreated: '2018-09-07T14:50:45.679690Z',
        dateModifiedAtLastProvider: '2018-09-07T14:50:45.679682Z',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isActive: true,
        isValidated: true,
        lastProviderId: null,
        modelName: 'Offerer',
        nOffers: 15,
        name: 'ACP LA MANUFACTURE CHANSON',
        postalCode: '75011',
        siren: '328582598',
        thumbCount: 0,
        managedVenuesIds: ['AFLA', 'AJ6Q'],
      },
      {
        id: 'A9RA',
        address: '20 RUE DES ECOUFFES',
        bic: null,
        city: 'PARIS 4',
        dateCreated: '2018-09-12T15:34:46.369677Z',
        dateModifiedAtLastProvider: '2018-09-12T15:34:46.369668Z',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isActive: true,
        isValidated: true,
        lastProviderId: null,
        modelName: 'Offerer',
        nOffers: 3,
        name: 'ADVENWORKS',
        postalCode: '75004',
        siren: '833332232',
        thumbCount: 0,
        managedVenuesIds: ['AMXA'],
      },
      {
        id: 'AG6A',
        address: "RTE DE L'AERODROME",
        bic: null,
        city: 'MARIPASOULA',
        dateCreated: '2018-09-06T17:41:15.352418Z',
        dateModifiedAtLastProvider: '2018-09-06T17:41:15.352411Z',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isActive: true,
        isValidated: true,
        lastProviderId: null,
        modelName: 'Offerer',
        nOffers: 0,
        name: 'AFIIKAN-LUTU',
        postalCode: '97370',
        siren: '403487549',
        thumbCount: 0,
        managedVenuesIds: ['AFHA', 'ALLA'],
      },
      {
        id: 'AHNQ',
        address: '8 SQUARE LEON GUILLOT',
        bic: null,
        city: 'PARIS 15',
        dateCreated: '2018-09-10T08:19:57.420854Z',
        dateModifiedAtLastProvider: '2018-09-10T08:19:57.420845Z',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isActive: true,
        isValidated: true,
        lastProviderId: null,
        modelName: 'Offerer',
        nOffers: 2,
        name: 'AGAIN! PRODUCTIONS',
        postalCode: '75015',
        siren: '791030331',
        thumbCount: 0,
        managedVenuesIds: ['ALWQ', 'AF8Q'],
      },
      {
        id: 'SQ',
        address: 'Angle avenue Gustave Charlery et avenue Virgile,',
        bic: null,
        city: 'Cayenne',
        dateCreated: '2018-06-27T11:28:40.344582Z',
        dateModifiedAtLastProvider: '2018-06-21T15:30:00Z',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: '151',
        isActive: true,
        isValidated: true,
        lastProviderId: 'AY',
        modelName: 'Offerer',
        nOffers: 1,
        name: 'Agapé',
        postalCode: '97300',
        siren: null,
        thumbCount: 0,
        managedVenuesIds: ['AKHA', 'SQ'],
      },
      {
        id: 'ANWA',
        address: '1 ROUTE DE MARCKOLSHEIM',
        bic: null,
        city: 'SELESTAT',
        dateCreated: '2018-10-19T08:17:33.706886Z',
        dateModifiedAtLastProvider: '2018-10-19T08:17:33.706877Z',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isActive: true,
        isValidated: true,
        lastProviderId: null,
        modelName: 'Offerer',
        nOffers: 0,
        name: 'AGENCE CULTURELLE GRAND EST',
        postalCode: '67600',
        siren: '309694750',
        thumbCount: 0,
        managedVenuesIds: ['AUFA'],
      },
    ],
    providers: [
      {
        id: 'AE',
        identifierDescription:
          "Identifiant de l'agenda (ex: 80942872). Il se trouve à la fin de l'adresse web de votre agenda.",
        identifierRegexp: '^\\d+$',
        isActive: true,
        localClass: 'OpenAgendaEvents',
        modelName: 'Provider',
        name: 'Open Agenda',
      },
    ],
    stocks: [
      {
        id: 'DCRA',
        available: null,
        bookingLimitDatetime: '2019-02-13T23:00:00Z',
        bookingRecapSent: null,
        dateModified: '2018-11-13T09:55:14.497468Z',
        dateModifiedAtLastProvider: '2018-11-13T09:55:14.497461Z',
        eventOccurrenceId: null,
        groupSize: 1,
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'Stock',
        offerId: 'AXCA',
        price: 0,
      },
      {
        id: 'DCQQ',
        available: 50,
        bookingLimitDatetime: '2018-11-29T14:00:13Z',
        bookingRecapSent: null,
        dateModified: '2018-11-13T09:40:34.820773Z',
        dateModifiedAtLastProvider: '2018-11-13T09:40:34.820766Z',
        eventOccurrenceId: 'F9WQ',
        groupSize: 1,
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'Stock',
        offerId: null,
        price: 0,
      },
      {
        id: 'DCQA',
        available: 50,
        bookingLimitDatetime: '2018-11-22T14:00:13Z',
        bookingRecapSent: null,
        dateModified: '2018-11-13T09:40:18.055540Z',
        dateModifiedAtLastProvider: '2018-11-13T09:40:18.055534Z',
        eventOccurrenceId: 'F9WA',
        groupSize: 1,
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'Stock',
        offerId: null,
        price: 0,
      },
      {
        id: 'DCPQ',
        available: 50,
        bookingLimitDatetime: '2018-11-15T14:00:13Z',
        bookingRecapSent: null,
        dateModified: '2018-11-13T09:39:52.380000Z',
        dateModifiedAtLastProvider: '2018-11-13T09:39:52.379990Z',
        eventOccurrenceId: 'F9VQ',
        groupSize: 1,
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'Stock',
        offerId: null,
        price: 0,
      },
      {
        id: 'DCPA',
        available: null,
        bookingLimitDatetime: null,
        bookingRecapSent: null,
        dateModified: '2018-11-12T10:12:33.822518Z',
        dateModifiedAtLastProvider: '2018-11-12T10:12:33.822512Z',
        eventOccurrenceId: null,
        groupSize: 1,
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'Stock',
        offerId: 'AXBA',
        price: 0,
      },
      {
        id: 'DC8Q',
        available: null,
        bookingLimitDatetime: '2019-03-31T09:00:53Z',
        bookingRecapSent: null,
        dateModified: '2018-11-12T10:03:02.436530Z',
        dateModifiedAtLastProvider: '2018-11-12T10:03:02.436522Z',
        eventOccurrenceId: 'F9VA',
        groupSize: 1,
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'Stock',
        offerId: null,
        price: 0,
      },
      {
        id: 'DC8A',
        available: null,
        bookingLimitDatetime: '2019-03-30T10:00:53Z',
        bookingRecapSent: null,
        dateModified: '2018-11-12T10:02:48.726098Z',
        dateModifiedAtLastProvider: '2018-11-12T10:02:48.726088Z',
        eventOccurrenceId: 'F9UQ',
        groupSize: 1,
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'Stock',
        offerId: null,
        price: 0,
      },
      {
        id: 'DCMQ',
        available: 80,
        bookingLimitDatetime: '2018-11-29T23:00:00Z',
        bookingRecapSent: null,
        dateModified: '2018-11-09T17:46:40.971498Z',
        dateModifiedAtLastProvider: '2018-11-09T17:46:40.971483Z',
        eventOccurrenceId: 'F9TQ',
        groupSize: 1,
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'Stock',
        offerId: null,
        price: 10,
      },
      {
        id: 'DCMA',
        available: 80,
        bookingLimitDatetime: '2018-11-15T23:00:00Z',
        bookingRecapSent: null,
        dateModified: '2018-11-09T16:39:09.749330Z',
        dateModifiedAtLastProvider: '2018-11-09T16:39:09.749318Z',
        eventOccurrenceId: 'F9TA',
        groupSize: 1,
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'Stock',
        offerId: null,
        price: 10,
      },
      {
        id: 'DCLQ',
        available: null,
        bookingLimitDatetime: '2018-11-29T23:00:00Z',
        bookingRecapSent: null,
        dateModified: '2018-11-09T14:48:40.905103Z',
        dateModifiedAtLastProvider: '2018-11-09T14:48:40.905082Z',
        eventOccurrenceId: null,
        groupSize: 1,
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'Stock',
        offerId: 'AW7A',
        price: 0,
      },
      {
        id: 'DCKQ',
        available: 2000,
        bookingLimitDatetime: '2018-12-15T12:00:48Z',
        bookingRecapSent: null,
        dateModified: '2018-11-09T14:14:11.372642Z',
        dateModifiedAtLastProvider: '2018-11-09T14:14:11.372631Z',
        eventOccurrenceId: 'F9SA',
        groupSize: 1,
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'Stock',
        offerId: null,
        price: 0,
      },
      {
        id: 'DCKA',
        available: 2000,
        bookingLimitDatetime: '2018-12-12T20:00:48Z',
        bookingRecapSent: null,
        dateModified: '2018-11-09T14:13:48.383895Z',
        dateModifiedAtLastProvider: '2018-11-09T14:13:48.383883Z',
        eventOccurrenceId: 'F9RQ',
        groupSize: 1,
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'Stock',
        offerId: null,
        price: 0,
      },
      {
        id: 'DCLA',
        available: 2000,
        bookingLimitDatetime: '2018-12-16T12:00:48Z',
        bookingRecapSent: null,
        dateModified: '2018-11-09T14:14:29.726956Z',
        dateModifiedAtLastProvider: '2018-11-09T14:14:29.726946Z',
        eventOccurrenceId: 'F9SQ',
        groupSize: 1,
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'Stock',
        offerId: null,
        price: 0,
      },
      {
        id: 'DCJA',
        available: 10,
        bookingLimitDatetime: '2018-11-10T10:00:44Z',
        bookingRecapSent: null,
        dateModified: '2018-11-09T13:56:43.722226Z',
        dateModifiedAtLastProvider: '2018-11-09T13:56:43.722210Z',
        eventOccurrenceId: 'F9QQ',
        groupSize: 1,
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'Stock',
        offerId: null,
        price: 0,
      },
      {
        id: 'DCJQ',
        available: 10,
        bookingLimitDatetime: '2018-12-08T10:00:44Z',
        bookingRecapSent: null,
        dateModified: '2018-11-09T13:58:31.705843Z',
        dateModifiedAtLastProvider: '2018-11-09T13:58:31.705830Z',
        eventOccurrenceId: 'F9RA',
        groupSize: 1,
        idAtProviders: null,
        isSoftDeleted: false,
        lastProviderId: null,
        modelName: 'Stock',
        offerId: null,
        price: 0,
      },
    ],
    things: [
      {
        id: 'V4',
        dateModifiedAtLastProvider: '2018-11-13T09:54:56.099516Z',
        description: 'Visite libre\n\nTous les jeudis à 15h00.',
        extraData: null,
        firstThumbDominantColor: null,
        idAtProviders: null,
        isNational: false,
        lastProviderId: null,
        mediaUrls: [],
        modelName: 'Thing',
        name: 'Visite',
        thumbCount: 0,
        type: 'ThingType.MUSEES_PATRIMOINE_ABO',
        url: null,
      },
      {
        id: 'VY',
        dateModifiedAtLastProvider: '2018-11-12T10:12:08.363059Z',
        description: null,
        extraData: null,
        firstThumbDominantColor: null,
        idAtProviders: null,
        isNational: false,
        lastProviderId: null,
        mediaUrls: [],
        modelName: 'Thing',
        name: 'essai meutes',
        thumbCount: 0,
        type: 'ThingType.MUSEES_PATRIMOINE_ABO',
        url: null,
      },
      {
        id: 'VU',
        dateModifiedAtLastProvider: '2018-11-09T14:48:17.207153Z',
        description:
          "Partez à la découverte du cinéma indépendant canadien grâce à l'offre exclusive de Festival Scope. \n\nRegardez 9 documentaires en compétition du festival RIDM en ligne et gratuitement. \n\nCette reprise en ligne est disponible seulement du 17 novembre au 1 décembre.",
        extraData: null,
        firstThumbDominantColor: null,
        idAtProviders: null,
        isNational: false,
        lastProviderId: null,
        mediaUrls: [],
        modelName: 'Thing',
        name: 'Rencontres internationales du documentaire de Montréal',
        thumbCount: 0,
        type: 'ThingType.AUDIOVISUEL',
        url: null,
      },
      {
        id: 'VQ',
        dateModifiedAtLastProvider: '2018-11-09T09:12:10.256533Z',
        description: null,
        extraData: null,
        firstThumbDominantColor: null,
        idAtProviders: null,
        isNational: true,
        lastProviderId: null,
        mediaUrls: [],
        modelName: 'Thing',
        name: 'test',
        thumbCount: 0,
        type: 'ThingType.JEUX_VIDEO',
        url: 'http://omega.outtheregame.com/',
      },
    ],
    types: [
      {
        id: 0,
        description:
          'Action, science-fiction, documentaire ou comédie sentimentale ? En salle, en plein air ou bien au chaud chez soi ? Et si c’était plutôt cette exposition qui allait faire son cinéma ?',
        label: 'Cinéma (Projections, Séances, Évènements)',
        offlineOnly: true,
        onlineOnly: false,
        sublabel: 'Regarder',
        type: 'Event',
        value: 'EventType.CINEMA',
      },
      {
        id: 1,
        description: 'Parfois une simple rencontre peut changer une vie...',
        label: 'Conférence — Débat — Dédicace',
        offlineOnly: true,
        onlineOnly: false,
        sublabel: 'Rencontrer',
        type: 'Event',
        value: 'EventType.CONFERENCE_DEBAT_DEDICACE',
      },
      {
        id: 2,
        description:
          'Résoudre l’énigme d’un jeu de piste dans votre ville ? Jouer en ligne entre amis ? Découvrir cet univers étrange avec une manette ?',
        label: 'Jeux (Évenements, Rencontres, Concours)',
        offlineOnly: true,
        onlineOnly: false,
        sublabel: 'Jouer',
        type: 'Event',
        value: 'EventType.JEUX',
      },
      {
        id: 3,
        description:
          'Plutôt rock, rap ou classique ? Sur un smartphone avec des écouteurs ou entre amis au concert ?',
        label: 'Musique (Concerts, Festivals)',
        offlineOnly: true,
        onlineOnly: false,
        sublabel: 'Écouter',
        type: 'Event',
        value: 'EventType.MUSIQUE',
      },
      {
        id: 4,
        description:
          'Action, science-fiction, documentaire ou comédie sentimentale ? En salle, en plein air ou bien au chaud chez soi ? Et si c’était plutôt cette exposition qui allait faire son cinéma ?',
        label:
          'Musées — Patrimoine (Expositions, Visites guidées, Activités spécifiques)',
        offlineOnly: true,
        onlineOnly: false,
        sublabel: 'Regarder',
        type: 'Event',
        value: 'EventType.MUSEES_PATRIMOINE',
      },
      {
        id: 5,
        description:
          'Jamais osé monter sur les planches ? Tenter d’apprendre la guitare, le piano ou la photographie ? Partir cinq jours découvrir un autre monde ? Bricoler dans un fablab, ou pourquoi pas, enregistrer votre premier titre ?',
        label: 'Pratique Artistique (Stages ponctuels)',
        offlineOnly: true,
        onlineOnly: false,
        sublabel: 'Pratiquer',
        type: 'Event',
        value: 'EventType.PRATIQUE_ARTISTIQUE',
      },
      {
        id: 6,
        description:
          'Suivre un géant de 12 mètres dans la ville ? Rire aux éclats devant un stand up ? Rêver le temps d’un opéra ou d’un spectacle de danse ? Assister à une pièce de théâtre, ou se laisser conter une histoire ?',
        label: 'Spectacle vivant',
        offlineOnly: true,
        onlineOnly: false,
        sublabel: 'Applaudir',
        type: 'Event',
        value: 'EventType.SPECTACLE_VIVANT',
      },
      {
        id: 7,
        description:
          'Action, science-fiction, documentaire ou comédie sentimentale ? En salle, en plein air ou bien au chaud chez soi ? Et si c’était plutôt cette exposition qui allait faire son cinéma ?',
        label: 'Audiovisuel (Films sur supports physiques et VOD)',
        offlineOnly: false,
        onlineOnly: false,
        sublabel: 'Regarder',
        type: 'Thing',
        value: 'ThingType.AUDIOVISUEL',
      },
      {
        id: 8,
        description:
          'Action, science-fiction, documentaire ou comédie sentimentale ? En salle, en plein air ou bien au chaud chez soi ? Et si c’était plutôt cette exposition qui allait faire son cinéma ?',
        label: 'Cinéma (Abonnements)',
        offlineOnly: true,
        onlineOnly: false,
        sublabel: 'Regarder',
        type: 'Thing',
        value: 'ThingType.CINEMA_ABO',
      },
      {
        id: 9,
        description:
          'Résoudre l’énigme d’un jeu de piste dans votre ville ? Jouer en ligne entre amis ? Découvrir cet univers étrange avec une manette ?',
        label: 'Jeux (Abonnements)',
        offlineOnly: true,
        onlineOnly: false,
        sublabel: 'Jouer',
        type: 'Thing',
        value: 'ThingType.JEUX_ABO',
      },
      {
        id: 10,
        description:
          'Résoudre l’énigme d’un jeu de piste dans votre ville ? Jouer en ligne entre amis ? Découvrir cet univers étrange avec une manette ?',
        label: 'Jeux (Biens physiques)',
        offlineOnly: true,
        onlineOnly: false,
        sublabel: 'Jouer',
        type: 'Thing',
        value: 'ThingType.JEUX',
      },
      {
        id: 11,
        description:
          'Résoudre l’énigme d’un jeu de piste dans votre ville ? Jouer en ligne entre amis ? Découvrir cet univers étrange avec une manette ?',
        label: 'Jeux Vidéo',
        offlineOnly: false,
        onlineOnly: true,
        sublabel: 'Jouer',
        type: 'Thing',
        value: 'ThingType.JEUX_VIDEO',
      },
      {
        id: 12,
        description:
          'S’abonner à un quotidien d’actualité ? À un hebdomadaire humoristique ? À un mensuel dédié à la nature ? Acheter une BD ou un manga ? Ou tout simplement ce livre dont tout le monde parle ?',
        label: 'Livre — Édition',
        offlineOnly: false,
        onlineOnly: false,
        sublabel: 'Lire',
        type: 'Thing',
        value: 'ThingType.LIVRE_EDITION',
      },
      {
        id: 13,
        description:
          'Action, science-fiction, documentaire ou comédie sentimentale ? En salle, en plein air ou bien au chaud chez soi ? Et si c’était plutôt cette exposition qui allait faire son cinéma ?',
        label: 'Musées — Patrimoine (Abonnements, Visites libres)',
        offlineOnly: true,
        onlineOnly: false,
        sublabel: 'Regarder',
        type: 'Thing',
        value: 'ThingType.MUSEES_PATRIMOINE_ABO',
      },
      {
        id: 14,
        description:
          'Plutôt rock, rap ou classique ? Sur un smartphone avec des écouteurs ou entre amis au concert ?',
        label: 'Musique (Abonnements concerts)',
        offlineOnly: true,
        onlineOnly: false,
        sublabel: 'Écouter',
        type: 'Thing',
        value: 'ThingType.MUSIQUE_ABO',
      },
      {
        id: 15,
        description:
          'Plutôt rock, rap ou classique ? Sur un smartphone avec des écouteurs ou entre amis au concert ?',
        label: 'Musique (sur supports physiques ou en ligne)',
        offlineOnly: false,
        onlineOnly: false,
        sublabel: 'Écouter',
        type: 'Thing',
        value: 'ThingType.MUSIQUE',
      },
      {
        id: 16,
        description:
          'Jamais osé monter sur les planches ? Tenter d’apprendre la guitare, le piano ou la photographie ? Partir cinq jours découvrir un autre monde ? Bricoler dans un fablab, ou pourquoi pas, enregistrer votre premier titre ?',
        label: 'Pratique Artistique (Abonnements)',
        offlineOnly: true,
        onlineOnly: false,
        sublabel: 'Pratiquer',
        type: 'Thing',
        value: 'ThingType.PRATIQUE_ARTISTIQUE_ABO',
      },
      {
        id: 17,
        description:
          'S’abonner à un quotidien d’actualité ? À un hebdomadaire humoristique ? À un mensuel dédié à la nature ? Acheter une BD ou un manga ? Ou tout simplement ce livre dont tout le monde parle ?',
        label: 'Presse (Abonnements)',
        offlineOnly: false,
        onlineOnly: true,
        sublabel: 'Lire',
        type: 'Thing',
        value: 'ThingType.PRESSE_ABO',
      },
    ],
    venues: [
      {
        id: 'AYJA',
        address: "Route de l'Oppidum",
        bic: null,
        bookingEmail: 'geza.frey@monuments-nationaux.fr',
        city: 'Nissan-lez-Enserune',
        comment: 'Pas de SIRET propre',
        dateModifiedAtLastProvider: '2018-11-13T09:36:35.890902Z',
        departementCode: '34',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isValidated: true,
        isVirtual: false,
        lastProviderId: null,
        latitude: 43.3105,
        longitude: 3.11591,
        managingOffererId: 'ALJQ',
        modelName: 'Venue',
        name: "Site archéologique et musée d'Ensérune",
        postalCode: '34440',
        siret: null,
        thumbCount: 0,
      },
      {
        id: 'AVQQ',
        address: '27 Rue du Pouly',
        bic: null,
        bookingEmail: 'contact@meandres.art',
        city: 'Huelgoat',
        comment:
          "Merci de contacter l'équipe pass Culture pour lui communiquer le SIRET de ce lieu.",
        dateModifiedAtLastProvider: '2018-10-25T19:21:53.543404Z',
        departementCode: '29',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isValidated: true,
        isVirtual: false,
        lastProviderId: null,
        latitude: 48.36517,
        longitude: -3.74586,
        managingOffererId: 'AJDQ',
        modelName: 'Venue',
        name: "méandres — lieu d'art contemporain",
        postalCode: '29690',
        siret: null,
        thumbCount: 0,
      },
      {
        id: 'AYHA',
        address: 'PLACE DU MARCHE',
        bic: null,
        bookingEmail: 'arnaud.paclet@le-repere.org',
        city: 'SCHIRMECK',
        comment: null,
        dateModifiedAtLastProvider: '2018-11-09T16:34:29.025566Z',
        departementCode: '67',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isValidated: true,
        isVirtual: false,
        lastProviderId: null,
        latitude: 48.48162,
        longitude: 7.21446,
        managingOffererId: 'AQ2A',
        modelName: 'Venue',
        name: 'ASS SOCIO CULTURELLE LE REPERE',
        postalCode: '67130',
        siret: '42417936400015',
        thumbCount: 0,
      },
      {
        id: 'AYGA',
        address: '59 RUE DE LA FONTAINE AU ROI',
        bic: null,
        bookingEmail: 'margo@festivalscope.com',
        city: 'PARIS 11',
        comment: null,
        dateModifiedAtLastProvider: '2018-11-09T14:42:11.027397Z',
        departementCode: '75',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isValidated: true,
        isVirtual: false,
        lastProviderId: null,
        latitude: 48.86835,
        longitude: 2.37423,
        managingOffererId: 'AQZA',
        modelName: 'Venue',
        name: 'MOVING SCOPE',
        postalCode: '75011',
        siret: '51940540100026',
        thumbCount: 0,
      },
      {
        id: '5E',
        address: '211 Avenue Jean Jaurès',
        bic: null,
        bookingEmail: 'a.bayou@villette.com',
        city: 'Paris',
        comment: null,
        dateModifiedAtLastProvider: '2018-07-24T14:53:55.018495Z',
        departementCode: '75',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isValidated: true,
        isVirtual: false,
        lastProviderId: null,
        latitude: 48.88895,
        longitude: 2.39244,
        managingOffererId: '7A',
        modelName: 'Venue',
        name: 'ETS PUBLIC PARC GRANDE HALLE VILLETTE',
        postalCode: '75019',
        siret: '39140695600014',
        thumbCount: 0,
      },
      {
        id: 'AQQQ',
        address: null,
        bic: null,
        bookingEmail: null,
        city: null,
        comment: null,
        dateModifiedAtLastProvider: '2018-10-03T12:15:02.739034Z',
        departementCode: null,
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isValidated: true,
        isVirtual: true,
        lastProviderId: null,
        latitude: null,
        longitude: null,
        managingOffererId: 'ALHA',
        modelName: 'Venue',
        name: 'Offre en ligne',
        postalCode: null,
        siret: null,
        thumbCount: 0,
      },
      {
        id: 'AUJA',
        address: '2 RUE JEAN PERRIN',
        bic: null,
        bookingEmail: 'louis@180gram.io',
        city: 'COLOMBELLES',
        comment: null,
        dateModifiedAtLastProvider: '2018-10-20T13:45:02.994550Z',
        departementCode: '14',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isVirtual: false,
        lastProviderId: null,
        latitude: 49.1893,
        longitude: -0.30369,
        managingOffererId: 'ANYQ',
        modelName: 'Venue',
        nOffers: 0,
        name: '180G',
        postalCode: '14460',
        siret: '82436838500012',
        thumbCount: 0,
      },
      {
        id: 'AU9Q',
        address: null,
        bic: null,
        bookingEmail: null,
        city: null,
        comment: null,
        dateModifiedAtLastProvider: '2018-10-20T13:43:58.678574Z',
        departementCode: null,
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isVirtual: true,
        lastProviderId: null,
        latitude: null,
        longitude: null,
        managingOffererId: 'ANYQ',
        modelName: 'Venue',
        nOffers: 0,
        name: 'Offre en ligne',
        postalCode: null,
        siret: null,
        thumbCount: 0,
      },
      {
        id: 'AEKQ',
        address: '5 RUE JAVELIN PAGNON',
        bic: null,
        bookingEmail: 'eric.petrotto@divercities.eu',
        city: 'SAINT ETIENNE',
        comment: null,
        dateModifiedAtLastProvider: '2018-08-25T11:38:20.927993Z',
        departementCode: '42',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isVirtual: false,
        lastProviderId: null,
        latitude: 45.44943,
        longitude: 4.38589,
        managingOffererId: 'AFRQ',
        modelName: 'Venue',
        nOffers: 2,
        name: 'DIVERCITIES',
        postalCode: '42000',
        siret: '75271071500034',
        thumbCount: 0,
      },
      {
        id: 'AGBQ',
        address: null,
        bic: null,
        bookingEmail: null,
        city: null,
        comment: null,
        dateModifiedAtLastProvider: null,
        departementCode: null,
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isVirtual: true,
        lastProviderId: null,
        latitude: null,
        longitude: null,
        managingOffererId: 'AFRQ',
        modelName: 'Venue',
        nOffers: 0,
        name: 'Offre en ligne',
        postalCode: null,
        siret: null,
        thumbCount: 0,
      },
      {
        id: 'AKPA',
        address: null,
        bic: null,
        bookingEmail: null,
        city: null,
        comment: null,
        dateModifiedAtLastProvider: null,
        departementCode: null,
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isVirtual: true,
        lastProviderId: null,
        latitude: null,
        longitude: null,
        managingOffererId: 'UQ',
        modelName: 'Venue',
        nOffers: 0,
        name: 'Offre en ligne',
        postalCode: null,
        siret: null,
        thumbCount: 0,
      },
      {
        id: 'UQ',
        address: '2750 route de Remire',
        bic: null,
        bookingEmail: 'toto@btmx.fr',
        city: 'Remire-Monjoly',
        comment:
          "Merci de contacter l'équipe pass Culture pour lui communiquer le SIRET de ce lieu.",
        dateModifiedAtLastProvider: '2018-06-26T09:51:00Z',
        departementCode: '97',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: '167',
        isVirtual: false,
        lastProviderId: 'AY',
        latitude: 4.89589,
        longitude: -52.27361,
        managingOffererId: 'UQ',
        modelName: 'Venue',
        nOffers: 1,
        name: '50s fifties',
        postalCode: '97354',
        siret: null,
        thumbCount: 0,
      },
      {
        id: 'AN2A',
        address: null,
        bic: null,
        bookingEmail: null,
        city: null,
        comment: null,
        dateModifiedAtLastProvider: '2018-09-16T09:29:54.973330Z',
        departementCode: null,
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isVirtual: true,
        lastProviderId: null,
        latitude: null,
        longitude: null,
        managingOffererId: 'AJLQ',
        modelName: 'Venue',
        nOffers: 0,
        name: 'Offre en ligne',
        postalCode: null,
        siret: null,
        thumbCount: 0,
      },
      {
        id: 'A8LA',
        address: '25 Avenue Maréchal Foch',
        bic: null,
        bookingEmail: 'acousticattack.asso@gmail.com',
        city: 'Brest',
        comment:
          "Merci de contacter l'équipe pass Culture pour lui communiquer le SIRET de ce lieu.",
        dateModifiedAtLastProvider: '2018-09-20T11:25:32.046081Z',
        departementCode: '29',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isVirtual: false,
        lastProviderId: null,
        latitude: 48.39635,
        longitude: -4.48879,
        managingOffererId: 'AJLQ',
        modelName: 'Venue',
        nOffers: 1,
        name: 'Piscine Foch',
        postalCode: '29200',
        siret: null,
        thumbCount: 0,
      },
      {
        id: 'AFLA',
        address: '124 AVENUE DE LA REPUBLIQUE',
        bic: null,
        bookingEmail: 'acp@manufacturechanson.org',
        city: 'PARIS 11',
        comment: null,
        dateModifiedAtLastProvider: '2018-09-07T14:51:12.087159Z',
        departementCode: '75',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isVirtual: false,
        lastProviderId: null,
        latitude: 48.863,
        longitude: 2.38568,
        managingOffererId: 'AHEQ',
        modelName: 'Venue',
        nOffers: 15,
        name: 'ACP LA MANUFACTURE CHANSON',
        postalCode: '75011',
        siret: '32858259800046',
        thumbCount: 0,
      },
      {
        id: 'AJ6Q',
        address: null,
        bic: null,
        bookingEmail: null,
        city: null,
        comment: null,
        dateModifiedAtLastProvider: null,
        departementCode: null,
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isVirtual: true,
        lastProviderId: null,
        latitude: null,
        longitude: null,
        managingOffererId: 'AHEQ',
        modelName: 'Venue',
        nOffers: 0,
        name: 'Offre en ligne',
        postalCode: null,
        siret: null,
        thumbCount: 0,
      },
      {
        id: 'AMXA',
        address: null,
        bic: null,
        bookingEmail: null,
        city: null,
        comment: null,
        dateModifiedAtLastProvider: '2018-09-12T15:34:46.382911Z',
        departementCode: null,
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isVirtual: true,
        lastProviderId: null,
        latitude: null,
        longitude: null,
        managingOffererId: 'A9RA',
        modelName: 'Venue',
        nOffers: 3,
        name: 'Offre en ligne',
        postalCode: null,
        siret: null,
        thumbCount: 0,
      },
      {
        id: 'AFHA',
        address: "RTE DE L'AERODROME",
        bic: null,
        bookingEmail: 'afiikanlutu@gmail.com',
        city: 'MARIPASOULA',
        comment: null,
        dateModifiedAtLastProvider: '2018-09-06T17:42:57.979536Z',
        departementCode: '97',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isVirtual: false,
        lastProviderId: null,
        latitude: 3.6466,
        longitude: -54.03168,
        managingOffererId: 'AG6A',
        modelName: 'Venue',
        nOffers: 0,
        name: 'AFIIKAN-LUTU',
        postalCode: '97370',
        siret: '40348754900012',
        thumbCount: 0,
      },
      {
        id: 'ALLA',
        address: null,
        bic: null,
        bookingEmail: null,
        city: null,
        comment: null,
        dateModifiedAtLastProvider: null,
        departementCode: null,
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isVirtual: true,
        lastProviderId: null,
        latitude: null,
        longitude: null,
        managingOffererId: 'AG6A',
        modelName: 'Venue',
        nOffers: 0,
        name: 'Offre en ligne',
        postalCode: null,
        siret: null,
        thumbCount: 0,
      },
      {
        id: 'ALWQ',
        address: null,
        bic: null,
        bookingEmail: null,
        city: null,
        comment: null,
        dateModifiedAtLastProvider: null,
        departementCode: null,
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isVirtual: true,
        lastProviderId: null,
        latitude: null,
        longitude: null,
        managingOffererId: 'AHNQ',
        modelName: 'Venue',
        nOffers: 0,
        name: 'Offre en ligne',
        postalCode: null,
        siret: null,
        thumbCount: 0,
      },
      {
        id: 'AF8Q',
        address: '52 Rue du Sergent Bobillot',
        bic: null,
        bookingEmail: 'nicolas.lorach@gmail.com',
        city: 'Montreuil',
        comment:
          "Merci de contacter l'équipe pass Culture pour lui communiquer le SIRET de ce lieu.",
        dateModifiedAtLastProvider: '2018-09-10T08:24:32.067295Z',
        departementCode: '93',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isVirtual: false,
        lastProviderId: null,
        latitude: 48.85433,
        longitude: 2.43344,
        managingOffererId: 'AHNQ',
        modelName: 'Venue',
        nOffers: 2,
        name: "L'Albatros",
        postalCode: '93100',
        siret: null,
        thumbCount: 0,
      },
      {
        id: 'AKHA',
        address: null,
        bic: null,
        bookingEmail: null,
        city: null,
        comment: null,
        dateModifiedAtLastProvider: null,
        departementCode: null,
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isVirtual: true,
        lastProviderId: null,
        latitude: null,
        longitude: null,
        managingOffererId: 'SQ',
        modelName: 'Venue',
        nOffers: 0,
        name: 'Offre en ligne',
        postalCode: null,
        siret: null,
        thumbCount: 0,
      },
      {
        id: 'SQ',
        address: 'Angle avenue Gustave Charlery et avenue Virgile',
        bic: null,
        bookingEmail: ' rayline.linyon@agapeguyane.org',
        city: 'Cayenne',
        comment:
          "Merci de contacter l'équipe pass Culture pour lui communiquer le SIRET de ce lieu.",
        dateModifiedAtLastProvider: '2018-06-21T15:30:00Z',
        departementCode: '97',
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: '151',
        isVirtual: false,
        lastProviderId: 'AY',
        latitude: 4.89855,
        longitude: -52.27898,
        managingOffererId: 'SQ',
        modelName: 'Venue',
        nOffers: 1,
        name: 'Agapé',
        postalCode: '97300',
        siret: null,
        thumbCount: 0,
      },
      {
        id: 'AUFA',
        address: null,
        bic: null,
        bookingEmail: null,
        city: null,
        comment: null,
        dateModifiedAtLastProvider: '2018-10-19T08:17:33.714589Z',
        departementCode: null,
        firstThumbDominantColor: null,
        iban: null,
        idAtProviders: null,
        isVirtual: true,
        lastProviderId: null,
        latitude: null,
        longitude: null,
        managingOffererId: 'ANWA',
        modelName: 'Venue',
        nOffers: 0,
        name: 'Offre en ligne',
        postalCode: null,
        siret: null,
        thumbCount: 0,
      },
    ],
    venueProviders: [],
    users: [
      {
        id: 'AF8A',
        canBookFreeOffers: false,
        dateCreated: '2018-06-26T14:32:51.060347Z',
        departementCode: '93',
        email: 'arnaud.betremieux@beta.gouv.fr',
        expenses: {
          all: {
            actual: 0,
            max: 500,
          },
          digital: {
            actual: 0,
            max: 200,
          },
          physical: {
            actual: 0,
            max: 100,
          },
        },
        firstName: '',
        firstThumbDominantColor: [100, 108, 19],
        isAdmin: true,
        lastName: '',
        modelName: 'User',
        phoneNumber: null,
        postalCode: '',
        publicName: 'Arnaud Bétrémieux',
        thumbCount: 1,
        wallet_balance: 0,
        wallet_is_activated: false,
      },
    ],
  },
  errors: {
    user: null,
    offer: null,
  },
  form: {
    offer: {
      name: ';lkjasdfasdf',
      type: 'ThingType.MUSIQUE',
      offererId: 'ANYQ',
      extraData: {
        musicType: '800',
        musicSubType: '812',
      },
      venueId: 'AUJA',
    },
  },
  loading: {
    config: {},
    isActive: false,
  },
  modal: {
    config: {
      fromDirection: 'right',
    },
    isActive: false,
    $modal: null,
  },
  notification: null,
  tracker: {
    'users/current': '2018-10-11T09:02:40.992Z',
    types: '2018-11-14T09:02:28.407Z',
    'offers?order_by=createdAt+desc&page=1': '2018-09-25T12:49:04.073Z',
    providers: '2018-11-14T09:02:37.094Z',
    'offers?order_by=createdAt+desc&venueId=ANXQ&page=1':
      '2018-09-18T14:23:44.475Z',
    offerers: '2018-10-11T09:05:38.662Z',
    'offerers/AJWA': '2018-09-20T08:25:52.712Z',
    'venueProviders?venueId=A89A': '2018-09-20T08:25:55.358Z',
    'offers/ANMA': '2018-09-20T08:32:56.503Z',
    'offers/ANEQ': '2018-09-25T09:42:38.930Z',
    'users/signout': '2018-09-25T12:49:24.323Z',
    'offers?order_by=createdAt+desc&page=2': '2018-09-25T12:49:08.185Z',
    'offers?order_by=createdAt+desc&page=3': '2018-09-25T12:49:10.298Z',
    'offerers?order_by=createdAt+desc&page=1': '2018-09-25T12:50:58.314Z',
    'offers?page=1&orderBy=offer.id+desc': '2018-11-14T09:02:28.760Z',
    'offers?page=1&search=gadzby&orderBy=offer.id+desc':
      '2018-10-04T15:20:00.418Z',
    'offers?page=1&search=GADZBY&orderBy=offer.id+desc':
      '2018-10-04T15:20:19.165Z',
    'offerers?page=1&': '2018-11-14T09:02:34.924Z',
    'offerers?page=1&search=ACP': '2018-10-04T15:20:32.975Z',
    'offerers/AHEQ': '2018-10-04T15:20:39.165Z',
    'offers?page=1&venueId=AFLA&orderBy=offer.id+desc':
      '2018-10-04T15:20:42.001Z',
    'offers?page=2&venueId=AFLA&orderBy=offer.id+desc':
      '2018-10-04T15:20:44.338Z',
    'offers?page=3&venueId=AFLA&orderBy=offer.id+desc':
      '2018-10-04T15:20:45.734Z',
    'offers/AJYA': '2018-10-04T15:21:11.965Z',
    'offers?page=2&orderBy=offer.id+desc': '2018-10-11T09:05:43.484Z',
    'offers?page=3&orderBy=offer.id+desc': '2018-10-09T09:12:01.175Z',
    'offers?page=4&orderBy=offer.id+desc': '2018-10-09T09:12:02.624Z',
    'offers?page=5&orderBy=offer.id+desc': '2018-10-09T09:12:14.085Z',
    'offers?page=1&keywords=test&orderBy=offer.id+desc':
      '2018-10-09T09:12:33.690Z',
    'offers?page=2&keywords=test&orderBy=offer.id+desc':
      '2018-10-09T09:15:55.705Z',
    'offers/ARHA': '2018-10-09T09:16:02.955Z',
    'offers?page=1&venueId=AEKQ&orderBy=offer.id+desc':
      '2018-10-09T09:16:17.154Z',
    'offers?page=2&venueId=AEKQ&orderBy=offer.id+desc':
      '2018-10-09T09:16:17.926Z',
    'offers/ARGQ': '2018-10-09T09:16:40.279Z',
    'offers/AR9Q': '2018-10-11T08:59:39.433Z',
    'offerers/AFRQ': '2018-10-11T09:06:04.961Z',
    'offers/ARJQ': '2018-10-11T09:05:46.832Z',
    'offers?page=1&keywords=titre&orderBy=offer.id+desc':
      '2018-10-11T09:05:22.099Z',
    'offerers/AFRQ/bookings?offererId=AFRQ&orderBy=booking.id+desc':
      '2018-10-11T09:05:38.877Z',
    'offers/ARKA': '2018-10-11T09:06:29.773Z',
    'offerers/UQ': '2018-10-11T09:06:40.358Z',
    'offers/ARKQ': '2018-10-11T09:07:08.861Z',
    'venueProviders?venueId=ARNA': '2018-10-11T09:07:33.574Z',
    'offerers/ANYQ': '2018-11-14T09:02:37.106Z',
  },
  user: {
    id: 'AF8A',
    canBookFreeOffers: false,
    dateCreated: '2018-06-26T14:32:51.060347Z',
    departementCode: '93',
    email: 'arnaud.betremieux@beta.gouv.fr',
    expenses: {
      all: {
        actual: 0,
        max: 500,
      },
      digital: {
        actual: 0,
        max: 200,
      },
      physical: {
        actual: 0,
        max: 100,
      },
    },
    firstName: '',
    firstThumbDominantColor: [100, 108, 19],
    isAdmin: true,
    lastName: '',
    modelName: 'User',
    phoneNumber: null,
    postalCode: '',
    publicName: 'Arnaud Bétrémieux',
    thumbCount: 1,
    wallet_balance: 0,
    wallet_is_activated: false,
  },
  _persist: {
    version: -1,
    rehydrated: true,
  },
}

describe('offerSelector', () => {
  it('should select an offer given an id', () => {
    // Given
    const state = mockState
    const offerId = 'AXBQ'

    // When
    const offer = selectOfferById(state, offerId)

    // Then
    expect(offer.id).toEqual(offerId)
  })
})
