"""remove_unused_columns

Revision ID: 1d5f4822d8a2
Revises: 6d7ee6ccaea7
Create Date: 2020-11-27 09:22:03.017394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "1d5f4822d8a2"
down_revision = "6d7ee6ccaea7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_column("booking", "isActive")
    op.drop_column("offerer", "firstThumbDominantColor")
    op.drop_column("venue", "firstThumbDominantColor")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.add_column("venue", sa.Column("firstThumbDominantColor", postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column(
        "offerer", sa.Column("firstThumbDominantColor", postgresql.BYTEA(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "booking",
        sa.Column("isActive", sa.BOOLEAN(), server_default=sa.text("true"), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
