"""Add apiUrl to Providers

Revision ID: 08e0af71bcfe
Revises: ee190d0fbe21
Create Date: 2021-03-10 10:53:21.884132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "08e0af71bcfe"
down_revision = "ee190d0fbe21"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column("provider", sa.Column("apiUrl", sa.String(), nullable=True))
    op.add_column("provider", sa.Column("authToken", sa.String(), nullable=True))
    # ### end Alembic commands ###

    op.create_check_constraint(
        "check_provider_has_localclass_or_apiUrl",
        "provider",
        '("localClass" IS NOT NULL AND "apiUrl" IS NULL) OR ("localClass" IS NULL AND "apiUrl" IS NOT NULL)',
    )


def downgrade():
    op.drop_constraint("check_provider_has_localclass_or_apiUrl", "provider")

    # ### commands auto generated by Alembic ###
    op.drop_column("provider", "authToken")
    op.drop_column("provider", "apiUrl")
    # ### end Alembic commands ###
