"""add Stock.dnBookedQuantity

Revision ID: 508c975a420b
Revises: bd142e43ea07
Create Date: 2021-03-18 14:39:01.811599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "508c975a420b"
down_revision = "bd142e43ea07"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.add_column("stock", sa.Column("dnBookedQuantity", sa.BigInteger(), nullable=False, server_default=sa.text("0")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_column("stock", "dnBookedQuantity")
    # ### end Alembic commands ###
