"""add_token_table

Revision ID: 2883f596068f
Revises: f80e66726491
Create Date: 2020-11-16 16:57:05.066712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2883f596068f"
down_revision = "f80e66726491"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.create_table(
        "token",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("userId", sa.BigInteger(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("creationDate", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("expirationDate", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_token_userId"), "token", ["userId"], unique=False)
    op.create_index(op.f("ix_token_value"), "token", ["value"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f("ix_token_value"), table_name="token")
    op.drop_index(op.f("ix_token_userId"), table_name="token")
    op.drop_table("token")
    # ### end Alembic commands ###
