"""add_isPermanent_property_to_venue

Revision ID: 3150b613c5b4
Revises: 04e6c3b7fd17
Create Date: 2021-02-15 09:35:07.246661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3150b613c5b4"
down_revision = "04e6c3b7fd17"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("venue", sa.Column("isPermanent", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("venue", "isPermanent")
    # ### end Alembic commands ###
