"""Drop canBookOffers

Revision ID: 4a5c2acfd867
Revises: ad5e76920552
Create Date: 2020-12-15 13:25:11.511490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4a5c2acfd867"
down_revision = "ad5e76920552"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_column("user", "canBookFreeOffers")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.add_column(
        "user",
        sa.Column(
            "canBookFreeOffers", sa.BOOLEAN(), server_default=sa.text("true"), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
