"""drop_seen_offer

Revision ID: 65e097fd4c74
Revises: b757109d4694
Create Date: 2021-01-08 14:52:02.285288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "65e097fd4c74"
down_revision = "b757109d4694"
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table("seen_offer")


def downgrade():
    # ### commands auto generated by Alembic ###
    op.create_table(
        "seen_offer",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("dateSeen", sa.DateTime(), nullable=False),
        sa.Column("offerId", sa.BigInteger(), nullable=False),
        sa.Column("userId", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["offerId"],
            ["offer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_seen_offer_offerId"), "seen_offer", ["offerId"], unique=False)
    op.create_index(op.f("ix_seen_offer_userId"), "seen_offer", ["userId"], unique=False)
    # ### end Alembic commands ###
