"""Add user.hasAllowedRecommendations

Revision ID: 6d7ee6ccaea7
Revises: 7be5dfa80f89
Create Date: 2020-11-25 11:51:36.936591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6d7ee6ccaea7"
down_revision = "7be5dfa80f89"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.add_column(
        "user", sa.Column("hasAllowedRecommendations", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_column("user", "hasAllowedRecommendations")
    # ### end Alembic commands ###
