"""add_creation_date_on_favorites

Revision ID: 6e99e0e5834d
Revises: 539a0d1a86d0
Create Date: 2021-01-28 15:21:15.087161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6e99e0e5834d"
down_revision = "539a0d1a86d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("favorite", sa.Column("dateCreated", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("favorite", "dateCreated")
    # ### end Alembic commands ###
