"""Add a default to user.isEmailValidated

Revision ID: 7be5dfa80f89
Revises: bc4ad3f45b5c
Create Date: 2020-11-20 07:35:45.408107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7be5dfa80f89"
down_revision = "bc4ad3f45b5c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.alter_column(
        "user", "isEmailValidated", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.alter_column("user", "isEmailValidated", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=True)
    # ### end Alembic commands ###
