"""add_is_beneficiary_column_in_user

Revision ID: 8c366d4230c7
Revises: b7c0ec4bb3c2
Create Date: 2020-11-24 08:21:11.314141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8c366d4230c7"
down_revision = "b7c0ec4bb3c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column("user", sa.Column("isBeneficiary", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column("user", "isBeneficiary")
    # ### end Alembic commands ###
