"""add_offer_disability_compliance_columns

Revision ID: 93d6975c3fa7
Revises: 55bf0bb6c53b
Create Date: 2020-12-21 10:29:45.914982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "93d6975c3fa7"
down_revision = "55bf0bb6c53b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column("offer", sa.Column("audioDisabilityCompliant", sa.Boolean(), nullable=True))
    op.add_column("offer", sa.Column("mentalDisabilityCompliant", sa.Boolean(), nullable=True))
    op.add_column("offer", sa.Column("motorDisabilityCompliant", sa.Boolean(), nullable=True))
    op.add_column("offer", sa.Column("visualDisabilityCompliant", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column("offer", "visualDisabilityCompliant")
    op.drop_column("offer", "motorDisabilityCompliant")
    op.drop_column("offer", "mentalDisabilityCompliant")
    op.drop_column("offer", "audioDisabilityCompliant")
    # ### end Alembic commands ###
