"""add_external_ticket_office_url

Revision ID: ebb6831ad781
Revises: 8b219e5ece28
Create Date: 2021-01-04 10:41:24.377617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ebb6831ad781"
down_revision = "8b219e5ece28"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column("offer", sa.Column("externalTicketOfficeUrl", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column("offer", "externalTicketOfficeUrl")
    # ### end Alembic commands ###
