export enum OFFER_TYPES {
  INDIVIDUAL_OR_DUO = 'INDIVIDUAL_OR_DUO',
  EDUCATIONAL = 'EDUCATIONAL',
}

export enum CATEGORY_STATUS {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  ONLINE_OR_OFFLINE = 'ONLINE_OR_OFFLINE',
}

export enum OFFER_WITHDRAWAL_TYPE_OPTIONS {
  ON_SITE = 'on_site',
  NO_TICKET = 'no_ticket',
  BY_EMAIL = 'by_email',
}
