#!/bin/bash

counter=0

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.py' ':!tests')
if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

LINTED_FILES=""

for FILE in $STAGED_FILES; do
  LINTED_FILES+=" ${FILE}"
done

echo -e "\033[0;96mRunning isort to organize imports\033[0m"
isort $LINTED_FILES

echo -e "\n\033[0;96mRunning mypy for type checking\033[0m\n"
mypy $LINTED_FILES --pretty
if [[ "$?" != 0 ]]; then
  counter=$((counter + 1))
fi

echo -e "\n\033[0;96mRunning pylint for code linting\033[0m\n"
pylint $LINTED_FILES --output-format="colorized" --score=no
if [[ "$?" != 0 ]]; then
  counter=$((counter + 1))
fi

if [[ $counter > 0 ]]; then
  echo -e "\n\033[0;96mIf you want to bypass it, add --no-verify option when committing.\033[0m\n"
  exit 1
fi
