#!/bin/bash

echo -e "\033[0;96mChecking commit message format...\033[0m"
MSG_FILE=$1
# Standard output is useless: commitizen just says that everything is
# fine.
if cz -n cz_customize check --commit-msg-file $MSG_FILE 1>/dev/null; then
    # Go up 1 line to overwrite "Checking..." line
    echo -e "\033[2F"
    echo -e "\033[2K\r\033[0;92mCommit message correctly formatted\033[0m"
else
    echo -e "\nWrong commit format. Commit should look like this:"
    cz schema
    echo -e "\nValid example:"
    cz example
    echo -e "\nUse \e[32mcz commit\e[0m to make sure your commit message is correct (You may need to install commitizen first)"
    exit 1
fi
