export const offerer1 = {
  id: 'offerer_1_id',
  name: 'Offerer 1',
}
export const offerer2 = {
  id: 'offerer_2_id',
  name: 'Offerer 2',
}
export const venueVirtual = {
  id: 'offerer_1_venue_virtual',
  isVirtual: true,
  managingOffererId: offerer1.id,
  managingOfferer: offerer1,
  name: 'Offerer 1 Venue virtual',
  offererName: 'Offerer 1',
  withdrawalDetails: null,
  audioDisabilityCompliant: null,
  mentalDisabilityCompliant: null,
  motorDisabilityCompliant: null,
  visualDisabilityCompliant: null,
}
export const venuePhysicalUndefinedAccessibility = {
  id: 'offerer_1_venue_physical_undefined_accessibility',
  isVirtual: false,
  managingOffererId: offerer1.id,
  managingOfferer: offerer1,
  name: 'Offerer 1 Venue physical undefined accessibility',
  offererName: 'Offerer 1',
  withdrawalDetails: 'Modalité retrait',
  audioDisabilityCompliant: null,
  mentalDisabilityCompliant: null,
  motorDisabilityCompliant: null,
  visualDisabilityCompliant: null,
}
export const venuePhysicalAccessible = {
  id: 'offerer_1_venue_physical_accessible',
  isVirtual: false,
  managingOffererId: offerer1.id,
  managingOfferer: offerer1,
  name: 'Offerer 1 Venue physical accessible',
  offererName: 'Offerer 1',
  withdrawalDetails: 'Modalité retrait',
  audioDisabilityCompliant: true,
  mentalDisabilityCompliant: false,
  motorDisabilityCompliant: true,
  visualDisabilityCompliant: false,
}
export const offerer2VenueVirtual = {
  id: 'offerer_2_venue_virtual',
  isVirtual: true,
  managingOffererId: offerer2.id,
  managingOfferer: offerer2,
  name: 'Offerer 2 Venue virtual',
  offererName: 'Offerer 2',
  withdrawalDetails: null,
  audioDisabilityCompliant: null,
  mentalDisabilityCompliant: null,
  motorDisabilityCompliant: null,
  visualDisabilityCompliant: null,
}
export const offerer2VenuePhysicalAccessible = {
  id: 'offerer_3_venue_physical_accessible',
  isVirtual: false,
  managingOffererId: offerer2.id,
  managingOfferer: offerer2,
  name: 'Offerer 2 Venue physical accessible',
  offererName: 'Offerer 2',
  withdrawalDetails: 'Modalité retrait',
  audioDisabilityCompliant: true,
  mentalDisabilityCompliant: true,
  motorDisabilityCompliant: true,
  visualDisabilityCompliant: true,
}
export const categories = {
  categories: [
    {
      id: 'CATEGORY_1',
      proLabel: 'Category 1',
      isSelectable: true,
    },
    {
      id: 'CATEGORY_2',
      proLabel: 'Category 2',
      isSelectable: true,
    },
  ],
  subcategories: [
    {
      id: 'ID_SUB_CATEGORY_1_ONLINE_OR_OFFLINE',
      categoryId: 'CATEGORY_1',
      proLabel: 'Sub-category 1 online or offline',
      appLabel: 'Sub-category 1 online or offline',
      isEvent: false,
      conditionalFields: [],
      canBeDuo: false,
      canBeEducational: true,
      onlineOfflinePlatform: 'ONLINE_OR_OFFLINE',
      isSelectable: true,
    },
    {
      id: 'ID_SUB_CATEGORY_1_OFFLINE',
      categoryId: 'CATEGORY_1',
      proLabel: 'Sub-category 1 offline',
      appLabel: 'Sub-category 1 offline',
      isEvent: false,
      conditionalFields: [],
      canBeDuo: false,
      canBeEducational: true,
      onlineOfflinePlatform: 'OFFLINE',
      isSelectable: true,
    },
    {
      id: 'ID_SUB_CATEGORY_1_ONLINE',
      categoryId: 'CATEGORY_1',
      proLabel: 'Sub-category 1 online',
      appLabel: 'Sub-category 1 online',
      isEvent: false,
      conditionalFields: [],
      canBeDuo: false,
      canBeEducational: true,
      onlineOfflinePlatform: 'ONLINE',
      isSelectable: true,
    },
    {
      id: 'ID_SUB_CATEGORY_2_ONLINE_OR_OFFLINE',
      categoryId: 'CATEGORY_2',
      proLabel: 'Sub-category 2 online or offline',
      appLabel: 'Sub-category 2 online or offline',
      isEvent: false,
      conditionalFields: [],
      canBeDuo: false,
      canBeEducational: true,
      onlineOfflinePlatform: 'ONLINE_OR_OFFLINE',
      isSelectable: true,
    },
  ],
}
export const offerAccessible = {
  id: 'AAA',
  nonHumanizedId: 111,
  subcategoryId: 'ID_SUB_CATEGORY_1_ONLINE_OR_OFFLINE',
  name: 'Offer accessible',
  venue: venuePhysicalAccessible,
  thumbUrl: null,
  description: 'My offer accessible description',
  withdrawalDetails: 'My offer accessible withdrawal details',
  status: 'SOLD_OUT',
  extraData: {},
  audioDisabilityCompliant: false,
  mentalDisabilityCompliant: true,
  motorDisabilityCompliant: false,
  visualDisabilityCompliant: true,
}
export const offerUndefinedAccessibility = {
  id: 'BBB',
  nonHumanizedId: 222,
  subcategoryId: 'ID_SUB_CATEGORY_1_ONLINE_OR_OFFLINE',
  name: 'Offer without accessibility',
  venue: venuePhysicalUndefinedAccessibility,
  thumbUrl: null,
  description: 'My offer without accessibility description',
  withdrawalDetails: 'My offer without accessibility withdrawal details',
  status: 'SOLD_OUT',
  extraData: {},
  audioDisabilityCompliant: null,
  mentalDisabilityCompliant: null,
  motorDisabilityCompliant: null,
  visualDisabilityCompliant: null,
}
export const offerUndefinedAccessibilityVenueAccessible = {
  id: 'BBB',
  nonHumanizedId: 222,
  subcategoryId: 'ID_SUB_CATEGORY_1_ONLINE_OR_OFFLINE',
  name: 'Offer without accessibility',
  venue: venuePhysicalAccessible,
  thumbUrl: null,
  description: 'My offer without accessibility description',
  withdrawalDetails: 'My offer without accessibility withdrawal details',
  status: 'SOLD_OUT',
  extraData: {},
  audioDisabilityCompliant: null,
  mentalDisabilityCompliant: null,
  motorDisabilityCompliant: null,
  visualDisabilityCompliant: null,
}
