ACCESLIBRE_RESULTS = {
    "count": 2,
    "page_size": 50,
    "next": None,
    "previous": None,
    "results": [
        {
            "url": "https://acceslibre.beta.gouv.fr/api/erps/le-bateau-livre/",
            "web_url": "https://acceslibre.beta.gouv.fr/app/59-lille/a/librairie/erp/le-bateau-livre/",
            "uuid": "5cfa5da3-5dac-494d-9061-6a0665072d18",
            "activite": {"nom": "Librairie", "slug": "librairie"},
            "nom": "Le Bateau Livre",
            "slug": "le-bateau-livre",
            "adresse": "154 Rue Leon Gambetta (Lille) 59000 Lille",
            "commune": "Lille",
            "code_insee": None,
            "code_postal": "59000",
            "geom": {"type": "Point", "coordinates": [3.054533, 50.629497]},
            "ban_id": "59350_5513_00154",
            "siret": None,
            "telephone": "03 20 78 16 30",
            "site_internet": "http://www.lebateaulivre.fr",
            "contact_email": None,
            "contact_url": None,
            "user_type": "public",
            "accessibilite": {
                "url": "https://acceslibre.beta.gouv.fr/api/accessibilite/197265/",
                "erp": "https://acceslibre.beta.gouv.fr/api/erps/le-bateau-livre/",
                "transport": {
                    "transport_station_presence": False,
                    "transport_information": "",
                    "stationnement_presence": False,
                    "stationnement_pmr": None,
                    "stationnement_ext_presence": True,
                    "stationnement_ext_pmr": None,
                },
                "cheminement_ext": {
                    "cheminement_ext_presence": False,
                    "cheminement_ext_terrain_stable": None,
                    "cheminement_ext_plain_pied": None,
                    "cheminement_ext_ascenseur": None,
                    "cheminement_ext_nombre_marches": None,
                    "cheminement_ext_sens_marches": None,
                    "cheminement_ext_reperage_marches": None,
                    "cheminement_ext_main_courante": None,
                    "cheminement_ext_rampe": None,
                    "cheminement_ext_pente_presence": None,
                    "cheminement_ext_pente_degre_difficulte": None,
                    "cheminement_ext_pente_longueur": None,
                    "cheminement_ext_devers": None,
                    "cheminement_ext_bande_guidage": None,
                    "cheminement_ext_retrecissement": None,
                },
                "entree": {
                    "entree_reperage": True,
                    "entree_porte_presence": True,
                    "entree_porte_manoeuvre": "battante",
                    "entree_porte_type": "manuelle",
                    "entree_vitree": True,
                    "entree_vitree_vitrophanie": None,
                    "entree_plain_pied": True,
                    "entree_ascenseur": None,
                    "entree_marches": None,
                    "entree_marches_sens": None,
                    "entree_marches_reperage": None,
                    "entree_marches_main_courante": None,
                    "entree_marches_rampe": None,
                    "entree_dispositif_appel": False,
                    "entree_dispositif_appel_type": [],
                    "entree_balise_sonore": False,
                    "entree_aide_humaine": False,
                    "entree_largeur_mini": 180,
                    "entree_pmr": False,
                    "entree_pmr_informations": "",
                },
                "accueil": {
                    "accueil_visibilite": None,
                    "accueil_cheminement_plain_pied": None,
                    "accueil_cheminement_ascenseur": None,
                    "accueil_cheminement_nombre_marches": None,
                    "accueil_cheminement_sens_marches": None,
                    "accueil_cheminement_reperage_marches": None,
                    "accueil_cheminement_main_courante": None,
                    "accueil_cheminement_rampe": None,
                    "accueil_retrecissement": None,
                    "accueil_chambre_nombre_accessibles": None,
                    "accueil_chambre_douche_plain_pied": None,
                    "accueil_chambre_douche_siege": None,
                    "accueil_chambre_douche_barre_appui": None,
                    "accueil_chambre_sanitaires_barre_appui": None,
                    "accueil_chambre_sanitaires_espace_usage": None,
                    "accueil_chambre_numero_visible": None,
                    "accueil_chambre_equipement_alerte": None,
                    "accueil_chambre_accompagnement": None,
                    "accueil_personnels": "non-formés",
                    "accueil_audiodescription_presence": None,
                    "accueil_audiodescription": [],
                    "accueil_equipements_malentendants_presence": None,
                    "accueil_equipements_malentendants": [],
                    "sanitaires_presence": False,
                    "sanitaires_adaptes": None,
                },
                "registre": {"registre_url": ""},
                "conformite": {"conformite": None},
                "commentaire": {"labels": [], "labels_familles_handicap": [], "labels_autre": None, "commentaire": ""},
            },
            "distance": None,
            "source_id": "fd9f411cf1e5f52716d50a17396c0aa828f61ef4",
            "asp_id": None,
            "updated_at": "2024-02-08T10:13:36.991603+01:00",
            "created_at": "2023-03-13T14:50:47.945955+01:00",
        },
        {
            "url": "https://acceslibre.beta.gouv.fr/api/erps/la-chouette-librairie/",
            "web_url": "https://acceslibre.beta.gouv.fr/app/59-lille/a/librairie/erp/la-chouette-librairie/",
            "uuid": "3b35474c-9211-4afa-b3b0-85a7d7392d60",
            "activite": {"nom": "Librairie", "slug": "librairie"},
            "nom": "La Chouette Librairie",
            "slug": "la-chouette-librairie",
            "adresse": "72 Rue de l'Hôpital Militaire 59800 Lille",
            "commune": "Lille",
            "code_insee": "59350",
            "code_postal": "59800",
            "geom": {"type": "Point", "coordinates": [3.060052, 50.635356]},
            "ban_id": "59350_4534_00072",
            "siret": "84009386800015",
            "telephone": "0320097968",
            "site_internet": "https://www.lachouettelibrairie.com/",
            "contact_email": "contact@lachouettelibrairie.com",
            "contact_url": None,
            "user_type": "gestionnaire",
            "accessibilite": {
                "url": "https://acceslibre.beta.gouv.fr/api/accessibilite/8328/",
                "erp": "https://acceslibre.beta.gouv.fr/api/erps/la-chouette-librairie/",
                "transport": {
                    "transport_station_presence": True,
                    "transport_information": "La navette du Vieux Lille passe dans la rue de l'Hôpital Militaire, il suffit de lui faire signe pour qu'elle s'arrête devant notre porte ou qu'elle vous dépose à la librairie.\r\nLe métro Rihour est à 300m.",
                    "stationnement_presence": False,
                    "stationnement_pmr": None,
                    "stationnement_ext_presence": True,
                    "stationnement_ext_pmr": None,
                },
                "cheminement_ext": {
                    "cheminement_ext_presence": None,
                    "cheminement_ext_terrain_stable": None,
                    "cheminement_ext_plain_pied": None,
                    "cheminement_ext_ascenseur": None,
                    "cheminement_ext_nombre_marches": None,
                    "cheminement_ext_sens_marches": None,
                    "cheminement_ext_reperage_marches": None,
                    "cheminement_ext_main_courante": None,
                    "cheminement_ext_rampe": None,
                    "cheminement_ext_pente_presence": None,
                    "cheminement_ext_pente_degre_difficulte": None,
                    "cheminement_ext_pente_longueur": None,
                    "cheminement_ext_devers": None,
                    "cheminement_ext_bande_guidage": None,
                    "cheminement_ext_retrecissement": None,
                },
                "entree": {
                    "entree_reperage": True,
                    "entree_porte_presence": True,
                    "entree_porte_manoeuvre": "battante",
                    "entree_porte_type": "manuelle",
                    "entree_vitree": True,
                    "entree_vitree_vitrophanie": True,
                    "entree_plain_pied": False,
                    "entree_ascenseur": False,
                    "entree_marches": 2,
                    "entree_marches_sens": "montant",
                    "entree_marches_reperage": False,
                    "entree_marches_main_courante": False,
                    "entree_marches_rampe": "amovible",
                    "entree_dispositif_appel": None,
                    "entree_dispositif_appel_type": [],
                    "entree_balise_sonore": False,
                    "entree_aide_humaine": True,
                    "entree_largeur_mini": 90,
                    "entree_pmr": False,
                    "entree_pmr_informations": "",
                },
                "accueil": {
                    "accueil_visibilite": True,
                    "accueil_cheminement_plain_pied": True,
                    "accueil_cheminement_ascenseur": None,
                    "accueil_cheminement_nombre_marches": None,
                    "accueil_cheminement_sens_marches": None,
                    "accueil_cheminement_reperage_marches": None,
                    "accueil_cheminement_main_courante": None,
                    "accueil_cheminement_rampe": None,
                    "accueil_retrecissement": True,
                    "accueil_chambre_nombre_accessibles": None,
                    "accueil_chambre_douche_plain_pied": None,
                    "accueil_chambre_douche_siege": None,
                    "accueil_chambre_douche_barre_appui": None,
                    "accueil_chambre_sanitaires_barre_appui": None,
                    "accueil_chambre_sanitaires_espace_usage": None,
                    "accueil_chambre_numero_visible": None,
                    "accueil_chambre_equipement_alerte": None,
                    "accueil_chambre_accompagnement": None,
                    "accueil_personnels": "formés",
                    "accueil_audiodescription_presence": None,
                    "accueil_audiodescription": [],
                    "accueil_equipements_malentendants_presence": False,
                    "accueil_equipements_malentendants": [],
                    "sanitaires_presence": False,
                    "sanitaires_adaptes": None,
                },
                "registre": {"registre_url": None},
                "conformite": {"conformite": None},
                "commentaire": {
                    "labels": [],
                    "labels_familles_handicap": [],
                    "labels_autre": None,
                    "commentaire": "Nous avions une sonnette pour appeler de l'extérieur, mais elle a été arrachée (malveillance). Il suffit de toquer à la porte ou de nous faire signe par la vitrine, nous vous ouvrirons et vous aiderons (ouverture de porte, rampe...).\r\nNous faisons également de notre mieux pour accompagner les personnes avec des déficiences auditives ou visuelles, n'hésitez pas à nous demander de l'aide.",
                },
            },
            "distance": None,
            "source_id": "8822a6168594f3526a0bb84e193bd6080306bf8b",
            "asp_id": None,
            "updated_at": "2023-04-13T15:00:47.870837+02:00",
            "created_at": "2021-05-20T17:18:54.646447+02:00",
        },
    ],
}

ACCESLIBRE_RESULTS_BY_NAME = {
    "count": 2,
    "page_size": 50,
    "next": None,
    "previous": None,
    "results": [
        {
            "url": "https://acceslibre.beta.gouv.fr/api/erps/furet-du-nord/",
            "web_url": "https://acceslibre.beta.gouv.fr/app/59-lille/a/librairie/erp/furet-du-nord/",
            "uuid": "4e0c4078-0441-4118-9401-676fb733e307",
            "activite": {"nom": "Librairie", "slug": "librairie"},
            "nom": "Furet du Nord",
            "slug": "furet-du-nord",
            "adresse": "15 Place du Général De Gaulle 59800 Lille",
            "commune": "Lille",
            "code_insee": "59350",
            "code_postal": "59800",
            "geom": {"type": "Point", "coordinates": [3.063081, 50.636688]},
            "ban_id": "59350_3839_00015",
            "siret": None,
            "telephone": "03.20.78.43.43",
            "site_internet": "http://Furet.com",
            "contact_email": None,
            "contact_url": None,
            "user_type": "gestionnaire",
            "accessibilite": {
                "url": "https://acceslibre.beta.gouv.fr/api/accessibilite/178102/",
                "erp": "https://acceslibre.beta.gouv.fr/api/erps/furet-du-nord/",
                "transport": {
                    "transport_station_presence": True,
                    "transport_information": "Metro Rihour",
                    "stationnement_presence": False,
                    "stationnement_pmr": None,
                    "stationnement_ext_presence": True,
                    "stationnement_ext_pmr": True,
                },
                "cheminement_ext": {
                    "cheminement_ext_presence": False,
                    "cheminement_ext_terrain_stable": None,
                    "cheminement_ext_plain_pied": None,
                    "cheminement_ext_ascenseur": None,
                    "cheminement_ext_nombre_marches": None,
                    "cheminement_ext_sens_marches": None,
                    "cheminement_ext_reperage_marches": None,
                    "cheminement_ext_main_courante": None,
                    "cheminement_ext_rampe": None,
                    "cheminement_ext_pente_presence": None,
                    "cheminement_ext_pente_degre_difficulte": None,
                    "cheminement_ext_pente_longueur": None,
                    "cheminement_ext_devers": None,
                    "cheminement_ext_bande_guidage": None,
                    "cheminement_ext_retrecissement": None,
                },
                "entree": {
                    "entree_reperage": True,
                    "entree_porte_presence": True,
                    "entree_porte_manoeuvre": "battante",
                    "entree_porte_type": "manuelle",
                    "entree_vitree": True,
                    "entree_vitree_vitrophanie": True,
                    "entree_plain_pied": True,
                    "entree_ascenseur": None,
                    "entree_marches": None,
                    "entree_marches_sens": None,
                    "entree_marches_reperage": None,
                    "entree_marches_main_courante": None,
                    "entree_marches_rampe": None,
                    "entree_dispositif_appel": False,
                    "entree_dispositif_appel_type": [],
                    "entree_balise_sonore": False,
                    "entree_aide_humaine": True,
                    "entree_largeur_mini": 180,
                    "entree_pmr": False,
                    "entree_pmr_informations": "",
                },
                "accueil": {
                    "accueil_visibilite": True,
                    "accueil_cheminement_plain_pied": False,
                    "accueil_cheminement_ascenseur": True,
                    "accueil_cheminement_nombre_marches": 0,
                    "accueil_cheminement_sens_marches": None,
                    "accueil_cheminement_reperage_marches": False,
                    "accueil_cheminement_main_courante": True,
                    "accueil_cheminement_rampe": "fixe",
                    "accueil_retrecissement": False,
                    "accueil_chambre_nombre_accessibles": None,
                    "accueil_chambre_douche_plain_pied": None,
                    "accueil_chambre_douche_siege": None,
                    "accueil_chambre_douche_barre_appui": None,
                    "accueil_chambre_sanitaires_barre_appui": None,
                    "accueil_chambre_sanitaires_espace_usage": None,
                    "accueil_chambre_numero_visible": None,
                    "accueil_chambre_equipement_alerte": None,
                    "accueil_chambre_accompagnement": None,
                    "accueil_personnels": "formés",
                    "accueil_audiodescription_presence": None,
                    "accueil_audiodescription": [],
                    "accueil_equipements_malentendants_presence": False,
                    "accueil_equipements_malentendants": [],
                    "sanitaires_presence": False,
                    "sanitaires_adaptes": None,
                },
                "registre": {"registre_url": ""},
                "conformite": {"conformite": None},
                "commentaire": {"labels": [], "labels_familles_handicap": [], "labels_autre": None, "commentaire": ""},
            },
            "distance": None,
            "source_id": None,
            "asp_id": None,
            "updated_at": "2023-10-31T14:04:33.366858+01:00",
            "created_at": "2022-12-08T12:02:51.533470+01:00",
        },
        {
            "url": "https://acceslibre.beta.gouv.fr/api/erps/theatre-du-nord-grandplace-lille/",
            "web_url": "https://acceslibre.beta.gouv.fr/app/59-lille/a/theatre/erp/theatre-du-nord-grandplace-lille/",
            "uuid": "7519d96d-e22b-496c-88ea-391e4a267902",
            "activite": {"nom": "Théâtre", "slug": "theatre"},
            "nom": "Théâtre du Nord - Grand'Place, Lille",
            "slug": "theatre-du-nord-grandplace-lille",
            "adresse": "4 Place du Général De Gaulle 59800 Lille",
            "commune": "Lille",
            "code_insee": None,
            "code_postal": "59800",
            "geom": {"type": "Point", "coordinates": [3.063927590847016, 50.636380356023245]},
            "ban_id": "59350_3839_00004",
            "siret": None,
            "telephone": "03.20.14.24.24",
            "site_internet": "https://www.theatredunord.fr",
            "contact_email": "accueil@theatredunord.fr",
            "contact_url": None,
            "user_type": "gestionnaire",
            "accessibilite": {
                "url": "https://acceslibre.beta.gouv.fr/api/accessibilite/199653/",
                "erp": "https://acceslibre.beta.gouv.fr/api/erps/theatre-du-nord-grandplace-lille/",
                "transport": {
                    "transport_station_presence": True,
                    "transport_information": "Métro Ligne 1 Station Rihour (à 100m)\r\nParking Grand'Place (à 120m)",
                    "stationnement_presence": False,
                    "stationnement_pmr": None,
                    "stationnement_ext_presence": True,
                    "stationnement_ext_pmr": True,
                },
                "cheminement_ext": {
                    "cheminement_ext_presence": False,
                    "cheminement_ext_terrain_stable": None,
                    "cheminement_ext_plain_pied": None,
                    "cheminement_ext_ascenseur": None,
                    "cheminement_ext_nombre_marches": None,
                    "cheminement_ext_sens_marches": None,
                    "cheminement_ext_reperage_marches": None,
                    "cheminement_ext_main_courante": None,
                    "cheminement_ext_rampe": None,
                    "cheminement_ext_pente_presence": None,
                    "cheminement_ext_pente_degre_difficulte": None,
                    "cheminement_ext_pente_longueur": None,
                    "cheminement_ext_devers": None,
                    "cheminement_ext_bande_guidage": None,
                    "cheminement_ext_retrecissement": None,
                },
                "entree": {
                    "entree_reperage": True,
                    "entree_porte_presence": True,
                    "entree_porte_manoeuvre": "battante",
                    "entree_porte_type": "manuelle",
                    "entree_vitree": True,
                    "entree_vitree_vitrophanie": True,
                    "entree_plain_pied": True,
                    "entree_ascenseur": None,
                    "entree_marches": None,
                    "entree_marches_sens": None,
                    "entree_marches_reperage": None,
                    "entree_marches_main_courante": None,
                    "entree_marches_rampe": None,
                    "entree_dispositif_appel": None,
                    "entree_dispositif_appel_type": [],
                    "entree_balise_sonore": None,
                    "entree_aide_humaine": True,
                    "entree_largeur_mini": 100,
                    "entree_pmr": False,
                    "entree_pmr_informations": "",
                },
                "accueil": {
                    "accueil_visibilite": True,
                    "accueil_cheminement_plain_pied": True,
                    "accueil_cheminement_ascenseur": None,
                    "accueil_cheminement_nombre_marches": None,
                    "accueil_cheminement_sens_marches": None,
                    "accueil_cheminement_reperage_marches": None,
                    "accueil_cheminement_main_courante": None,
                    "accueil_cheminement_rampe": None,
                    "accueil_retrecissement": False,
                    "accueil_chambre_nombre_accessibles": None,
                    "accueil_chambre_douche_plain_pied": None,
                    "accueil_chambre_douche_siege": None,
                    "accueil_chambre_douche_barre_appui": None,
                    "accueil_chambre_sanitaires_barre_appui": None,
                    "accueil_chambre_sanitaires_espace_usage": None,
                    "accueil_chambre_numero_visible": None,
                    "accueil_chambre_equipement_alerte": None,
                    "accueil_chambre_accompagnement": None,
                    "accueil_personnels": "formés",
                    "accueil_audiodescription_presence": True,
                    "accueil_audiodescription": ["avec_équipement_occasionnel"],
                    "accueil_equipements_malentendants_presence": True,
                    "accueil_equipements_malentendants": ["bmp", "lsf", "sts", "autres"],
                    "sanitaires_presence": True,
                    "sanitaires_adaptes": True,
                },
                "registre": {"registre_url": "https://www.theatredunord.fr/avec-les-publics/public-handicape"},
                "conformite": {"conformite": None},
                "commentaire": {"labels": [], "labels_familles_handicap": [], "labels_autre": None, "commentaire": ""},
            },
            "distance": None,
            "source_id": None,
            "asp_id": None,
            "updated_at": "2023-03-23T11:41:10.422438+01:00",
            "created_at": "2023-03-23T11:21:15.118227+01:00",
        },
    ],
}

ACCESLIBRE_RESULTS_EMPTY = {"count": 0, "page_size": 50, "next": None, "previous": None, "results": []}
