/* istanbul ignore file */
import fullArchiveIcon from 'icons/full-archive.svg'
import fullArrowLeftIcon from 'icons/full-arrow-left.svg'
import fullArrowRightIcon from 'icons/full-arrow-right.svg'
import fullBackIcon from 'icons/full-back.svg'
import fullBookIcon from 'icons/full-book.svg'
import fullBoostedIcon from 'icons/full-boosted.svg'
import fullBurgerIcon from 'icons/full-burger.svg'
import fullCheckIcon from 'icons/full-check.svg'
import fullClearIcon from 'icons/full-clear.svg'
import fullCloseIcon from 'icons/full-close.svg'
import fullCodeIcon from 'icons/full-code.svg'
import fullDisclosureCloseIcon from 'icons/full-disclosure-close.svg'
import fullDisclosureOpenIcon from 'icons/full-disclosure-open.svg'
import fullDownIcon from 'icons/full-down.svg'
import fullDownloadIcon from 'icons/full-download.svg'
import fullDuplicateIcon from 'icons/full-duplicate.svg'
import fullEditIcon from 'icons/full-edit.svg'
import fullErrorIcon from 'icons/full-error.svg'
import fullGoTop from 'icons/full-go-top.svg'
import fullGridIcon from 'icons/full-grid.svg'
import fullHelpIcon from 'icons/full-help.svg'
import fullHideIcon from 'icons/full-hide.svg'
import fullInfoIcon from 'icons/full-info.svg'
import fullKeyIcon from 'icons/full-key.svg'
import fullLeftIcon from 'icons/full-left.svg'
import fullLessIcon from 'icons/full-less.svg'
import fullLinkIcon from 'icons/full-link.svg'
import fullListIcon from 'icons/full-list.svg'
import fullLocationIcon from 'icons/full-location.svg'
import fullLogoutIcon from 'icons/full-logout.svg'
import fullMailIcon from 'icons/full-mail.svg'
import fullMoreIcon from 'icons/full-more.svg'
import fullNextIcon from 'icons/full-next.svg'
import fullOtherIcon from 'icons/full-other.svg'
import fullParametersIcon from 'icons/full-parameters.svg'
import fullPauseIcon from 'icons/full-pause.svg'
import fullPlayIcon from 'icons/full-play.svg'
import fullPlusIcon from 'icons/full-plus.svg'
import fullProfilIcon from 'icons/full-profil.svg'
import fullRefreshIcon from 'icons/full-refresh.svg'
import fullRightIcon from 'icons/full-right.svg'
import fullShowIcon from 'icons/full-show.svg'
import fullSmsIcon from 'icons/full-sms.svg'
import fullSortIcon from 'icons/full-sort.svg'
import fullStarIcon from 'icons/full-star.svg'
import fullSwitchIcon from 'icons/full-switch.svg'
import fullThreeDotsIcon from 'icons/full-three-dots.svg'
import fullThumbUpIcon from 'icons/full-thumb-up.svg'
import fullTrashIcon from 'icons/full-trash.svg'
import fullUpIcon from 'icons/full-up.svg'
import fullValidateIcon from 'icons/full-validate.svg'
import fullWaitIcon from 'icons/full-wait.svg'
import fullWarningIcon from 'icons/full-warning.svg'
import logoPassCultureProFullIcon from 'icons/logo-pass-culture-pro-full.svg'
import logoPassCultureProIcon from 'icons/logo-pass-culture-pro.svg'
import logoPassCultureIcon from 'icons/logo-pass-culture.svg'
import stroke404Icon from 'icons/stroke-404.svg'
import strokeAccessibilityBrainIcon from 'icons/stroke-accessibility-brain.svg'
import strokeAccessibilityEarIcon from 'icons/stroke-accessibility-ear.svg'
import strokeAccessibilityEyeIcon from 'icons/stroke-accessibility-eye.svg'
import strokeAccessibilityLegIcon from 'icons/stroke-accessibility-leg.svg'
import strokeAddCalendarIcon from 'icons/stroke-add-calendar.svg'
import strokeArticleIcon from 'icons/stroke-article.svg'
import strokeBagIcon from 'icons/stroke-bag.svg'
import strokeBarcodeIcon from 'icons/stroke-barcode.svg'
import strokeBookedIcon from 'icons/stroke-booked.svg'
import strokeBookingHold from 'icons/stroke-booking-hold.svg'
import strokeBuildingIcon from 'icons/stroke-building.svg'
import strokeCalendarIcon from 'icons/stroke-calendar.svg'
import strokeCheckIcon from 'icons/stroke-check.svg'
import strokeClockIcon from 'icons/stroke-clock.svg'
import strokeCloseIcon from 'icons/stroke-close.svg'
import strokeCodeIcon from 'icons/stroke-code.svg'
import strokeCollaboratorIcon from 'icons/stroke-collaborator.svg'
import strokeConnectIcon from 'icons/stroke-connect.svg'
import strokeDateIcon from 'icons/stroke-date.svg'
import strokeDeskIcon from 'icons/stroke-desk.svg'
import strokeDoubleCheckIcon from 'icons/stroke-double-check.svg'
import strokeDownIcon from 'icons/stroke-down.svg'
import strokeDraftIcon from 'icons/stroke-draft.svg'
import strokeDuoIcon from 'icons/stroke-duo.svg'
import strokeDuplicateOfferIcon from 'icons/stroke-duplicate-offer.svg'
import strokeErrorIcon from 'icons/stroke-error.svg'
import strokeEuroIcon from 'icons/stroke-euro.svg'
import strokeEventsIcon from 'icons/stroke-events.svg'
import strokeFranceIcon from 'icons/stroke-france.svg'
import strokeFraudIcon from 'icons/stroke-fraud.svg'
import strokeHideIcon from 'icons/stroke-hide.svg'
import strokeHomeIcon from 'icons/stroke-home.svg'
import strokeHourglassIcon from 'icons/stroke-hourglass.svg'
import strokeInfoIcon from 'icons/stroke-info.svg'
import strokeInstitutionIcon from 'icons/stroke-institution.svg'
import strokeLeftIcon from 'icons/stroke-left.svg'
import strokeLessIcon from 'icons/stroke-less.svg'
import strokeLibraryIcon from 'icons/stroke-library.svg'
import strokeLinkIcon from 'icons/stroke-link.svg'
import strokeLocationIcon from 'icons/stroke-location.svg'
import strokeMailIcon from 'icons/stroke-mail.svg'
import strokeMoreIcon from 'icons/stroke-more.svg'
import strokeNearIcon from 'icons/stroke-near.svg'
import strokeNewOfferIcon from 'icons/stroke-new-offer.svg'
import strokeNoBookingIcon from 'icons/stroke-no-booking.svg'
import strokeOfferIcon from 'icons/stroke-offer.svg'
import strokePageNotFoundIcon from 'icons/stroke-page-not-found.svg'
import strokePartyIcon from 'icons/stroke-party.svg'
import strokePassIcon from 'icons/stroke-pass.svg'
import strokePhoneIcon from 'icons/stroke-phone.svg'
import strokePictureIcon from 'icons/stroke-picture.svg'
import strokePriceIcon from 'icons/stroke-price.svg'
import strokeRepaymentIcon from 'icons/stroke-repayment.svg'
import strokeRightIcon from 'icons/stroke-right.svg'
import strokeSearchIcon from 'icons/stroke-search.svg'
import strokeShareIcon from 'icons/stroke-share.svg'
import strokeShowIcon from 'icons/stroke-show.svg'
import strokeStarIcon from 'icons/stroke-star.svg'
import strokeTeacherIcon from 'icons/stroke-teacher.svg'
import strokeTemplateOfferIcon from 'icons/stroke-template-offer.svg'
import strokeThingIcon from 'icons/stroke-thing.svg'
import strokeTrashIcon from 'icons/stroke-trash.svg'
import strokeUserIcon from 'icons/stroke-user.svg'
import strokeValidIcon from 'icons/stroke-valid.svg'
import strokeVenueIcon from 'icons/stroke-venue.svg'
import strokeVirtualEventIcon from 'icons/stroke-virtual-event.svg'
import strokeVirtualThingIcon from 'icons/stroke-virtual-thing.svg'
import strokeVisualArtIcon from 'icons/stroke-visual-art.svg'
import strokeWarningIcon from 'icons/stroke-warning.svg'
import strokeWipIcon from 'icons/stroke-wip.svg'
import strokeWrongIcon from 'icons/stroke-wrong.svg'
interface IconListItem {
  src: string
  viewBox?: string
}

// Those icons are put in the order of the design library here:
// https://www.figma.com/file/AEXCkb4KbUyPmB4BRFa88s/PRO---Library?type=design&node-id=8059-111986&t=sLfFXFbaXGFLjdhX-0
export const fullIcons: IconListItem[] = [
  { src: fullThumbUpIcon },
  { src: fullPauseIcon },
  { src: fullPlayIcon },
  { src: fullValidateIcon },
  { src: fullClearIcon },
  { src: fullInfoIcon },
  { src: fullErrorIcon },
  { src: fullHelpIcon },
  { src: fullLinkIcon },
  { src: fullMoreIcon },
  { src: fullLessIcon },
  { src: fullMailIcon },
  { src: fullEditIcon },
  { src: fullDuplicateIcon },
  { src: fullShowIcon },
  { src: fullHideIcon },
  { src: fullBackIcon },
  { src: fullBookIcon },
  { src: fullNextIcon },
  { src: fullWaitIcon },
  { src: fullRefreshIcon },
  { src: fullOtherIcon },
  { src: fullDownloadIcon },
  { src: fullTrashIcon },
  { src: fullParametersIcon },
  { src: fullKeyIcon },
  { src: fullPlusIcon },
  { src: fullSortIcon },
  { src: fullLocationIcon },
  { src: fullLogoutIcon },
  { src: fullCodeIcon },
  { src: fullDownIcon },
  { src: fullUpIcon },
  { src: fullRightIcon },
  { src: fullLeftIcon },
  { src: fullGoTop },
  { src: fullArrowRightIcon },
  { src: fullArrowLeftIcon },
  { src: fullStarIcon },
  { src: fullBurgerIcon },
  { src: fullWarningIcon },
  { src: fullGridIcon },
  { src: fullListIcon },
  { src: fullCheckIcon },
  { src: fullDisclosureCloseIcon },
  { src: fullDisclosureOpenIcon },
  { src: fullProfilIcon },
  { src: fullCloseIcon },
  { src: fullThreeDotsIcon },
  { src: fullSwitchIcon },
  { src: fullArchiveIcon },
  { src: fullBoostedIcon },
  { src: fullSmsIcon },
]

export const strokeIcons: IconListItem[] = [
  { src: strokeUserIcon },
  { src: strokeFraudIcon },
  { src: strokeErrorIcon },
  { src: strokeWarningIcon },
  { src: strokeInfoIcon },
  { src: strokeClockIcon },
  { src: strokeValidIcon },
  { src: strokeWrongIcon },
  { src: strokeMoreIcon },
  { src: strokeLessIcon },
  { src: strokeCheckIcon },
  { src: strokeDoubleCheckIcon },
  { src: strokeOfferIcon },
  { src: strokeRepaymentIcon },
  { src: strokeEuroIcon },
  { src: strokePriceIcon },
  { src: strokeEventsIcon },
  { src: strokeThingIcon },
  { src: strokeDuoIcon },
  { src: strokeVirtualEventIcon },
  { src: strokeVirtualThingIcon },
  { src: strokeTemplateOfferIcon },
  { src: strokeBookedIcon },
  { src: strokeConnectIcon },
  { src: strokeMailIcon },
  { src: strokePhoneIcon },
  { src: strokeNearIcon },
  { src: strokeLocationIcon },
  { src: strokeFranceIcon },
  { src: strokeHomeIcon },
  { src: strokeBuildingIcon },
  { src: strokeDeskIcon },
  { src: strokeCalendarIcon },
  { src: strokeDateIcon },
  { src: strokeHourglassIcon },
  { src: strokeShowIcon },
  { src: strokeHideIcon },
  { src: strokeShareIcon },
  { src: strokeSearchIcon },
  { src: strokeTrashIcon },
  { src: strokeDraftIcon },
  { src: strokeTeacherIcon },
  { src: strokeCodeIcon },
  { src: strokeAccessibilityEyeIcon },
  { src: strokeAccessibilityEarIcon },
  { src: strokeAccessibilityLegIcon },
  { src: strokeAccessibilityBrainIcon },
  { src: strokePartyIcon },
  { src: strokeNewOfferIcon },
  { src: strokeDuplicateOfferIcon },
  { src: strokeCloseIcon },
  { src: strokeLeftIcon },
  { src: strokeRightIcon },
  { src: strokeDownIcon },
  { src: strokeLinkIcon },
  { src: strokePassIcon },
  { src: strokeLibraryIcon },
  { src: strokeVenueIcon },
  { src: strokeStarIcon },
  { src: strokeArticleIcon },
  { src: strokeInstitutionIcon },
  { src: strokeWipIcon },
  { src: strokeNoBookingIcon },
  { src: strokeBookingHold },
  { src: stroke404Icon },
  { src: strokeCollaboratorIcon },
  { src: strokeBagIcon },
  { src: strokeBarcodeIcon },
  { src: strokePageNotFoundIcon },
  { src: strokeVisualArtIcon },
  { src: strokeAddCalendarIcon },
  { src: strokePictureIcon, viewBox: '0 0 58 58' },
]

export const otherIcons: IconListItem[] = [
  { src: logoPassCultureIcon, viewBox: '0 0 71 24' },
  { src: logoPassCultureProIcon, viewBox: '0 0 119 40' },
  { src: logoPassCultureProFullIcon, viewBox: '0 0 282 120' },
]
