PASS_CULTURE_VOUCHER_CODE = "PSCULTURE"
VOUCHER_PAYMENT_TYPE_CDS = "VCH"
SEATMAP_HARDCODED_LABELS_SCREENID = "SEATMAP_HARDCODED_LABELS_SCREENID_"
CDS_TICKET_ALREADY_CANCELED_ERROR_MESSAGE = "TICKET_ALREADY_CANCELED"
CDS_SHOWTIMES_STOCKS_CACHE_KEY = "api:cinema_provider:cds:stocks:%s:%s"
CDS_SHOWTIMES_STOCKS_CACHE_TIMEOUT = 60
