PASS_CULTURE_VOUCHER_CODE = "PSCULTURE"
VOUCHER_PAYMENT_TYPE_CDS = "VCH"
SEATMAP_HARDCODED_LABELS_SCREENID = "SEATMAP_HARDCODED_LABELS_SCREENID_"
CDS_TICKET_ALREADY_CANCELED_ERROR_MESSAGE = "TICKET_ALREADY_CANCELED"
