export const FEATURES = {
  HOMEPAGE: 'WEBAPP_HOMEPAGE',
  ALLOW_IDCHECK_REGISTRATION: 'ALLOW_IDCHECK_REGISTRATION',
  AUTO_ACTIVATE_DIGITAL_BOOKINGS: 'AUTO_ACTIVATE_DIGITAL_BOOKINGS',
  ENABLE_ACTIVATION_CODES: 'ENABLE_ACTIVATION_CODES',
  USE_APP_SEARCH_ON_WEBAPP: 'USE_APP_SEARCH_ON_WEBAPP',
  ENABLE_NEW_AUTO_EXPIRY_DELAY_BOOKS_BOOKINGS: 'ENABLE_NEW_AUTO_EXPIRY_DELAY_BOOKS_BOOKINGS',
  WEBAPP_V2_ENABLED: 'WEBAPP_V2_ENABLED',
}

export const DEFAULT_WHOLE_FRANCE_OPENING_VALUE = true
