import type { CompatibleBrowser } from './type'

// Auto-generated by scripts/generateSupportedBrowsers.js
// Run `pnpm supported-browsers` after changing browserslist config.
export const compatibleBrowsersList: Record<string, CompatibleBrowser> = {
  and_chr: {
    name: 'Chrome Android',
    minVersion: 149,
  },
  and_ff: {
    name: 'Firefox Android',
    minVersion: 151,
  },
  and_uc: {
    name: 'UC Browser Android',
    minVersion: 15,
  },
  android: {
    name: 'Android Browser',
    minVersion: 149,
  },
  chrome: {
    name: 'Google Chrome',
    minVersion: 126,
  },
  edge: {
    name: 'Microsoft Edge',
    minVersion: 126,
  },
  firefox: {
    name: 'Mozilla Firefox',
    minVersion: 128,
  },
  ios_saf: {
    name: 'Safari iOS',
    minVersion: 26,
  },
  op_mob: {
    name: 'Opera Mobile',
    minVersion: 80,
  },
  opera: {
    name: 'Opera',
    minVersion: 105,
  },
  safari: {
    name: 'Apple Safari',
    minVersion: 26,
  },
  samsung: {
    name: 'Samsung Internet',
    minVersion: 7,
  },
}
