EAN_SEARCH_FIXTURE = {
    "type": 1,
    "magid": "7",
    "compatibility": [],
    "oeuvre": {
        "id": "1048932",
        "titre": "Immortelle randonnée ; Compostelle malgré moi",
        "auteurs": "Jean-Christophe Rufin",
        "auteurs_multi": {"10078": "Jean-Christophe Rufin"},
        "auteurs_id": ["10078"],
        "auteurs_fonction": [],
        "realisateur_multi": [],
        "article": [
            {
                "nombre": 0,
                "gencod": "9782070455379",
                "id_catalogue": ["0"],
                "collection": "Folio",
                "collection_no": "5833",
                "editeur": "Folio",
                "distributeur": "Sodis",
                "code_distributeur": "21",
                "prix": 8.1,
                "prixpays": {
                    "fr": {"value": 8.1, "devise": "&euro;"},
                    "be": {"value": 8.1, "devise": "&euro;"},
                    "ch": {"value": 13.5, "devise": "CHF"},
                },
                "dateparution": "02/10/2014",
                "dateparutionentier": 1412200800,
                "dispo": 1,
                "dispopays": {"fr": 1, "be": 1, "ch": 1},
                "libelledispo": "Disponible",
                "resume": "Un mois sur le Camino del Norte, de Bayonne à Santiago, 40 kilomètres de marche par jour : étape après étape, Jean-Christophe Rufin se transforme en clochard céleste, en routard de Compostelle. Pourquoi prendre le Chemin, quand on a déjà éprouvé toutes les marches, toutes les aventures physiques ? \" Je n'avais en réalité pas eu le choix. Le virus de Saint-Jacques m'avait profondément infecté. J'ignore par qui et par quoi s'est opérée la contagion. \r\nMais, après une phase d'incubation silencieuse, la maladie avait éclaté, et j'en avais tous les symptômes. \" 876 kilomètres plus loin, un mois plus tard, après l'arrivée à Santiago, le constat est là. Comme tous les grands pèlerinages, le Chemin est une expérience de désincarnation, il libère du \" tropplein \", mais il est aussi un itinéraire spirituel, entre cathédrales et ermitages, et humain, car chaque rencontre y prend une résonance particulière.\r",
                "image": "1",
                "image_spe": "1",
                "image_alkor": 0,
                "image_4": "1",
                "imagesUrl": {
                    "recto": "https://images.epagine.fr/379/9782070455379_1_75.jpg",
                    "vign": "https://images.epagine.fr/379/9782070455379_1_v.jpg",
                    "moyen": "https://images.epagine.fr/379/9782070455379_1_m.jpg",
                    "verso": "https://images.epagine.fr/379/9782070455379_4_75.jpg",
                },
                "detailUrl": "/livre/9782070455379-immortelle-randonnee-compostelle-malgre-moi-jean-christophe-rufin/",
                "langue": "Français",
                "langueiso": "fra",
                "langueflag": "https://static.epagine.fr/commonfiles/flags/fr.png",
                "nbmag": "519",
                "codesupport": "P",
                "libellesupport": "Poche",
                "codesupport2": [],
                "libellesupport2": [],
                "chapitre": 0,
                "biblio": "0",
                "extrait": 0,
                "extrait_oeuvre": "1",
                "pages": "288",
                "longueur": 17.8,
                "largeur": 10.8,
                "hauteur": 0,
                "epaisseur": 1.8,
                "poids": "180",
                "biographie": "1",
                "biographies": [],
                "websites": [],
                "datecreation": "23/05/2014",
                "datecreationentier": 1400796000,
                "datemodification": "01/01/2023",
                "serie": "Non précisée",
                "idserie": "0",
                "scolaire": "0",
                "livre_etranger": "0",
                "racine_editeur": "207",
                "code_clil": "3665",
                "type_prix": "4",
                "contenu_explicite": 0,
                "nb_galettes": 0,
                "duree": 0,
                "anneesortie": 0,
                "interpretes": [],
                "typeproduit": 0,
                "colors": [],
                "langues": [],
                "audios": [],
                "soustitres": [],
                "iad": "0",
                "id_code_langue": "10000",
                "taux_tva": "5.50",
                "code_tva": "2",
                "nboccasions": 0,
                "stock": 0,
                "gtl": {
                    "first": {
                        "1": {"code": "1000000", "libelle": "Litt&eacute;rature"},
                        "2": {"code": "1050000", "libelle": "R&eacute;cit"},
                    }
                },
                "gtlvideo": [],
                "operations": [],
                "tracks": [],
                "cmb": "110206",
                "deee_ht": 0,
                "tva": 0,
                "minutesdejeu": 0,
                "nbjoueursmin": 0,
                "nbjoueursmax": 0,
                "colisage": 0,
                "longueurboite": 0,
                "largeurboite": 0,
                "hauteurboite": 0,
                "grammesboite": 0,
                "nbpiles": 0,
                "pilesincluses": 0,
                "nbanneegarantie": 0,
                "produits_recycles": 0,
                "nbpages": 0,
                "grammage": 0,
                "taille_ecriture_mm": 0,
                "poignee": 0,
                "lavable": 0,
                "impermeable": 0,
                "contenance_ml": 0,
                "nbfeuilles": 0,
                "diametre": 0,
                "diametreboite": 0,
                "garantiemois": 0,
                "precommande": 0,
                "ispromotion": 0,
                "isnew": 0,
                "multijoueur": 0,
                "nblicenses": 0,
                "nbutilisateur": 0,
                "internet": 0,
                "pegi": [],
                "drmlcp": 0,
                "bonus_extraits": {
                    "gencod": "9782070455379",
                    "pagesinterieures": "0",
                    "pdfextrait": "0",
                    "pdfpremierchapitre": "0",
                    "pdfparagraphe": "0",
                    "mp3_count": "0",
                },
                "id_lectorat": "0",
                "livre_lu": "0",
                "grands_caracteres": "0",
                "multilingue": "0",
                "illustre": "0",
                "luxe": "0",
                "relie": "0",
                "broche": "1",
                "lectureEnLigne": 0,
                "NombreMagasins": 0,
                "collector": "0",
                "code_editeur": "27818",
                "sorecop": 0,
                "pcb": 0,
                "spcb": 0,
                "volume": 0,
                "compartiment": 0,
                "poche": 0,
            }
        ],
        "biographies": [],
        "websites": [],
        "typeproduit": 0,
    },
    "magOptions": {
        "Data": {
            "MagasinId": "7",
            "MessagerieCommandes": "1",
            "ComboProduits": '{"produits":{"0":{"id":0,"ordre":1,"search":"paper","libelle":"livres"},"1":{"id":1,"ordre":2,"search":"ebook","libelle":"livres_numeriques"},"3":{"id":3,"ordre":3,"search":"dvd","libelle":"dvd"},"4":{"id":4,"ordre":4,"search":"music","libelle":"musique"},"5":{"id":5,"ordre":5,"search":"jouet","libelle":"recherche_jouet"},"6":{"id":6,"ordre":6,"search":"papeterie","libelle":"recherche_papeterie"},"7":{"id":7,"ordre":7,"search":"jeuvideo","libelle":"jeux_video"},"2":{"id":2,"ordre":8,"search":"liseuse","libelle":"liseuses"}},"options":{"tous_produits":{"affichage":2,"search":"all","libelle":"tous_produits"},"tous_livres":{"affichage":1,"search":"allbooks","libelle":"allbooks"},"ebooks_fr":0,"ebooks_gb":0,"ebooks_nl":0,"livres_fr":0}}',
            "TvaEtrangere0": "0",
            "BlocageReimpression": "0",
            "MATOMO": "Matomo",
            "DetailTables": "1",
            "ExtraitsAudio": "0",
            "SEGMENT": "Segment",
        },
        "Keys": [],
        "LibKeys": [],
        "Database": "OAI-PMH",
        "Fields": [],
        "DateFields": [],
        "DefaultFields": [],
        "ReferencedObjects": [],
    },
    "ean": "9782070455379",
    "changeEncodingTo": "UTF-8",
    "extraparams": {"ws": 1},
}
