BOOK_BY_EAN_FIXTURE = {
    "type": 1,
    "magid": "7",
    "compatibility": [],
    "oeuvre": {
        "id": "1048932",
        "titre": "Immortelle randonnée ; Compostelle malgré moi",
        "auteurs": "Jean-Christophe Rufin",
        "auteurs_multi": {"10078": "Jean-Christophe Rufin"},
        "auteurs_id": ["10078"],
        "auteurs_fonction": [],
        "realisateur_multi": [],
        "article": [
            {
                "nombre": 0,
                "gencod": "9782070455379",
                "id_catalogue": ["0"],
                "collection": "Folio",
                "collection_no": "5833",
                "editeur": "Folio",
                "distributeur": "Sodis",
                "code_distributeur": "21",
                "prix": 8.1,
                "prixpays": {
                    "fr": {"value": 8.1, "devise": "&euro;"},
                    "be": {"value": 8.1, "devise": "&euro;"},
                    "ch": {"value": 13.5, "devise": "CHF"},
                },
                "dateparution": "02/10/2014",
                "dateparutionentier": 1412200800,
                "dispo": 1,
                "dispopays": {"fr": 1, "be": 1, "ch": 1},
                "libelledispo": "Disponible",
                "resume": "Un mois sur le Camino del Norte, de Bayonne à Santiago, 40 kilomètres de marche par jour : étape après étape, Jean-Christophe Rufin se transforme en clochard céleste, en routard de Compostelle. Pourquoi prendre le Chemin, quand on a déjà éprouvé toutes les marches, toutes les aventures physiques ? \" Je n'avais en réalité pas eu le choix. Le virus de Saint-Jacques m'avait profondément infecté. J'ignore par qui et par quoi s'est opérée la contagion. \r\nMais, après une phase d'incubation silencieuse, la maladie avait éclaté, et j'en avais tous les symptômes. \" 876 kilomètres plus loin, un mois plus tard, après l'arrivée à Santiago, le constat est là. Comme tous les grands pèlerinages, le Chemin est une expérience de désincarnation, il libère du \" tropplein \", mais il est aussi un itinéraire spirituel, entre cathédrales et ermitages, et humain, car chaque rencontre y prend une résonance particulière.\r",
                "image": "1",
                "image_spe": "1",
                "image_alkor": 0,
                "image_4": "1",
                "imagesUrl": {
                    "recto": "https://images.epagine.fr/379/9782070455379_1_75.jpg",
                    "vign": "https://images.epagine.fr/379/9782070455379_1_v.jpg",
                    "moyen": "https://images.epagine.fr/379/9782070455379_1_m.jpg",
                    "verso": "https://images.epagine.fr/379/9782070455379_4_75.jpg",
                },
                "detailUrl": "/livre/9782070455379-immortelle-randonnee-compostelle-malgre-moi-jean-christophe-rufin/",
                "langue": "Français",
                "langueiso": "fra",
                "langueflag": "https://static.epagine.fr/commonfiles/flags/fr.png",
                "nbmag": "519",
                "codesupport": "P",
                "libellesupport": "Poche",
                "codesupport2": [],
                "libellesupport2": [],
                "chapitre": 0,
                "biblio": "0",
                "extrait": 0,
                "extrait_oeuvre": "1",
                "pages": "288",
                "longueur": 17.8,
                "largeur": 10.8,
                "hauteur": 0,
                "epaisseur": 1.8,
                "poids": "180",
                "biographie": "1",
                "biographies": [],
                "websites": [],
                "datecreation": "23/05/2014",
                "datecreationentier": 1400796000,
                "datemodification": "01/01/2023",
                "serie": "Non précisée",
                "idserie": "0",
                "scolaire": "0",
                "livre_etranger": "0",
                "racine_editeur": "207",
                "code_clil": "3665",
                "type_prix": "4",
                "contenu_explicite": 0,
                "nb_galettes": 0,
                "duree": 0,
                "anneesortie": 0,
                "interpretes": [],
                "typeproduit": 0,
                "colors": [],
                "langues": [],
                "audios": [],
                "soustitres": [],
                "iad": "0",
                "id_code_langue": "10000",
                "taux_tva": "5.50",
                "code_tva": "2",
                "nboccasions": 0,
                "stock": 0,
                "gtl": {
                    "first": {
                        "1": {"code": "1000000", "libelle": "Litt&eacute;rature"},
                        "2": {"code": "1050000", "libelle": "R&eacute;cit"},
                    }
                },
                "gtlvideo": [],
                "operations": [],
                "tracks": [],
                "cmb": "110206",
                "deee_ht": 0,
                "tva": 0,
                "minutesdejeu": 0,
                "nbjoueursmin": 0,
                "nbjoueursmax": 0,
                "colisage": 0,
                "longueurboite": 0,
                "largeurboite": 0,
                "hauteurboite": 0,
                "grammesboite": 0,
                "nbpiles": 0,
                "pilesincluses": 0,
                "nbanneegarantie": 0,
                "produits_recycles": 0,
                "nbpages": 0,
                "grammage": 0,
                "taille_ecriture_mm": 0,
                "poignee": 0,
                "lavable": 0,
                "impermeable": 0,
                "contenance_ml": 0,
                "nbfeuilles": 0,
                "diametre": 0,
                "diametreboite": 0,
                "garantiemois": 0,
                "precommande": 0,
                "ispromotion": 0,
                "isnew": 0,
                "multijoueur": 0,
                "nblicenses": 0,
                "nbutilisateur": 0,
                "internet": 0,
                "pegi": [],
                "drmlcp": 0,
                "bonus_extraits": {
                    "gencod": "9782070455379",
                    "pagesinterieures": "0",
                    "pdfextrait": "0",
                    "pdfpremierchapitre": "0",
                    "pdfparagraphe": "0",
                    "mp3_count": "0",
                },
                "id_lectorat": "0",
                "livre_lu": "0",
                "grands_caracteres": "0",
                "multilingue": "0",
                "illustre": "0",
                "luxe": "0",
                "relie": "0",
                "broche": "1",
                "lectureEnLigne": 0,
                "NombreMagasins": 0,
                "collector": "0",
                "code_editeur": "27818",
                "sorecop": 0,
                "pcb": 0,
                "spcb": 0,
                "volume": 0,
                "compartiment": 0,
                "poche": 0,
            }
        ],
        "biographies": [],
        "websites": [],
        "typeproduit": 0,
    },
    "magOptions": {
        "Data": {
            "MagasinId": "7",
            "MessagerieCommandes": "1",
            "ComboProduits": '{"produits":{"0":{"id":0,"ordre":1,"search":"paper","libelle":"livres"},"1":{"id":1,"ordre":2,"search":"ebook","libelle":"livres_numeriques"},"3":{"id":3,"ordre":3,"search":"dvd","libelle":"dvd"},"4":{"id":4,"ordre":4,"search":"music","libelle":"musique"},"5":{"id":5,"ordre":5,"search":"jouet","libelle":"recherche_jouet"},"6":{"id":6,"ordre":6,"search":"papeterie","libelle":"recherche_papeterie"},"7":{"id":7,"ordre":7,"search":"jeuvideo","libelle":"jeux_video"},"2":{"id":2,"ordre":8,"search":"liseuse","libelle":"liseuses"}},"options":{"tous_produits":{"affichage":2,"search":"all","libelle":"tous_produits"},"tous_livres":{"affichage":1,"search":"allbooks","libelle":"allbooks"},"ebooks_fr":0,"ebooks_gb":0,"ebooks_nl":0,"livres_fr":0}}',
            "TvaEtrangere0": "0",
            "BlocageReimpression": "0",
            "MATOMO": "Matomo",
            "DetailTables": "1",
            "ExtraitsAudio": "0",
            "SEGMENT": "Segment",
        },
        "Keys": [],
        "LibKeys": [],
        "Database": "OAI-PMH",
        "Fields": [],
        "DateFields": [],
        "DefaultFields": [],
        "ReferencedObjects": [],
    },
    "ean": "9782070455379",
    "changeEncodingTo": "UTF-8",
    "extraparams": {"ws": 1},
}


NO_RESULT_BY_EAN_FIXTURE = {
    "type": 1,
    "magid": "7",
    "compatibility": [],
    "magOptions": {
        "Data": {
            "MagasinId": "7",
            "MessagerieCommandes": "1",
            "ComboProduits": '{"produits":{"0":{"id":0,"ordre":1,"search":"paper","libelle":"livres"},"1":{"id":1,"ordre":2,"search":"ebook","libelle":"livres_numeriques"},"3":{"id":3,"ordre":3,"search":"dvd","libelle":"dvd"},"4":{"id":4,"ordre":4,"search":"music","libelle":"musique"},"5":{"id":5,"ordre":5,"search":"jouet","libelle":"recherche_jouet"},"6":{"id":6,"ordre":6,"search":"papeterie","libelle":"recherche_papeterie"},"7":{"id":7,"ordre":7,"search":"jeuvideo","libelle":"jeux_video"},"2":{"id":2,"ordre":8,"search":"liseuse","libelle":"liseuses"}},"options":{"tous_produits":{"affichage":2,"search":"all","libelle":"tous_produits"},"tous_livres":{"affichage":1,"search":"allbooks","libelle":"allbooks"},"ebooks_fr":0,"ebooks_gb":0,"ebooks_nl":0,"livres_fr":0}}',
            "TvaEtrangere0": "0",
            "BlocageReimpression": "0",
            "MATOMO": "Matomo",
            "DetailTables": "1",
            "ExtraitsAudio": "0",
            "SEGMENT": "Segment",
        },
        "Keys": [],
        "LibKeys": [],
        "Database": "OAI-PMH",
        "Fields": [],
        "DateFields": [],
        "DefaultFields": [],
        "ReferencedObjects": [],
    },
    "ean": "9782067256018",
    "changeEncodingTo": "UTF-8",
    "extraparams": {"ws": 1},
}

NO_GTL_IN_RESULT_FIXTURE = {
    "type": 1,
    "magid": "7",
    "compatibility": [],
    "oeuvre": {
        "id": "3634325",
        "titre": "Voyage au pays des nonas",
        "auteurs": "Paule Giron",
        "auteurs_multi": {"333357": "Paule Giron"},
        "auteurs_id": ["333357"],
        "auteurs_fonctions": [],
        "realisateur_multi": [],
        "article": [
            {
                "nombre": 0,
                "gencod": "9791030204704",
                "id_catalogue": ["-131072"],
                "collection_no": "0",
                "editeur": "Fauves editions",
                "distributeur": "ePagine",
                "code_distributeur": "309",
                "diffuseur": "Harmattan",
                "entrepot": "Harmattan",
                "prix": 8.99,
                "prixpays": {
                    "fr": {"value": 8.99, "devise": "&euro;"},
                    "be": {"value": 8.99, "devise": "&euro;"},
                    "nl": {"value": 8.99, "devise": "&euro;"},
                    "ch": {"value": 9.8, "devise": "CHF"},
                },
                "dateparution": "15/03/2023",
                "dateparutionentier": 1678834800,
                "dispo": 1,
                "dispopays": {"fr": 1, "be": 1, "ch": 1},
                "libelledispo": "Disponible",
                "resume": "\"J'avoue que, plus je prends de l'\u00e2ge, plus vieillir m'\u00e9tonne ! Ces derni\u00e8res ann\u00e9es, le vent s'est mis \u00e0 tourner et les vieux ont de plus en plus envie d'exister \u00e0 part enti\u00e8re. Finies les d\u00e9cisions prises pour nous et \u00e0 notre place. Notre nouveau mot d'ordre est devenu : \"Pour la vieillesse, rien sans nous et tout avec nous\". Un bonheur n'arrivant jamais seul, la long\u00e9vit\u00e9 s'est mise de la partie pour nous offrir, comme nous n'en avions encore jamais vu, un concours de centenaires. J'aurais pu poser ma propre plume en pensant que nous avions \u00e0 peu pr\u00e8s tout dit sur la vieillesse. Et puis, je me suis aper\u00e7ue qu'il y avait vieux et vieux et qu'entre un octog\u00e9naire et un nonag\u00e9naire, il n'y avait pas seulement une diff\u00e9rence de...vieillissement, mais un changement \u00e0 la fois si subtil et si radical qu'il valait qu'on s'y arr\u00eate pour examiner son contenu.\" Soyons vieux, soyons actifs ! Tel est l'adage de Paule Giron, jeune nonag\u00e9naire qui d\u00e9montre avec humour que l'\u00eatre humain n'en finit pas de devenir.",
                "image": "1",
                "image_spe": 0,
                "image_alkor": 0,
                "image_4": "0",
                "imagesUrl": {
                    "recto": "https://images.epagine.fr/704/9791030204704_1_75.jpg",
                    "vign": "https://images.epagine.fr/704/9791030204704_1_v.jpg",
                    "moyen": "https://images.epagine.fr/704/9791030204704_1_m.jpg",
                    "verso": "https://images.epagine.fr/no_ebook.png",
                },
                "detailUrl": "/ebook/9791030204704-voyage-au-pays-des-nonas-paule-giron/",
                "langue": "Fran\u00e7ais",
                "langueiso": "fra",
                "langueflag": "https://static.epagine.fr/commonfiles/flags/fr.png",
                "nbmag": "19",
                "codesupport": "LE",
                "libellesupport": "ebook (pdf)",
                "codesupport2": [],
                "libellesupport2": [],
                "idformat": "4030929",
                "libelleformat": "pdf",
                "drm": "0",
                "chapitre": 0,
                "biblio": "0",
                "extrait": "0",
                "extrait_oeuvre": "0",
                "pages": "100",
                "longueur": 0,
                "largeur": 0,
                "hauteur": 0,
                "epaisseur": 0,
                "poids": "0",
                "biographie": "0",
                "biographies": [],
                "websites": [],
                "datecreation": "16/03/2023",
                "datecreationentier": 1678923118,
                "datemodification": "10/10/2023",
                "serie": "Non pr\u00e9cis\u00e9e",
                "idserie": "0",
                "scolaire": "0",
                "commentaire": "pr\u00e9face Marie-Fran\u00e7oise Fuchs",
                "livre_etranger": "0",
                "type_prix": 0,
                "accessibilite": [],
                "contenu_explicite": 0,
                "nb_galettes": 0,
                "duree": 0,
                "anneesortie": 0,
                "interpretes": [],
                "typeproduit": "1",
                "colors": [],
                "langues": [],
                "audios": [],
                "soustitres": [],
                "iad": "0",
                "usage": '{"IT":{"print":"01","copy":"01"}}',
                "id_code_langue": "10000",
                "taux_tva": "5.50",
                "code_tva": "2",
                "nboccasions": 0,
                "stock": 0,
                "gtl": [],
                "gtlvideo": [],
                "operations": [],
                "tracks": [],
                "cmb": "320101",
                "deee_ht": 0,
                "tva": 0,
                "minutesdejeu": 0,
                "nbjoueursmin": 0,
                "nbjoueursmax": 0,
                "colisage": 0,
                "longueurboite": 0,
                "largeurboite": 0,
                "hauteurboite": 0,
                "grammesboite": 0,
                "nbpiles": 0,
                "pilesincluses": 0,
                "nbanneegarantie": 0,
                "produits_recycles": 0,
                "nbpages": 0,
                "grammage": 0,
                "taille_ecriture_mm": 0,
                "poignee": 0,
                "lavable": 0,
                "impermeable": 0,
                "contenance_ml": 0,
                "nbfeuilles": 0,
                "diametre": 0,
                "diametreboite": 0,
                "garantiemois": 0,
                "drm_libelle": "DRM Adobe",
                "precommande": 0,
                "ispromotion": 0,
                "isnew": 0,
                "editeur_id_epagine": "3732",
                "multijoueur": 0,
                "nblicenses": 0,
                "nbutilisateur": 0,
                "internet": 0,
                "pegi": [],
                "solo": 0,
                "online": 0,
                "avertissement": [],
                "drmlcp": "0",
                "bonus_extraits": {
                    "gencod": "9791030204704",
                    "pagesinterieures": "0",
                    "pdfextrait": "0",
                    "pdfchapitre": "0",
                    "pdfparagraphe": "0",
                    "mp3_count": "0",
                },
                "id_lectorat": "0",
                "livre_lu": "0",
                "grands_caracteres": "0",
                "multilingue": "0",
                "illustre": "0",
                "luxe": "0",
                "relie": "0",
                "broche": "0",
                "DrmId": "1",
                "EntrepotID": "700",
                "lectureEnLigne": "0",
                "NombreMagasins": 0,
                "collector": "0",
                "code_editeur": "21897",
                "sorecop": 0,
                "pcb": 0,
                "spcb": 0,
                "volume": 0,
                "compartiment": 0,
                "poche": 0,
            }
        ],
        "biographies": [],
        "websites": [],
        "typeproduit": 0,
    },
    "ean": "9791030204704",
    "changeEncodingTo": "UTF-8",
    "extraparams": {"ws": 1},
}


MUSIC_SEARCH_FIXTURE = {
    "type": 4,
    "magid": "7",
    "nombre": 25,
    "page": 1,
    "result": [
        {
            "id": 871729,
            "titre": "Les dernières volontés de Mozart (symphony)",
            "auteurs_multi": [],
            "auteurs_id": [],
            "auteurs_fonction": [],
            "realisateur_multi": [],
            "article": {
                "1": {
                    "nombre": 0,
                    "gencod": "3700187679323",
                    "id_catalogue": ["0"],
                    "editeur": "BELIEVE",
                    "distributeur": "Believe",
                    "code_distributeur": "MCT",
                    "prix": 14.99,
                    "codeprix": "AP1249",
                    "prixpays": {
                        "fr": {"value": 14.99, "devise": "&euro;"},
                        "be": {"value": 14.99, "devise": "&euro;"},
                    },
                    "dateparution": "02/12/2022",
                    "dateparutionentier": 1669935600,
                    "dispo": 1,
                    "dispopays": {"fr": 1, "be": 1, "ch": 1},
                    "libelledispo": "Disponible",
                    "resume": 'GIMS revient avec " Les dernières volontés de Mozart ", un album de tubes.',
                    "image": "1",
                    "image_spe": "1",
                    "image_alkor": 0,
                    "image_4": "1",
                    "imagesUrl": {
                        "recto": "https://images.epagine.fr/323/3700187679323.jpg",
                        "vign": "https://images.epagine.fr/323/3700187679323_vd.jpg",
                        "moyen": "https://images.epagine.fr/323/3700187679323.jpg",
                        "verso": "https://images.epagine.fr/323/3700187679323_2.jpg",
                    },
                    "detailUrl": "/music/3700187679323-les-dernieres-volontes-de-mozart-symphony-gims/",
                    "nbmag": "62",
                    "codesupport": "38",
                    "libellesupport": "CD Digipack",
                    "libellesupportcourt": "CD Dig.",
                    "codesupport2": [],
                    "libellesupport2": [],
                    "chapitre": 0,
                    "biblio": "0",
                    "extrait": 0,
                    "extrait_oeuvre": "0",
                    "pages": 0,
                    "longueur": 0,
                    "largeur": 0,
                    "hauteur": 0,
                    "epaisseur": 0,
                    "poids": 0,
                    "biographies": [],
                    "websites": [],
                    "datemodification": "01/12/2022",
                    "idserie": 0,
                    "livre_etranger": 0,
                    "type_prix": 0,
                    "contenu_explicite": 0,
                    "nb_galettes": "1",
                    "duree": 0,
                    "anneesortie": 0,
                    "interprete": "Gims",
                    "interpretes": [],
                    "typeproduit": "4",
                    "colors": [],
                    "langues": [],
                    "audios": [],
                    "soustitres": [],
                    "artiste": "Gims",
                    "compositeur": "Gims",
                    "nbtracks": "0",
                    "label": "PLAY TWO",
                    "taux_tva": 0,
                    "code_tva": "3",
                    "nboccasions": 0,
                    "stock": 0,
                    "gtl": {
                        "first": {
                            "1": {"code": "110000", "libelle": "Rap / Hip Hop"},
                            "2": {"code": "110400", "libelle": "Rap / Hip Hop francophone"},
                        }
                    },
                    "gtlvideo": [],
                    "operations": [],
                    "tracks": [],
                    "deee_ht": 0,
                    "tva": 0,
                    "minutesdejeu": 0,
                    "nbjoueursmin": 0,
                    "nbjoueursmax": 0,
                    "colisage": 0,
                    "longueurboite": 0,
                    "largeurboite": 0,
                    "hauteurboite": 0,
                    "grammesboite": 0,
                    "nbpiles": 0,
                    "pilesincluses": 0,
                    "nbanneegarantie": 0,
                    "produits_recycles": 0,
                    "nbpages": 0,
                    "grammage": 0,
                    "taille_ecriture_mm": 0,
                    "poignee": 0,
                    "lavable": 0,
                    "impermeable": 0,
                    "contenance_ml": 0,
                    "nbfeuilles": 0,
                    "diametre": 0,
                    "diametreboite": 0,
                    "garantiemois": 0,
                    "precommande": 0,
                    "ispromotion": 0,
                    "isnew": 0,
                    "multijoueur": 0,
                    "nblicenses": 0,
                    "nbutilisateur": 0,
                    "internet": 0,
                    "pegi": [],
                    "drmlcp": 0,
                    "bonus_extraits": {"gencod": "3700187679323"},
                    "livre_lu": 0,
                    "grands_caracteres": 0,
                    "multilingue": 0,
                    "illustre": 0,
                    "luxe": 0,
                    "relie": 0,
                    "broche": 0,
                    "ReferenceInterne": "BLV7932",
                    "prix_ht": 12.49,
                    "lectureEnLigne": 0,
                    "NombreMagasins": 0,
                    "collector": 0,
                    "code_editeur": 0,
                    "sorecop": 0,
                    "pcb": 0,
                    "spcb": 0,
                    "volume": 0,
                    "compartiment": 0,
                    "poche": 0,
                },
                "2": {
                    "nombre": 0,
                    "gencod": "3700187679324",
                    "id_catalogue": ["0"],
                    "editeur": "BELIEVE",
                    "distributeur": "Believe",
                    "code_distributeur": "MCT",
                    "prix": 14.99,
                    "codeprix": "AP1249",
                    "prixpays": {
                        "fr": {"value": 14.99, "devise": "&euro;"},
                        "be": {"value": 14.99, "devise": "&euro;"},
                    },
                    "dateparution": "02/12/2022",
                    "dateparutionentier": 1669935600,
                    "dispo": 1,
                    "dispopays": {"fr": 1, "be": 1, "ch": 1},
                    "libelledispo": "Disponible",
                    "resume": 'GIMS revient avec " Les dernières volontés de Mozart ", un album de tubes.',
                    "image": "1",
                    "image_spe": "1",
                    "image_alkor": 0,
                    "image_4": "1",
                    "imagesUrl": {
                        "recto": "https://images.epagine.fr/323/3700187679324.jpg",
                        "vign": "https://images.epagine.fr/323/3700187679324_vd.jpg",
                        "moyen": "https://images.epagine.fr/323/3700187679324.jpg",
                        "verso": "https://images.epagine.fr/323/3700187679324_2.jpg",
                    },
                    "detailUrl": "/music/3700187679324-les-dernieres-volontes-de-mozart-symphony-gims/",
                    "nbmag": "63",
                    "codesupport": "7",
                    "libellesupport": "Album Vinyle",
                    "libellesupportcourt": "LP",
                    "codesupport2": [],
                    "libellesupport2": [],
                    "chapitre": 0,
                    "biblio": "0",
                    "extrait": 0,
                    "extrait_oeuvre": "0",
                    "pages": 0,
                    "longueur": 0,
                    "largeur": 0,
                    "hauteur": 0,
                    "epaisseur": 0,
                    "poids": 0,
                    "biographies": [],
                    "websites": [],
                    "datemodification": "01/12/2022",
                    "idserie": 0,
                    "livre_etranger": 0,
                    "type_prix": 0,
                    "contenu_explicite": 0,
                    "nb_galettes": "1",
                    "duree": 0,
                    "anneesortie": 0,
                    "interprete": "Gims",
                    "interpretes": [],
                    "typeproduit": "4",
                    "colors": [],
                    "langues": [],
                    "audios": [],
                    "soustitres": [],
                    "artiste": "Gims",
                    "compositeur": "Gims",
                    "nbtracks": "0",
                    "label": "PLAY TWO",
                    "taux_tva": 0,
                    "code_tva": "3",
                    "nboccasions": 0,
                    "stock": 0,
                    "gtl": [],
                    "gtlvideo": [],
                    "operations": [],
                    "tracks": [],
                    "deee_ht": 0,
                    "tva": 0,
                    "minutesdejeu": 0,
                    "nbjoueursmin": 0,
                    "nbjoueursmax": 0,
                    "colisage": 0,
                    "longueurboite": 0,
                    "largeurboite": 0,
                    "hauteurboite": 0,
                    "grammesboite": 0,
                    "nbpiles": 0,
                    "pilesincluses": 0,
                    "nbanneegarantie": 0,
                    "produits_recycles": 0,
                    "nbpages": 0,
                    "grammage": 0,
                    "taille_ecriture_mm": 0,
                    "poignee": 0,
                    "lavable": 0,
                    "impermeable": 0,
                    "contenance_ml": 0,
                    "nbfeuilles": 0,
                    "diametre": 0,
                    "diametreboite": 0,
                    "garantiemois": 0,
                    "precommande": 0,
                    "ispromotion": 0,
                    "isnew": 0,
                    "multijoueur": 0,
                    "nblicenses": 0,
                    "nbutilisateur": 0,
                    "internet": 0,
                    "pegi": [],
                    "drmlcp": 0,
                    "bonus_extraits": {"gencod": "3700187679324"},
                    "livre_lu": 0,
                    "grands_caracteres": 0,
                    "multilingue": 0,
                    "illustre": 0,
                    "luxe": 0,
                    "relie": 0,
                    "broche": 0,
                    "ReferenceInterne": "BLV7932",
                    "prix_ht": 12.49,
                    "lectureEnLigne": 0,
                    "NombreMagasins": 0,
                    "collector": 0,
                    "code_editeur": 0,
                    "sorecop": 0,
                    "pcb": 0,
                    "spcb": 0,
                    "volume": 0,
                    "compartiment": 0,
                    "poche": 0,
                },
            },
            "biographies": [],
            "websites": [],
            "typeproduit": 4,
            "interprete": "Gims",
        },
        {
            "id": 869715,
            "titre": "Cracker Island",
            "auteurs_multi": [],
            "auteurs_id": [],
            "auteurs_fonction": [],
            "realisateur_multi": [],
            "article": {
                "1": {
                    "nombre": 0,
                    "gencod": "5054197199738",
                    "id_catalogue": ["0"],
                    "editeur": "WARNER MUSIC UK",
                    "distributeur": "Warner Music France",
                    "code_distributeur": "WAR",
                    "codeprix": "461",
                    "prixpays": {
                        "fr": {"value": 19.98, "devise": "&euro;"},
                        "be": {"value": 19.98, "devise": "&euro;"},
                    },
                    "dateparution": "24/02/2023",
                    "dateparutionentier": 1677193200,
                    "dispo": 1,
                    "dispopays": {"fr": 1, "be": 1, "ch": 1},
                    "libelledispo": "Disponible",
                    "resume": "Ce huitième album studio de Gorillaz est une collection énergique, optimiste et riche en genres de 10 titres mettant en vedette un line-up stellaire de collaborateurs : Thundercat, Tame Impala, Bad Bunny, Stevie Nicks, Adeleye Omotayo, Bootie Brown et Beck.",
                    "image": "1",
                    "image_spe": "1",
                    "image_alkor": 0,
                    "image_4": "1",
                    "imagesUrl": {
                        "recto": "https://images.epagine.fr/738/5054197199738.jpg",
                        "vign": "https://images.epagine.fr/738/5054197199738_vd.jpg",
                        "moyen": "https://images.epagine.fr/738/5054197199738.jpg",
                        "verso": "https://images.epagine.fr/738/5054197199738_2.jpg",
                    },
                    "detailUrl": "/music/5054197199738-cracker-island-gorillaz/",
                    "nbmag": "34",
                    "codesupport": "7",
                    "libellesupport": "Album Vinyle",
                    "libellesupportcourt": "LP",
                    "codesupport2": [],
                    "libellesupport2": [],
                    "chapitre": 0,
                    "biblio": "0",
                    "extrait": 0,
                    "extrait_oeuvre": "0",
                    "pages": 0,
                    "longueur": 0,
                    "largeur": 0,
                    "hauteur": 0,
                    "epaisseur": 0,
                    "poids": 0,
                    "biographies": [],
                    "websites": [],
                    "datemodification": "18/08/2023",
                    "idserie": 0,
                    "livre_etranger": 0,
                    "type_prix": 0,
                    "contenu_explicite": 0,
                    "nb_galettes": "1",
                    "duree": 0,
                    "anneesortie": 0,
                    "interprete": "Gorillaz",
                    "interpretes": [],
                    "typeproduit": "4",
                    "colors": [],
                    "langues": [],
                    "audios": [],
                    "soustitres": [],
                    "artiste": "Gorillaz",
                    "compositeur": "Gorillaz",
                    "nbtracks": "10",
                    "label": "WARNER MUSIC UK",
                    "taux_tva": 0,
                    "code_tva": "3",
                    "nboccasions": 0,
                    "stock": 0,
                    "gtl": {
                        "first": {
                            "1": {"code": "50000", "libelle": "Pop"},
                            "2": {"code": "50300", "libelle": "Brit Pop"},
                        }
                    },
                    "gtlvideo": [],
                    "operations": [],
                    "tracks": [],
                    "deee_ht": 0,
                    "tva": 0,
                    "minutesdejeu": 0,
                    "nbjoueursmin": 0,
                    "nbjoueursmax": 0,
                    "colisage": 0,
                    "longueurboite": 0,
                    "largeurboite": 0,
                    "hauteurboite": 0,
                    "grammesboite": 0,
                    "nbpiles": 0,
                    "pilesincluses": 0,
                    "nbanneegarantie": 0,
                    "produits_recycles": 0,
                    "nbpages": 0,
                    "grammage": 0,
                    "taille_ecriture_mm": 0,
                    "poignee": 0,
                    "lavable": 0,
                    "impermeable": 0,
                    "contenance_ml": 0,
                    "nbfeuilles": 0,
                    "diametre": 0,
                    "diametreboite": 0,
                    "garantiemois": 0,
                    "precommande": 0,
                    "ispromotion": 0,
                    "isnew": 0,
                    "multijoueur": 0,
                    "nblicenses": 0,
                    "nbutilisateur": 0,
                    "internet": 0,
                    "pegi": [],
                    "drmlcp": 0,
                    "bonus_extraits": {"gencod": "5054197199738"},
                    "livre_lu": 0,
                    "grands_caracteres": 0,
                    "multilingue": 0,
                    "illustre": 0,
                    "luxe": 0,
                    "relie": 0,
                    "broche": 0,
                    "ReferenceInterne": "5419719973",
                    "prix_ht": 16.65,
                    "lectureEnLigne": 0,
                    "NombreMagasins": 0,
                    "collector": 0,
                    "code_editeur": 0,
                    "sorecop": 0,
                    "pcb": 0,
                    "spcb": 0,
                    "volume": 0,
                    "compartiment": 0,
                    "poche": 0,
                }
            },
            "biographies": [],
            "websites": [],
            "typeproduit": 4,
            "interprete": "Gorillaz",
        },
    ],
    "suggestions": [],
    "nbreponses": 50000,
    "changeEncodingTo": "UTF-8",
    "ws": 1,
}

EMPTY_MUSIC_SEARCH_FIXTURE = {"type": 4, "magid": "7", "nombre": 25, "page": 2, "result": []}
