def remove_trailing_zeros(response: dict) -> dict:
    for key, value in response.items():
        if isinstance(value, dict):
            response[key] = remove_trailing_zeros(value)
        elif isinstance(value, str):
            response[key] = value.lstrip("0")
    return response


def build_gtl_response_fixture(gtl_id, gtl_level=1) -> dict:
    if gtl_level == 1:
        gtl_level_1 = gtl_id
        response = {"first": {"1": {"code": f"{gtl_level_1}", "libelle": f"Level {gtl_level} libelle"}}}
    elif gtl_level == 2:
        gtl_level_2 = gtl_id
        gtl_level_1 = gtl_id[:-2].ljust(8, "0")
        response = {
            "first": {
                "1": {"code": f"{gtl_level_1}", "libelle": f"Level {gtl_level} libelle"},
                "2": {"code": f"{gtl_level_2}", "libelle": f"Level {gtl_level} libelle"},
            }
        }

    elif gtl_level == 3:
        gtl_level_3 = gtl_id
        gtl_level_2 = gtl_id[:-2].ljust(8, "0")
        gtl_level_1 = gtl_id[:-4].ljust(8, "0")
        response = {
            "first": {
                "1": {"code": f"{gtl_level_1}", "libelle": f"Level {gtl_level} libelle"},
                "2": {"code": f"{gtl_level_2}", "libelle": f"Level {gtl_level} libelle"},
                "3": {"code": f"{gtl_level_3}", "libelle": f"Level {gtl_level} libelle"},
            }
        }
    elif gtl_level == 4:
        gtl_level_4 = gtl_id
        gtl_level_3 = gtl_id[:-2].ljust(8, "0")
        gtl_level_2 = gtl_id[:-4].ljust(8, "0")
        gtl_level_1 = gtl_id[:-6].ljust(8, "0")
        response = {
            "first": {
                "1": {"code": f"{gtl_level_1}", "libelle": f"Level {gtl_level} libelle"},
                "2": {"code": f"{gtl_level_2}", "libelle": f"Level {gtl_level} libelle"},
                "3": {"code": f"{gtl_level_3}", "libelle": f"Level {gtl_level} libelle"},
                "4": {"code": f"{gtl_level_4}", "libelle": f"Level {gtl_level} libelle"},
            }
        }

    response = remove_trailing_zeros(response)
    return response


def build_titelive_one_book_response(
    title="The Book of All Things",
    ean="9782370730541",
    gtl_id=None,
    gtl_level=1,
    no_gtl=False,
    code_tva="2",
    taux_tva="5.50",
    support_code="BL",
    id_lectorat="0",
    auteurs_multi=None,
) -> dict:
    if auteurs_multi is None:
        auteurs_multi = ["Eraticerrata"]
    if no_gtl:
        gtl_response = None
    else:
        if gtl_id is not None:
            gtl_response = build_gtl_response_fixture(gtl_id, gtl_level)
        else:
            gtl_response = {
                "first": {
                    "1": {"code": "3000000", "libelle": "Bandes dessin&eacute;es / Comics / Mangas"},
                    "2": {"code": "3020000", "libelle": "Bandes dessin&eacute;es"},
                    "3": {"code": "3020300", "libelle": "Romans graphiques"},
                }
            }

    # extracted from actual response: curl --location 'https://catsearch.epagine.fr/v1/search?base=paper&nombre=1&page=1' --header 'Authorization: Bearer xxx'
    return {
        "type": 1,
        "magid": "6505",
        "nombre": 1,
        "page": "1",
        "result": [
            {
                "id": 2842547,
                "titre": title,
                "auteurs": "Eraticerrata",
                "auteurs_multi": auteurs_multi,
                "auteurs_id": [],
                "auteurs_fonctions": [],
                "realisateur_multi": [],
                "article": {
                    "1": {
                        "nombre": 0,
                        "gencod": ean,
                        "id_catalogue": ["0"],
                        "collection_no": "0",
                        "editeur": "ALLARY",
                        "distributeur": "INTERFORUM",
                        "code_distributeur": "371",
                        "prix": 22.9,
                        "prixpays": {
                            "fr": {"value": 22.9, "devise": "&euro;"},
                            "be": {"value": 22.9, "devise": "&euro;"},
                            "ch": {"value": 35.6, "devise": "CHF"},
                        },
                        "dateparution": "11/06/2015",
                        "dateparutionentier": 1433973600,
                        "dispo": 1,
                        "dispopays": {"fr": 1, "be": 1, "ch": 1},
                        "libelledispo": "Disponible",
                        "resume": "The book of all the good things",
                        "image": "1",
                        "image_spe": "1",
                        "image_alkor": 0,
                        "image_4": "1",
                        "imagesUrl": {
                            "recto": f"https://images.epagine.fr/541/{ean}_1_75.jpg",
                            "vign": f"https://images.epagine.fr/541/{ean}_1_v.jpg",
                            "moyen": f"https://images.epagine.fr/541/{ean}_1_m.jpg",
                            "verso": f"https://images.epagine.fr/541/{ean}_4_75.jpg",
                        },
                        "detailUrl": f"/livre/{ean}-the-book-of-all-404/",
                        "langue": "Français",
                        "langueiso": "fra",
                        "langueflag": "https://static.epagine.fr/commonfiles/flags/fr.png",
                        "nbmag": "998",
                        "codesupport": support_code,
                        "libellesupport": f"Libelle pour {support_code}",
                        "codesupport2": [],
                        "libellesupport2": [],
                        "chapitre": 0,
                        "biblio": "0",
                        "extrait": 0,
                        "extrait_oeuvre": "0",
                        "pages": "160",
                        "longueur": 24.2,
                        "largeur": 17.2,
                        "hauteur": 0,
                        "epaisseur": 2.3,
                        "poids": "540",
                        "biographie": "1",
                        "biographies": [],
                        "websites": [],
                        "datecreation": "05/03/2015",
                        "datecreationentier": 1425510000,
                        "datemodification": "23/02/2024",
                        "serie": "l'Arabe du futur",
                        "idserie": "3540",
                        "scolaire": "0",
                        "livre_etranger": "0",
                        "racine_editeur": "237073",
                        "code_clil": "3774",
                        "type_prix": "4",
                        "contenu_explicite": 0,
                        "nb_galettes": 0,
                        "duree": 0,
                        "anneesortie": 0,
                        "interpretes": [],
                        "typeproduit": 0,
                        "colors": [],
                        "langues": [],
                        "audios": [],
                        "soustitres": [],
                        "iad": "0",
                        "id_code_langue": "10000",
                        "taux_tva": taux_tva,
                        "code_tva": code_tva,
                        "nboccasions": 0,
                        "stock": 0,
                        "gtl": gtl_response,
                        "gtlvideo": [],
                        "operations": [],
                        "tracks": [],
                        "cmb": "130115",
                        "deee_ht": 0,
                        "tva": 0,
                        "minutesdejeu": 0,
                        "nbjoueursmin": 0,
                        "nbjoueursmax": 0,
                        "colisage": 0,
                        "longueurboite": 0,
                        "largeurboite": 0,
                        "hauteurboite": 0,
                        "grammesboite": 0,
                        "nbpiles": 0,
                        "pilesincluses": 0,
                        "nbanneegarantie": 0,
                        "produits_recycles": 0,
                        "nbpages": 0,
                        "grammage": 0,
                        "taille_ecriture_mm": 0,
                        "poignee": 0,
                        "lavable": 0,
                        "impermeable": 0,
                        "contenance_ml": 0,
                        "nbfeuilles": 0,
                        "diametre": 0,
                        "diametreboite": 0,
                        "garantiemois": 0,
                        "precommande": 0,
                        "ispromotion": 0,
                        "isnew": 0,
                        "multijoueur": 0,
                        "nblicenses": 0,
                        "nbutilisateur": 0,
                        "internet": 0,
                        "pegi": [],
                        "solo": 0,
                        "online": 0,
                        "avertissement": [],
                        "drmlcp": 0,
                        "bonus_extraits": {
                            "gencod": ean,
                            "pagesinterieures": "0",
                            "pdfextrait": "0",
                            "pdfchapitre": "0",
                            "pdfparagraphe": "0",
                            "mp3_count": "0",
                        },
                        "id_lectorat": id_lectorat,
                        "livre_lu": "0",
                        "grands_caracteres": "0",
                        "multilingue": "0",
                        "illustre": "0",
                        "luxe": "0",
                        "relie": "1",
                        "broche": "0",
                        "lectureEnLigne": 0,
                        "NombreMagasins": 0,
                        "collector": "0",
                        "code_editeur": "20799",
                        "sorecop": 0,
                        "pcb": 0,
                        "spcb": 0,
                        "volume": 0,
                        "compartiment": 0,
                        "poche": 0,
                    }
                },
                "biographies": [],
                "websites": [],
                "typeproduit": 1,
            },
        ],
        "suggestions": [],
        "nbreponses": 50000,
        "temps": 1.18904,
        "tri_ordre": "desc",
        "params": {
            "base": "paper",
            "login": "PASSCULTURE",
            "mid": "6505",
            "nombre": "2",
            "page": "1",
            "hash": "839cbc2ea11289d2f551e829aa8d3749",
            "dispo": [0, 1, 2],
            "biblio": 0,
            "is_promotion": 0,
            "magasin": ["6505"],
            "support": 1,
            "ws": 1,
        },
        "exact": [],
        "version": "json",
        "magasin": ["6505", 0],
        "support": "1",
        "dispo": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        "biblio": 0,
        "stocks": 0,
        "drmlcp": 0,
        "occasion": 0,
        "image": 0,
        "ws": 1,
        "compatibility": [],
        "is_promotion": 0,
        "flou": 0,
        "idserie": 0,
        "scolaire": 0,
        "changeEncodingTo": "UTF-8",
    }


TWO_BOOKS_RESPONSE_FIXTURE = {
    "type": 1,
    "magid": "6505",
    "nombre": 10,
    "page": "1",
    "result": [
        {
            "id": 2842547,
            "titre": "L'Arabe du futur Tome 2 : une jeunesse au Moyen-Orient (1984-1985)",
            "auteurs": "Riad Sattouf",
            "auteurs_multi": ["Riad Sattouf"],
            "auteurs_id": [],
            "auteurs_fonctions": [],
            "realisateur_multi": [],
            "article": {
                "1": {
                    "nombre": 0,
                    "gencod": "9782370730541",
                    "id_catalogue": ["0"],
                    "collection_no": "0",
                    "editeur": "ALLARY",
                    "distributeur": "INTERFORUM",
                    "code_distributeur": "371",
                    "prix": 22.9,
                    "prixpays": {
                        "fr": {"value": 22.9, "devise": "&euro;"},
                        "be": {"value": 22.9, "devise": "&euro;"},
                        "ch": {"value": 35.6, "devise": "CHF"},
                    },
                    "dateparution": "11/06/2015",
                    "dateparutionentier": 1433973600,
                    "dispo": 1,
                    "dispopays": {"fr": 1, "be": 1, "ch": 1},
                    "libelledispo": "Disponible",
                    "resume": "L'Arabe du futur, une jeunesse au Moyen-Orient (1978-2011) est une série de bande dessinée en six tomes, écrite et dessinée par Riad Sattouf.\r\n Vendue à plus de 3 millions d'exemplaires et traduite en 23 langues, elle raconte l'enfance et l'adolescence de l'auteur, fils aîné d'une mère française et d'un père syrien. L'histoire nous mène de la Libye du colonel Kadhafi à la Syrie d'Hafez Al-Assad en passant par la Bretagne, de Rennes au cap Fréhel.\r\nCe deuxième tome couvre les années 1984-1985.",
                    "image": "1",
                    "image_spe": "1",
                    "image_alkor": 0,
                    "image_4": "1",
                    "imagesUrl": {
                        "recto": "https://images.epagine.fr/541/9782370730541_1_75.jpg",
                        "vign": "https://images.epagine.fr/541/9782370730541_1_v.jpg",
                        "moyen": "https://images.epagine.fr/541/9782370730541_1_m.jpg",
                        "verso": "https://images.epagine.fr/541/9782370730541_4_75.jpg",
                    },
                    "detailUrl": "/livre/9782370730541-l-arabe-du-futur-tome-2-une-jeunesse-au-moyen-orient-1984-1985-riad-sattouf/",
                    "langue": "Français",
                    "langueiso": "fra",
                    "langueflag": "https://static.epagine.fr/commonfiles/flags/fr.png",
                    "nbmag": "998",
                    "codesupport": "T",
                    "libellesupport": "Grand format",
                    "codesupport2": [],
                    "libellesupport2": [],
                    "chapitre": 0,
                    "biblio": "0",
                    "extrait": 0,
                    "extrait_oeuvre": "0",
                    "pages": "160",
                    "longueur": 24.2,
                    "largeur": 17.2,
                    "hauteur": 0,
                    "epaisseur": 2.3,
                    "poids": "540",
                    "biographie": "1",
                    "biographies": [],
                    "websites": [],
                    "datecreation": "05/03/2015",
                    "datecreationentier": 1425510000,
                    "datemodification": "23/02/2024",
                    "serie": "l'Arabe du futur",
                    "idserie": "3540",
                    "scolaire": "0",
                    "livre_etranger": "0",
                    "racine_editeur": "237073",
                    "code_clil": "3774",
                    "type_prix": "4",
                    "contenu_explicite": 0,
                    "nb_galettes": 0,
                    "duree": 0,
                    "anneesortie": 0,
                    "interpretes": [],
                    "typeproduit": 0,
                    "colors": [],
                    "langues": [],
                    "audios": [],
                    "soustitres": [],
                    "iad": "0",
                    "id_code_langue": "10000",
                    "taux_tva": "5.50",
                    "code_tva": "2",
                    "nboccasions": 0,
                    "stock": 0,
                    "gtl": {
                        "first": {
                            "1": {"code": "3000000", "libelle": "Bandes dessin&eacute;es / Comics / Mangas"},
                            "2": {"code": "3020000", "libelle": "Bandes dessin&eacute;es"},
                            "3": {"code": "3020300", "libelle": "Romans graphiques"},
                        }
                    },
                    "gtlvideo": [],
                    "operations": [],
                    "tracks": [],
                    "cmb": "130115",
                    "deee_ht": 0,
                    "tva": 0,
                    "minutesdejeu": 0,
                    "nbjoueursmin": 0,
                    "nbjoueursmax": 0,
                    "colisage": 0,
                    "longueurboite": 0,
                    "largeurboite": 0,
                    "hauteurboite": 0,
                    "grammesboite": 0,
                    "nbpiles": 0,
                    "pilesincluses": 0,
                    "nbanneegarantie": 0,
                    "produits_recycles": 0,
                    "nbpages": 0,
                    "grammage": 0,
                    "taille_ecriture_mm": 0,
                    "poignee": 0,
                    "lavable": 0,
                    "impermeable": 0,
                    "contenance_ml": 0,
                    "nbfeuilles": 0,
                    "diametre": 0,
                    "diametreboite": 0,
                    "garantiemois": 0,
                    "precommande": 0,
                    "ispromotion": 0,
                    "isnew": 0,
                    "multijoueur": 0,
                    "nblicenses": 0,
                    "nbutilisateur": 0,
                    "internet": 0,
                    "pegi": [],
                    "solo": 0,
                    "online": 0,
                    "avertissement": [],
                    "drmlcp": 0,
                    "bonus_extraits": {
                        "gencod": "9782370730541",
                        "pagesinterieures": "0",
                        "pdfextrait": "0",
                        "pdfchapitre": "0",
                        "pdfparagraphe": "0",
                        "mp3_count": "0",
                    },
                    "id_lectorat": "0",
                    "livre_lu": "0",
                    "grands_caracteres": "0",
                    "multilingue": "0",
                    "illustre": "0",
                    "luxe": "0",
                    "relie": "1",
                    "broche": "0",
                    "lectureEnLigne": 0,
                    "NombreMagasins": 0,
                    "collector": "0",
                    "code_editeur": "20799",
                    "sorecop": 0,
                    "pcb": 0,
                    "spcb": 0,
                    "volume": 0,
                    "compartiment": 0,
                    "poche": 0,
                }
            },
            "biographies": [],
            "websites": [],
            "typeproduit": 1,
        },
        {
            "id": 1151334,
            "titre": "Mortelle Adèle Tome 1 : tout ça finira mal",
            "auteurs": "Mr tan, Miss prickly, Rémi Chaurand",
            "auteurs_multi": ["Mr tan", "Miss prickly", "Rémi Chaurand"],
            "auteurs_id": [],
            "auteurs_fonctions": [],
            "realisateur_multi": [],
            "article": {
                "1": {
                    "nombre": 0,
                    "gencod": "9782848018676",
                    "id_catalogue": ["0"],
                    "collection_no": "0",
                    "editeur": "BAYARD JEUNESSE",
                    "distributeur": "HACHETTE",
                    "code_distributeur": "64",
                    "prix": 11.5,
                    "prixpays": {
                        "fr": {"value": 11.5, "devise": "&euro;"},
                        "be": {"value": 12.9, "devise": "&euro;"},
                        "ch": {"value": 17.8, "devise": "CHF"},
                    },
                    "dateparution": "06/06/2013",
                    "dateparutionentier": 1370469600,
                    "dispo": 1,
                    "dispopays": {"fr": 1, "be": 1, "ch": 1},
                    "libelledispo": "Disponible",
                    "resume": "« Que ce soit pour faire enrager mes parents, torturer mon stupide chat, lutter contre Jade et ses copines ou briser le coeur de Geoffroy... j'ai toujours une idée intéressante ! »\r\n\r\nUne bonne dose d'humour noir et un soupçon de tendresse, voici la recette d'Adèle, une héroïne d'un nouveau genre... Accrochez votre ceinture, ça va déménager !\r\n\r\n© Mr Tan / Miss Prickly",
                    "image": "1",
                    "image_spe": "1",
                    "image_alkor": 0,
                    "image_4": "1",
                    "imagesUrl": {
                        "recto": "https://images.epagine.fr/676/9782848018676_1_75.jpg",
                        "vign": "https://images.epagine.fr/676/9782848018676_1_v.jpg",
                        "moyen": "https://images.epagine.fr/676/9782848018676_1_m.jpg",
                        "verso": "https://images.epagine.fr/676/9782848018676_4_75.jpg",
                    },
                    "detailUrl": "/livre/9782848018676-mortelle-adele-tome-1-tout-ca-finira-mal-mr-tan-miss-prickly-remi-chaurand/",
                    "langue": "Français",
                    "langueiso": "fra",
                    "langueflag": "https://static.epagine.fr/commonfiles/flags/fr.png",
                    "nbmag": "996",
                    "codesupport": "T",
                    "libellesupport": "Grand format",
                    "codesupport2": [],
                    "libellesupport2": [],
                    "chapitre": 0,
                    "biblio": "0",
                    "extrait": 0,
                    "extrait_oeuvre": "1",
                    "pages": "96",
                    "longueur": 20.2,
                    "largeur": 16,
                    "hauteur": 0,
                    "epaisseur": 1,
                    "poids": "282",
                    "biographie": "1",
                    "biographies": [],
                    "websites": [],
                    "datecreation": "18/01/2013",
                    "datecreationentier": 1358463600,
                    "datemodification": "21/03/2024",
                    "serie": "mortelle Adèle",
                    "idserie": "2170",
                    "scolaire": "0",
                    "lectorat": "à partir de 8 ANS",
                    "livre_etranger": "0",
                    "racine_editeur": "27470",
                    "code_clil": "3772",
                    "type_prix": "4",
                    "contenu_explicite": 0,
                    "nb_galettes": 0,
                    "duree": 0,
                    "anneesortie": 0,
                    "interpretes": [],
                    "typeproduit": 0,
                    "colors": [],
                    "langues": [],
                    "audios": [],
                    "soustitres": [],
                    "iad": "0",
                    "id_code_langue": "10000",
                    "taux_tva": "5.50",
                    "code_tva": "2",
                    "nboccasions": 0,
                    "stock": 0,
                    "gtl": {
                        "first": {
                            "1": {"code": "3000000", "libelle": "Bandes dessin&eacute;es / Comics / Mangas"},
                            "2": {"code": "3020000", "libelle": "Bandes dessin&eacute;es"},
                            "3": {"code": "3020200", "libelle": "Tout public"},
                            "4": {"code": "3020211", "libelle": "Humour"},
                        }
                    },
                    "gtlvideo": [],
                    "operations": [],
                    "tracks": [],
                    "cmb": "130114",
                    "deee_ht": 0,
                    "tva": 0,
                    "minutesdejeu": 0,
                    "nbjoueursmin": 0,
                    "nbjoueursmax": 0,
                    "colisage": 0,
                    "longueurboite": 0,
                    "largeurboite": 0,
                    "hauteurboite": 0,
                    "grammesboite": 0,
                    "nbpiles": 0,
                    "pilesincluses": 0,
                    "nbanneegarantie": 0,
                    "produits_recycles": 0,
                    "nbpages": 0,
                    "grammage": 0,
                    "taille_ecriture_mm": 0,
                    "poignee": 0,
                    "lavable": 0,
                    "impermeable": 0,
                    "contenance_ml": 0,
                    "nbfeuilles": 0,
                    "diametre": 0,
                    "diametreboite": 0,
                    "garantiemois": 0,
                    "precommande": 0,
                    "ispromotion": 0,
                    "isnew": 0,
                    "multijoueur": 0,
                    "nblicenses": 0,
                    "nbutilisateur": 0,
                    "internet": 0,
                    "pegi": [],
                    "solo": 0,
                    "online": 0,
                    "avertissement": [],
                    "drmlcp": 0,
                    "bonus_extraits": {
                        "gencod": "9782848018676",
                        "pagesinterieures": "0",
                        "pdfextrait": "0",
                        "pdfchapitre": "0",
                        "pdfparagraphe": "0",
                        "mp3_count": "0",
                    },
                    "id_lectorat": "5",
                    "livre_lu": "0",
                    "grands_caracteres": "0",
                    "multilingue": "0",
                    "illustre": "0",
                    "luxe": "0",
                    "relie": "0",
                    "broche": "1",
                    "lectureEnLigne": 0,
                    "NombreMagasins": 0,
                    "collector": "0",
                    "code_editeur": "12165",
                    "sorecop": 0,
                    "pcb": 0,
                    "spcb": 0,
                    "volume": 0,
                    "compartiment": 0,
                    "poche": 0,
                },
            },
            "biographies": [],
            "websites": [],
            "typeproduit": 1,
        },
    ],
    "suggestions": [],
    "nbreponses": 50000,
    "temps": 1.18904,
    "tri_ordre": "desc",
    "params": {
        "base": "paper",
        "login": "PASSCULTURE",
        "mid": "6505",
        "nombre": "2",
        "page": "1",
        "hash": "839cbc2ea11289d2f551e829aa8d3749",
        "dispo": [0, 1, 2],
        "biblio": 0,
        "is_promotion": 0,
        "magasin": ["6505"],
        "support": 1,
        "ws": 1,
    },
    "exact": [],
    "version": "json",
    "magasin": ["6505", 0],
    "support": "1",
    "dispo": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    "biblio": 0,
    "stocks": 0,
    "drmlcp": 0,
    "occasion": 0,
    "image": 0,
    "ws": 1,
    "compatibility": [],
    "is_promotion": 0,
    "flou": 0,
    "idserie": 0,
    "scolaire": 0,
    "changeEncodingTo": "UTF-8",
}


# Extracted from actual response:
# curl --location 'https://catsearch.epagine.fr/v1/ean/9782070455379' --header 'Authorization: Bearer xxx'
BOOK_BY_EAN_FIXTURE = {
    "type": 1,
    "magid": "6505",
    "compatibility": [],
    "oeuvre": {
        "id": "1072422",
        "titre": "Immortelle randonnée ; Compostelle malgré moi",
        "auteurs": "Jean-Christophe Rufin",
        "auteurs_multi": {"10078": "Jean-Christophe Rufin"},
        "auteurs_id": ["10078"],
        "auteurs_fonctions": [],
        "realisateur_multi": [],
        "article": [
            {
                "nombre": 0,
                "gencod": "9782070455379",
                "id_catalogue": ["0"],
                "collection": "Folio",
                "collection_no": "5833",
                "editeur": "FOLIO",
                "distributeur": "SODIS",
                "code_distributeur": "21",
                "prix": 8.3,
                "prixpays": {
                    "fr": {"value": 8.3, "devise": "&euro;"},
                    "be": {"value": 8.3, "devise": "&euro;"},
                    "ch": {"value": 14, "devise": "CHF"},
                },
                "dateparution": "02/10/2014",
                "dateparutionentier": 1412200800,
                "dispo": 1,
                "dispopays": {"fr": 1, "be": 1, "ch": 1},
                "libelledispo": "Disponible",
                "resume": "Un mois sur le Camino del Norte, de Bayonne à Santiago, 40 kilomètres de marche par jour : étape après étape, Jean-Christophe Rufin se transforme en clochard céleste, en routard de Compostelle. Pourquoi prendre le Chemin, quand on a déjà éprouvé toutes les marches, toutes les aventures physiques ? \" Je n'avais en réalité pas eu le choix. Le virus de Saint-Jacques m'avait profondément infecté. J'ignore par qui et par quoi s'est opérée la contagion. \r\nMais, après une phase d'incubation silencieuse, la maladie avait éclaté, et j'en avais tous les symptômes. \" 876 kilomètres plus loin, un mois plus tard, après l'arrivée à Santiago, le constat est là. Comme tous les grands pèlerinages, le Chemin est une expérience de désincarnation, il libère du \" tropplein \", mais il est aussi un itinéraire spirituel, entre cathédrales et ermitages, et humain, car chaque rencontre y prend une résonance particulière.\r",
                "image": "1",
                "image_spe": "1",
                "image_alkor": 0,
                "image_4": "1",
                "imagesUrl": {
                    "recto": "https://images.epagine.fr/379/9782070455379_1_75.jpg",
                    "vign": "https://images.epagine.fr/379/9782070455379_1_v.jpg",
                    "moyen": "https://images.epagine.fr/379/9782070455379_1_m.jpg",
                    "verso": "https://images.epagine.fr/379/9782070455379_4_75.jpg",
                },
                "detailUrl": "/livre/9782070455379-immortelle-randonnee-compostelle-malgre-moi-jean-christophe-rufin/",
                "langue": "Français",
                "langueiso": "fra",
                "langueflag": "https://static.epagine.fr/commonfiles/flags/fr.png",
                "nbmag": "540",
                "codesupport": "P",
                "libellesupport": "Poche",
                "codesupport2": [],
                "libellesupport2": [],
                "chapitre": 0,
                "biblio": "0",
                "extrait": 0,
                "extrait_oeuvre": "1",
                "pages": "288",
                "longueur": 17.8,
                "largeur": 10.8,
                "hauteur": 0,
                "epaisseur": 1.8,
                "poids": "180",
                "biographie": "1",
                "biographies": [],
                "websites": [],
                "datecreation": "23/05/2014",
                "datecreationentier": 1400796000,
                "datemodification": "03/01/2024",
                "serie": "Non précisée",
                "idserie": "0",
                "scolaire": "0",
                "livre_etranger": "0",
                "racine_editeur": "207",
                "code_clil": "3665",
                "type_prix": "4",
                "contenu_explicite": 0,
                "nb_galettes": 0,
                "duree": 0,
                "anneesortie": 0,
                "interpretes": [],
                "typeproduit": 0,
                "colors": [],
                "langues": [],
                "audios": [],
                "soustitres": [],
                "iad": "0",
                "id_code_langue": "10000",
                "taux_tva": "5.50",
                "code_tva": "2",
                "nboccasions": 0,
                "stock": 0,
                "gtl": {
                    "first": {
                        "1": {"code": "1000000", "libelle": "Litt&eacute;rature"},
                        "2": {"code": "1050000", "libelle": "R&eacute;cit"},
                    }
                },
                "gtlvideo": [],
                "operations": [],
                "tracks": [],
                "cmb": "110206",
                "deee_ht": 0,
                "tva": 0,
                "minutesdejeu": 0,
                "nbjoueursmin": 0,
                "nbjoueursmax": 0,
                "colisage": 0,
                "longueurboite": 0,
                "largeurboite": 0,
                "hauteurboite": 0,
                "grammesboite": 0,
                "nbpiles": 0,
                "pilesincluses": 0,
                "nbanneegarantie": 0,
                "produits_recycles": 0,
                "nbpages": 0,
                "grammage": 0,
                "taille_ecriture_mm": 0,
                "poignee": 0,
                "lavable": 0,
                "impermeable": 0,
                "contenance_ml": 0,
                "nbfeuilles": 0,
                "diametre": 0,
                "diametreboite": 0,
                "garantiemois": 0,
                "precommande": 0,
                "ispromotion": 0,
                "isnew": 0,
                "multijoueur": 0,
                "nblicenses": 0,
                "nbutilisateur": 0,
                "internet": 0,
                "pegi": [],
                "solo": 0,
                "online": 0,
                "avertissement": [],
                "drmlcp": 0,
                "bonus_extraits": {
                    "gencod": "9782070455379",
                    "pagesinterieures": "0",
                    "pdfextrait": "0",
                    "pdfchapitre": "0",
                    "pdfparagraphe": "0",
                    "mp3_count": "0",
                },
                "id_lectorat": "0",
                "livre_lu": "0",
                "grands_caracteres": "0",
                "multilingue": "0",
                "illustre": "0",
                "luxe": "0",
                "relie": "0",
                "broche": "1",
                "lectureEnLigne": 0,
                "NombreMagasins": 0,
                "collector": "0",
                "code_editeur": "27818",
                "sorecop": 0,
                "pcb": 0,
                "spcb": 0,
                "volume": 0,
                "compartiment": 0,
                "poche": 0,
            }
        ],
        "biographies": [],
        "websites": [],
        "typeproduit": 0,
    },
    "ean": "9782070455379",
    "changeEncodingTo": "UTF-8",
    "extraparams": {"ws": 1},
}

INELIGIBLE_BOOK_BY_EAN_FIXTURE = {
    "type": 1,
    "magid": "6505",
    "compatibility": [],
    "oeuvre": {
        "id": "3869601",
        "titre": "Annales ABC du bac ; sujets & corrig\u00e9s : math\u00e9matiques ; terminale (\u00e9dition 2024)",
        "auteurs": "Julien Besson, Isabelle Lericque, Luis Mateus, Jo\u00ebl Ternoy",
        "auteurs_multi": {
            "356832": "Julien Besson",
            "356833": "Luis Mateus",
            "414043": "Isabelle Lericque",
            "414044": "Jo\u00ebl Ternoy",
        },
        "auteurs_id": ["356832", "414043", "356833", "414044"],
        "auteurs_fonctions": [],
        "article": [
            {
                "nombre": 0,
                "gencod": "9782095023584",
                "id_catalogue": ["0"],
                "collection": "Annales Abc Du Bac ; Sujets & Corriges",
                "collection_no": "0",
                "editeur": "Nathan",
                "distributeur": "Interforum",
                "code_distributeur": "371",
                "prix": 8.9,
                "taux_tva": "5.50",
                "code_tva": 2,
                "prixpays": {
                    "fr": {"value": 8.9, "devise": "&euro;"},
                    "be": {"value": 8.9, "devise": "&euro;"},
                    "ch": {"value": 14.6, "devise": "CHF"},
                },
                "dateparution": "24/08/2023",
                "dateparutionentier": 1692828000,
                "datecreation": "19/04/2023",
                "datecreationentier": 1681855200,
                "datemodification": "30/05/2024",
                "dispo": 1,
                "dispopays": {"fr": 1, "be": 1, "ch": 1},
                "libelledispo": "Disponible",
                "resume": "Les Annales ABC du BAC pour r\u00e9viser et pr\u00e9parer l'\u00e9preuve de Math\u00e9matiques Terminale du Bac 2024.\r\n-  30 sujets corrig\u00e9s pour pr\u00e9parer l'\u00e9preuve et le Grand oral.\r\n-  Des fiches de r\u00e9visions pour retenir l'essentiel.\r\n-  Des exercices pour contr\u00f4ler ses connaissances.\r\n-  Des aides pas \u00e0 pas et la m\u00e9thode en contexte + R\u00e9dig\u00e9 par des enseignants ! + Annales ABC du BAC 2024 Math\u00e9matiques Terminale - Enseignement de sp\u00e9cialit\u00e9 Conforme aux programmes du Bac Une nouvelle formule pour pr\u00e9parer avec succ\u00e8s l'\u00e9preuve finale du nouveau Bac !\r\nLes \u00e9preuves du nouveau Bac expliqu\u00e9es.\r\nLes bonnes m\u00e9thodes \u00e0 acqu\u00e9rir pour r\u00e9ussir.\r\nDes rappels de cours, des QCM et des exercices pour faire le point.\r\nDes sujets pas \u00e0 pas avec des corrig\u00e9s expliqu\u00e9s.\r\nDes sujets de Bac comme \u00e0 l'examen pour s'exercer.\r\nUn cahier sp\u00e9cial Grand oral.",
                "image": 1,
                "image_spe": 1,
                "image_4": 0,
                "imagesUrl": {
                    "recto": "https://images.epagine.fr/584/9782095023584_1_75.jpg",
                    "vign": "https://images.epagine.fr/584/9782095023584_1_v.jpg",
                    "moyen": "https://images.epagine.fr/584/9782095023584_1_m.jpg",
                    "verso": "https://images.epagine.fr/is/6505/9782095023584_4_75.jpg",
                },
                "detailUrl": "/livre/9782095023584-annales-abc-du-bac-sujets-corriges-mathematiques-terminale-edition-2024-julien-besson-isabelle-lericque-luis-mateus-joel-ternoy/",
                "langue": "Fran\u00e7ais",
                "langueiso": "fra",
                "langueflag": "https://static.epagine.fr/commonfiles/flags/fr.png",
                "nbmag": 183,
                "codesupport": "T",
                "libellesupport": "Grand format",
                "drm": 0,
                "biblio": 0,
                "extrait": 0,
                "extrait_oeuvre": 1,
                "pages": 384,
                "longueur": 21.2,
                "largeur": 14.6,
                "epaisseur": 2.2,
                "poids": 478,
                "biographie": 0,
                "biographies": [],
                "websites": [],
                "serie": "Non pr\u00e9cis\u00e9e",
                "idserie": "0",
                "scolaire": 0,
                "livre_etranger": 0,
                "racine_editeur": "209",
                "code_clil": "3006",
                "type_prix": "0",
                "typeproduit": 0,
                "iad": "0",
                "id_code_langue": "10000",
                "stock": 0,
                "gtl": {
                    "first": {
                        "1": {"code": "12000000", "libelle": "Parascolaire"},
                        "2": {"code": "12090000", "libelle": "Baccalaur&eacute;at g&eacute;n&eacute;ral (annales)"},
                        "3": {"code": "12090400", "libelle": "Math&eacute;matiques"},
                        "4": {"code": "12090418", "libelle": "Terminale Enseignement de Sp&eacute;cialit&eacute;"},
                    }
                },
                "public_averti": 0,
                "replace": ["9782091572758"],
                "precommande": 0,
                "ispromotion": 0,
                "isnew": 0,
                "drmlcp": 0,
                "bonus_extraits": {
                    "gencod": "9782095023584",
                    "pagesinterieures": 0,
                    "pdfextrait": 0,
                    "pdfchapitre": 0,
                    "pdfparagraphe": 0,
                    "mp3_count": 0,
                },
                "id_lectorat": 0,
                "livre_lu": 0,
                "grands_caracteres": 0,
                "multilingue": 0,
                "illustre": 0,
                "luxe": 0,
                "relie": 0,
                "broche": 1,
                "NombreMagasins": 0,
                "collector": 0,
                "code_editeur": "77",
            }
        ],
        "biographies": [],
        "websites": [],
        "typeproduit": 0,
    },
    "ean": "9782095023584",
    "changeEncodingTo": "UTF-8",
    "extraparams": {"ws": 1},
}


NO_RESULT_BY_EAN_FIXTURE = {
    "type": 1,
    "magid": "7",
    "compatibility": [],
    "magOptions": {
        "Data": {
            "MagasinId": "7",
            "MessagerieCommandes": "1",
            "ComboProduits": '{"produits":{"0":{"id":0,"ordre":1,"search":"paper","libelle":"livres"},"1":{"id":1,"ordre":2,"search":"ebook","libelle":"livres_numeriques"},"3":{"id":3,"ordre":3,"search":"dvd","libelle":"dvd"},"4":{"id":4,"ordre":4,"search":"music","libelle":"musique"},"5":{"id":5,"ordre":5,"search":"jouet","libelle":"recherche_jouet"},"6":{"id":6,"ordre":6,"search":"papeterie","libelle":"recherche_papeterie"},"7":{"id":7,"ordre":7,"search":"jeuvideo","libelle":"jeux_video"},"2":{"id":2,"ordre":8,"search":"liseuse","libelle":"liseuses"}},"options":{"tous_produits":{"affichage":2,"search":"all","libelle":"tous_produits"},"tous_livres":{"affichage":1,"search":"allbooks","libelle":"allbooks"},"ebooks_fr":0,"ebooks_gb":0,"ebooks_nl":0,"livres_fr":0}}',
            "TvaEtrangere0": "0",
            "BlocageReimpression": "0",
            "MATOMO": "Matomo",
            "DetailTables": "1",
            "ExtraitsAudio": "0",
            "SEGMENT": "Segment",
        },
        "Keys": [],
        "LibKeys": [],
        "Database": "OAI-PMH",
        "Fields": [],
        "DateFields": [],
        "DefaultFields": [],
        "ReferencedObjects": [],
    },
    "ean": "9782067256018",
    "changeEncodingTo": "UTF-8",
    "extraparams": {"ws": 1},
}

NO_GTL_IN_RESULT_FIXTURE = {
    "type": 1,
    "magid": "7",
    "compatibility": [],
    "oeuvre": {
        "id": "3634325",
        "titre": "Voyage au pays des nonas",
        "auteurs": "Paule Giron",
        "auteurs_multi": {"333357": "Paule Giron"},
        "auteurs_id": ["333357"],
        "auteurs_fonctions": [],
        "realisateur_multi": [],
        "article": [
            {
                "nombre": 0,
                "gencod": "9791030204704",
                "id_catalogue": ["-131072"],
                "collection_no": "0",
                "editeur": "Fauves editions",
                "distributeur": "ePagine",
                "code_distributeur": "309",
                "diffuseur": "Harmattan",
                "entrepot": "Harmattan",
                "prix": 8.99,
                "prixpays": {
                    "fr": {"value": 8.99, "devise": "&euro;"},
                    "be": {"value": 8.99, "devise": "&euro;"},
                    "nl": {"value": 8.99, "devise": "&euro;"},
                    "ch": {"value": 9.8, "devise": "CHF"},
                },
                "dateparution": "15/03/2023",
                "dateparutionentier": 1678834800,
                "dispo": 1,
                "dispopays": {"fr": 1, "be": 1, "ch": 1},
                "libelledispo": "Disponible",
                "resume": "\"J'avoue que, plus je prends de l'\u00e2ge, plus vieillir m'\u00e9tonne ! Ces derni\u00e8res ann\u00e9es, le vent s'est mis \u00e0 tourner et les vieux ont de plus en plus envie d'exister \u00e0 part enti\u00e8re. Finies les d\u00e9cisions prises pour nous et \u00e0 notre place. Notre nouveau mot d'ordre est devenu : \"Pour la vieillesse, rien sans nous et tout avec nous\". Un bonheur n'arrivant jamais seul, la long\u00e9vit\u00e9 s'est mise de la partie pour nous offrir, comme nous n'en avions encore jamais vu, un concours de centenaires. J'aurais pu poser ma propre plume en pensant que nous avions \u00e0 peu pr\u00e8s tout dit sur la vieillesse. Et puis, je me suis aper\u00e7ue qu'il y avait vieux et vieux et qu'entre un octog\u00e9naire et un nonag\u00e9naire, il n'y avait pas seulement une diff\u00e9rence de...vieillissement, mais un changement \u00e0 la fois si subtil et si radical qu'il valait qu'on s'y arr\u00eate pour examiner son contenu.\" Soyons vieux, soyons actifs ! Tel est l'adage de Paule Giron, jeune nonag\u00e9naire qui d\u00e9montre avec humour que l'\u00eatre humain n'en finit pas de devenir.",
                "image": "1",
                "image_spe": 0,
                "image_alkor": 0,
                "image_4": "0",
                "imagesUrl": {
                    "recto": "https://images.epagine.fr/704/9791030204704_1_75.jpg",
                    "vign": "https://images.epagine.fr/704/9791030204704_1_v.jpg",
                    "moyen": "https://images.epagine.fr/704/9791030204704_1_m.jpg",
                    "verso": "https://images.epagine.fr/no_ebook.png",
                },
                "detailUrl": "/ebook/9791030204704-voyage-au-pays-des-nonas-paule-giron/",
                "langue": "Fran\u00e7ais",
                "langueiso": "fra",
                "langueflag": "https://static.epagine.fr/commonfiles/flags/fr.png",
                "nbmag": "19",
                "codesupport": "LE",
                "libellesupport": "ebook (pdf)",
                "codesupport2": [],
                "libellesupport2": [],
                "idformat": "4030929",
                "libelleformat": "pdf",
                "drm": "0",
                "chapitre": 0,
                "biblio": "0",
                "extrait": "0",
                "extrait_oeuvre": "0",
                "pages": "100",
                "longueur": 0,
                "largeur": 0,
                "hauteur": 0,
                "epaisseur": 0,
                "poids": "0",
                "biographie": "0",
                "biographies": [],
                "websites": [],
                "datecreation": "16/03/2023",
                "datecreationentier": 1678923118,
                "datemodification": "10/10/2023",
                "serie": "Non pr\u00e9cis\u00e9e",
                "idserie": "0",
                "scolaire": "0",
                "commentaire": "pr\u00e9face Marie-Fran\u00e7oise Fuchs",
                "livre_etranger": "0",
                "type_prix": 0,
                "accessibilite": [],
                "contenu_explicite": 0,
                "nb_galettes": 0,
                "duree": 0,
                "anneesortie": 0,
                "interpretes": [],
                "typeproduit": "1",
                "colors": [],
                "langues": [],
                "audios": [],
                "soustitres": [],
                "iad": "0",
                "usage": '{"IT":{"print":"01","copy":"01"}}',
                "id_code_langue": "10000",
                "taux_tva": "5.50",
                "code_tva": "2",
                "nboccasions": 0,
                "stock": 0,
                "gtl": [],
                "gtlvideo": [],
                "operations": [],
                "tracks": [],
                "cmb": "320101",
                "deee_ht": 0,
                "tva": 0,
                "minutesdejeu": 0,
                "nbjoueursmin": 0,
                "nbjoueursmax": 0,
                "colisage": 0,
                "longueurboite": 0,
                "largeurboite": 0,
                "hauteurboite": 0,
                "grammesboite": 0,
                "nbpiles": 0,
                "pilesincluses": 0,
                "nbanneegarantie": 0,
                "produits_recycles": 0,
                "nbpages": 0,
                "grammage": 0,
                "taille_ecriture_mm": 0,
                "poignee": 0,
                "lavable": 0,
                "impermeable": 0,
                "contenance_ml": 0,
                "nbfeuilles": 0,
                "diametre": 0,
                "diametreboite": 0,
                "garantiemois": 0,
                "drm_libelle": "DRM Adobe",
                "precommande": 0,
                "ispromotion": 0,
                "isnew": 0,
                "editeur_id_epagine": "3732",
                "multijoueur": 0,
                "nblicenses": 0,
                "nbutilisateur": 0,
                "internet": 0,
                "pegi": [],
                "solo": 0,
                "online": 0,
                "avertissement": [],
                "drmlcp": "0",
                "bonus_extraits": {
                    "gencod": "9791030204704",
                    "pagesinterieures": "0",
                    "pdfextrait": "0",
                    "pdfchapitre": "0",
                    "pdfparagraphe": "0",
                    "mp3_count": "0",
                },
                "id_lectorat": "0",
                "livre_lu": "0",
                "grands_caracteres": "0",
                "multilingue": "0",
                "illustre": "0",
                "luxe": "0",
                "relie": "0",
                "broche": "0",
                "DrmId": "1",
                "EntrepotID": "700",
                "lectureEnLigne": "0",
                "NombreMagasins": 0,
                "collector": "0",
                "code_editeur": "21897",
                "sorecop": 0,
                "pcb": 0,
                "spcb": 0,
                "volume": 0,
                "compartiment": 0,
                "poche": 0,
            }
        ],
        "biographies": [],
        "websites": [],
        "typeproduit": 0,
    },
    "ean": "9791030204704",
    "changeEncodingTo": "UTF-8",
    "extraparams": {"ws": 1},
}


MUSIC_SEARCH_FIXTURE = {
    "type": 4,
    "magid": "7",
    "nombre": 25,
    "page": 1,
    "result": [
        {
            "id": 871729,
            "titre": "Les dernières volontés de Mozart (symphony)",
            "auteurs_multi": [],
            "auteurs_id": [],
            "auteurs_fonction": [],
            "realisateur_multi": [],
            "article": {
                "1": {
                    "nombre": 0,
                    "gencod": "3700187679323",
                    "id_catalogue": ["0"],
                    "editeur": "BELIEVE",
                    "distributeur": "Believe",
                    "code_distributeur": "MCT",
                    "prix": 14.99,
                    "codeprix": "AP1249",
                    "prixpays": {
                        "fr": {"value": 14.99, "devise": "&euro;"},
                        "be": {"value": 14.99, "devise": "&euro;"},
                    },
                    "dateparution": "02/12/2022",
                    "dateparutionentier": 1669935600,
                    "dispo": 1,
                    "dispopays": {"fr": 1, "be": 1, "ch": 1},
                    "libelledispo": "Disponible",
                    "resume": 'GIMS revient avec " Les dernières volontés de Mozart ", un album de tubes.',
                    "image": "1",
                    "image_spe": "1",
                    "image_alkor": 0,
                    "image_4": "1",
                    "imagesUrl": {
                        "recto": "https://images.epagine.fr/323/3700187679323.jpg",
                        "vign": "https://images.epagine.fr/323/3700187679323_vd.jpg",
                        "moyen": "https://images.epagine.fr/323/3700187679323.jpg",
                        "verso": "https://images.epagine.fr/323/3700187679323_2.jpg",
                    },
                    "detailUrl": "/music/3700187679323-les-dernieres-volontes-de-mozart-symphony-gims/",
                    "nbmag": "62",
                    "codesupport": "38",
                    "libellesupport": "CD Digipack",
                    "libellesupportcourt": "CD Dig.",
                    "codesupport2": [],
                    "libellesupport2": [],
                    "chapitre": 0,
                    "biblio": "0",
                    "extrait": 0,
                    "extrait_oeuvre": "0",
                    "pages": 0,
                    "longueur": 0,
                    "largeur": 0,
                    "hauteur": 0,
                    "epaisseur": 0,
                    "poids": 0,
                    "biographies": [],
                    "websites": [],
                    "datemodification": "01/12/2022",
                    "idserie": 0,
                    "livre_etranger": 0,
                    "type_prix": 0,
                    "contenu_explicite": 0,
                    "nb_galettes": "1",
                    "duree": 0,
                    "anneesortie": 0,
                    "interprete": "Gims",
                    "interpretes": [],
                    "typeproduit": "4",
                    "colors": [],
                    "langues": [],
                    "audios": [],
                    "soustitres": [],
                    "artiste": "Gims",
                    "compositeur": "Gims",
                    "nbtracks": "0",
                    "label": "PLAY TWO",
                    "taux_tva": 0,
                    "code_tva": "3",
                    "nboccasions": 0,
                    "stock": 0,
                    "gtl": {
                        "first": {
                            "1": {"code": "110000", "libelle": "Rap / Hip Hop"},
                            "2": {"code": "110400", "libelle": "Rap / Hip Hop francophone"},
                        }
                    },
                    "gtlvideo": [],
                    "operations": [],
                    "tracks": [],
                    "deee_ht": 0,
                    "tva": 0,
                    "minutesdejeu": 0,
                    "nbjoueursmin": 0,
                    "nbjoueursmax": 0,
                    "colisage": 0,
                    "longueurboite": 0,
                    "largeurboite": 0,
                    "hauteurboite": 0,
                    "grammesboite": 0,
                    "nbpiles": 0,
                    "pilesincluses": 0,
                    "nbanneegarantie": 0,
                    "produits_recycles": 0,
                    "nbpages": 0,
                    "grammage": 0,
                    "taille_ecriture_mm": 0,
                    "poignee": 0,
                    "lavable": 0,
                    "impermeable": 0,
                    "contenance_ml": 0,
                    "nbfeuilles": 0,
                    "diametre": 0,
                    "diametreboite": 0,
                    "garantiemois": 0,
                    "precommande": 0,
                    "ispromotion": 0,
                    "isnew": 0,
                    "multijoueur": 0,
                    "nblicenses": 0,
                    "nbutilisateur": 0,
                    "internet": 0,
                    "pegi": [],
                    "drmlcp": 0,
                    "bonus_extraits": {"gencod": "3700187679323"},
                    "livre_lu": 0,
                    "grands_caracteres": 0,
                    "multilingue": 0,
                    "illustre": 0,
                    "luxe": 0,
                    "relie": 0,
                    "broche": 0,
                    "ReferenceInterne": "BLV7932",
                    "prix_ht": 12.49,
                    "lectureEnLigne": 0,
                    "NombreMagasins": 0,
                    "collector": 0,
                    "code_editeur": 0,
                    "sorecop": 0,
                    "pcb": 0,
                    "spcb": 0,
                    "volume": 0,
                    "compartiment": 0,
                    "poche": 0,
                },
                "2": {
                    "nombre": 0,
                    "gencod": "3700187679324",
                    "id_catalogue": ["0"],
                    "editeur": "BELIEVE",
                    "distributeur": "Believe",
                    "code_distributeur": "MCT",
                    "prix": 14.99,
                    "codeprix": "AP1249",
                    "prixpays": {
                        "fr": {"value": 14.99, "devise": "&euro;"},
                        "be": {"value": 14.99, "devise": "&euro;"},
                    },
                    "dateparution": "02/12/2022",
                    "dateparutionentier": 1669935600,
                    "dispo": 1,
                    "dispopays": {"fr": 1, "be": 1, "ch": 1},
                    "libelledispo": "Disponible",
                    "resume": 'GIMS revient avec " Les dernières volontés de Mozart ", un album de tubes.',
                    "image": "1",
                    "image_spe": "1",
                    "image_alkor": 0,
                    "image_4": "1",
                    "imagesUrl": {
                        "recto": "https://images.epagine.fr/323/3700187679324.jpg",
                        "vign": "https://images.epagine.fr/323/3700187679324_vd.jpg",
                        "moyen": "https://images.epagine.fr/323/3700187679324.jpg",
                        "verso": "https://images.epagine.fr/323/3700187679324_2.jpg",
                    },
                    "detailUrl": "/music/3700187679324-les-dernieres-volontes-de-mozart-symphony-gims/",
                    "nbmag": "63",
                    "codesupport": "7",
                    "libellesupport": "Album Vinyle",
                    "libellesupportcourt": "LP",
                    "codesupport2": [],
                    "libellesupport2": [],
                    "chapitre": 0,
                    "biblio": "0",
                    "extrait": 0,
                    "extrait_oeuvre": "0",
                    "pages": 0,
                    "longueur": 0,
                    "largeur": 0,
                    "hauteur": 0,
                    "epaisseur": 0,
                    "poids": 0,
                    "biographies": [],
                    "websites": [],
                    "datemodification": "01/12/2022",
                    "idserie": 0,
                    "livre_etranger": 0,
                    "type_prix": 0,
                    "contenu_explicite": 0,
                    "nb_galettes": "1",
                    "duree": 0,
                    "anneesortie": 0,
                    "interprete": "Gims",
                    "interpretes": [],
                    "typeproduit": "4",
                    "colors": [],
                    "langues": [],
                    "audios": [],
                    "soustitres": [],
                    "artiste": "Gims",
                    "compositeur": "Gims",
                    "nbtracks": "0",
                    "label": "PLAY TWO",
                    "taux_tva": 0,
                    "code_tva": "3",
                    "nboccasions": 0,
                    "stock": 0,
                    "gtl": [],
                    "gtlvideo": [],
                    "operations": [],
                    "tracks": [],
                    "deee_ht": 0,
                    "tva": 0,
                    "minutesdejeu": 0,
                    "nbjoueursmin": 0,
                    "nbjoueursmax": 0,
                    "colisage": 0,
                    "longueurboite": 0,
                    "largeurboite": 0,
                    "hauteurboite": 0,
                    "grammesboite": 0,
                    "nbpiles": 0,
                    "pilesincluses": 0,
                    "nbanneegarantie": 0,
                    "produits_recycles": 0,
                    "nbpages": 0,
                    "grammage": 0,
                    "taille_ecriture_mm": 0,
                    "poignee": 0,
                    "lavable": 0,
                    "impermeable": 0,
                    "contenance_ml": 0,
                    "nbfeuilles": 0,
                    "diametre": 0,
                    "diametreboite": 0,
                    "garantiemois": 0,
                    "precommande": 0,
                    "ispromotion": 0,
                    "isnew": 0,
                    "multijoueur": 0,
                    "nblicenses": 0,
                    "nbutilisateur": 0,
                    "internet": 0,
                    "pegi": [],
                    "drmlcp": 0,
                    "bonus_extraits": {"gencod": "3700187679324"},
                    "livre_lu": 0,
                    "grands_caracteres": 0,
                    "multilingue": 0,
                    "illustre": 0,
                    "luxe": 0,
                    "relie": 0,
                    "broche": 0,
                    "ReferenceInterne": "BLV7932",
                    "prix_ht": 12.49,
                    "lectureEnLigne": 0,
                    "NombreMagasins": 0,
                    "collector": 0,
                    "code_editeur": 0,
                    "sorecop": 0,
                    "pcb": 0,
                    "spcb": 0,
                    "volume": 0,
                    "compartiment": 0,
                    "poche": 0,
                },
            },
            "biographies": [],
            "websites": [],
            "typeproduit": 4,
            "interprete": "Gims",
        },
        {
            "id": 869715,
            "titre": "Cracker Island",
            "auteurs_multi": [],
            "auteurs_id": [],
            "auteurs_fonction": [],
            "realisateur_multi": [],
            "article": {
                "1": {
                    "nombre": 0,
                    "gencod": "5054197199738",
                    "id_catalogue": ["0"],
                    "editeur": "WARNER MUSIC UK",
                    "distributeur": "Warner Music France",
                    "code_distributeur": "WAR",
                    "codeprix": "461",
                    "prixpays": {
                        "fr": {"value": 19.98, "devise": "&euro;"},
                        "be": {"value": 19.98, "devise": "&euro;"},
                    },
                    "dateparution": "24/02/2023",
                    "dateparutionentier": 1677193200,
                    "dispo": 1,
                    "dispopays": {"fr": 1, "be": 1, "ch": 1},
                    "libelledispo": "Disponible",
                    "resume": "Ce huitième album studio de Gorillaz est une collection énergique, optimiste et riche en genres de 10 titres mettant en vedette un line-up stellaire de collaborateurs : Thundercat, Tame Impala, Bad Bunny, Stevie Nicks, Adeleye Omotayo, Bootie Brown et Beck.",
                    "image": "1",
                    "image_spe": "1",
                    "image_alkor": 0,
                    "image_4": "1",
                    "imagesUrl": {
                        "recto": "https://images.epagine.fr/738/5054197199738.jpg",
                        "vign": "https://images.epagine.fr/738/5054197199738_vd.jpg",
                        "moyen": "https://images.epagine.fr/738/5054197199738.jpg",
                        "verso": "https://images.epagine.fr/738/5054197199738_2.jpg",
                    },
                    "detailUrl": "/music/5054197199738-cracker-island-gorillaz/",
                    "nbmag": "34",
                    "codesupport": "7",
                    "libellesupport": "Album Vinyle",
                    "libellesupportcourt": "LP",
                    "codesupport2": [],
                    "libellesupport2": [],
                    "chapitre": 0,
                    "biblio": "0",
                    "extrait": 0,
                    "extrait_oeuvre": "0",
                    "pages": 0,
                    "longueur": 0,
                    "largeur": 0,
                    "hauteur": 0,
                    "epaisseur": 0,
                    "poids": 0,
                    "biographies": [],
                    "websites": [],
                    "datemodification": "18/08/2023",
                    "idserie": 0,
                    "livre_etranger": 0,
                    "type_prix": 0,
                    "contenu_explicite": 0,
                    "nb_galettes": "1",
                    "duree": 0,
                    "anneesortie": 0,
                    "interprete": "Gorillaz",
                    "interpretes": [],
                    "typeproduit": "4",
                    "colors": [],
                    "langues": [],
                    "audios": [],
                    "soustitres": [],
                    "artiste": "Gorillaz",
                    "compositeur": "Gorillaz",
                    "nbtracks": "10",
                    "label": "WARNER MUSIC UK",
                    "taux_tva": 0,
                    "code_tva": "3",
                    "nboccasions": 0,
                    "stock": 0,
                    "gtl": {
                        "first": {
                            "1": {"code": "50000", "libelle": "Pop"},
                            "2": {"code": "50300", "libelle": "Brit Pop"},
                        }
                    },
                    "gtlvideo": [],
                    "operations": [],
                    "tracks": [],
                    "deee_ht": 0,
                    "tva": 0,
                    "minutesdejeu": 0,
                    "nbjoueursmin": 0,
                    "nbjoueursmax": 0,
                    "colisage": 0,
                    "longueurboite": 0,
                    "largeurboite": 0,
                    "hauteurboite": 0,
                    "grammesboite": 0,
                    "nbpiles": 0,
                    "pilesincluses": 0,
                    "nbanneegarantie": 0,
                    "produits_recycles": 0,
                    "nbpages": 0,
                    "grammage": 0,
                    "taille_ecriture_mm": 0,
                    "poignee": 0,
                    "lavable": 0,
                    "impermeable": 0,
                    "contenance_ml": 0,
                    "nbfeuilles": 0,
                    "diametre": 0,
                    "diametreboite": 0,
                    "garantiemois": 0,
                    "precommande": 0,
                    "ispromotion": 0,
                    "isnew": 0,
                    "multijoueur": 0,
                    "nblicenses": 0,
                    "nbutilisateur": 0,
                    "internet": 0,
                    "pegi": [],
                    "drmlcp": 0,
                    "bonus_extraits": {"gencod": "5054197199738"},
                    "livre_lu": 0,
                    "grands_caracteres": 0,
                    "multilingue": 0,
                    "illustre": 0,
                    "luxe": 0,
                    "relie": 0,
                    "broche": 0,
                    "ReferenceInterne": "5419719973",
                    "prix_ht": 16.65,
                    "lectureEnLigne": 0,
                    "NombreMagasins": 0,
                    "collector": 0,
                    "code_editeur": 0,
                    "sorecop": 0,
                    "pcb": 0,
                    "spcb": 0,
                    "volume": 0,
                    "compartiment": 0,
                    "poche": 0,
                }
            },
            "biographies": [],
            "websites": [],
            "typeproduit": 4,
            "interprete": "Gorillaz",
        },
    ],
    "suggestions": [],
    "nbreponses": 50000,
    "changeEncodingTo": "UTF-8",
    "ws": 1,
}

EMPTY_MUSIC_SEARCH_FIXTURE = {"type": 4, "magid": "7", "nombre": 25, "page": 2, "result": []}
