import {
  GetVenueResponseModel,
  StudentLevels,
  VenueTypeCode,
} from 'apiClient/v1'

import { COLLECTIVE_DATA_FORM_INITIAL_VALUES } from '../CollectiveDataForm/initialValues'
import { extractInitialValuesFromVenue } from '../CollectiveDataForm/utils/extractInitialValuesFromVenue'

describe('extractInitialValuesFromVenue', () => {
  it('should extract initial values', () => {
    const venue: GetVenueResponseModel = {
      address: '1 boulevard Poissonnière',
      audioDisabilityCompliant: false,
      bannerMeta: null,
      bannerUrl: null,
      bic: null,
      bookingEmail: 'venue26@example.net',
      businessUnit: {
        id: 240,
        iban: 'FR0710010000000000000000036',
        bic: 'BDFEFRPP',
        name: 'Business unit #26',
      },
      businessUnitId: 240,
      city: 'Paris',
      collectiveAccessInformation: null,
      collectiveDescription: 'description EAC',
      collectiveDomains: [{ id: 1, name: 'domain1' }],
      collectiveEmail: null,
      collectiveInterventionArea: null,
      collectiveLegalStatus: '2',
      collectiveNetwork: null,
      collectivePhone: null,
      collectiveStudents: [
        StudentLevels.CAP_1RE_ANN_E,
        StudentLevels.CAP_2E_ANN_E,
      ],
      collectiveWebsite: null,
      comment: null,
      contact: {
        email: 'contact@venue.com',
        website: 'https://my@website.com',
        phoneNumber: '+33102030405',
      },
      dateCreated: '2022-07-11T23:02:00.356596Z',
      dateModifiedAtLastProvider: '2022-07-11T23:02:00.356587Z',
      demarchesSimplifieesApplicationId: null,
      departementCode: '75',
      description: 'Western piece may foreign middle someone instead.',
      dmsToken: '6bab3a2b8351',
      fieldsUpdated: [],
      iban: null,
      id: 'ATMA',
      idAtProviders: null,
      isBusinessUnitMainVenue: true,
      isPermanent: true,
      isValidated: true,
      isVirtual: false,
      lastProviderId: null,
      latitude: 48.87004,
      longitude: 2.3785,
      managingOfferer: {
        address: '1 boulevard Poissonnière',
        bic: null,
        city: 'Paris',
        dateCreated: '2022-07-11T23:02:00.266856Z',
        dateModifiedAtLastProvider: '2022-07-11T23:02:00.266847Z',
        demarchesSimplifieesApplicationId: null,
        fieldsUpdated: [],
        iban: null,
        id: 'Z9',
        idAtProviders: null,
        isValidated: true,
        lastProviderId: null,
        name: "Bonne structure pour l'EAC (siren)",
        postalCode: '75000',
        siren: '950469494',
      },
      managingOffererId: 'Z9',
      mentalDisabilityCompliant: false,
      motorDisabilityCompliant: false,
      name: '[EAC] Opéra Royal de Versailles - Salle 0',
      nonHumanizedId: 1240,
      postalCode: '75000',
      pricingPoint: null,
      publicName: '[EAC] Opéra Royal de Versailles - Salle 0',
      reimbursementPointId: null,
      siret: '95046949400020',
      venueLabelId: null,
      venueTypeCode: VenueTypeCode.COURS_ET_PRATIQUE_ARTISTIQUES,
      visualDisabilityCompliant: false,
      withdrawalDetails: null,
    }

    expect(extractInitialValuesFromVenue(venue)).toStrictEqual({
      collectiveDescription: 'description EAC',
      collectiveStudents: [
        StudentLevels.CAP_1RE_ANN_E,
        StudentLevels.CAP_2E_ANN_E,
      ],
      collectiveWebsite: COLLECTIVE_DATA_FORM_INITIAL_VALUES.collectiveWebsite,
      collectivePhone: COLLECTIVE_DATA_FORM_INITIAL_VALUES.collectivePhone,
      collectiveEmail: COLLECTIVE_DATA_FORM_INITIAL_VALUES.collectiveEmail,
      collectiveLegalStatus: 2,
      collectiveDomains: ['1'],
      collectiveNetwork: [],
      collectiveInterventionArea:
        COLLECTIVE_DATA_FORM_INITIAL_VALUES.collectiveInterventionArea,
    })
  })
})
