from pcapi.core.fraud.ubble import models as ubble_fraud_models


UBBLE_IDENTIFICATION_RESPONSE = {
    "data": {
        "type": "identifications",
        "id": "3191295",
        "attributes": {
            "score": ubble_fraud_models.UbbleScore.INVALID.value,
            "anonymized-at": None,
            "comment": None,
            "created-at": "2021-11-18T18:59:59.273402Z",
            "ended-at": None,
            "identification-id": "29d9eca4-dce6-49ed-b1b5-8bb0179493a8",
            "identification-url": "https://id.ubble.ai/29d9eca4-dce6-49ed-b1b5-8bb0179493a8",
            "is-live": False,
            "number-of-attempts": 0,
            "redirect-url": "https://example.com/redirect-url",
            "started-at": None,
            "status-updated-at": "2021-11-18T18:59:59.273171Z",
            "status": "uninitiated",
            "updated-at": "2021-11-18T18:59:59.329011Z",
            "user-agent": None,
            "user-ip-address": None,
            "webhook": "https://example.com/webhook",
        },
        "relationships": {
            "identity": {
                "data": {"type": "identities", "id": "3187041"},
                "links": {"related": "https://api.example.com/api/identifications/3191295/identity"},
            },
            "reference-data": {
                "data": {"type": "reference-data", "id": "119617"},
                "links": {"related": "https://api.example.com/api/identifications/3191295/reference_data"},
            },
            "reason-codes": {
                "meta": {"count": 2},
                "data": [
                    {"type": "reason-codes", "id": "1304"},
                    {"type": "reason-codes", "id": "1310"},
                ],
            },
        },
    },
    "included": [
        {
            "type": "identities",
            "id": "3187041",
            "attributes": {"birth-date": None, "first-name": None, "last-name": None},
        },
        {
            "type": "reference-data",
            "id": "119617",
            "attributes": {"last-name": "LastName", "first-name": "FirstName", "birth-date": "2003-10-18"},
        },
        {
            "type": "document-checks",
            "id": "4997875",
            "attributes": {
                "data-extracted-score": ubble_fraud_models.UbbleScore.INVALID.value,
                "expiry-date-score": ubble_fraud_models.UbbleScore.INVALID.value,
                "issue-date-score": None,
                "live-video-capture-score": None,
                "mrz-validity-score": ubble_fraud_models.UbbleScore.INVALID.value,
                "mrz-viz-score": ubble_fraud_models.UbbleScore.INVALID.value,
                "ove-back-score": ubble_fraud_models.UbbleScore.INVALID.value,
                "ove-front-score": ubble_fraud_models.UbbleScore.INVALID.value,
                "ove-score": ubble_fraud_models.UbbleScore.INVALID.value,
                "quality-score": ubble_fraud_models.UbbleScore.INVALID.value,
                "score": ubble_fraud_models.UbbleScore.INVALID.value,
                "supported": ubble_fraud_models.UbbleScore.INVALID.value,
                "visual-back-score": ubble_fraud_models.UbbleScore.INVALID.value,
                "visual-front-score": ubble_fraud_models.UbbleScore.INVALID.value,
            },
            "relationships": {},
        },
        {
            "type": "documents",
            "id": "4998439",
            "attributes": {
                "birth-date": "2003-10-18",
                "birth-place": None,
                "document-number": "777777777777",
                "document-type": "ID",
                "document-type-detailed": None,
                "expiry-date": "2031-09-07",
                "first-name": "FirstName",
                "gender": "M",
                "issue-date": None,
                "issue-place": None,
                "issuing-state-code": "FRA",
                "last-name": "LastName",
                "married-name": None,
                "media-type": "video",
                "mrz": "MRZ",
                "nationality": None,
                "obtaining-date": None,
                "personal-number": None,
                "remarks": None,
            },
            "relationships": {},
        },
    ],
}
