export const VENUE_CREATION_PATCH_KEYS = [
  'address',
  'bic',
  'bookingEmail',
  'city',
  'comment',
  'iban',
  'latitude',
  'longitude',
  'managingOffererId',
  'name',
  'publicName',
  'postalCode',
  'siret',
  'venue-type',
]

export const VENUE_MODIFICATION_PATCH_KEYS = [
  'bookingEmail',
  'publicName',
  'address',
  'city',
  'comment',
  'latitude',
  'longitude',
  'name',
  'postalCode',
  'siret',
  'venue-type',
]
