import { execFileSync } from 'node:child_process'
import { promises as fs } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const OUTPUT_PATH = join(
  __dirname,
  '../src/components/WarningObsoleteNavigator/supportedBrowsers.js'
)

const COMPATIBLE_BROWSERS_LIST_PATH = join(
  __dirname,
  '../src/pages/CompatibleBrowsers/CompatibleBrowsersList.ts'
)

const PACKAGE_JSON_PATH = join(__dirname, '../package.json')

const PROJECT_ROOT = join(__dirname, '..')

const BROWSER_LABELS = {
  and_chr: 'Chrome Android',
  and_ff: 'Firefox Android',
  and_qq: 'QQ Browser Android',
  and_uc: 'UC Browser Android',
  android: 'Android Browser',
  baidu: 'Baidu Browser',
  bb: 'BlackBerry Browser',
  chrome: 'Google Chrome',
  edge: 'Microsoft Edge',
  firefox: 'Mozilla Firefox',
  ie: 'Internet Explorer',
  ie_mob: 'Internet Explorer Mobile',
  ios_saf: 'Safari iOS',
  kaios: 'KaiOS Browser',
  op_mini: 'Opera Mini',
  op_mob: 'Opera Mobile',
  opera: 'Opera',
  safari: 'Apple Safari',
  samsung: 'Samsung Internet',
}

const getBrowserDisplayName = (browserKey) => {
  if (browserKey in BROWSER_LABELS) {
    return BROWSER_LABELS[browserKey]
  }

  return browserKey
    .split('_')
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join(' ')
}

const getMajorVersion = (resolvedBrowserVersion) => {
  const versionPart = resolvedBrowserVersion.split(' ')[1]
  const majorVersion = Number.parseInt(versionPart.split('-')[0], 10)
  return Number.isInteger(majorVersion) ? majorVersion : null
}

const resolveBrowserslistEntries = (queries) => {
  const joinedQueries = queries.join(', ')

  return execFileSync('pnpm', ['exec', 'browserslist', joinedQueries], {
    cwd: PROJECT_ROOT,
    encoding: 'utf-8',
  })
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
}

const getCompatibleBrowsersFromPackageBrowserslist = (queries) => {
  const browsersByKey = {}

  const resolvedVersions = resolveBrowserslistEntries(queries)

  for (const resolvedVersion of resolvedVersions) {
    const [browserKey] = resolvedVersion.split(' ')
    const majorVersion = getMajorVersion(resolvedVersion)

    if (!browserKey || majorVersion === null) {
      continue
    }

    if (!(browserKey in browsersByKey)) {
      browsersByKey[browserKey] = {
        name: getBrowserDisplayName(browserKey),
        minVersion: majorVersion,
      }
      continue
    }

    browsersByKey[browserKey].minVersion = Math.min(
      browsersByKey[browserKey].minVersion,
      majorVersion
    )
  }

  return browsersByKey
}

const toCompatibleBrowsersListFileContent = (browsersByKey) => {
  const orderedKeys = Object.keys(browsersByKey).sort((a, b) =>
    a.localeCompare(b)
  )

  const browsersLines = orderedKeys.map((key) => {
    const browser = browsersByKey[key]
    return `  ${key}: {\n    name: '${browser.name}',\n    minVersion: ${browser.minVersion},\n  },`
  })

  return [
    "import type { CompatibleBrowser } from './type'",
    '',
    '// Auto-generated by scripts/generateSupportedBrowsers.js',
    '// Run `pnpm supported-browsers` after changing browserslist config.',
    'export const compatibleBrowsersList: Record<string, CompatibleBrowser> = {',
    ...browsersLines,
    '}',
    '',
  ].join('\n')
}

const generateSupportedBrowsers = async () => {
  try {
    const packageJson = JSON.parse(
      await fs.readFile(PACKAGE_JSON_PATH, 'utf-8')
    )
    const browserslistQueries = packageJson.browserslist

    if (
      !Array.isArray(browserslistQueries) ||
      browserslistQueries.length === 0
    ) {
      throw new Error('No browserslist array found in package.json.')
    }

    const regexp = execFileSync(
      'browserslist-useragent-regexp',
      ['--allowHigherVersions'],
      {
        cwd: PROJECT_ROOT,
        encoding: 'utf-8',
      }
    ).trim()

    const browsersByKey =
      getCompatibleBrowsersFromPackageBrowserslist(browserslistQueries)
    const compatibleBrowsersListContent =
      toCompatibleBrowsersListFileContent(browsersByKey)

    await fs.writeFile(OUTPUT_PATH, `export default ${regexp}\n`, 'utf-8')
    await fs.writeFile(
      COMPATIBLE_BROWSERS_LIST_PATH,
      compatibleBrowsersListContent,
      'utf-8'
    )
    console.info(
      'info => supportedBrowsers.js and CompatibleBrowsersList.ts generated successfully'
    )
  } catch (error) {
    console.error('error => failed to generate supported browser files')
    if (error instanceof Error) {
      console.error(error.message)
    }
    process.exit(1)
  }
}

generateSupportedBrowsers()
