export const FEATURES = {
  HOMEPAGE: 'WEBAPP_HOMEPAGE',
  APPLY_BOOKING_LIMITS_V2: 'APPLY_BOOKING_LIMITS_V2',
  ALLOW_IDCHECK_REGISTRATION: 'ALLOW_IDCHECK_REGISTRATION',
  WHOLE_FRANCE_OPENING: 'WHOLE_FRANCE_OPENING',
}

export const DEFAULT_WHOLE_FRANCE_OPENING_VALUE = true
