export const FEATURES = {
  HOMEPAGE: 'WEBAPP_HOMEPAGE',
  APPLY_BOOKING_LIMITS_V2: 'APPLY_BOOKING_LIMITS_V2',
  ALLOW_IDCHECK_REGISTRATION: 'ALLOW_IDCHECK_REGISTRATION',
  WHOLE_FRANCE_OPENING: 'WHOLE_FRANCE_OPENING',
  AUTO_ACTIVATE_DIGITAL_BOOKINGS: 'AUTO_ACTIVATE_DIGITAL_BOOKINGS',
  ENABLE_ACTIVATION_CODES: 'ENABLE_ACTIVATION_CODES',
  USE_APP_SEARCH_ON_WEBAPP: 'USE_APP_SEARCH_ON_WEBAPP',
}

export const DEFAULT_WHOLE_FRANCE_OPENING_VALUE = true
