CREATE OR REPLACE FUNCTION pg_temp.fake_last_name(id bigint)
  RETURNS TEXT AS $$
DECLARE
  -- To keep data anonymized but be able to search from first name and last name with realistic data,
  -- we assign last names from the name of all rivers in France (list from Wikipedia)
  rivers TEXT[] = ARRAY[
    'Abloux', 'Acheneau', 'Acolin', 'Aër', 'Aff', 'Agout', 'Ailette', 'Aille', 'Ain', 'Ainan', 'Aire', 'Airin',
    'Airon', 'Aisne', 'Aixette', 'Alagnon', 'Albarine', 'Albe', 'Alène', 'Allaine', 'Allier', 'Allière', 'Allondon',
    'Almont', 'Alzette', 'Alzon', 'Amance', 'Amous', 'Ance', 'Ancre', 'Andelle', 'Andelot', 'Andlau', 'Andon', 'Ange',
    'Anglin', 'Anguison', 'Antenne', 'Apance', 'Arc', 'Arconce', 'Ardèche', 'Ardière', 'Ardour', 'Argenton', 'Argonce',
    'Ariège', 'Arize', 'Arly', 'Armalause', 'Armance', 'Armançon', 'Arn', 'Arnon', 'Arnoult', 'Aroffe', 'Aron',
    'Arrats', 'Arré', 'Arros', 'Arroux', 'Artuby', 'Arvan', 'Arve', 'Arz', 'Asco', 'Aube', 'Aubetin', 'Aubois',
    'Audeux', 'Augronne', 'Aujon', 'Aumance', 'Aunette', 'Aure', 'Aurence', 'Auron', 'Auroue', 'Aussoue', 'Authion',
    'Authre', 'Autize', 'Automne', 'Auvézère', 'Auxance', 'Auxois', 'Auze', 'Auzon', 'Auzoue', 'Avance', 'Aveyron',
    'Avre', 'Azergues', 'Baïse', 'Baïsole', 'Baize', 'Bandiat', 'Bar', 'Barbuise', 'Barguelonne', 'Barguelonnette',
    'Barse', 'Bartassec', 'Bayon ou Bayeux', 'Beaume', 'Beauze', 'Benaize', 'Bénovie', 'Bernesse', 'Béronnelle',
    'Bertrande', 'Bès', 'Besbre', 'Béthune', 'Beuvron', 'Bèze', 'Biaysse', 'Bidouze', 'Bienne', 'Bièvre', 'Bionne',
    'Biourière', 'Blaise', 'Bléone', 'Blies', 'Boëme', 'Boivre', 'Bonne', 'Bonnieure', 'Bono', 'Boralde Flaujaguèse',
    'Borne', 'Bouble', 'Bouleure', 'Boulogne', 'Bourbeuse', 'Bourbince', 'Bourbre', 'Bourdic', 'Bourne', 'Boutonne',
    'Bouzanne', 'Bradascou', 'Braize', 'Brame', 'Bras de Bronne', 'Braye', 'Brêche', 'Brême', 'Brenne', 'Brestalou',
    'Breuchin', 'Brévogne', 'Brezons', 'Brézou', 'Briance', 'Brionneau', 'Brivet', 'Bromme', 'Bruche', 'Bruxenelle',
    'Buëch', 'Cailly', 'Calavon', 'Cambre', 'Cance', 'Canche', 'Cantache', 'Caramy', 'Cauron', 'Cause ou Infernet',
    'Cazine', 'Célé', 'Celle', 'Céor', 'Céou', 'Cère', 'Cérou', 'Cesse', 'Cèze', 'Chalaronne', 'Chapeauroux',
    'Charentonne', 'Chasse', 'Chassezac', 'Chat Cros', 'Chavanon', 'Chée', 'Cher', 'Chéran', 'Chère', 'Chiers',
    'Choisille', 'Ciron', 'Cisse', 'Claie', 'Clain', 'Claise', 'Clarée', 'Clarence', 'Cligneux', 'Clouère', 'Coise',
    'Colagne', 'Côle', 'Colmont', 'Colombine', 'Combade', 'Combeauté', 'Côney', 'Conie', 'Conroy', 'Corrèze', 'Cosson',
    'Couarde', 'Couasnon', 'Coulazou', 'Cousances', 'Cousin', 'Couze Chambon', 'Couze Pavin', 'Credogne', 'Creuse',
    'Crieulon', 'Crueize', 'Crusnes', 'Cuisance', 'Cure', 'Cusancin', 'Dadalouze', 'Dadou', 'Dan', 'Dathée',
    'Dessoubre', 'Deûle', 'Dheune', 'Diane', 'Diège', 'Dive', 'Dive du Sud', 'Doire', 'Doller', 'Don', 'Dordogne',
    'Dore', 'Doron de Beaufort', 'Doron de Bozel', 'Doron des Allues', 'Doubs', 'Doueff', 'Dourbie', 'Dourdou',
    'Doustre', 'Doux', 'Douyne', 'Douze', 'Drac', 'Drac Blanc', 'Dragne', 'Dranse', 'Drôme', 'Dronne', 'Dropt',
    'Droude', 'Druance', 'Drugeon', 'Durance', 'Durgeon', 'Eau Blanche', 'Eau Bourde', 'Eau d''Olle', 'Eau Salée',
    'Écaillon', 'Échandon', 'Échez', 'Egvonne', 'Eichel', 'Elle', 'Epte', 'Erdre', 'Ernée', 'Erve', 'Esch', 'Esches',
    'Esque', 'Essonne', 'Estampon', 'Estéron', 'Etze', 'Eure', 'Ével', 'Èvre', 'Eygues', 'Eyrieux', 'Èze', 'Fecht',
    'Fenioux', 'Fensch', 'Ferrand', 'Feuillade', 'Fier', 'Fil de Gorges', 'Flamenne', 'Flûme', 'Fouzon', 'Fresquel',
    'Furan', 'Furans', 'Fure', 'Furon', 'Fusain', 'Gabas', 'Galaure', 'Garbet', 'Gard', 'Gardon d''Alès',
    'Gardon d''Anduze', 'Gartempe', 'Gave d''Aspe', 'Gave de Pau', 'Gave d''Oloron', 'Gave d''Ossau', 'Gélise',
    'Gères', 'Gers', 'Gesse', 'Gier', 'Giessen', 'Giffre', 'Gijou', 'Gimone', 'Girou', 'Gizia', 'Gland', 'Gloire',
    'Gondoire', 'Gosne', 'Goul', 'Gourgeonne', 'Grande Thonaise', 'Grand Morin', 'Gravona', 'Gresse', 'Grosne',
    'Guerge', 'Guiers', 'Guil', 'Guisane', 'Hallue', 'Helpe Majeure', 'Helpe Mineure', 'Hem', 'Hérisson', 'Hers-Mort',
    'Hers-Vif', 'Houille', 'Hozain', 'Huisne', 'Hyrôme', 'Ill', 'Ille', 'Inam', 'Indre', 'Indrois', 'Isac', 'Isch',
    'Isère', 'Isle', 'Isole', 'Issole', 'Iton', 'Ixeure', 'Jamagne', 'Jarret', 'Jeu', 'Joigne', 'Jordanne', 'Jouanne',
    'Juine', 'Kirneck', 'Laignes', 'Laize', 'Landion', 'Langladure', 'Lanterne', 'Largue', 'Lary', 'Lathan', 'Lauch',
    'Launette', 'Lavaldenan', 'Lawe', 'Layon', 'Lède', 'Léez', 'Leff', 'Lemboulas', 'Lembron', 'Lemme', 'Lendou',
    'Lère', 'Les Usses', 'Leysse', 'Lez', 'Lézarde', 'Lèze', 'Liamou', 'Lidoire', 'Lié', 'Liège', 'Lièpvrette',
    'Ligne', 'Lignon', 'Lignon du Forez', 'Lignon du Velay', 'Linon', 'Lison', 'Livenne', 'Lizaine', 'Lizonne',
    'Loing', 'Loir', 'Loiret', 'Loison', 'Lot', 'Loue', 'Louge', 'Loyre', 'Lozon', 'Lumansonesque', 'Lunain', 'Luy',
    'Luy de Béarn', 'Luy de France', 'Luynes', 'Luzège', 'Lys', 'Madine', 'Madon', 'Maine', 'Malsanne', 'Maltorne',
    'Mamoul', 'Marmande', 'Marne', 'Maronne', 'Marque', 'Mars', 'Maulde', 'Mauldre', 'Maumont', 'Mayenne', 'Menoge',
    'Méouzette', 'Merdereau', 'Merderet', 'Mère', 'Meu', 'Meurthe', 'Midouze', 'Mimente', 'Minette', 'Moder', 'Moine',
    'Montane', 'Morbras', 'Morge', 'Mortagne', 'Morthe', 'Moselle', 'Moselotte', 'Mouzon', 'Naïc', 'Nartuby', 'Naute',
    'Nauze', 'Nave', 'Né', 'Négron', 'Nère', 'Neste', 'Niche', 'Nied', 'Nièvre', 'Ninian', 'Nive', 'Nizerand',
    'Nohain', 'Noireau', 'Nonette', 'Noue', 'Nouère', 'Odon', 'Œil', 'Ognon', 'Oignin', 'Oir', 'Oise', 'Oison',
    'Orain', 'Orbiel', 'Orbieu', 'Orge', 'Oriège', 'Orillon', 'Ornain', 'Orne', 'Orne champenoise', 'Orne saosnoise',
    'Orthe', 'Osse', 'Othain', 'Ouanne', 'Ouche', 'Oudon', 'Ouette', 'Ougeotte', 'Ource', 'Ourcq', 'Ourse', 'Oust',
    'Ouvèze', 'OUvèze', 'Ouysse', 'Oyon', 'Ozanne', 'Oze', 'Ozerain', 'Panouille', 'Petit Buëch', 'Petite Baïse',
    'Petite Creuse', 'Petite Rhue', 'Petite Sauldre', 'Petite Thonaise', 'Petit Lay', 'Petit Morin', 'Piou', 'Plaine',
    'Queugne', 'Rabodeau', 'Raddon', 'Rahun', 'Ramel', 'Rance', 'Récourt', 'Rémarde', 'Rère', 'Restonica', 'Réveillon',
    'Reverotte', 'Reyssouze', 'Rhins', 'Rhone', 'Rhônelle', 'Rhue', 'Rimarde', 'Risle', 'Roanne', 'Rôge', 'Rognon',
    'Rohan', 'Roizonne', 'Romaine', 'Romanche', 'Romme', 'Roule Crottes', 'Rouvre', 'Rozeille', 'Ru de Gally',
    'Rupt de Mad', 'Saine', 'Saint-Bonnette', 'Saint-Niel', 'Saison', 'Salat', 'Salindrenque', 'Salleron', 'Salon',
    'Sambre', 'Sâne Morte', 'Sâne Vive', 'Sânon', 'Santoire', 'Saône', 'Saônelle', 'Sarrampion', 'Sarre', 'Sarthe',
    'Sasse', 'Sauer', 'Sauldre', 'Saulx', 'Sausseron', 'Save', 'Savoureuse', 'Scardon', 'Scarpe', 'Scey', 'Scheer',
    'Scye', 'Sédelle', 'Sègre', 'Seiche', 'Seille', 'Selle', 'Selves', 'Semène', 'Semine', 'Semme', 'Semnon', 'Semois',
    'Semouse', 'Senouire', 'Séoune', 'Serein', 'Serre', 'Sesserant', 'Seugne', 'Sévenne', 'Séveraisse', 'Sèves',
    'Sèvre Nantaise', 'Sevron', 'Siguer', 'Siniq', 'Sioule', 'Smagne', 'Solnan', 'Solre', 'Somme-Soude', 'Sor',
    'Sorgue', 'Sormonne', 'Sorne', 'Sornin', 'Souche', 'Souchon', 'Soudaine', 'Sou de Laroque', 'Sou de Val de Daigne',
    'Souleuvre', 'Souloise', 'Soulzon', 'Suippe', 'Sumène', 'Superbe', 'Suran', 'Surmelin', 'Tardes', 'Tardoire',
    'Tarentaine', 'Tarn', 'Tarnon', 'Tarsy', 'Tartuguié', 'Tarun', 'Taurion', 'Taute', 'Télhuet', 'Tenise', 'Tenu',
    'Ternin', 'Ternoise', 'Terrette', 'Thérain', 'Thérouanne', 'Thin', 'Thiou', 'Tholon', 'Thon', 'Thonne', 'Thoré',
    'Thouanne', 'Thouaret', 'Thouet', 'Thur', 'Tialle', 'Tille', 'Tinée', 'Torse', 'Tortonne', 'Touch', 'Tourmente',
    'Tourtoulloux', 'Touvre', 'Trévelo', 'Trézon', 'Triouzoune', 'Trois Doms', 'Tronçon', 'Trottebec', 'Truyère',
    'Ubaye', 'Ubayette', 'Udon', 'Ure', 'Vaige', 'Vair', 'Val du Breuil', 'Vallière', 'Valloirette', 'Valouse',
    'Valserine', 'Vanne', 'Varenne', 'Vaucouleurs', 'Vaudelle', 'Vauvise', 'Vauvre', 'Vaux', 'Vauxonne', 'Vèbre',
    'Vecchio', 'Vègre', 'Vence', 'Vendée', 'Véore', 'Verdon', 'Verdouble', 'Vère', 'Vernaison', 'Vert', 'Verzée',
    'Vesgre', 'Vesle', 'Vésubie', 'Veuve', 'Veyle', 'Veynon', 'Vézère', 'Vezouze', 'Vianon', 'Viaur', 'Vicdessos',
    'Vicoin', 'Vie', 'Vienne', 'Vière', 'Vimbelle', 'Vimeuse', 'Vincou', 'Vingeanne', 'Vioulou', 'Virène', 'Virenque',
    'Vis', 'Vistre', 'Voire', 'Voise', 'Volane ', 'Vologne', 'Vonne', 'Voueize', 'Vouge', 'Voulzie', 'Vouraie', 'Vrin',
    'Weiss', 'Wiseppe', 'Woigot', 'Yerre', 'Yerres', 'Yèvre', 'Yon', 'Yonne', 'Yron', 'Yvel', 'Yvette', 'Yzeron',
    'Zinsel du Nord', 'Zinsel du Sud', 'Zorn'
  ];
  rivers_length int = 773;
BEGIN
  -- avoid having names in alphabetical order with ids, so this mixes a little bit
  RETURN rivers[((id * id + id) % rivers_length)+1];
END; $$
LANGUAGE plpgsql;
