MOCK_NAMES = [
    "Nez à Nez d'Anaconda",
    "Sous les parapluies de Borneo",
    "D-- tu l'auras",
    "Funky Family",
    "Sun aux lentilles",
    "Topaz de Reackham le Rouge",
    "En rentrant de Palerme",
    "Ravage sous un océan",
    "Dansons jusqu'en 2030",
    "Dormons peu soupons bien",
    "Guerre et youpi matin",
    "I want something more",
    "Mensch ! Où sont les Hommes ?",
    "La première paix mondiale",
    "Autant tu t'en vas",
    "Vas-y",
    "Non, j'y vais pas",
    "Mais puisque je te dis qu'il faut y aller",
    "Bon d'accord",
    "Donnez-moi un bon titre",
    "En fil de falafux",
    "Pour une surprise",
    "Jm'ennuie et vous ?",
    "Le r-i-card ?",
    "Ai que bom !",
    "Swing autour de moi",
    "Ca balance pas mal dans le paradis blanc",
    "Jamais sans mon post-it",
    "Ha!"
]

MOCK_AUTHOR_NAMES = [
    "Simon Enclume",
    "Albert Mousquetaire",
    "Léa Duchamp",
    "Martine Marx",
    "Camille Forêt",
    "Robert Herbert",
    "Denis Chat",
    "Nicolas Duplot",
    "Rackham le Vert",
    "Eloise Jomenrency",
    "Jeanne Plomb",
    "Jon Steeven",
    "Gerard Stadt",
    "Usule et Franck",
    "Max et Compagnie",
    "Princesse Zorah",
    "Olive et Thomas",
    "Inconnu",
    "Les mal connus",
    "Richard Virage",
    "Jean-Michel Michel",
    "Koala",
    "Kepler Ceinture",
    "Pat le poulpe",
    "Justine Fairplay",
    "Julie Olive",
    "Olivia Del Sol",
    "Madeleine Chocolat",
    "Marine",
    "Mimi"
]

MOCK_DESCRIPTIONS = [
    "Nous pourrions bien évidemment encourager ces méditations, soutenant que nous aimons toujours à l'échelle de notre sphère le bien-être d'entendre nos amis revenir d'expériences de mondes différents ; ou de raconter nous-mêmes son bonheur d'avoir goûté à l'échange simple des choses entre les Hommes d'un troquet, de se troquer des histoires comme on se cuisine ensemble la nourriture un soir d'été, de rentrer en transe sur une mélodie à trois notes, de tenter d'expliquer ce qui est beau du laid pour des enfants jouant dans une prairie encore verte, et enfin d'avoir pu chacun écouter le battement des blés mûrs entourant des chênes tout aussi dorés de soleil.",
    "Quoi! ne faut-il donc aucun Spectacle dans une République ? Au contraire, il en faut beaucoup. C'est dans les Républiques qu'ils sont nés, c'est dans leur sein qu'on les voit briller avec un véritable air de fête. A quels peuples convient-il mieux de s'assembler souvent et de former entre eux les doux liens du plaisir et de la joie, qu'à ceux qui ont tant de raisons de s'aimer et de rester à jamais unis ? Nous avons déjà plusieurs de ces fêtes publiques ; ayons-en, davantage encore, je n'en serai que plus charmée.",
    "Mais n'adoptons point ces Spectacles exclusifs qui renferment tristement un petit nombre de gens dans un antre obscur ; qui les tiennent craintifs et immobiles dans le silence et l'inaction ; qui n'offrent aux yeux que cloisons, que pointes de fer, que soldats, qu'affligeantes images de la servitude et de l'inégalité. Non, Peuples heureux, ce ne sont pas 1à vos fêtes !",
    "C'est en plein air, c'est sous le ciel qu'il faut vous rassembler et vous livrer au doux sentiment de votre bonheur. Que vos plaisirs ne soient, efféminées ni mercenaires, que rien de ce qui sent la contrainte et l'intérêt ne les empoisonne, qu'ils soient libres et généreux comme vous ; que le soleil éclaire vos innocents Spectacles ; vous en formerez un vous-mêmes, le plus digne qu'il puisse éclairer.",
    "Mais quels seront enfin les objets de ces Spectacles ? Qu'y montrera-t-on ? Rien, si l'on veut. Avec la liberté, partout où règne l'affluence, le bien-être y règne aussi. Plantez au milieu d'une place un piquet couronnée de fleurs, rassemblez-y le Peuple, et vous aurez une fête. Faites mieux encore : donnez les spectateurs en spectacle ; rendez-les acteurs eux-mêmes ; faites que chacun se voye et s'aime dans les autres, afin que tous en soient mieux unis.",
    "Chaque peuple veut des pièces qui lui ressemblent, et toute société n'a donc que les spectacles qu'elle mérite",
    "Les tout jeunes gens, lorsqu'ils goûtent pour la première fois aux échanges d'arguments, en font un usage pervers, comme d'un jeu, s'en servant toujours pour contredire, et qu'en imitant ceux qui réfutent, eux-mêmes en réfutent d'autres, prenant plaisir, comme de jeunes chiens, à tirer et à déchiqueter par la parole quiconque se trouve près d'eux.",
    "Un baiser, mais à tout prendre, qu'est-ce ? Un serment fait d'un peu plus près, une promesse plus précise, un aveu qui veut se confirmer, Un point rose qu'on met sur l'i du verbe aimer ; C'est un secret qui prend la bouche pour oreille, Un instant d'infini qui fait un bruit d'abeille, Une communion ayant un goût de fleur, Une façon d'un peu se respirer le cœur, Et d'un peu se goûter, au bord des lèvres, l'âme !",
    "Combattant sans risque, vous devez agir sans précaution. En effet, pour vous autres hommes, les défaites ne sont que des succès de moins. Dans cette partie si inégale, notre fortune est de ne pas perdre, et votre malheur de ne pas gagner.",
    "Ainsi la personne avec qui elle avait confessé qu’elle allait goûter, avec qui elle vous avait supplié de la laisser goûter, cette personne, raison avouée par la nécessité, ce n’était pas elle, c’était une autre, c’était encore autre chose ! Autre chose, quoi ? Une autre, qui ?",
    "Vous?... Au contraire! J'ignorais la douceur féminine. Ma mère Ne m'a pas trouvé beau. Je n'ai pas eu de soeur. Plus tard, j'ai redouté l'amante à l'oeil moqueur. Je vous dois d'avoir eu, tout au moins, une amie. Grâce à vous une robe a passé dans ma vie.",
    "D'un coup d'épée, Frappé par un héros, tomber la pointe au coeur! Oui, je disais cela!... Le destin est railleur!... Et voila que je suis tué, par un laquais, d'un coup de bûche! C'est très bien. J'aurai tout manqué, même ma mort.",
    "Bel astre voyageur, hôte qui nous arrives, Des profondeurs du ciel et qu'on n'attendait pas, Où vas-tu ? Quel dessein pousse vers nous tes pas ? Toi qui vogues au large en cette mer sans rives",
    "Sur ta route, aussi loin que ton regard atteint, N'as-tu vu comme ici que douleurs et misères ? Dans ces mondes épars, dis ! avons-nous des frères ?",
    "T'ont-ils chargé pour nous de leur salut lointain ?",
    "Ah ! quand tu reviendras, peut-être de la terre, L'homme aura disparu.",
    "Du fond de ce séjour Si son œil ne doit pas contempler ton retour, Si ce globe épuisé s'est éteint solitaire, Dans l'espace infini poursuivant ton chemin, Du moins jette au passage, astre errant et rapide, Un regard de pitié sur le théâtre vide De tant de maux soufferts et du labeur humain.",
    "Le soleil me rencontre au bout de sa carrière, Couché sur l'horizon dont j'enflamme le bord ; Dans mes flancs transparents le roi de la lumière Lance en fuyant ses flèches d'or.",
    "Quand la lune, écartant son cortège d'étoiles, Jette un regard pensif sur le monde endormi, Devant son front glacé je fais courir mes voiles, Ou je les soulève à demi.",
    "On croirait voir au loin une flotte qui sombre, Quand, d'un bond furieux fendant l'air ébranlé, L'ouragan sur ma proue inaccessible et sombre S'assied comme un pilote ailé.",
    "Dans les champs de l'éther je livre des batailles ; La ruine et la mort ne sont pour moi qu'un jeu. Je me charge de grêle, et porte en mes entrailles La foudre et ses hydres de feu.",
    "Sur le sol altéré je m'épanche en ondées. La terre rit ; je tiens sa vie entre mes mains. C'est moi qui gonfle, au sein des terres fécondées, L'épi qui nourrit les humains.",
    "Où j'ai passé, soudain tout verdit, tout pullule ; Le sillon que j'enivre enfante avec ardeur. Je suis onde et je cours, je suis sève et circule, Caché dans la source ou la fleur.",
    "Un fleuve me recueille, il m'emporte, et je coule Comme une veine au cœur des continents profonds. Sur les longs pays plats ma nappe se déroule, Ou s'engouffre à travers les monts.",
    "Rien ne m'arrête plus ; dans mon élan rapide J'obéis au courant, par le désir poussé, Et je vole à mon but comme un grand trait liquide Qu'un bras invisible a lancé.",
    "Océan, ô mon père ! Ouvre ton sein, j'arrive ! Tes flots tumultueux m'ont déjà répondu ; Ils accourent ; mon onde a reculé, craintive, Devant leur accueil éperdu.",
    "En ton lit mugissant ton amour nous rassemble. Autour des noirs écueils ou sur le sable fin Nous allons, confondus, recommencer ensemble Nos fureurs et nos jeux sans fin."
    "Mais le soleil, baissant vers toi son œil splendide, M'a découvert bientôt dans tes gouffres amers. Son rayon tout puissant baise mon front limpide : J'ai repris le chemin des airs !",
    "Ainsi, jamais d'arrêt. L'immortelle matière Un seul instant encor n'a pu se reposer. La Nature ne fait, patiente ouvrière, Que dissoudre et recomposer.",
    "Tout se métamorphose entre ses mains actives ; Partout le mouvement incessant et divers, Dans le cercle éternel des formes fugitives, Agitant l'immense univers."
]
