SELECT anon_1."publicationDatetime", anon_1."bookingAllowedDatetime", anon_1.ean, anon_1."jsonData", anon_1."lastProviderId", anon_1.name, anon_1."productId", anon_1."subcategoryId", anon_1.url, anon_1."offererAddressId", anon_1.id, anon_1.validation, anon_1."venueId", anon_1."dateCreated", provider_1."localClass", provider_1.id AS id_1, product_mediation_1."dateModifiedAtLastProvider", product_mediation_1."imageType", product_mediation_1."lastProviderId" AS "lastProviderId_1", product_mediation_1."productId" AS "productId_1", product_mediation_1.uuid, product_mediation_1.id AS id_2, product_1.id AS id_3, product_1."thumbCount", offerer_1.name AS name_1, offerer_1.id AS id_4, address_1."banId", address_1."inseeCode", address_1.street, address_1."postalCode", address_1.city, address_1.latitude, address_1.longitude, address_1."departmentCode", address_1.timezone, address_1."isManualEdition", address_1.id AS id_5, EXISTS (SELECT 1 
FROM venue AS venue_1 
WHERE venue_1."offererAddressId" = offerer_address_1.id) AS anon_2, offerer_address_1.label, offerer_address_1."addressId", offerer_address_1."offererId", offerer_address_1.type, offerer_address_1."venueId" AS "venueId_1", offerer_address_1.id AS id_6, venue_2.name AS name_2, venue_2."departementCode", venue_2."publicName", venue_2."isVirtual", venue_2.id AS id_7, address_2."banId" AS "banId_1", address_2."inseeCode" AS "inseeCode_1", address_2.street AS street_1, address_2."postalCode" AS "postalCode_1", address_2.city AS city_1, address_2.latitude AS latitude_1, address_2.longitude AS longitude_1, address_2."departmentCode" AS "departmentCode_1", address_2.timezone AS timezone_1, address_2."isManualEdition" AS "isManualEdition_1", address_2.id AS id_8, EXISTS (SELECT 1 
FROM venue AS venue_3 
WHERE venue_3."offererAddressId" = offerer_address_2.id) AS anon_3, offerer_address_2.label AS label_1, offerer_address_2."addressId" AS "addressId_1", offerer_address_2."offererId" AS "offererId_1", offerer_address_2.type AS type_1, offerer_address_2."venueId" AS "venueId_2", offerer_address_2.id AS id_9, headline_offer_1."offerId", headline_offer_1."venueId" AS "venueId_3", headline_offer_1.timespan, headline_offer_1.id AS id_10, mediation_1.credit, mediation_1."dateCreated" AS "dateCreated_1", mediation_1.id AS id_11, mediation_1."thumbCount" AS "thumbCount_1", mediation_1."isActive", stock_1."beginningDatetime", stock_1."bookingLimitDatetime", stock_1."dnBookedQuantity", stock_1.quantity, stock_1.id AS id_12, stock_1."isSoftDeleted" 
FROM (SELECT offer."publicationDatetime" AS "publicationDatetime", offer."bookingAllowedDatetime" AS "bookingAllowedDatetime", offer.ean AS ean, offer."jsonData" AS "jsonData", offer."lastProviderId" AS "lastProviderId", offer.name AS name, offer."productId" AS "productId", offer."subcategoryId" AS "subcategoryId", offer.url AS url, offer."offererAddressId" AS "offererAddressId", offer.id AS id, offer.validation AS validation, offer."venueId" AS "venueId", offer."dateCreated" AS "dateCreated" 
FROM offer JOIN venue ON venue.id = offer."venueId" JOIN offerer ON offerer.id = venue."managingOffererId" JOIN user_offerer ON offerer.id = user_offerer."offererId" 
WHERE user_offerer."userId" = 1 AND user_offerer."validationStatus" = 'VALIDATED' AND venue."managingOffererId" = 1 ORDER BY offer."dateCreated" DESC 
 LIMIT 10 OFFSET 190) AS anon_1 LEFT OUTER JOIN provider AS provider_1 ON provider_1.id = anon_1."lastProviderId" LEFT OUTER JOIN product AS product_1 ON product_1.id = anon_1."productId" LEFT OUTER JOIN product_mediation AS product_mediation_1 ON product_1.id = product_mediation_1."productId" LEFT OUTER JOIN venue AS venue_2 ON venue_2.id = anon_1."venueId" LEFT OUTER JOIN offerer AS offerer_1 ON offerer_1.id = venue_2."managingOffererId" LEFT OUTER JOIN offerer_address AS offerer_address_1 ON offerer_address_1.id = venue_2."offererAddressId" LEFT OUTER JOIN address AS address_1 ON address_1.id = offerer_address_1."addressId" LEFT OUTER JOIN offerer_address AS offerer_address_2 ON offerer_address_2.id = anon_1."offererAddressId" LEFT OUTER JOIN address AS address_2 ON address_2.id = offerer_address_2."addressId" LEFT OUTER JOIN headline_offer AS headline_offer_1 ON anon_1.id = headline_offer_1."offerId" LEFT OUTER JOIN mediation AS mediation_1 ON anon_1.id = mediation_1."offerId" LEFT OUTER JOIN stock AS stock_1 ON anon_1.id = stock_1."offerId" ORDER BY anon_1."dateCreated" DESC
