name: "Run actionlint"

on:
    push:
        branches:
            - actionlint

permissions: write-all

jobs:
  actionlint:
    runs-on: ubuntu-24.04
    steps:
      - name: setup
        uses: actions/checkout@v6
    
      - name: test
        run: "echo ${{ runner.workspace }}"

      - uses: pass-culture/common-workflows/actions/actionlint-check@f4db7db202ff3cddc97fcbf08c3821ebc78b10fb

