name: 0 [CD] Create hotfix release

run-name: "Create a hotfix release from ${{ github.ref }}"

on: workflow_dispatch

permissions: write-all

jobs:
  check-github-ref-is-maint-branch:
    name: Check Github ref is a maintenance branch
    runs-on: ubuntu-22.04
    steps:
      - env:
          REF: ${{ github.ref }}
        run: |
          if ! [[ "$REF" =~ ^refs/heads/maint/v.*$ ]]; then
            echo "This workflow can only be triggered from a maintenance branch (starting with 'maint/v')"
            exit 1
          fi

  compute-hotfix-tag-number:
    # Compute the next hotfix version
    # Example: given branch maint/v200 and existing tags v200.0.0, v200.0.1 then output == 200.0.2
    name: Compute hotfix tag number
    needs: check-github-ref-is-maint-branch
    runs-on: ubuntu-22.04
    outputs:
      hotfix-tag-number: ${{ steps.compute-hotfix-tag-number.outputs.hotfix-tag-number }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0 # Fetch all history to get all tags
      - name: "Find hotfix tag number"
        id: "compute-hotfix-tag-number"
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          MAJOR_NUMBER="${GITHUB_REF//refs\/heads\/maint\/v/}"
          CURRENT_PATCH_NUMBER="$(git tag -l "v${MAJOR_NUMBER}.0.*" | sort -V | tail -n 1 | cut -d. -f3)"
          NEXT_PATCH_NUMBER="$((CURRENT_PATCH_NUMBER + 1))"
          echo "hotfix-tag-number=${MAJOR_NUMBER}.0.${NEXT_PATCH_NUMBER}" | tee -a "$GITHUB_OUTPUT"

  create-release:
    name: Create hotfix release
    needs: compute-hotfix-tag-number
    uses: ./.github/workflows/cd_sub_create_release.yml
    with:
      tag-number: ${{ needs.compute-hotfix-tag-number.outputs.hotfix-tag-number }}
      ref: ${{ github.ref }}
      base-ref-is-a-branch: true
    secrets: inherit

  notify-success:
    name: "Send workflow success notification"
    needs: [create-release, compute-hotfix-tag-number]
    if: always() && !failure() && !cancelled()
    uses: ./.github/workflows/slack_post_message_workflow.yml
    with:
      channel: ${{vars.SLACK_ALERTES_DEPLOIEMENT_CHANNEL_ID}}
      message: ":github-success: Release `v${{ needs.compute-hotfix-tag-number.outputs.hotfix-tag-number }}` créée avec succès. <https://github.com/pass-culture/pass-culture-main/actions/workflows/cd_deploy_staging.yml|Déployer> :rocket:"
    secrets: inherit

  notify-failure:
    name: "Send workflow failure notification"
    needs: [create-release, compute-hotfix-tag-number]
    if: always() && (failure() || cancelled())
    uses: ./.github/workflows/slack_post_message_workflow.yml
    with:
      channel: ${{vars.SLACK_ALERTES_DEPLOIEMENT_CHANNEL_ID}}
      message: ":github-failure: La création de la release `v${{ needs.compute-hotfix-tag-number.outputs.hotfix-tag-number }}` a échoué. <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Voir le détail>"
    secrets: inherit
