name: 0 [CD] Create major release

on:
  schedule:
    # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#onschedule
    # “At 08:27 on every day-of-week from Monday through Friday.”
    - cron: '27 8 * * 1-5'
      timezone: "Europe/Paris"
  workflow_dispatch:

permissions: write-all

jobs:
  check-major-release-creation-is-allowed: # TODO (tcoudray-pass, 15/04/2026) Refacto when we get rid of the old workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - id: check-date-exclusion
        run: ./.github/workflows/scripts/check-schedule-exclusion.sh >> "$GITHUB_OUTPUT"
      - name: Check is allowed
        env:
          date_is_excluded: steps.check-date-exclusion.outputs.schedule_exclusion == 'true'
          is_dispatch: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          if [[ $is_dispatch ]] || [[ ! $date_is_excluded ]]; then
            exit 0
          fi
          echo "Today is excluded – ${{ steps.check-date-exclusion.outputs.reason }}"
          exit 1

  compute-major-version-variables:
    needs: check-major-release-creation-is-allowed
    runs-on: ubuntu-latest
    outputs:
      release-number: ${{ steps.version.outputs.release-number }}
      sha: ${{ steps.rc_commit.outputs.sha }}
      latest-tag: ${{ steps.version.outputs.latest-tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with: 
          fetch-tags: true
          persist-credentials: false

      - name: Get release-number major version
        id: version
        run: |
          # Get all with format vX.X.X, sort them and get the last one
          latest_tag="$(git tag -l "v[0-9]*.[0-9]*.[0-9]*" | sort -V | tail -n 1)"
          echo "latest-tag=$latest_tag" >> "$GITHUB_OUTPUT"

          # Extract major version
          major="$(echo "$latest_tag" | sed -E 's/^v([0-9]+)\..*/\1/')"

          release_number="$((major + 1))"
          echo "release-number=$release_number" >> "$GITHUB_OUTPUT"

      - name: Get commit hash from RC tag
        id: rc_commit
        run: |
          rc_tag="$(git tag -l "rc" | tail -n 1)"
          if [ -z "$rc_tag" ]; then
            echo "Pas de tag RC trouvé"
            exit 1
          fi
          commit_hash="$(git rev-list -n 1 "$rc_tag")"
          echo "sha=$commit_hash" >> "$GITHUB_OUTPUT"

  notify-workflow-start:
    needs: compute-major-version-variables
    name: Notify major release creation has started
    uses: ./.github/workflows/slack_post_message_workflow.yml
    with:
      channel: ${{vars.SLACK_ALERTES_DEPLOIEMENT_CHANNEL_ID}}
      message: ":github-pending: La <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|création de la release>  `v${{ needs.compute-major-version-variables.outputs.release-number }}` est lancée"
    secrets: inherit

  create-release:
    name: Create major release
    needs: compute-major-version-variables
    uses: ./.github/workflows/cd_sub_create_release.yml
    with:
      tag-number: ${{ needs.compute-major-version-variables.outputs.release-number }}.0.0
      ref: ${{ needs.compute-major-version-variables.outputs.sha }}
      base-ref-is-a-branch: false
    secrets: inherit

  edit-maintenance-branches:
    name: Edit maintenance branches
    needs: [create-release, compute-major-version-variables]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout new tag
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: v${{ needs.compute-major-version-variables.outputs.release-number }}.0.0
          persist-credentials: true
      - name: Create new maintenance branch (v${{ needs.compute-major-version-variables.outputs.release-number }}.0.0)
        env:
          NEW_MAINTENANCE_BRANCH: maint/v${{ needs.compute-major-version-variables.outputs.release-number }}
        run: |
          git checkout -b "$NEW_MAINTENANCE_BRANCH"
          git push origin "$NEW_MAINTENANCE_BRANCH"
      - name: Delete old maintenance branch
        continue-on-error: true
        run: |
          release_number="${{ needs.compute-major-version-variables.outputs.release-number }}"
          old_branch_number="$((release_number-2))"
          git push origin --delete "maint/v$old_branch_number"

  notify-success:
    name: "Send workflow success notification"
    needs:
      - notify-workflow-start
      - compute-major-version-variables
      - edit-maintenance-branches
    if: always() && !failure() && !cancelled()
    uses: ./.github/workflows/slack_update_message_workflow.yml
    with:
      channel: ${{vars.SLACK_ALERTES_DEPLOIEMENT_CHANNEL_ID}}
      message-ts: ${{ needs.notify-workflow-start.outputs.message-ts }}
      message: ":github-success: La <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|release> `v${{ needs.compute-major-version-variables.outputs.release-number }}` a été créé avec succès"
    secrets: inherit

  notify-failure:
    name: "Send workflow failure notification"
    needs:
      - notify-workflow-start
      - compute-major-version-variables
      - edit-maintenance-branches
    if: always() && (failure() || cancelled())
    uses: ./.github/workflows/slack_update_message_workflow.yml
    with:
      channel: ${{vars.SLACK_ALERTES_DEPLOIEMENT_CHANNEL_ID}}
      message-ts: ${{ needs.notify-workflow-start.outputs.message-ts }}
      message: ":github-failure: La création de la <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|release> `v${{ needs.compute-major-version-variables.outputs.release-number }}` a échoué cc <!subteam^${{vars.SLACK_SHERIF_BACK_ID}}> <!subteam^${{vars.SLACK_SHERIF_INFRA_ID}}>"
    secrets: inherit
