name: 3 [CD] Deploy app
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      app_version:
        type: string
        required: true
      cluster_scope:
        type: string
        required: false
        default: metier
      cluster_environment:
        type: string
        required: false
        default: ehp
      workload_identity_provider_secret_name:
        type: string
        required: true
      apply_algolia_config:
        type: boolean
        required: false
        default: false
      deploy_api:
        type: boolean
        required: false
        default: false
      deploy_pro:
        type: boolean
        required: false
        default: false
      doc-api-entrypoint:
        type: string
        required: false
        default: "api/documentation"
      # Variables used for the new infra
      environment_short_name: # Required for deploying to new infra
        type: string
        required: false
      is_new_infra:
        type: boolean
        required: false
        default: false
      location:
        type: string
        required: false
        default: europe-west9
      workflow_cluster_name:
        type: string
        required: false
      workflow_project_id:
        type: string
        required: false
      app_project_id:
        type: string
        required: false
      app_cluster_name:
        type: string
        required: false
      continue_on_error:
        type: boolean
        required: false
        default: false
    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER:
        required: true
      GCP_EHP_SERVICE_ACCOUNT:
        required: true
      PASSCULTURE_GITHUB_ACTION_APP_ID:
        required: true
        description: "Github Application ID to use to clone other repos"
      PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY:
        required: true
        description: "Private key for the Github application used to clone other repos"

jobs:
  deploy-api:
    name: "Deploy api"
    concurrency:
      group: deploy-pcapi-${{ inputs.environment }}-${{ inputs.is_new_infra }}
      cancel-in-progress: false
    runs-on: ubuntu-22.04
    environment:
      name: pcapi-${{ inputs.environment_short_name }}
      deployment: false
    permissions:
      id-token: write
      contents: read
    continue-on-error: ${{ inputs.continue_on_error }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Argo Workflows CLI 
        uses: pass-culture/common-workflows/actions/setup-argo@setup-argo/v1.0.0

      - name: Install passdirector
        uses: ./.github/actions/setup-passdirector
        with:
          version: v0.4.0
          github_app_id: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_ID}}
          github_app_private_key: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY}}

      - name: "Authentification to Google"
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          service_account: ${{ vars.PCAPI_CD_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PRD }}

      - name: Authenticate to GKE cluster
        uses: google-github-actions/get-gke-credentials@3da1e46a907576cefaa90c484278bb5b259dd395 # v3.0.0
        with:
          cluster_name: ${{ inputs.workflow_cluster_name }}
          project_id: ${{ inputs.workflow_project_id }}
          location: ${{ inputs.location }}
          use_dns_based_endpoint: true

      - name: "Deploy pcapi"
        shell: bash
        env:
          PCAPI_ENVIRONMENT_SHORT_NAME: ${{ inputs.environment_short_name }}
          PCAPI_VERSION: ${{ inputs.app_version }}
        run: |
          passdirector pcapi deploy -e "${PCAPI_ENVIRONMENT_SHORT_NAME}" --app-version "${PCAPI_VERSION}"

  deploy-api-doc-on-firebase:
    name: "Deploy api doc on firebase"
    uses: ./.github/workflows/cd_sub_deploy_api_doc.yml
    if: ${{ inputs.deploy_api && (inputs.environment != 'opsv2' && inputs.environment != 'ops' && inputs.environment != 'integration') }}
    permissions:
      id-token: write
      contents: read
    with:
      environment: ${{ inputs.environment }}
    needs: deploy-api

  deploy-pro-on-firebase-testing:
    name: "Deploy pro on testing live channel"
    concurrency:
      group: deploy-pro-${{ inputs.environment }}
      cancel-in-progress: false
    needs: deploy-api
    if: |
      always() &&
      inputs.environment == 'testing' &&
      inputs.deploy_pro == true
    uses: ./.github/workflows/cd_sub_deploy_front_pro.yml
    with:
      ENV: testing
      CHANNEL: "live"
      REF: ${{ github.ref }}
      CACHE_BUCKET_NAME: "passculture-infra-prod-github-runner-cache"
      continue_on_error: ${{ inputs.continue_on_error }}
      version: "${{ github.sha }}"

  publish-pro-to-live-on-firebase:
    name: "Deploy pro"
    concurrency:
      group: deploy-pro-${{ inputs.environment }}
      cancel-in-progress: false
    needs: deploy-api
    if: |
      always() &&
      (needs.deploy-api.result == 'success' || needs.deploy-api.result == 'skipped') &&
      ( inputs.environment != 'testing' ) &&
      inputs.deploy_pro == true
    uses: ./.github/workflows/dev_on_workflow_configure_live_channel_pro_generic.yml
    with:
      environment: ${{ inputs.environment }}
      app_version: ${{ inputs.app_version }}
      continue_on_error: ${{ inputs.continue_on_error }}

  deploys-outcome:
    needs:
      - deploy-api
      - deploy-api-doc-on-firebase
      - deploy-pro-on-firebase-testing
      - publish-pro-to-live-on-firebase
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      deployment: true # Github creates a deployment for this environment only if all deploys succeed (pcapi, pro, doc)
    if: always()
    env:
      ENV: ${{ inputs.environment }}
    continue-on-error: ${{ inputs.continue_on_error }}
    steps:
      - name: Check deploy jobs status
        run: |
          if [ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" = "true" ]; then
            echo "Not all deploy jobs have succeeded :("
            exit 1
          fi
      - name: Deployments Success
        run: echo "All deploy jobs for $ENV are successful !"
