name: 3 [CD] Deploy maintenance site

on:
  workflow_call:

jobs:
  deploy:
    name: "Deploy maintenance site to bucket"
    runs-on: ubuntu-22.04
    environment:
      name: site-maintenance-ci-prd
      deployment: false
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PRD }}
          service_account: ${{ vars.MAINTENANCE_SITE_DEPLOY_SERVICE_ACCOUNT }}
      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1
      - name: "Push web site files to bucket"
        working-directory: maintenance-site
        run: gsutil rsync  -x '.*/\..*|^\..*' -r . gs://passculture-metier-prod-production-maintenance
