name: "1 [CI] PR checks"

on:
  pull_request:
    branches-ignore:
      - docs

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions: write-all

env:
  docker_registry: "europe-west1-docker.pkg.dev/passculture-infra-prod/pass-culture-artifact-registry"

jobs:
  labeler:
    name: Add labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - id: label-pr
        uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          sync-labels: true

      - run: |
          echo "These labels are added to the PR: ${{ steps.label-pr.outputs.all-labels }}"

  compute-changes:
    name: Compute changes
    runs-on: ubuntu-latest
    outputs:
      api-changed: ${{ steps.check-api-changes.outputs.any_modified }}
      api-documentation-changed: ${{ steps.check-api-documentation-changes.outputs.any_modified }}
      api-script-test-changed: ${{ steps.check-api-script-test-changes.outputs.any_modified }}
      pro-changed: ${{ steps.check-pro-changes.outputs.any_modified }}
      dependencies-changed: ${{ steps.check-dependencies-changes.outputs.any_modified }}
      github-changed: ${{ steps.check-github-changes.outputs.any_modified }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with: { fetch-tags: false }
      - name: "Check api folder changes"
        id: check-api-changes
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: |
            api/**
            !api/documentation/**
            !api/src/pcapi/scripts/**/main.py
            !api/src/pcapi/scripts/**/test_script.py
            !api/tests/scripts/**/test_main.py
            !api/src/pcapi/scripts/**/main.sql
      - name: "Check api documentation folder changes"
        id: check-api-documentation-changes
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: api/documentation/**
      - name: "Check api script test folder changes"
        id: check-api-script-test-changes
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: |
            api/tests/scripts/**/test_main.py
      - name: "Check pro folder changes"
        id: check-pro-changes
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: |
            .github/workflows/dev_on_pull_request_workflow.yml
            .github/workflows/test_front_pro.yml
            .github/workflows/test_e2e.yml
            pro/**
      - name: "Check changes in dependencies (frontend + backend)"
        id: check-dependencies-changes
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: |
            api/poetry.lock
            pro/yarn.lock
      - name: "Check changes in .github"
        id: check-github-changes
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: |
            .github/**
      - name: "Publish Summary"
        run: |
          {
            echo "### :rocket: Init Job summary"
            echo "| Results                              | Value |"
            echo "| ------------------------------------ | ----- |"
            echo "| commit sha                           | ${{ github.sha }} |"
            echo "| [api] content changed                | ${{ steps.check-api-documentation-changes.outputs.any_modified }} |"
            echo "| [api-documentation] content changed  | ${{ steps.check-api-documentation-changes.outputs.any_modified }} |"
            echo "| [pro] content changed                | ${{ steps.check-pro-changes.outputs.any_modified }} |"
            echo "| [dependencies] content changed       | ${{ steps.check-dependencies-changes.outputs.any_modified }} |"
            echo "| [github] content changed             | ${{ steps.check-github-changes.outputs.any_modified }} |"
          } >> "$GITHUB_STEP_SUMMARY"

  lint-github-actions:
    name: Lint GitHub actions & worflows
    needs: pr-changes
    if: needs.pr-changes.outputs.github-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with: { fetch-tags: false }
      - name: "Run actionlint"
        uses: pass-culture/common-workflows/actions/actionlint-check@b2eaf34df9945c76e68cffc6e4bf27037f6ea21a # v0.2

  build-backend-image:
    name: Build backend image
    needs: compute-changes
    if: |
      needs.compute-changes.outputs.api-changed == 'true' ||
      needs.compute-changes.outputs.api-script-test-changed == 'true' ||
      needs.compute-changes.outputs.pro-changed == 'true' ||
      needs.compute-changes.outputs.github-changed == 'true'
    uses: ./.github/workflows/dev_on_workflow_build_docker_image.yml
    with:
      image: pcapi-tests
      tag: ${{ github.sha }}

  run-mypy-cop:
    name: "MyPy cop"
    needs: compute-changes
    if: |
      needs.compute-changes.outputs.api-changed == 'true' ||
      needs.compute-changes.outputs.github-changed == 'true'
    uses: ./.github/workflows/dev_on_workflow_mypy_cop.yml

  check-api-client-update:
    name: Front API Client
    needs: [compute-changes, build-backend-image]
    uses: ./.github/workflows/test_api_client_update.yml
    concurrency:
      group: check-api-client-update-${{ github.ref }}
      cancel-in-progress: true
    with:
      PCAPI_DOCKER_TAG: ${{ github.sha }}
      TRIGGER_ONLY_ON_API_CHANGE: true
      TRIGGER_ONLY_ON_DEPENDENCY_CHANGE: true
      CACHE_BUCKET_NAME: "passculture-infra-prod-github-runner-cache"
      api-changed: ${{ needs.compute-changes.outputs.api-changed }}
      dependencies-changed: ${{ needs.compute-changes.outputs.dependencies-changed }}
    secrets: inherit

  test-backend:
    name: Backend
    needs: [compute-changes, build-backend-image]
    if: |
      needs.compute-changes.outputs.api-changed == 'true' ||
      needs.compute-changes.outputs.github-changed == 'true'
    uses: ./.github/workflows/test_backend.yml
    with:
      tag: ${{ github.sha }}
    secrets: inherit

  test-api-script:
    name: "Tests api scripts"
    needs: [compute-changes, build-backend-image]
    if: |
      needs.compute-changes.outputs.api-script-test-changed == 'true'
    uses: ./.github/workflows/test_api_scripts_workflow.yml
    with:
      tag: ${{ github.sha }}
    secrets: inherit

  test-api-documentation:
    name: Public API documentation
    needs: compute-changes
    if: |
      needs.compute-changes.outputs.api-documentation-changed == 'true' ||
      needs.compute-changes.outputs.github-changed == 'true'
    uses: ./.github/workflows/test_api_documentation.yml
    secrets: inherit

  test-pro:
    name: Front Pro
    needs: compute-changes
    if: |
      needs.compute-changes.outputs.pro-changed == 'true' ||
      needs.compute-changes.outputs.github-changed == 'true'
    uses: ./.github/workflows/test_front_pro.yml
    with:
      CACHE_BUCKET_NAME: "passculture-infra-prod-github-runner-cache"
    secrets: inherit

  test-pro-e2e:
    name: E2E
    needs: [compute-changes, build-backend-image]
    uses: ./.github/workflows/test_e2e.yml
    if: always() &&
      !cancelled() &&
      needs.compute-changes.outputs.api-changed == 'true' ||
      needs.compute-changes.outputs.pro-changed == 'true' ||
      needs.compute-changes.outputs.github-changed == 'true'
    with:
      ENV: "development"
      tag: ${{ needs.build-backend-image.result == 'skipped' && 'latest' || github.sha }}
      CACHE_BUCKET_NAME: "passculture-infra-prod-github-runner-cache"
    secrets: inherit

  dependabot-auto-merge:
    name: Dependabot
    needs: [test-pro, test-pro-e2e, test-api-documentation]
    if: |
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      always() &&
      !cancelled() &&
      !failure()
    uses: ./.github/workflows/dev_on_workflow_dependabot_auto_merge.yml
    secrets: inherit
