name: "1 [CI] PR checks"

on:
  pull_request:
    branches-ignore:
      - docs

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions: write-all

jobs:
  add-labels:
    name: Add labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - id: label-pr
        uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with: { sync-labels: true }

  compute-changes:
    name: Compute changes
    uses: ./.github/workflows/ci_compute_changes.yml

  test-changes:
    name: Test changes
    needs: compute-changes
    uses: ./.github/workflows/ci_test_changes.yml
    secrets: inherit
    with:
      api-changed: ${{ needs.compute-changes.outputs.api-changed == 'true' }}
      api-documentation-changed: ${{ needs.compute-changes.outputs.api-documentation-changed == 'true' }}
      pro-changed: ${{ needs.compute-changes.outputs.pro-changed == 'true' }}
      github-changed: ${{ needs.compute-changes.outputs.github-changed == 'true' }}

  run-mypy-cop:
    name: MyPy cop
    needs: compute-changes
    if: needs.compute-changes.outputs.api-changed == 'true' || needs.compute-changes.outputs.github-changed == 'true'
    uses: ./.github/workflows/dev_on_workflow_mypy_cop.yml

  dependabot-auto-merge:
    name: Dependabot
    needs: test-changes
    if: |
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      always() &&
      !cancelled() &&
      !failure()
    uses: ./.github/workflows/ci_dependabot_auto_merge.yml
    secrets: inherit
