name: 1 [CI] PR checks

on:
  pull_request:
    branches-ignore:
      - docs

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions: write-all

jobs:
  add-labels:
    name: Add labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - id: label-pr
        uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
        with: { sync-labels: true }

  compute-changes:
    name: Compute changes
    uses: ./.github/workflows/ci_sub_compute_changes.yml

  test-changes:
    name: Test changes
    needs: compute-changes
    uses: ./.github/workflows/ci_sub_test_changes.yml
    with:
      api-changed: ${{ needs.compute-changes.outputs.api-changed == 'true' }}
      api-documentation-changed: ${{ needs.compute-changes.outputs.api-documentation-changed == 'true' }}
      pro-changed: ${{ needs.compute-changes.outputs.pro-changed == 'true' }}
      github-changed: ${{ needs.compute-changes.outputs.github-changed == 'true' }}

  run-mypy-cop:
    name: MyPy cop
    needs: compute-changes
    if: needs.compute-changes.outputs.api-changed == 'true' || needs.compute-changes.outputs.github-changed == 'true'
    uses: ./.github/workflows/ci_sub_mypy_cop.yml

  dependabot-auto-merge:
    name: Dependabot
    needs: test-changes
    if: |
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      always() &&
      !cancelled() &&
      !failure()
    uses: ./.github/workflows/ci_sub_dependabot_auto_merge.yml
    secrets: inherit
  
  semgrep_scan:
    name: Semgrep scan
    runs-on: ubuntu-22.04
    container:
      image: semgrep/semgrep@sha256:a3d49dc967b8534a6a76628e50c51cbfe33eb7195dc2feab1fdc0f100852c8ef # v1.156.0
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Perform Semgrep Analysis
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
        run: |
          semgrep scan --config auto --baseline-commit "$BASE_SHA" --error --exclude-rule=python.django.security.django-no-csrf-token.django-no-csrf-token
