name: 1 [CI] Push on master checks

on:
  push: { branches: master }

permissions: write-all

jobs:
  compute-changes:
    name: Compute changes
    uses: ./.github/workflows/ci_sub_compute_changes.yml

  test-changes:
    name: Test changes
    needs: compute-changes
    uses: ./.github/workflows/ci_sub_test_changes.yml
    with:
      api-changed: ${{ needs.compute-changes.outputs.api-changed == 'true' }}
      api-documentation-changed: ${{ needs.compute-changes.outputs.api-documentation-changed == 'true' }}
      pro-changed: ${{ needs.compute-changes.outputs.pro-changed == 'true' }}
      github-changed: ${{ needs.compute-changes.outputs.github-changed == 'true' }}

  notify-failed-test:
    name: Send failed test notification on Slack
    needs: test-changes
    if: always() && needs.test-changes.outputs.failed-tests-matrix != '[]'
    strategy:
      matrix:
        failed-test: ${{ fromJson(needs.test-changes.outputs.failed-tests-matrix) }}
    uses: ./.github/workflows/slack_post_message_workflow.yml
    with:
      message: ":github-failure: Les tests <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|${{matrix.failed-test}}> ont échoué sur `master`"
    secrets: inherit

  deploy-storybook:
    name: "Deploy Storybook"
    needs: [compute-changes, test-changes]
    if: ${{ always() && needs.compute-changes.outputs.pro-changed == 'true' }}
    uses: ./.github/workflows/ci_sub_deploy_storybook.yml

  deploy-maintenance-site:
    name: "Deploy maintenance site"
    needs: [compute-changes, test-changes]
    if: ${{ always() && needs.compute-changes.outputs.maintenance-site-changed == 'true' }}
    uses: ./.github/workflows/cd_sub_deploy_maintenance_site.yml
    secrets: inherit

  ping-data-team-on-slack:
    name: "Ping data team on slack"
    needs: [compute-changes, test-changes]
    if: ${{ always() && needs.compute-changes.outputs.alembic-changed == 'true' }}
    uses: ./.github/workflows/ci_sub_ping_data_team.yml
    secrets:
      PASSCULTURE_GITHUB_ACTION_APP_ID: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_ID }}
      PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  tag-rc:
    name: Push rc tag
    runs-on: ubuntu-latest
    needs: test-changes
    if: ${{ always() && success() }}
    env:
      GIT_CONFIG_EMAIL: ${{ vars.GH_ACTIONS_BOT_EMAIL }}
      GIT_CONFIG_NAME: ${{ github.actor }}
    steps:
      - name: Checkout ref
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure git author
        run: |
          git config --global user.email "$GIT_CONFIG_EMAIL"
          git config --global user.name "$GIT_CONFIG_NAME"

      - name: Push rc tag
        run: |
          git tag -f rc
          git push origin rc --force
