name: 0 [CD] Deploy Preview Environment v2

on:
  push:
  workflow_dispatch:

jobs:
  deploy-preview-environment:
    name: Deploy Preview Environment API
    runs-on: ubuntu-22.04
    environment:
      name: pcapi-preview
      deployment: true
    permissions:
      id-token: write
      contents: read
    # continue-on-error: ${{ inputs.continue_on_error }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Argo Workflows CLI
        uses: pass-culture/common-workflows/actions/setup-argo@setup-argo/v1.0.0

      - name: Install passdirector
        uses: ./.github/actions/setup-passdirector
        with:
          version: v0.4.1
          github_app_id: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_ID}}
          github_app_private_key: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY}}

      - name: Authentification to Google
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          service_account: ${{ vars.PCAPI_PREVIEW_CD_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PRD }}

      - name: Authenticate to GKE cluster
        uses: google-github-actions/get-gke-credentials@3da1e46a907576cefaa90c484278bb5b259dd395 # v3.0.0
        with:
          cluster_name: ${{ vars.K8S_CLUSTER_NAME }}
          project_id: ${{ vars.PROJECT_ID }}
          location: ${{ vars.LOCATION }}
          use_dns_based_endpoint: true

      - name: Hello World
        shell: bash
        env:
          NAMESPACE: ${{ vars.K8S_NAMESPACE }}
          WORKFLOW_TEMPLATE: ${{ vars.WORKFLOW_TEMPLATE_PROVISIONER }}
          PULL_REQUEST_ID: 1234567890
          PCAPI_IMAGE_TAG: b28a52a0a3d875d45107
        run: |
          passdirector workflows submit --namespace "${NAMESPACE}" --template "${WORKFLOW_TEMPLATE}" --parameter pullRequestId="${PULL_REQUEST_ID}" --parameter pcapiImageTag="${PCAPI_IMAGE_TAG}"
