name: 0 [CD] Deploy Preview Environment v2

on:
  push:
  workflow_dispatch:

jobs:
  hello-world:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, World!"
