name: 0 [CI] Deploy Storybook preview

on:
  workflow_dispatch:
    inputs:
      EXPIRES:
        type: string
        default: "2d"
      firebase_cli_version:
        type: string
        required: false
        default: 15.18.0

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy-storybook:
    name: "Build and deploy Storybook"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout 🛎️"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install passdirector
        uses: pass-culture/common-workflows/actions/setup-passdirector@b470d76b19d7f3ebcda367f5e17484228021d388 # v1.0.0
        with:
          version: v0.7.2
          github_app_id: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_ID}}
          github_app_private_key: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY}}

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 11.11.0

      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: pnpm
          node-version-file: "pro/package.json"
          cache-dependency-path: "pro/pnpm-lock.yaml"

      - uses: pass-culture/common-workflows/actions/setup-safe-chain@aeb09c2a8b4dde6291cd1f8b986c1fe3f3c0655c

      - uses: pass-culture/common-workflows/actions/setup-firebase-tools@IC-1390-create-setup-firebase-tools-action

      - name: "OpenID Connect Authentication"
        id: "openid-auth"
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          service_account: ${{ vars.PRO_STORYBOOK_CI_SERVIE_ACCOUNT }}
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PRD }}

      - name: "Install dependencies"
        working-directory: pro
        # we cannot use an action like nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2 along with `working-directory`
        run: pnpm ci

      - name: "Build Storybook 🔧"
        working-directory: pro
        run: pnpm build-storybook

      - name: Deploy Storybook preview
        working-directory: pro
        id: deploy
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          URL=$(passdirector firebase deploy-preview --project-id "pc-pro-testing" --target "pc-pro-storybook" --channel "${REF_NAME}")
          echo "preview_url=$URL" | tee -a "$GITHUB_OUTPUT"

      - name: "Publish Summary"
        run: |
          {
            echo "### :rocket: Deploy PRO Storybook Summary"
            echo "| Results                              | Value |"
            echo "| ------------------------------------ | ----- |"
            echo "| [pro] preview url                    |  ${{ steps.deploy.outputs.preview_url }} |"
          } >> "$GITHUB_STEP_SUMMARY"
