name: 2 [CI] Ping data team on significant DB changes

on:
  pull_request: { types: closed }

permissions: write-all

jobs:
  check-significant-changes:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.changes }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: |
            api/src/pcapi/alembic/versions/**

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0

      - name: Detect DB changes
        id: changes
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          changes="$(python api/bin/alembic_detect_significant_changes.py ${{ steps.changed-files.outputs.all_changed_files }})"
          # See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          EOF="$(dd if=/dev/urandom bs=15 count=1 status=none | base64)"
          {
            echo "changes<<$EOF"
            echo "$changes"
            echo "$EOF" 
          } >> "$GITHUB_OUTPUT"

  send-slack-notification:
    name: "Send DB changes notification"
    needs: check-significant-changes
    if: needs.check-significant-changes.outputs.changes != ''
    uses: ./.github/workflows/slack_post_message_workflow.yml
    with:
      channel: ${{vars.SLACK_DB_CHANGES_CHANNEL_ID}}
      message: "Cette <${{ github.event.pull_request.html_url }}|PR> contient:\\n ${{ needs.check-significant-changes.outputs.changes }}"
    secrets:
      PASSCULTURE_GITHUB_ACTION_APP_ID: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_ID }}
      PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
