name: 3 [CI] Check API documentation can be built

on:
  workflow_call:
    inputs:
      doc-api-entrypoint:
        type: string
        required: false
        default: "api/documentation"

jobs:
  api-documentation-build-checks:
    name: Build check
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: "${{ inputs.doc-api-entrypoint }}/package.json"
      - uses: pass-culture/common-workflows/actions/setup-safe-chain@afae2577022181fccdaead9537235886c461f36a
      - name: "Build documentation"
        run: |
          set -e
          npm install
          npm run build
        env:
          ENV: ci-tests
        working-directory: "${{ inputs.doc-api-entrypoint }}"
