name: 3 [CI] Check API Client is up-to-date

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      image:
        type: string
        required: true

jobs:
  check-api-client-update:
    name: Check API client is up-to-date
    runs-on: ubuntu-22.04
    env:
      RUN_ENV: tests
      DATABASE_URL_TEST: postgresql://pytest:pytest@postgres:5432/pass_culture
      REDIS_URL: redis://redis:6379
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres:
        image: postgis/postgis:15-3.4-alpine
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: pytest
          POSTGRES_PASSWORD: pytest
          POSTGRES_DB: pass_culture
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 11.11.0

      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          cache: pnpm
          node-version-file: "pro/package.json"
          cache-dependency-path: "pro/pnpm-lock.yaml"
      - uses: pass-culture/common-workflows/actions/setup-safe-chain@afae2577022181fccdaead9537235886c461f36a

      - name: Load docker image
        id: load-docker-image
        uses: ./.github/actions/load-docker-image
        with:
          image: ${{ inputs.image }}
          tag: ${{ inputs.tag }}

      - name: "Setup database"
        run: |
          docker run \
            --network "${{ job.container.network }}" \
            --env RUN_ENV --env DATABASE_URL_TEST \
            --entrypoint bash \
            "${{ steps.load-docker-image.outputs.image-name }}" \
            -c '
              set -e
              flask install_postgres_extensions
              alembic upgrade pre@head
              alembic upgrade post@head
              flask install_data
            '

      - name: "Run API server"
        run: |
          docker run \
            --env RUN_ENV --env DATABASE_URL_TEST \
            --tty \
            --detach \
            --network "${{ job.container.network }}" \
            --publish 5001:5001 \
            --entrypoint bash \
            "${{ steps.load-docker-image.outputs.image-name }}" \
            -c "python src/pcapi/app.py"

      - name: "Wait for migrations to be run"
        uses: iFaxity/wait-on-action@a7d13170ec542bdca4ef8ac4b15e9c6aa00a6866 # v1.2.1
        with:
          resource: http://localhost:5001/health/api
          timeout: 120000
      - name: "Install dependencies PRO"
        working-directory: pro
        run: pnpm ci
      - name: "Update api client"
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            cd pro
            pnpm generate:api:client:local:no:docker
      - name: "Check if there are changes"
        id: "changes"
        working-directory: pro
        run: |
          diff="$(git diff -- src)"
          if [[ "${diff}" != "" ]]; then
            echo "Found changes in the API."
            echo "${diff}" | awk '{ print "\t" $0 }'
            echo "Please run 'pnpm generate:api:client:local' or 'pnpm run generate:api:client:local:no:docker' and add the changes to the commit(s) that change the API."
            exit 1
          fi
      - name: "Show pcapi log when it fails"
        if: failure()
        run: docker logs pc-api
