name: 3 [CI] Check API documentation can be built

on:
  workflow_call:
    inputs:
      doc-api-entrypoint:
        type: string
        required: false
        default: "api/documentation"

jobs:
  api-documentation-build-checks:
    name: Build check
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 11.11.0

      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: pnpm
          node-version-file: "${{ inputs.doc-api-entrypoint }}/package.json"
          cache-dependency-path: "${{ inputs.doc-api-entrypoint }}/pnpm-lock.yaml"
      - uses: pass-culture/common-workflows/actions/setup-safe-chain@aeb09c2a8b4dde6291cd1f8b986c1fe3f3c0655c
      - name: "Build documentation"
        run: |
          set -e
          pnpm install
          pnpm run build
        env:
          ENV: ci-tests
        working-directory: "${{ inputs.doc-api-entrypoint }}"
