name: 3 [CI] Build and deploy Storybook

on: workflow_call

jobs:
  build-and-deploy-storybook:
    name: Build and deploy Storybook
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: "pro/package.json"
      - uses: pass-culture/common-workflows/actions/setup-safe-chain@afae2577022181fccdaead9537235886c461f36a
      - run: yarn install --immutable
        working-directory: pro
      - run: yarn build-storybook
        working-directory: pro
      - name: Deploy Storybook on GitHub pages
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "docs"
          folder: "pro/docs-build"
          clean: true
          target-folder: "docs"
