name: "3 [CI] Test changes"

on:
  workflow_call:
    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: { required: true }
      GCP_EHP_SERVICE_ACCOUNT: { required: true }
    outputs:
      # changes
      api-changed:
        value: ${{ jobs.compute-changes.outputs.api-changed }}
      api-documentation-changed:
        value: ${{ jobs.compute-changes.outputs.api-documentation-changed }}
      pro-changed:
        value: ${{ jobs.compute-changes.outputs.pro-changed }}
      github-changed:
        value: ${{ jobs.compute-changes.outputs.github-changed }}
      alembic-changed:
        value: ${{ jobs.compute-changes.outputs.alembic-changed }}
      maintenance-site-changed:
        value: ${{ jobs.compute-changes.outputs.maintenance-site-changed }}
      # stringified array, ex: '["GitHub actions","Front Pro","Backend"]'
      failed-tests-matrix:
        value: ${{ jobs.compute-failed-tests-matrix.outputs.failed-tests-matrix }}

permissions: write-all

jobs:
  compute-changes:
    name: Compute changes
    runs-on: ubuntu-latest
    outputs:
      api-changed: ${{ steps.check-api-changes.outputs.any_modified }}
      api-documentation-changed: ${{ steps.check-api-documentation-changes.outputs.any_modified }}
      pro-changed: ${{ steps.check-pro-changes.outputs.any_modified }}
      github-changed: ${{ steps.check-github-changes.outputs.any_modified }}
      alembic-changed: ${{ steps.check-alembic-changes.outputs.any_modified }}
      maintenance-site-changed: ${{ steps.check-maintenance-site-changes.outputs.any_modified }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with: { fetch-tags: false }
      - name: Check api folder changes
        id: check-api-changes
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: |
            api/**
            !api/documentation/**
            !api/src/pcapi/scripts/**/main.py
            !api/src/pcapi/scripts/**/test_script.py
            !api/src/pcapi/scripts/**/main.sql
      - name: Check public API documentation folder changes
        id: check-api-documentation-changes
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with: { files: api/documentation/** }
      - name: Check pro folder changes
        id: check-pro-changes
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: pro/**
      - name: Check .github folder changes
        id: check-github-changes
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with: { files: .github/** }
      - name: "Check maintenance-site folder changes"
        id: check-maintenance-site-changes
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: maintenance-site/**
      - name: Check alembic folder changes
        id: check-alembic-changes
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: |-
            api/src/pcapi/alembic/versions/**
            api/src/pcapi/alembic/run_migrations.py
      - name: Publish Summary
        run: |
          {
            echo "### Changes summary"
            echo "**commit:** \`${{ github.sha }}\`"
            echo "| Folder               | Status |"
            echo "| -------------------- | ------ |"
            echo "| \`/api\`               | ${{ steps.check-api-changes.outputs.any_modified == 'true' && ':arrows_counterclockwise: Modified' || ':white_check_mark: Not modified' }} |"
            echo "| \`/api/documentation\` | ${{ steps.check-api-documentation-changes.outputs.any_modified == 'true' && ':arrows_counterclockwise: Modified' || ':white_check_mark: Not modified' }} |"
            echo "| \`/api/**/alembic\`    | ${{ steps.check-alembic-changes.outputs.any_modified == 'true' && ':arrows_counterclockwise: Modified' || ':white_check_mark: Not modified' }} |"
            echo "| \`/pro\`               | ${{ steps.check-pro-changes.outputs.any_modified == 'true' && ':arrows_counterclockwise: Modified' || ':white_check_mark: Not modified' }} |"
            echo "| \`/.github\`           | ${{ steps.check-github-changes.outputs.any_modified == 'true' && ':arrows_counterclockwise: Modified' || ':white_check_mark: Not modified' }} |"
            echo "| \`/maintenance-site\`  | ${{ steps.check-maintenance-site-changes.outputs.any_modified == 'true' && ':arrows_counterclockwise: Modified' || ':white_check_mark: Not modified' }} |"
          } >> "$GITHUB_STEP_SUMMARY"

  lint-github-actions:
    name: Lint GitHub actions & worflows
    needs: compute-changes
    if: needs.compute-changes.outputs.github-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with: { fetch-tags: false }
      - name: "Run actionlint"
        uses: pass-culture/common-workflows/actions/actionlint-check@b2eaf34df9945c76e68cffc6e4bf27037f6ea21a # v0.2

  build-backend-image:
    name: Build backend image
    needs: compute-changes
    if: |
      needs.compute-changes.outputs.api-changed == 'true' ||
      needs.compute-changes.outputs.pro-changed == 'true' ||
      needs.compute-changes.outputs.github-changed == 'true'
    uses: ./.github/workflows/dev_on_workflow_build_docker_image.yml
    with:
      image: pcapi-tests
      tag: ${{ github.sha }}

  run-mypy-cop:
    name: "MyPy cop"
    needs: compute-changes
    if: |
      needs.compute-changes.outputs.api-changed == 'true' ||
      needs.compute-changes.outputs.github-changed == 'true'
    uses: ./.github/workflows/dev_on_workflow_mypy_cop.yml

  check-api-client-update:
    name: Front API Client
    needs: [compute-changes, build-backend-image]
    uses: ./.github/workflows/ci_test_api_client_update.yml
    with:
      tag: ${{ github.sha }}
      image: pcapi-tests

  test-backend:
    name: Backend
    needs: [compute-changes, build-backend-image]
    if: |
      needs.compute-changes.outputs.api-changed == 'true' ||
      needs.compute-changes.outputs.github-changed == 'true'
    uses: ./.github/workflows/ci_test_backend.yml
    with:
      tag: ${{ github.sha }}
    secrets: inherit

  test-api-documentation:
    name: Public API documentation
    needs: compute-changes
    if: |
      needs.compute-changes.outputs.api-documentation-changed == 'true' ||
      needs.compute-changes.outputs.github-changed == 'true'
    uses: ./.github/workflows/ci_test_api_documentation.yml

  test-pro:
    name: Front Pro
    needs: compute-changes
    if: |
      needs.compute-changes.outputs.pro-changed == 'true' ||
      needs.compute-changes.outputs.github-changed == 'true'
    uses: ./.github/workflows/ci_test_front_pro.yml
    with:
      CACHE_BUCKET_NAME: "passculture-infra-prod-github-runner-cache"
    secrets: inherit

  test-e2e:
    name: E2E
    needs: [compute-changes, build-backend-image]
    uses: ./.github/workflows/ci_test_e2e.yml
    if: always() &&
      !cancelled() &&
      needs.compute-changes.outputs.api-changed == 'true' ||
      needs.compute-changes.outputs.pro-changed == 'true' ||
      needs.compute-changes.outputs.github-changed == 'true'
    with:
      ENV: "development"
      tag: ${{ github.sha }}
      CACHE_BUCKET_NAME: "passculture-infra-prod-github-runner-cache"

  # If the following jobs have failed: lint-github-actions, test_pro_result, test_backend_result
  # this job will return '["GitHub actions","Front Pro","Backend"]' in `failed-tests-matrix` output
  compute-failed-tests-matrix:
    name: Compute failed tests matrix
    runs-on: ubuntu-latest
    needs:
      - lint-github-actions
      - test-pro
      - test-e2e
      - test-backend
      - check-api-client-update
      - test-api-documentation
    if: always()
    env:
      lint_github_actions_result: ${{contains(needs.lint-github-actions.result, 'failure') && 'GitHub actions' || ''}}
      test_pro_result: ${{contains(needs.test-pro.result, 'failure') && 'Front Pro' || ''}}
      test_e2e_result: ${{contains(needs.test-e2e.result, 'failure') && 'E2E' || ''}}
      test_backend_result: ${{contains(needs.test-backend.result, 'failure') && 'Backend' || ''}}
      test_api_client_result: ${{contains(needs.check-api-client-update.result, 'failure') && 'Client API Front' || ''}}
      test_api_documentation: ${{contains(needs.test-api-documentation.result, 'failure') && 'Documentation API' || ''}}
    outputs:
      failed-tests-matrix: ${{ steps.compute-matrix.outputs.failed-tests-matrix }}
    steps:
      - id: compute-matrix
        run: |
          failed_results=("$lint_github_actions_result"  "$test_pro_result"  "$test_e2e_result"  "$test_backend_result"  "$test_api_documentation")
          json_array=$(printf '%s\n' "${failed_results[@]}" | jq -R -s '
            split("\n")
            | map(select(length > 0))
            | .
          ' -c)
          echo "failed-tests-matrix=$json_array" >> "$GITHUB_OUTPUT"
