name: Deploy
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      deploy_adage:
        type: boolean
        required: false
        default: false
      deploy_api:
        type: boolean
        required: false
        default: false
      deploy_pro:
        type: boolean
        required: false
        default: false

env:
  REGION: europe-west1

jobs:
  deploy-adage-front:
    name: Deploy adage
    if: |
      always() &&
      inputs.environment == 'production'
    uses: ./.github/workflows/deploy-gcs-front.yml
    with:
      app_name: adage
      app_directory: adage-front
      environment: ${{ inputs.environment }}
    secrets:
      gcp_project: ${{ secrets.METIER_GCP_PROJECT }}
      service_account: ${{ secrets.METIER_CIRCLECI_SERVICE_ACCOUNT }}
      workload_identity_provider: ${{ secrets.METIER_GCP_WORKLOAD_IDENTITY_PROVIDER }}

