name: "3 [on_workflow] Tests E2E Playwright"

on:
  workflow_call:
    inputs:
      ENV:
        type: string
        required: true
      image:
        type: string
        required: false
        default: pcapi-tests
      tag:
        type: string
        required: true
      CACHE_BUCKET_NAME:
        type: string
        required: true
    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER:
        required: true
      GCP_EHP_SERVICE_ACCOUNT:
        required: true

defaults:
  run:
    working-directory: pro

jobs:
  install:
    name: "Install Playwright E2E 🔧"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
          node-version-file: "pro/package.json"

      - uses: pass-culture/common-workflows/actions/setup-safe-chain@5f7b7837d099ddbb8e4f2e15400434d41d78c51b

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build vite application
        env:
          ENV: ${{ inputs.ENV }}
        run: yarn run "build:$ENV"

      - name: Save build folder
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: build-playwright
          if-no-files-found: error
          path: pro/build

      - name: Cache Docker layers
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile', '**/docker-compose*.yml') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Cache Poetry
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-buildx-

      # FIXME: remove deprecated GH action
      - name: "Cache Workflow Conclusion"
        uses: technote-space/workflow-conclusion-action@45ce8e0eb155657ab8ccf346ade734257fd196a5 # v3.0.3

  playwright-run:
    name: "Run Playwright E2E"
    runs-on: ubuntu-24.04
    needs: [install]
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2]
        shardTotal: [2]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
          node-version-file: "pro/package.json"

      - uses: pass-culture/common-workflows/actions/setup-safe-chain@5f7b7837d099ddbb8e4f2e15400434d41d78c51b

      - name: "Authentification to Google"
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}

      - name: "Get Secret"
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@bc9c54b29fdffb8a47776820a7d26e77b379d262 # v3.0.0
        with:
          secrets: |-
            ARTIFACT_REGISTRY_WORKLOAD_IDENTITY_PROVIDER:passculture-metier-ehp/infra-prod-gcp-workload-identity-provider
            ARTIFACT_REGISTRY_SERVICE_ACCOUNT:passculture-metier-ehp/passculture-main-artifact-registry-service-account

      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: "2.40.3"

      - name: "Fix local permissions"
        run: sudo chown -R "$PCAPI_UID:$PCAPI_GID" .
        working-directory: api
        env:
          PCAPI_UID: 1000
          PCAPI_GID: 1000

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install Playwright browsers
        run: yarn playwright install chromium --with-deps

      - name: "OpenID Connect Authentication"
        id: openid-auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          create_credentials_file: false
          token_format: "access_token"
          workload_identity_provider: ${{ steps.secrets.outputs.ARTIFACT_REGISTRY_WORKLOAD_IDENTITY_PROVIDER  }}
          service_account: ${{ steps.secrets.outputs.ARTIFACT_REGISTRY_SERVICE_ACCOUNT }}

      - name: "Docker login"
        id: docker-login
        uses: "docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2" # v4.0.0
        with:
          registry: "europe-west1-docker.pkg.dev"
          username: "oauth2accesstoken"
          password: "${{ steps.openid-auth.outputs.access_token }}"

      - name: "Compute docker image name:tag"
        id: compute-image-name
        env:
          IMAGE: ${{ inputs.image }}
          TAG: ${{ inputs.tag }}
        run: |
          echo "image_name=$IMAGE:$TAG" | tee -a "${GITHUB_OUTPUT}"
          echo "::notice:: Running playwright e2e-tests with $IMAGE:$TAG"

      - name: "Run postgres and redis server"
        run: docker-compose -f ../docker-compose-backend.yml up postgres redis -d

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1

      - name: "Download artifact"
        if: ${{ inputs.tag != 'latest' }}
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ inputs.image }}-${{ inputs.tag }}.tar
          path: ${{ runner.temp }}

      - name: "Run API server"
        env:
          IMAGE: ${{ inputs.image }}
          TAG: ${{ inputs.tag }}
        run: |
          if [ "$TAG" != "latest" ]; then
            docker load --input "${{ runner.temp }}/$IMAGE-$TAG.tar"
          fi
          docker run \
            --name pc-api \
            --workdir /usr/src/app \
            --volume ./../api:/usr/src/app \
            --env-file ./../env_file \
            --tty \
            --detach \
            --network pass-culture-main_db_nw \
            --publish 5001:5001 \
            --publish 10002:10002 \
            --entrypoint bash \
            "${{ steps.compute-image-name.outputs.image_name }}" \
            -c "set -e ; flask install_postgres_extensions ; alembic upgrade pre@head ; alembic upgrade post@head ; flask install_data ; FLASK_USE_RELOADER=0 python src/pcapi/app.py"

      - name: "Wait for migrations to be run"
        uses: iFaxity/wait-on-action@a7d13170ec542bdca4ef8ac4b15e9c6aa00a6866 # v1.2.1
        with:
          resource: http://localhost:5001/health/api
          timeout: 120000

      - name: Download the build folder
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: build-playwright
          path: pro/build

      - name: "Serve vite preview"
        run: yarn serve &

      - name: "Wait for front-end to listen"
        run: |
          # shellcheck disable=SC2016
          timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:3001)" != "200" ]]; do sleep 5; done' || false

      - name: "Playwright run"
        run: yarn test:e2e:ci --reporter=blob --shard="${{ matrix.shardIndex }}/${{matrix.shardTotal }}"

      - name: "Upload Playwright report"
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: ${{ !cancelled() }}
        with:
          name: report-chromium-${{ matrix.shardIndex }}
          path: pro/blob-report/
          retention-days: 30

      - name: "Show pcapi log when it fails"
        if: failure()
        run: docker logs pc-api

  merge-reposrts:
    if: ${{ !cancelled() }}
    needs: [playwright-run]
    name: "Merge playwright reports"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: "pro/package.json"
      - uses: pass-culture/common-workflows/actions/setup-safe-chain@5f7b7837d099ddbb8e4f2e15400434d41d78c51b

      - name: "Cache the node_modules"
        id: "yarn-modules-cache"
        uses: pass-culture-github-actions/cache@v1.0.0
        with:
          compression-method: "gzip"
          bucket: ${{ inputs.CACHE_BUCKET_NAME }}
          path: |
            **/node_modules
          key: v1-yarn-pro-dependency-cache-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            v1-yarn-pro-dependency-cache-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: "Install dependencies (3 attempts)"
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          timeout_minutes: 2
          max_attempts: 3
          command: |
            cd pro
            yarn install --immutable

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: pro/all-blob-reports
          pattern: report-chromium-*
          merge-multiple: true

      - name: Merge reports
        run: npx playwright merge-reports --reporter html ./all-blob-reports

      - name: Upload HTML report
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: html-report--attempt-${{ github.run_attempt }}
          path: pro/playwright-report
          retention-days: 14


  notify-playwright-failure:
    name: "Notification of Playwright tests failure"
    needs: playwright-run
    if: always() && needs.playwright-run.result == 'failure' && github.ref == 'refs/heads/master'
    uses: ./.github/workflows/dev_on_workflow_post_slack_message.yml
    with:
      channel: ${{vars.SLACK_CI_NOTIFICATIONS_CHANNEL_ID}}
      color: "#A30002"
      message: ":github-failure: <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|Pro Playwright E2E Tests> a échoué sur `master`"
    secrets:
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
