name: "[DEVOPS][TEST][on_dispatch] Deploy OPS"

on:
  workflow_dispatch:
    inputs:
      pcapi_image_tag:
        description: pcapi image tag to deploy
        required: true

permissions: write-all

jobs:
  deploy-to-ops:
    name: "Deploy to ops"
    uses: ./.github/workflows/dev_on_workflow_deploy.yml
    with:
      environment: ops
      app_version: ${{ inputs.pcapi_image_tag }}
      cluster_name: gke-backend-tst-eu9
      gcp_project_id: pc-backend-tst
      workload_identity_provider_secret_name: ${{ secrets.V2_GCP_WORKLOAD_IDENTITY_PROVIDER }}
      deploy_api: true
      deploy_pro: false
    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.V2_GCP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.V2_GCP_SERVICE_ACCOUNT }}
      PASSCULTURE_GITHUB_ACTION_APP_ID: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_ID }}
      PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY }}
