name: "[on_workflow] Run actionlint"

on:
  workflow_call:

permissions: write-all

jobs:
  actionlint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pass-culture/common-workflows/actions/actionlint-check@f4db7db202ff3cddc97fcbf08c3821ebc78b10fb

