name: "[DEVOPS][TEST][on_dispatch] Deploy OPS"

on:
  workflow_dispatch:
    inputs:
      pcapi_image_tag:
        description: pcapi image tag to deploy
        required: true

permissions: write-all

jobs:
  deploy-to-ops:
    name: "Deploy to ops"
    uses: ./.github/workflows/dev_on_workflow_deploy.yml
    with:
      environment: opsv2
      app_version: ${{ inputs.pcapi_image_tag }}
      cluster_name: gke-infra-tst-eu9
      location: europe-west9
      gcp_project_id: pc-infra-tst
      is_new_infra: true
      deploy_api: true
    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secret.V2_GCP_WORKLOAD_IDENTITY_PROVIDER }} # To rename after migration for consistency
      GCP_EHP_SERVICE_ACCOUNT: ${{ V2_GCP_SERVICE_ACCOUNT }} # To rename after migration for consistency
