name: 99 Check Alembic Migrations for significant changes

on:
  pull_request:
    types:
      - closed
  # TODO: remove before merge
  push:
    branches:
      - backup/PC-40140

permissions: write-all

jobs:
  check-significant-changes:
    # TODO: uncomment before merge
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.changes }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - id: get-remote-master-sha
        run : |
          remote_master_sha=$(git ls-remote -q | grep refs/heads/master | awk '{print $1}')
          echo "remote_master_sha=$remote_master_sha" >> "$GITHUB_OUTPUT"

      - id: changed-files
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          base_sha: ${{ steps.get-remote-master-sha.outputs.remote_master_sha }}
          files: |
            api/src/pcapi/alembic/versions/**

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0

      - name: Detect DB changes
        id: changes
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          changes=$(python api/bin/alembic_detect_significant_changes.py ${{ steps.changed-files.outputs.all_changed_files }})
          # See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          EOF="$(dd if=/dev/urandom bs=15 count=1 status=none | base64)"
          {
            echo "changes<<$EOF"
            echo "$changes"
            echo "$EOF" 
          } >> "$GITHUB_OUTPUT"

  send-slack-notification:
    name: "Send DB changes notification"
    needs: check-significant-changes
    if: needs.check-significant-changes.outputs.changes != '[]'
    uses: ./.github/workflows/dev_on_workflow_post_slack_message.yml
    with:
#      channel: ${{vars.SLACK_DB_CHANGES_CHANNEL_ID}}
      channel: "C082B7TEXL3"
      color: "#008080"  # teal
      message: "Cette <${{ github.event.pull_request.html_url }}|PR> contient:\\n ${{ needs.check-significant-changes.outputs.changes }}"
    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
