name: 4 [Slack] Post message

on:
  workflow_call:
    inputs:
      channel:
        type: string
        required: false
        default: ${{vars.SLACK_CI_NOTIFICATIONS_CHANNEL_ID}}
      message:
        type: string
        required: true
    secrets:
      PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY: { required: true }
      PASSCULTURE_GITHUB_ACTION_APP_ID: { required: true }
      SLACK_BOT_TOKEN: { required: true }
    outputs:
      message-ts:
        value: ${{ jobs.post-slack-message.outputs.message-ts }}

jobs:
  post-slack-message:
    runs-on: ubuntu-24.04
    continue-on-error: true
    outputs:
      message-ts: ${{ steps.post-message.outputs.message-ts }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-tags: false
          persist-credentials: false
      - name: Install passdirector
        uses: ./.github/actions/setup-passdirector
        with:
          version: v0.7.2
          github_app_id: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_ID }}
          github_app_private_key: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY }}
      - name: Post message
        id: post-message
        shell: bash
        env:
          CHANNEL: ${{inputs.channel}}
          MESSAGE: ${{inputs.message}}
          GITHUB_ACTOR: ${{github.actor}}
          PASSDIRECTOR_SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
        run: |
          message_ts=$(passdirector slack post -c "${CHANNEL}" -m "${MESSAGE}" -a "${GITHUB_ACTOR}")
          echo "message-ts=$message_ts" >> "$GITHUB_OUTPUT"
