name: "test"
on:
  push:

jobs:
  deploy-ehp:
    name: "Deploy on EHP environnement"
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "testing"
      deploy_api: true
      deploy_pro: true
    secrets: inherit

