name: Debug


on:
  push:

jobs:
  openssl:
    name: Recover With OpenSSL
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - env:
          METIER_CIRCLECI_SERVICE_ACCOUNT: ${{ secrets.METIER_CIRCLECI_SERVICE_ACCOUNT }}
        run: |
          echo "MY_CLIENT_ID (base64) = $(echo ${METIER_CIRCLECI_SERVICE_ACCOUNT} | base64)"
