name: Test main
run-name: Test main${{ github.ref == 'refs/heads/master' && ' and deploy to testing' || '' }}
on:
  push:

jobs:

  test-backoffice:
    name: Test backoffice
    needs: check-backoffice-folder-changes
    uses: ./.github/workflows/tests-backoffice-v3.yml
    secrets: inherit

