name: "[DEVOPS][TESTCI] 3 [on_workflow] Deploy"
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      app_version:
        type: string
        required: false
      deploy_api:
        type: boolean
        required: false
        default: false
      deploy_pro:
        type: boolean
        required: false
        default: false
      ENTRYPOINT:
        type: string
        required: true
        default: 'api/documentation'
      CHANNEL:
        type: string
        required: false
      EXPIRES:
        type: string
        required: false
        default: '7d'
      APPNAME:
        type: string
        required: true

    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER:
        required: true
      GCP_EHP_SERVICE_ACCOUNT:
        required: true

jobs:
  deploy-api-doc-on-firebase:
    name: "Deploy api"
    if: ${{ inputs.deploy_api }}
    runs-on: ubuntu-latest
    environment: testing
    # environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4.1.7
      - name: "Authentification to Google"
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: '${{ inputs.ENTRYPOINT }}/.nvmrc'
      - name: "Build documentation"
        run: |
            set -e
            npm install
            npm run build
        env:
          ENV: ${{ inputs.environment }}
        working-directory: '${{ inputs.ENTRYPOINT }}'
      - name: "OpenID Connect Authentication"
        id: "openid-auth"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
      - name: "Get Secret"
        id: "secrets"
        uses: "google-github-actions/get-secretmanager-secrets@v2"
        with:
          secrets: |-
            FIREBASE_TOKEN:passculture-metier-ehp/pc_doc_api_${{ inputs.environment }}_firebase_json
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ steps.secrets.outputs.FIREBASE_TOKEN }}"
          expires: "${{ inputs.EXPIRES }}"
          projectId: "${{ inputs.APPNAME }}-${{ inputs.environment }}"
          entryPoint: "${{ inputs.ENTRYPOINT }}"
          channelId: "${{ inputs.CHANNEL }}"
