name: Tests api
on: push

env:
  region: europe-west1
  tests_docker_image: europe-west1-docker.pkg.dev/passculture-infra-prod/pass-culture-artifact-registry/pcapi-tests:${{ github.sha }}

defaults:
  run:
    working-directory: api

jobs:
  build-tests-docker-image:
    name: Build tests docker image
    uses: ./.github/workflows/build-and-push-docker-images.yml
    with:
      tag: ${{ github.sha }}
      tests: true
    secrets: inherit

  pylint-check:
    name: Pylint
    runs-on: [self-hosted, linux, x64]
    needs: build-tests-docker-image
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - id: openid-auth
        name: "OpenID Connect Authentication"
        uses: "google-github-actions/auth@v1"
        with:
          create_credentials_file: false
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.INFRA_PROD_GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.ARTIFACT_REGISTRY_SERVICE_ACCOUNT }}
      - uses: docker/login-action@v2
        with:
          registry: "${{ env.region }}-docker.pkg.dev"
          username: oauth2accesstoken
          password: ${{ steps.openid-auth.outputs.access_token }}
      - run: docker pull ${{ env.tests_docker_image }}
      - name: Show installed Python packages
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ env.tests_docker_image }}
          run: pip freeze
      - name: Run pylint
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ env.tests_docker_image }}
          run: pylint src tests --jobs=0
      - name: Slack Notification
        if: ${{ failure() && github.ref == 'refs/heads/master'  }}
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # channel #dev
          channel-id: "CPZ7U1CNP"
          payload: |
            {
            "attachments": [
              {
                "mrkdwn_in": ["text"],
                "color": "#A30002",
                "author_name": "${{github.actor}}",
                "author_link": "https://github.com/${{github.actor}}",
                "author_icon": "https://github.com/${{github.actor}}.png",
                "title": "Api tests",
                "title_link": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}",
                "text": "Les tests pylint-checks échouent sur `master` :boom:"
              }
            ],
            "unfurl_links": false,
            "unfurl_media": false
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

