import { SubcategoryIdEnum } from 'apiClient/v1'

export const venueTypeSubcategoriesMapping: Record<
  string,
  Array<SubcategoryIdEnum>
> = {
  ['ADMINISTRATIVE']: [
    SubcategoryIdEnum.SPECTACLE_REPRESENTATION,
    SubcategoryIdEnum.ATELIER_PRATIQUE_ART,
    SubcategoryIdEnum.CONCERT,
    SubcategoryIdEnum.SEANCE_CINE,
    SubcategoryIdEnum.ABO_PRATIQUE_ART,
  ],
  ['ARTISTIC_COURSE']: [
    SubcategoryIdEnum.ABO_PRATIQUE_ART,
    SubcategoryIdEnum.ATELIER_PRATIQUE_ART,
    SubcategoryIdEnum.MATERIEL_ART_CREATIF,
    SubcategoryIdEnum.SPECTACLE_REPRESENTATION,
    SubcategoryIdEnum.SEANCE_ESSAI_PRATIQUE_ART,
  ],
  ['BOOKSTORE']: [
    SubcategoryIdEnum.LIVRE_PAPIER,
    SubcategoryIdEnum.SUPPORT_PHYSIQUE_MUSIQUE,
    SubcategoryIdEnum.MATERIEL_ART_CREATIF,
    SubcategoryIdEnum.SUPPORT_PHYSIQUE_FILM,
    SubcategoryIdEnum.ACHAT_INSTRUMENT,
  ],
  ['CONCERT_HALL']: [
    SubcategoryIdEnum.CONCERT,
    SubcategoryIdEnum.SPECTACLE_REPRESENTATION,
    SubcategoryIdEnum.FESTIVAL_MUSIQUE,
    SubcategoryIdEnum.ABO_CONCERT,
    SubcategoryIdEnum.EVENEMENT_MUSIQUE,
  ],
  ['CREATIVE_ARTS_STORE']: [
    SubcategoryIdEnum.LIVRE_PAPIER,
    SubcategoryIdEnum.MATERIEL_ART_CREATIF,
    SubcategoryIdEnum.ATELIER_PRATIQUE_ART,
    SubcategoryIdEnum.ABO_PRATIQUE_ART,
  ],
  ['CULTURAL_CENTRE']: [
    SubcategoryIdEnum.LIVRE_PAPIER,
    SubcategoryIdEnum.SEANCE_CINE,
    SubcategoryIdEnum.SPECTACLE_REPRESENTATION,
    SubcategoryIdEnum.SUPPORT_PHYSIQUE_MUSIQUE,
    SubcategoryIdEnum.CONCERT,
  ],
  ['DIGITAL']: [
    SubcategoryIdEnum.LIVRE_NUMERIQUE,
    SubcategoryIdEnum.VOD,
    SubcategoryIdEnum.TELECHARGEMENT_MUSIQUE,
    SubcategoryIdEnum.CINE_VENTE_DISTANCE,
    SubcategoryIdEnum.ABO_PRESSE_EN_LIGNE,
  ],
  ['DISTRIBUTION_STORE']: [
    SubcategoryIdEnum.LIVRE_PAPIER,
    SubcategoryIdEnum.SUPPORT_PHYSIQUE_MUSIQUE,
    SubcategoryIdEnum.SUPPORT_PHYSIQUE_FILM,
    SubcategoryIdEnum.MATERIEL_ART_CREATIF,
  ],
  ['FESTIVAL']: [
    SubcategoryIdEnum.FESTIVAL_MUSIQUE,
    SubcategoryIdEnum.CONCERT,
    SubcategoryIdEnum.FESTIVAL_SPECTACLE,
    SubcategoryIdEnum.SPECTACLE_REPRESENTATION,
    SubcategoryIdEnum.LIVRE_PAPIER,
  ],
  ['GAMES']: [
    SubcategoryIdEnum.ESCAPE_GAME,
    SubcategoryIdEnum.EVENEMENT_JEU,
    SubcategoryIdEnum.CARTE_MUSEE,
    SubcategoryIdEnum.MATERIEL_ART_CREATIF,
    SubcategoryIdEnum.LIVRE_PAPIER,
  ],
  ['LIBRARY']: [
    SubcategoryIdEnum.SPECTACLE_REPRESENTATION,
    SubcategoryIdEnum.ABO_BIBLIOTHEQUE,
    SubcategoryIdEnum.RENCONTRE,
    SubcategoryIdEnum.CONFERENCE,
    SubcategoryIdEnum.ATELIER_PRATIQUE_ART,
  ],
  ['MOVIE']: [
    SubcategoryIdEnum.SEANCE_CINE,
    SubcategoryIdEnum.EVENEMENT_CINE,
    SubcategoryIdEnum.FESTIVAL_CINE,
    SubcategoryIdEnum.CARTE_CINE_MULTISEANCES,
    SubcategoryIdEnum.CINE_PLEIN_AIR,
  ],
  ['MUSEUM']: [
    SubcategoryIdEnum.EVENEMENT_PATRIMOINE,
    SubcategoryIdEnum.VISITE,
    SubcategoryIdEnum.VISITE_GUIDEE,
    SubcategoryIdEnum.CONFERENCE,
    SubcategoryIdEnum.ABO_MUSEE,
  ],
  ['MUSICAL_INSTRUMENT_STORE']: [
    SubcategoryIdEnum.ACHAT_INSTRUMENT,
    SubcategoryIdEnum.LIVRE_PAPIER,
    SubcategoryIdEnum.PARTITION,
    SubcategoryIdEnum.SUPPORT_PHYSIQUE_MUSIQUE,
    SubcategoryIdEnum.ABO_PRATIQUE_ART,
  ],
  ['OTHER']: [
    SubcategoryIdEnum.LIVRE_PAPIER,
    SubcategoryIdEnum.SPECTACLE_REPRESENTATION,
    SubcategoryIdEnum.ATELIER_PRATIQUE_ART,
    SubcategoryIdEnum.ABO_PRATIQUE_ART,
    SubcategoryIdEnum.SEANCE_CINE,
  ],
  ['PATRIMONY_TOURISM']: [
    SubcategoryIdEnum.LIVRE_PAPIER,
    SubcategoryIdEnum.VISITE_GUIDEE,
    SubcategoryIdEnum.VISITE,
    SubcategoryIdEnum.CONCERT,
    SubcategoryIdEnum.EVENEMENT_PATRIMOINE,
  ],
  ['PERFORMING_ARTS']: [
    SubcategoryIdEnum.SPECTACLE_REPRESENTATION,
    SubcategoryIdEnum.CONCERT,
    SubcategoryIdEnum.SEANCE_CINE,
    SubcategoryIdEnum.FESTIVAL_SPECTACLE,
    SubcategoryIdEnum.ATELIER_PRATIQUE_ART,
  ],
  ['RECORD_STORE']: [
    SubcategoryIdEnum.SUPPORT_PHYSIQUE_MUSIQUE,
    SubcategoryIdEnum.LIVRE_PAPIER,
    SubcategoryIdEnum.ACHAT_INSTRUMENT,
    SubcategoryIdEnum.CONCERT,
    SubcategoryIdEnum.MATERIEL_ART_CREATIF,
  ],
  ['SCIENTIFIC_CULTURE']: [
    SubcategoryIdEnum.VISITE,
    SubcategoryIdEnum.SEANCE_CINE,
    SubcategoryIdEnum.EVENEMENT_PATRIMOINE,
    SubcategoryIdEnum.CONFERENCE,
    SubcategoryIdEnum.VISITE_GUIDEE,
  ],
  ['TRAVELING_CINEMA']: [
    SubcategoryIdEnum.CINE_PLEIN_AIR,
    SubcategoryIdEnum.SEANCE_CINE,
    SubcategoryIdEnum.FESTIVAL_CINE,
    SubcategoryIdEnum.CARTE_CINE_MULTISEANCES,
  ],
  ['VISUAL_ARTS']: [
    SubcategoryIdEnum.VISITE,
    SubcategoryIdEnum.ATELIER_PRATIQUE_ART,
    SubcategoryIdEnum.MATERIEL_ART_CREATIF,
    SubcategoryIdEnum.ABO_MUSEE,
    SubcategoryIdEnum.SEANCE_CINE,
  ],
}
